### ISSUE TITLE
I am trying to implement walk through functionality in wexbim viewer, but not getting any proper solution, please help 

### ISSUE THREAD

**Issue by ranjitchapale** [xBimTeam/XbimWebUI#10]

**Comment by edocs** [comment]
Hi @ranjitchapale,

Please see my comment on [issue 9](https://github.com/xBimTeam/XbimWebUI/issues/9) - our company has forked this repo and implemented a walk/fly through navigation mode which may be what you are after.

**Comment by ranjitchapale** [comment]
Hello, I have checked that source but I didn't find walk/fly option,can you please tell me where it is implemented

**Comment by edocs** [comment]
Of course, sorry. You will need to set the navigationMode property to "fly" on the xViewer instance. Example code below:

```javascript
var viewer = new xViewer(viewerId);
viewer.set('navigationMode', 'fly');
```

**Comment by edocs** [comment]
It may also be worth mentioning that I've set the following new properties as well in my application:

```javascript
viewer.set('scrollSpeed', 2);
viewer.set('panSpeed', 0.5);
```

**Comment by ranjitchapale** [comment]
HI,
Thanks for your help, I will try by implementing given solution






Thanks & Regards,
Ranjit Chapale
09623185639

**Comment by ranjitchapale** [comment]
I had tried with given solutions,still its not working
viewer.set('navigationMode', 'fly');
viewer.set('scrollSpeed', 2);
viewer.set('panSpeed', 0.5);

**Comment by edocs** [comment]
What's not working? Do the controls not do anything? Does the model not render? Are there any errors in the developer console of the browser?
