### ISSUE TITLE
Merge two Wexbim files

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#100]
Hi  @LloydPickering @martin1cerny ,

Is it possible to merge two wexbim files into one wexbim . And it will display into viewer. If Yes , then how i can implement it .?

[if this issue is not related to this repository ,then please forward it to particular repository]

**Comment by martin1cerny** [comment]
It is not possible to merge two wexBIM files. However, it is possible to load two wexBIM files into one xViewer.

**Comment by BIMDevelopement** [comment]
Okay . So you mean to say that Two wexBIM files can show in one xViewer at a time . 
Is it right ?

**Comment by martin1cerny** [comment]
Yes, that's right.

2016-06-28 15:48 GMT+02:00 Amol D <notifications@github.com>:

**Comment by BIMDevelopement** [comment]
Hi Martin ,

Can you please provide any idea to implement above concept.

**Comment by martin1cerny** [comment]
Just use the [load()](http://xbimteam.github.io/XbimWebUI/xViewer.html#load) function multiple times.

**Comment by BIMDevelopement** [comment]
okay . Thank you

**Comment by BIMDevelopement** [comment]
Hi Martin ,

I have tried above solution . I got success to load multiple model in one canvas viewer. But i get same scenerio which you metioned in #101 issue . (ie. You can see an example here.). 

Actually , I have some floorwise ifc files for one building . I have to load all that floor model in one viewer . After loading a all floors model , It looks like as Building.

I have create some ruff layout for your understanding purpose. Please help to do that . 
![sketch](https://cloud.githubusercontent.com/assets/10378872/16614391/9867e92a-438e-11e6-9648-8686c50f2497.png)

**Comment by martin1cerny** [comment]
Can you be more specific about the issue you are having?

**Comment by BIMDevelopement** [comment]
I divide a three floors buildiing ifc files into three separate ifc files . And Each file will be uploaded on viewer by selecting a checkbox that have been shown in previous diagram.

Suppose , I have select a first floor ifc file , then it will show First floor model on Viewer . likewise other floors. 

When I have uploaded all three floors on same Xviewer . It will look as one Building .

[First floor + second floor + third floor == One Building ]

**Comment by martin1cerny** [comment]
That is exactly how it works. See the example [here](http://htmlpreview.github.io/?https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/simpleviewer.html).
