### ISSUE TITLE
How to clear canvas

### ISSUE THREAD

**Issue by Tpullmann** [xBimTeam/XbimWebUI#101]
When I bind a new instance of xViewer to a canvas, picking elements does not work any more. If I bind to a new canvas all is fine. Is there a way to clear the canvas, it's events or whatever?

**Comment by martin1cerny** [comment]
This is brand new feature implemented thanks to funding from [BIM Point](http://www.bim-point.com/). It is possible now to unload model(s) from the viewer. You can see an example [here](http://htmlpreview.github.io/?https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/simpleviewer.html). You can select multiple wexBIM files and than stop/start/unload them. Unloading would free GPU memory and is not reversible.
