### ISSUE TITLE
How to get color of object of viewer model 

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#102]
Hi ,

I need help to get a color of object of viewer model .

**Comment by martin1cerny** [comment]
This is not accessible through the API. Plus one object can have many colours. Which one would you take?

**Comment by BIMDevelopement** [comment]
Suppose I want to get color of wall . Then how I will get that color.

**Comment by martin1cerny** [comment]
You can get it from IFC file. 
`IfcWall->Representation->Representations->Items->StyledByItem->Styles->Styles`
