### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by gijskoning** [xBimTeam/XbimWebUI#106]
I'm trying to get some ui working from the xbim team. But i've tried all the demos but those have deprecated depencies. My question is: is there a tutorial or method for any combination of XbimWebUI with Essentials and Geometry? Or just a simple tutorial/explanation to get started. It's very difficult to find information because it's deprecated or the links are not working anymore.
I've also tried just combining the latest development versions of Essential and Geometry but the solution got stuck at running cl.exe.

**Comment by AlainBolduc** [comment]
I feel your pain, I have struggled quite a bit when I first tried to use the libraries. Now that they are under heavy development for ifc4 support, the way of creating wexbim files changed a little from what you can find in the issues or documentation... 

I have found the required code in xBim.Exchange in the test cases.. 

You can make a simple console application that uses the latest Essentials / geometry from the development nuget repository (https://www.myget.org/F/xbim-develop/api/v2) 
You will need Xbim.Essentials and Xbim.Geometry.

Use the following code to convert a .ifc file to .wexbim file:

`            using (IfcStore ifcStore = IfcStore.Open("Path_to_your_IFC_file"))
            {
                var context = new Xbim3DModelContext(ifcStore);
                context.CreateContext();

                using (var ms = new FileStream("Path_to_Target_wexbim_file", FileMode.Create))
                {
                    using (var binaryWriter = new BinaryWriter(ms))
                    {
                        ifcStore.SaveAsWexBim(binaryWriter);
                    }
                }
            }`

This will give you a binary .wexbim file, which can be loaded in xBimWebUI using the Load method on the xViewer object. (for which you can find examples [Here](http://xbimteam.github.io/XbimWebUI/))

Hope this helps,

**Comment by gijskoning** [comment]
Thank you for your help. I did what you said and it is working when i'm running the html with intellij. Because this ide makes a server when you run it. But i wan't to run it on a remote windows 2012 server. But it says: xbim-viewer.debug.bundle.js:66 Uncaught Failed to fetch binary data from server. Server code: 404. This might be due to CORS policy of your browser if you run this as a local file.

**Comment by martin1cerny** [comment]
Get the URL you pass to xViewer and paste it to the browser. If you can't get it neither can the xViewer. Watch all errors in the console of your browser. My guess is that you you need to configure your IIS to serve *.wexbim files as static files.

**Comment by gijskoning** [comment]
Thanks for the comment. I already fixed it by putting the .wexbim extension in the extension list of the server
