### ISSUE TITLE
Saved Views from Viewer

### ISSUE THREAD

**Issue by dazmahal** [xBimTeam/XbimWebUI#107]
Hi All
On a recent WebUI check In mentioned it included functionality to save views from a model within the viewer.
How is this functionality invoked or does it require additional Plug in?

Thanks
Daz

**Comment by martin1cerny** [comment]
This function doesn't save a view but state of the model (like changed
colours, visibility, x-ray mode etc). If you also want to save the view you
need to save camera matrix and model view matrix.
