### ISSUE TITLE
Selection in xBIM webViewer

### ISSUE THREAD

**Issue by BIMDeveloper** [xBimTeam/XbimWebUI#11]
Hello all,
I can't select from the viewer...
thanks in advance...

**Comment by martin1cerny** [comment]
Hi @BIMDeveloper,

I'm sorry but your question is very general. Could you try to describe the issue more in detail?

Martin

**Comment by BIMDeveloper** [comment]
Ok...
Can I click on a specific element and catch its ID and determine its properties like desktop xBIM Xplorer?
I hope I became more clear, Thanks for your caring @martin1cerny 

Micheal

![selection](https://cloud.githubusercontent.com/assets/12292418/7562544/9a4769f6-f7d5-11e4-8956-4a57f08a4458.PNG)

**Comment by martin1cerny** [comment]
Sure, that is one of the first features implemented in the viewer. You have to listen to one of the mouse events ([mouseDown](http://xbimteam.github.io/XbimWebUI/xViewer.html#event:mouseDown), [pick](http://xbimteam.github.io/XbimWebUI/xViewer.html#event:pick) or [dblclick](http://xbimteam.github.io/XbimWebUI/xViewer.html#event:dblclick)). It is also described in [this tutorial](http://xbimteam.github.io/XbimWebUI/tutorial-3_Eventful_building.html).

**Comment by BIMDeveloper** [comment]
Hi @martin1cerny,
the tutorial was very helpful which made me to catch the id and handling the events but I still cant catch the element by its id.

thanks in advance.
Micheal

**Comment by martin1cerny** [comment]
Hi Micheal,

I'm glad you found the tutorials useful. Could you be more specific on what
you are trying to achieve please?

Martin
Dne 1. 6. 2015 16:26 "BIMDeveloper" <notifications@github.com> napsal(a):

**Comment by BIMDeveloper** [comment]
Hi Martin,
I'm trying to read the properties of the element like its type, family, location, (width, level, height if it has)
please find the below snap shots taken from desktop Xplorer
![image](https://cloud.githubusercontent.com/assets/12292418/7933679/08c90e28-0921-11e5-984c-a8c0e1a6f635.png)
![image](https://cloud.githubusercontent.com/assets/12292418/7933708/588d1738-0921-11e5-854b-8e1ab257bb3b.png)
![image](https://cloud.githubusercontent.com/assets/12292418/7933723/7367ee70-0921-11e5-813a-f047220ede34.png)


Thanks,
Micheal

**Comment by martin1cerny** [comment]
Hi Micheal,

the xViewer class is only handling geometry visualization. It uses wexbim file which only contains compressed preprocessed geometry. If you need to access semantic data related to the element you need a semantic JSON file which is a hierarchical structure representing COBie view on IFC file. xBIM can produce both wexbim and JSON files. You need to use [xBrowser](http://xbimteam.github.io/XbimWebUI/xBrowser.html) class to visualize/access the semantic data. I haven't written the tutorial for this yet but if you get the latest code of [XbimWebUI](https://github.com/xBimTeam/XbimWebUI) project the initial page will show you all you need.

I hope this helps,

Martin

**Comment by Harara81** [comment]
Thanks Martin you can close this issue

Micheal
