### ISSUE TITLE
Touch Event Not working on Google Chrome- Android

### ISSUE THREAD

**Issue by mukeshmishra997** [xBimTeam/XbimWebUI#110]
I have created a Sample Web App and try to open in Google Chrome on Android Platform. But, I am unable to rotate the 3d view and Pinch to Zoom.

**Comment by martin1cerny** [comment]
Current WebUI doesn't implement touch navigation. Feel free to contribute by extending current functionality.

**Comment by mukeshmishra997** [comment]
I worked on touch functionality and it is working as I needed for now. I want to you review with code once and help it to improve for better performance. Please let me know steps to contribute to this repo.

**Comment by martin1cerny** [comment]
The best way to contribute is to use [GitHub pull request](https://help.github.com/articles/creating-a-pull-request/).

**Comment by palktonderAtpowelno** [comment]
Is something happening here? I'm really looking for touch functionality and would like to try this out

**Comment by martin1cerny** [comment]
No pull request from @mukeshmishra997 yet.

**Comment by GeorgDangl** [comment]
I think this issue can be closed, the functionality is present now (see 9a8c2c8).

**Comment by palktonderAtpowelno** [comment]
Right now it's only part of the develop branch. When will this be merged to the master branch?

**Comment by martin1cerny** [comment]
We need to improve build performance first. Georg has already suggested some changes but I didn't find the time to review it and sort it out. That might also affect deployment strategy. Will merge it into master after that.

**Comment by martin1cerny** [comment]
Closing the issue because the functionality is available in `develop` branch already.
