### ISSUE TITLE
jsmin.exe and spacker.exe

### ISSUE THREAD

**Issue by chadbimuser** [xBimTeam/XbimWebUI#111]
I would like to know what are jsmin.exe and spacker.exe used for? I've seen them in the "XbimWebUI" solution.

Thanks!

**Comment by martin1cerny** [comment]
These are compile time utilities. [jsmin.exe](https://github.com/Taritsyn/JSMin.NET) is used to minify javascript files and [spacker.exe](https://github.com/xBimTeam/XbimWebUI/tree/master/Utilities/ShaderPacker) is used to minify shaders and convert them into javascript strings. It is more convenient to keep shaders in separate files with .c extension which gives better syntax highlighting and is easier to read/maintain.
