### ISSUE TITLE
Selection of scene objects

### ISSUE THREAD

**Issue by chadbimuser** [xBimTeam/XbimWebUI#112]
Hi,
Do the libraries support?
1- Keep the selected objects on scene opaque and make the unselected ones transparent
2- Change the color of or mark somehow the select object on scene

Thanks

**Comment by martin1cerny** [comment]
Yes it does. See the tutorial [here](http://xbimteam.github.io/XbimWebUI/tutorial-5_Colourful_building.html). Colours are rgb**A** so you can set any transparenty you want. Also see the documentation about [X-Ray rendering mode](http://xbimteam.github.io/XbimWebUI/xViewer.html#renderingMode) which can be combined with state of the objects [HIGHLIGHTED and XRAYVISIBLE](http://xbimteam.github.io/XbimWebUI/global.html#xState).
