### ISSUE TITLE
Json file with metadata

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimWebUI#114]
Hello!

How was created Lakeside Restaurant.json? Or any other json file with metadata?
there is a utility to create them? What is?

Regards, Oleg

**Comment by martin1cerny** [comment]
It is our own schema called COBieLiteUK and is implemented in XbimExchange where you can also find a code for conversions. However, converting complete model into single JSON semantic file is not viable for large models. Resulting files tend to be too large for web publishing.
