### ISSUE TITLE
Problem with custom Home plugin image

### ISSUE THREAD

**Issue by andykazmaier** [xBimTeam/XbimWebUI#115]
Hello,

There seems to be a problem with the xNavigationHome.prototype.init function.  When you try to load a custom image, it breaks on the addEventListener calls.

Currently, the calls look like this:

image.addEventListener(...)

That image variable only exists if no image is passed to the constructor.  Instead, they should look like this:

self._image.addEventListener(...)

I'll try to push those changes up sometime this week.  Just wanted to log this in case anyone had trouble using it.  Thanks,

Andy

**Comment by martin1cerny** [comment]
Thanks Andy, looking forward to merging this pull request in.
