### ISSUE TITLE
Background change into white on Mozilla Firefox

### ISSUE THREAD

**Issue by mukeshmishra997** [xBimTeam/XbimWebUI#116]
Hi,
When I open XbimWebUI on Mozilla Firefox. Canvas background color change to white.

![image](https://cloud.githubusercontent.com/assets/22657475/19507850/11c7c978-95f3-11e6-8f2a-f19a43bb9217.png)

Can you please check what is the issue.

**Comment by martin1cerny** [comment]
Hi @mukeshmishra997 , [background](http://xbimteam.github.io/XbimWebUI/xViewer.html#background) is a property of the viewer. You can set it to anything you want.
