### ISSUE TITLE
Is it possible to add markers on Selected Object

### ISSUE THREAD

**Issue by mukeshmishra997** [xBimTeam/XbimWebUI#117]
Hi,

I am trying to add markers on Selected Object. Is this functionality feasible with XBim.

Thank you!

**Comment by martin1cerny** [comment]
No, this is not supported in XbimWebUI.

Dne 19. 10. 2016 8:33 napsal uživatel "mukeshmishra997" <
notifications@github.com>:

**Comment by mukeshmishra997** [comment]
Thank you so much.........

**Comment by martin1cerny** [comment]
No, any contributions are welcome.
