### ISSUE TITLE
How to convert Ifc To Wexbim Using IfcStore Function??

### ISSUE THREAD

**Issue by mukeshmishra997** [xBimTeam/XbimWebUI#118]
Hi,
I am trying to convert Ifc file to Wexbim using IfcStore. Can you please help me how I will achieve this functionality.

I have noticed when I am trying to convert Ifc to Wexbim using XbimExchange the "Write" function missing under "Xbim3DModelContext".
Below is XbimExchange details:
Runtime Version :  v4.0.30319
Version : 3.1.0.0

**Comment by martin1cerny** [comment]
Try this simple code:
```CS
using System.IO;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;

namespace CreateWexBIM
{
    class Program
    {
        public static void Main()
        {
            const string fileName = "SampleHouse.ifc";
            using (var model = IfcStore.Open(fileName))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var wexBimFilename = Path.ChangeExtension(fileName, "wexBIM");
                using (var wexBiMfile = new FileStream(wexBimFilename, FileMode.Create, FileAccess.Write))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter);
                        wexBimBinaryWriter.Close();
                    }
                    wexBiMfile.Close();
                }
            }
        }
    }
}

```

**Comment by mukeshmishra997** [comment]
IfcStore.Open can't able to open Ifc files. Its throwing below exception.

Additional information: Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The system cannot find the file specified.

**Comment by martin1cerny** [comment]
I just run it on my PC and it works perfectly fine. `'ICSharpCode.SharpZipLib` is a dependency of xBIM Essentials NuGet package. If you use NuGet to get xBIM all should be sorted out for you.

**Comment by martin1cerny** [comment]
@mukeshmishra997 do you still have this issue?

**Comment by mukeshmishra997** [comment]
No, Thank you for help.

**Comment by oliviersaintgobain** [comment]
Hello,
I use NuGet to get xBIM and this assembly seems to be present.
But, I still have the same issue than describe with this error : 
Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The system cannot find the file specified.

thanks for your help.

olivier
