### ISSUE TITLE
Converting to wexbim - Removing elements from a .wexbim File to improve Performance

### ISSUE THREAD

**Issue by CBenghi** [xBimTeam/XbimWebUI#119]
_From @dazmahal on December 14, 2015 14:14_

Hi folks
Query related to Converting to wexbim -
Our developer has worked on .json file removing any unwanted elements, and after the web optimization got  the payload down from 70mb to < 5mb.
Can we undergo a similar process with the .wexbim file - What type of elements can be removed without effecting its integrity?

Thanks
Darren

_Copied from original issue: xBimTeam/XbimExchange#7_

**Comment by martin1cerny** [comment]
Hi @dazmahal, as well as with JSON file this highly depends on what you actually need to show. WexBIM file doesn't contain any information which wouldn't be necessary to create a 3D view. The only way to decrease its size is to remove some objects from your 3D view.

**Comment by martin1cerny** [comment]
Also this question should rather be asked in Exchange or Essentials because XbimWebUI doesn't have anything to do with data conversion/filtering etc.

**Comment by andyward** [comment]
I think we should close here. Optimising/stripping the Wexbim file would be a Essentials issue as Martin says.
