### ISSUE TITLE
Conversion Problem: Not creating a complete JSON file from Ifc file

### ISSUE THREAD

**Issue by dhundaleamol** [xBimTeam/XbimWebUI#12]
Hi 

Not converting a complete JSON file for some ifc file.It create only facility and floor types in tree.
It is not generating a space and asset type .

Problem occur mainly big size of ifc files.

**Comment by dhundaleamol** [comment]
Hello ,

I am using Xbim.COBieLite.dll, v1.0.0.0 dll for converting a json file. 
In helper object , I am getting a count ZERO of spaceAssestLookup and spaceFloorLookup. But I am getting a count of DefiningTypeObjectMap .

I think,Its a dll problem of old version. If you have a latest a version of Dll ,Please send me .

**Comment by CBenghi** [comment]
Hi Amol,
I'd suggest that you try downloading the source of the xbim.exchange solution and try to convert your file there.
In this way you can have a better idea if the specific failure mode.
We are happy to help once you isolate the problem clearly.
Best, 
Claudio

**Comment by dhundaleamol** [comment]
Hi Claudio,

I have alredy tested my ifc file with latest XbimExchange source, I have got a same incomplete file conversion . That source is also not generating spaceAssestLookup and spaceFloorLookup..Due to count of Zero of both , The tree is not generating a properly.(ie assets and space is not available in tree).
I have sent you screenshot of small size of ifc file tree and big size ifc file tree,Hope so ,It will help you .
![bigfile](https://cloud.githubusercontent.com/assets/10378872/7697684/7018f0b6-fe27-11e4-9099-82ce5346a5cd.png)
![smallfile](https://cloud.githubusercontent.com/assets/10378872/7697685/70282ef0-fe27-11e4-9999-176bc4da3e73.png)

**Comment by martin1cerny** [comment]
Hi Amol, can you please confirm/inspect that the source IFC file itself contains the data you expect? It is hard to tell what is the problem from your explanation.

**Comment by dhundaleamol** [comment]
I have tested file with solibri software() which generates tree correctly but same thing I am doing with wexbim source some nodes are not binding

**Comment by dhundaleamol** [comment]
![bigfile](https://cloud.githubusercontent.com/assets/10378872/7702828/93f1dc72-fe50-11e4-8c4c-e900eb76eed0.png)
In above large size file count for SpaceAssetLookup and SpaceFloorLookup comes 0 which should not correct but If I use simple IfC file shows count for  SpaceAssetLookup and SpaceFloorLookup as below
![smallfile](https://cloud.githubusercontent.com/assets/10378872/7702831/953b1c7e-fe50-11e4-96d8-b96e6e54210d.png)

**Comment by martin1cerny** [comment]
Can you share the IFC file Amol?

**Comment by dhundaleamol** [comment]
Okay .
Please check this following link  for ifc file download.
https://www.dropbox.com/s/fqmejl85aet29u9/MEP%20-%20Central%20-%2014.ifc?dl=0

and also check [XbimWebUI] Error in converting Ifc file to wexbim (#7). issue regarding a performance if possible for you.

**Comment by martin1cerny** [comment]
Hi Amol. The model you sent here doesn't contain any spaces. The JSON is a hierarchical representation of COBie data where it is a requirement that every element is defined in a space from where it is being serviced. We may handle the case where elements are referenced into storey, building or site but it is an additional processing.

**Comment by martin1cerny** [comment]
For the performance issue start the new issue thread please. It is unrelated to the original issue and makes it messy.

**Comment by dhundaleamol** [comment]
Hi Martin , 
So you want to say that,Ifc file is not contain spaces?But, It shows a tree in other software as follows.
![untitled](https://cloud.githubusercontent.com/assets/10378872/7724753/1ee44dda-ff12-11e4-9b5a-abd4ae46175e.png)

Could you please provide me the steps or way to check if the input ifc file is correct.
Also how did you check the model file for spaces .

I have all ifc files which is related to Buliding elements.

**Comment by ranjitchapale** [comment]
Hi Martin,
     How can we check the ifc file is correct or not, Is there any way to check it in source code?

**Comment by CBenghi** [comment]
The treeview on the model that the viewer makes by default is based on IfcSpaces.
Since your model does not have any spaces defined it lacks the element in the treeview.
A way to check that programmatically is to look for instances of IfcSpace within a model with code like:

```csharp
var hasSpaces = Model.Instances.OfType<IfcSpace>().Any();
```

The option then is to build a different hierarchical view of the model; that will take a little more work. 

You might also want to read up on how to include spaces when exporting IFC from your BIM tool (Revit, in the case of the file above).

**Comment by martin1cerny** [comment]
To @dhundaleamol: Your tree view is right - elements are referenced on the level of IfcBuildingStorey, **not IfcSpace**.

**Comment by dhundaleamol** [comment]
Hey Martin,

Please tell me this issue . 
Why complete assest is not generating in JSON file.
I am sending you screenshot .
![stree](https://cloud.githubusercontent.com/assets/10378872/7861796/dff6ae2e-056f-11e5-96e0-b22f1ff93cf1.png)

Here Red color part is not generating in my tree.
This is my tree screen shot as follows
![bimtree](https://cloud.githubusercontent.com/assets/10378872/7861829/0c27b268-0570-11e5-89b1-777cda83bff1.png)

Why this is not creating . T/FDN contain IFCWALLSTANDARDCASE . and also IFCSITE name is also not creating. 

Please tell me .why this is not generating.For your reference ,i have sent you IFC file.
https://www.dropbox.com/s/0ti6xw7pjo9p3c5/Duplex_A_20110907.ifc?dl=0

**Comment by martin1cerny** [comment]
As I said before. These elements are not assigned to any space in your IFC. As you can see in Solibri they are assigned to a floor called T/FDN, **NOT A SPACE**. JSON structure generated from IFC is a COBie view of the building which assumes everything of interest to be assigned to a space. There is a way around this but you would have to either change the original IFC (which is perfectly possible and easy to do with xBIM) or change the export so that it creates COBie space from the IfcBuildingStorey. This is also possible and not hard to do.
