### ISSUE TITLE
Taking a too much time to convert from ifc to wexbim 

### ISSUE THREAD

**Issue by CBenghi** [xBimTeam/XbimWebUI#120]
_From @Marks10 on December 3, 2015 10:54_

Hi ,
I am trying to convert 600MB ifc file ,It is converted but it takes a near about 1 hour for that.
Please help me to reduce time for this.

My hardware configuration is as follows:
1) NVIDIA graphics card- 2gb
2)
![configure](https://cloud.githubusercontent.com/assets/16130194/11558714/41c32cdc-99da-11e5-9d15-4d5b80e7177f.png)

_Copied from original issue: xBimTeam/XbimExchange#6_

**Comment by martin1cerny** [comment]
This question should really be asked in other place (Exchange, Essentials or Geometry) because XbimWebUI doesn't have anything to do with the conversion.
