### ISSUE TITLE
Magic number mismatch from a converted IFC to WEXBIM file

### ISSUE THREAD

**Issue by b3it-om** [xBimTeam/XbimWebUI#122]
Hi, 

So i followed the tutorial found here for the xbimviewer-sample: http://xbimteam.github.io/XbimWebUI/ using the provided model "SampleHouse.wexbim", everything worked fine. The model rendered fine and all. Then i wanted to try to use my own model of a building which is in *.ifc format. 

I first used the XbimConvert-application found in the XbimUtilities-master solution. The conversion seemed to work fine, BUT i was given a *.xBIM.file that didnt work with the xbimviewer-sample app? I then used the project XbimWindowsUI-master to open my ifc-file and export as wexbim. But now i got another error in the web-console -> row 240 in xbim-viewer.debug.bundle.js : "if (magicNumber != 94132117) throw '_Magic number mismatch_.';". 

As i understand it the 'magic number mismatch' error means something like that the file is missing a key binary sequence at the beginning of the file that is supposed to verify that the wexbim is indeed a wexbim and not just another file that happens to be named ending in .wexbim?

What am i doing wrong and how can i in the most simple way display my *ifc file in the  xbimviewer?

Regards, om

**Comment by martin1cerny** [comment]
See this example please: https://xbimteam.github.io/examples/creating-wexbim-file.html

**Comment by martin1cerny** [comment]
Did it work @b3it-om ?

**Comment by xyjwyq** [comment]
@martin1cerny     log4net:ERROR Failed to find configuration section 'log4net' in the application's .config file. Check your .config file for the and elements. The configuration should look like : ` <section name ="log4net" type = "log4net. Config. Log4NetConfigurationSectionHandler , log4net"/>  `

**Comment by martin1cerny** [comment]
http://docs.xbim.net/examples/watch-the-log.html
