### ISSUE TITLE
Combining WeXBIM Files Client-Side

### ISSUE THREAD

**Issue by VisualMelon** [xBimTeam/XbimWebUI#124]
Good day,

We are working on a client-server BIM application, which needs to work offline, adhere to limited storage requirements, and minimise bandwidth. As a result, we are keen to package up independent chunks of WeXBIM files (created from different (non-intersecting) subsets of IFC files by xBIM), which can be distributed separately, and recombined into a single navigable model by the client (JavaScript).

We are impressed by the ease of use of xBIM, and the XbimWebUI, but are unclear if there is existing capability for combing such WeXBIM files in JavaScript, or perhaps a reference in another language (I can't see anything in the xBIM APIs).

Having looked at the code to parse them, it looks perfectly feasible to write a combiner, but we've not been able to find a specification for the WeXBIM format, and wanted to ask if it's just eluding us before going ahead and deriving one.

**Comment by martin1cerny** [comment]
Hi @VisualMelon , there is no written specification for wexBIM file format but you will see it is not very complicated. The code is [here](https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc/IfcStore.cs#L979). xViewer is perfectly capable of showing multiple wexBIM files. Just use [load](http://xbimteam.github.io/XbimWebUI/xViewer.html#load) function multiple times. So you don't really need to combine binary files.

**Comment by VisualMelon** [comment]
@martin1cerny Thank you very much indeed! I am slightly saddened to hear there is no spec, but reusing load will surly meet our use-case with considerably less effort.

Thank you again for your insightful and swift response. Feel free to close this, though I wonder if the combining capability would be useful otherwise (though it probably ought be another issue).

**Comment by martin1cerny** [comment]
We didn't design wexBIM format to be a public standard. If you feel it would be beneficial to document it feel free to contribute. I'll be happy to add it to our web site.

**Comment by VisualMelon** [comment]
I've confirmed that simply calling load twice (would be too easy, wouldn't it?!) works as intended. Thank you again for your guidance, and in such short order.

Feel free to close this, though if there is other interest in combining files, then it may be best to leave it open (or create a new issue).
