### ISSUE TITLE
problem in xviewer.js

### ISSUE THREAD

**Issue by oliviersaintgobain** [xBimTeam/XbimWebUI#125]
hello, I'm new in usage of XBim. 
I'm trying to get a webviewer and I want to test the XBim library and especially xviewer.

When I run the sample code, I have this error message 
"0x800a1391 - Erreur d’exécution JavaScript: « xShaders » est indéfini"

in the source code of xviewer.Js, the referent line is :
 //fragment shader
    var fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
    compile(fragmentShader, xShaders.fragment_shader);

I don't see in the code where the xshaders object is created....

thanks for your help.

just to show the sample code:
<!DOCTYPE html>
<html>
<head>
    <title>Hello building!</title>
    <script src="Viewer/xbim-viewer.debug.js"></script>
    <script src="Scripts/webgl-utils.js"></script>
    <script src="Scripts/gl-matrix.js"></script>
</head>
<body>
    <canvas id="viewer" width="500" height="300"></canvas>
    <script type="text/javascript">
        var viewer = new xViewer('viewer');
        viewer.load('data/SampleHouse.wexbim');
        viewer.start();
    </script>
</body>
</html>

**Comment by LloydPickering** [comment]
Have a look at https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-shaders.debug.js

Note this is generated from the .c files alongside.

**Comment by martin1cerny** [comment]
Do you use the NuGet [distribution package](https://www.nuget.org/packages/XbimWebUI)? It seems you are missing reference to some JS files. Final JS files are built as a (minified) bundle of source files. Also have a look at [documentation and tutorials](http://docs.xbim.net/XbimWebUI/).

**Comment by oliviersaintgobain** [comment]
thanks for your answers.
I used Nuget distribution :
Xbim.essentials
xbim.bcf
xbim.webui (I have validated replacement of js files)
I have tested again and I still have the same problem.
I have all Js requested in the example described in the document in your link (I used same code and the data folder).

Olivier

**Comment by LloydPickering** [comment]
Olivier your code sample is loading this:
<script src="Viewer/xbim-viewer.debug.js"></script>

the example provided by Martin is loading this:c
<script src="js/xbim-viewer.debug.bundle.js"></script>

**Note that these are different.** 

If you have all the files from Nuget, then it should be as simple as referencing the correct bundled javascript file as in Martin's example.

**Comment by oliviersaintgobain** [comment]
thanks again. You are right.
it's working now.
I close the issue (which was not really one).

have a nice day.

olivier
