### ISSUE TITLE
io filenotfound exception to open IFC

### ISSUE THREAD

**Issue by oliviersaintgobain** [xBimTeam/XbimWebUI#126]
Hello,
I use NuGet to get xBIM and this assembly seems to be present.
But, I still have the same issue than describe with this error :
Could not load file or assembly 'ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73' or one of its dependencies. The system cannot find the file specified.

thanks for your help.
![xbim](https://cloud.githubusercontent.com/assets/22198623/21045613/6d21522c-be01-11e6-9c1e-2ff506749e9b.PNG)

![image](https://cloud.githubusercontent.com/assets/22198623/21045661/92b2caca-be01-11e6-9909-328b2f42590e.png)

olivier

**Comment by martin1cerny** [comment]
This seems to be down to your deployment. SharpZipLib is a dependency package of xBIM Essentials. Check that you have it installed please.

**Comment by oliviersaintgobain** [comment]
I don't know why, but the dll was not in the directory.
that's ok now.
sorry...
