### ISSUE TITLE
Stream wexBim files

### ISSUE THREAD

**Issue by DrorSegev** [xBimTeam/XbimWebUI#127]
Hi,
I'm looking for a way to stream wexBim files while processing it.
We have some 50M files that are slow to download and slow to process.
If possible I can download it in a chuncks and let the viewer process while downloading.

Thanks
Dror Regev

**Comment by martin1cerny** [comment]
Hi Dror,

complete IFC model is necessary to create any wexBIM file(s). This is not a
constraint of xBIM but the nature of IFC. It is not a hierarchical model
but interrelated graph so partial upload and processing would require
complex client side code which would need to extract particular data
islands. These data islands would be overlapping so the final upload would
be even bigger.

Best regards

Martin

Dne 29. 12. 2016 13:14 napsal uživatel "DrorSegev" <notifications@github.com

**Comment by DrorSegev** [comment]
Hi Martin, Thanks for your reply.
I'm not talking about the creation of the wexBim files. Since we need to display large plans (ifc - 400M) 
I'm creating the wexBim files in the background. They are getting a size of around 50M.
The problem is with the download to the browser. currently the viewer download the file and than process it. Is it possible to download in chuncks and process the graphics in parallel?
Dror

**Comment by martin1cerny** [comment]
Hi Dror,

I am sorry I didn't understand the original question. It is possible to
extract multiple partial wexBIM files and to process them per partes. See
IfcStore.SaveAsWexBim() arguments. Background worker might make it parallel
but it won't solve the overall download time. This is possible but not
supported out of the box.

Regards

Martin

Dne 5. 1. 2017 9:24 napsal uživatel "DrorSegev" <notifications@github.com>:

**Comment by DrorSegev** [comment]
Great start.
It will not solve overall download time but it might give a better user expirience- the user will see the model built gradually.
Does the  web viewer support multiple wexbim files as input( which are all for the same model)?
Dror

**Comment by martin1cerny** [comment]
Yes it does. Just load them all.

Dne 6. 1. 2017 11:16 napsal uživatel "DrorSegev" <notifications@github.com>:

**Comment by DrorSegev** [comment]
Thanks!!!!

Dror

**Comment by OmarKhairyHosny** [comment]
Hi Dror,
@DrorSegev Can you show your solution ? 

Omar

**Comment by DrorSegev** [comment]
hi. we decided to stop using this tool.

**Comment by OmarKhairyHosny** [comment]
Hi Dore,

I hope everything is groovy with you
why did you decide to stop using xbim ?

Regards,
Omar

**Comment by DrorSegev** [comment]
The main issue was IFC limitations - specially for mimic revit links
behavior

Dror

**Comment by OmarKhairyHosny** [comment]
Did you find another way or solution ?Did

Omar

**Comment by DrorSegev** [comment]
we are working directly with autodesk forge api
Dror
