### ISSUE TITLE
Sync elements in view and browser

### ISSUE THREAD

**Issue by AhuvaCohen** [xBimTeam/XbimWebUI#128]
Hi everybody

I show the tree in the left, and the drawing in the middle of the page.
When a user double clicks element in the drawing, I want to highlight this element in the tree.
How can I do that?
Thanks a lot!

**Comment by CBenghi** [comment]
Hello,
what you describe should be the default behaviour of the application.
I'm surprised it does not work for you; this is a feature that has been in the viewer for a long time.
We need more information to see what the problem might be.

Can you try again downloading the following file, then selecting different walls and see if it works?
https://github.com/xBimTeam/XbimEssentials/raw/master/Xbim.IO.Tests/TestFiles/4walls1floorSite.ifc
Thanks,
Claudio

**Comment by martin1cerny** [comment]
This is not implemented in the simple thee view. You would need to make some simple changes in the `xBrowser` class in the `_renderTreeView()` private function to encode entity ID for every leaf. You get an ID from the double click in `xViewer` and than just use jQuery to expand the tree, scroll to the right `<li>` element and select it.
Or you can enhance internal representation of the model to contain references to respective `<li>` elements and you can work from that. Either way you will need to do some changes in the code.
