### ISSUE TITLE
Set camera with different direction vector values

### ISSUE THREAD

**Issue by theTIOM** [xBimTeam/XbimWebUI#129]
Hi, I have a question regarding "setCameraPosition" function as below.

**xViewer.prototype.setCameraPosition = function (coordinates) {
    if (typeof (coordinates) == 'undefined') throw 'Parameter coordinates must be defined';
    mat4.lookAt(this._mvMatrix, coordinates, this._origin, [0,0,1]);**

I understood that this function presents BIM model views with "coordinates" values and a direction vector value that calculated using "coordinates" and "this._origin" values. I assumed it is correct, hence, I changed "this._origin" values to see views with different direction vectors, but it was not working. 

How can I visualize different vector views with same coordinate values? Do I have to revise  "xShaders.fragment_shader," "xShaders.vertex_shader," and "xShaders.vertex_shader_noFPT" parts regarding "mat4?" If my thought is correct, what lines or files should be changed?

**Comment by martin1cerny** [comment]
Your first assumption is correct. You don't need to change anything in shaders. I don't know why this wouldn't work. I just checked and it is perfectly fine. 
```js
mat4.lookAt(viewer._mvMatrix, [20000,20000,2000], [0,0,2000], [0,0,1]);
```
You just need to use the right units. That might be why it didn't have the effect you expected. As you said, these are coordinates in the model space. So if the model is in millimetres you have to use millimetres.

**Comment by theTIOM** [comment]
Thanks for your confirmation. I realized that it was related to Google Chrome cookie. After erasing cookie, everything was fine.
