### ISSUE TITLE
Problem to create JSON file from Big IFC file

### ISSUE THREAD

**Issue by sunilgurav241** [xBimTeam/XbimWebUI#13]
I am working on xBIMTeam project but we facing one problem to convert IFC file to JSON file.
At the conversion, IFC file completely converted but issue in creating JSON file that issue come when file size greater than 100mb.

Please give me idea to convert complete file size in JSON.

**Comment by martin1cerny** [comment]
Hi @sunilgurav241 ,

could you try to explain the problem more in detail please? I've seen bigger models converted before so it is hard to tell where the problem lies from your description.

Martin

**Comment by andyward** [comment]
I think we close this. If it's an issue still it should be in [XbimExchange](https://github.com/xBimTeam/XbimExchange) anyway.
