### ISSUE TITLE
How to convert IFC data format to WexBIM data format？

### ISSUE THREAD

**Issue by xyjwyq** [xBimTeam/XbimWebUI#131]
Excuse me! I want to use your CreateWexBIM program to convert IFC data into WexBIM data, but there are a lot of errors, and the resulting exe file can not be used, can you help me solve it? Thank you!

log4net:ERROR Failed to find configuration section 'log4net' in the application's .config file.  Check your .config file for the <log4net> and <configSections> elements.  The configuration should look like : `<section name ="log4net"  type = "log4net.  Config.  Log4NetConfigurationSectionHandler , log4net" />`

**Comment by martin1cerny** [comment]
This is not an exception it only fails to find a valid logging configuration. See this example for reference please:
http://docs.xbim.net/examples/watch-the-log.html

Also, `CreateWexBIM` is not a part of `XbimWebUI` project so this is not the right place to raise the issue.

**Comment by xyjwyq** [comment]
Thanks, my question got a good solution!
At the beginning I got this question in the `XbimWebUI `, but didn‘’t get the answer, so……! I'm sorry about this！
I have seen the question of walking function in the issyes of the project, I also tried the solution, but the experience is not particularly good! Is there a better way now?

**Comment by xyjwyq** [comment]
@martin1cerny Thanks, my question got a good solution!
At the beginning I got this question in the `XbimWebUI`, but didn‘’t get the answer, so……! I'm sorry about this！
I have seen the question of walking function in the issyes of the project, I also tried the solution, but the experience is not particularly good! Is there a better way now?

**Comment by martin1cerny** [comment]
No, there is no built-in walking navigation. Feel free to contribute.
