### ISSUE TITLE
JS Error in Rendering Wexbim File on Mozilla Browser

### ISSUE THREAD

**Issue by ravigarg1** [xBimTeam/XbimWebUI#132]
Hello xBIM Team,
![getting error in model viewer](https://cloud.githubusercontent.com/assets/10277898/23748001/cffedb44-04e7-11e7-8575-5926b9d58205.PNG)

First of all thanks to your efforts. It is very useful library to parse and display .IFC files. 

We are facing an issue where some of the files are not being displayed in the browser. Some files render with out any issue and some files don't render the 3d model at all? No error comes no message displays, just it will not show up there.

I tried to figure out in Mozilla and found there is some JS issue. Can any one let me know what could be the reason behind this? This file is opening properly in other viewers like Tekla BIMsight very easily.

Attached is the screenshot of error.

RangeError: invalid array length 
xTriangulatedShape.prototype.parse   in /modelview/Viewer/xbim-triangulated-shape.debug.js:41:13
xModelGeometry.prototype.parse in /modelview/Viewer/xbim-model-geometry.debug.js:162:9
xModelGeometry.prototype.load/br.onloaded in /modelview/Viewer/xbim-model-geometry.debug.js:236:9
xBinaryReader.prototype.load/xhr.onreadystatechange/fReader.onloadend in /modelview/Viewer/xbim-binary-reader.debug.js:28:29

Thanks.

**Comment by martin1cerny** [comment]
Hi @ravigarg1 , this is very hard to tell without having the data. Which NuGet versions of XbimWebUI, XbimEssentials and XbimGeometry do you use? Can you share the IFC file and/or the wexBIM file?

**Comment by ravigarg1** [comment]
Hello Martin,

**Which NuGet versions of XbimWebUI, XbimEssentials and XbimGeometry do you use?** 
Geometry - 4.0.11, Essential - 4.0.27, We downloaded WebUI from GitHub - https://github.com/xBimTeam/XbimWebUI
**Can you share the IFC file and/or the wexBIM file?**
Pls follow the link - https://www.dropbox.com/sh/1ivgeio6q0srq92/AAAfovs37cJ3yZ6EDOEJw0XKa?dl=0
Let me know once you have downloaded files

**Comment by martin1cerny** [comment]
Got the files.

**Comment by martin1cerny** [comment]
I just had a look and your file contains huge amount of complicated Boolean geometry. Your file comes from Telka. Where I love that they store geometry as extrusions and sweeps it makes the resulting triangulated geometry very heavy. Our desktop viewer (XbimXplorer) can open it but even that took almost 10GB of RAM. WexBIM file only contains triangulated geometry of the model and 100MB of condensed geometry is pretty huge. I tried to open it in several browsers and the result is the same for all of them. GPU just crashes under the load of too much data. Unfortunately, it doesn't give any reasonable message or anything. It just dies. This model is simply behind abilities of WebGL and/or our implementation. If you find a WebGL tool which could handle this model I'd love to have a look to learn something new.

**Comment by ravigarg1** [comment]
Thanks. Will explore and come back to you with my findings, if any.

**Comment by ravigarg1** [comment]
Hello Martin,

Today i tried to upload a tiny file and found the 3D viewer died again. IFC file was very small - 5mb and wexbim file is only 295kb. Still Mozilla threw error. I suspect there might be some issue in code because this time file size is very less compared to previous files.

Note- I downloaded latest WebUI today and tried to run the wexbim file in that. No custom code is in the code.

`RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer  xbim-binary-reader.debug.js:79:9`

```
![js error in xbim webui](https://cloud.githubusercontent.com/assets/10277898/24030353/80c44ef8-0b02-11e7-8ccc-429c67ead7a3.PNG)

xBinaryReader.prototype.read http://localhost:5981/Viewer/xbim-binary-reader.debug.js:79:9
	xBinaryReader.prototype.readFloat32 http://localhost:5981/Viewer/xbim-binary-reader.debug.js:101:12
	xTriangulatedShape.prototype.parse http://localhost:5981/Viewer/xbim-triangulated-shape.debug.js:9:21
	xModelGeometry.prototype.parse http://localhost:5981/Viewer/xbim-model-geometry.debug.js:162:9
	xModelGeometry.prototype.load/br.onloaded http://localhost:5981/Viewer/xbim-model-geometry.debug.js:236:9
	xBinaryReader.prototype.load/xhr.onreadystatechange/fReader.onloadend http://localhost:5981/Viewer/xbim-binary-reader.debug.js:28:29
```

**Comment by ravigarg1** [comment]
Same issue in Chrome as well -

Uncaught RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (native)
    at xBinaryReader.read (http://localhost:5981/Viewer/xbim-binary-reader.debug.js:79:9)
    at xBinaryReader.readFloat32 (http://localhost:5981/Viewer/xbim-binary-reader.debug.js:101:17)
    at xTriangulatedShape.parse (http://localhost:5981/Viewer/xbim-triangulated-shape.debug.js:9:31)
    at xModelGeometry.parse (http://localhost:5981/Viewer/xbim-model-geometry.debug.js:162:19)
    at xBinaryReader.br.onloaded (http://localhost:5981/Viewer/xbim-model-geometry.debug.js:236:14)
    at FileReader.fReader.onloadend (http://localhost:5981/Viewer/xbim-binary-reader.debug.js:28:34)

**Comment by martin1cerny** [comment]
Can you share the IFC file? I will have a look.

**Comment by ravigarg1** [comment]
https://www.dropbox.com/s/dfre4rx2699hd00/3D_Model_Concrete.ifc?dl=0

Pls let me know once you get the file..

**Comment by martin1cerny** [comment]
I just tried with the latest code and I could visualize it in Firefox, Chrome, Edge and Internet Explorer:

![image](https://cloud.githubusercontent.com/assets/773078/24046949/954da88e-0b24-11e7-9d96-b38c7a92178e.png)

I only used sample code as presented [here](http://docs.xbim.net/examples/creating-wexbim-file.html), with the latest nugget packages.

**Comment by ravigarg1** [comment]
Strange.

I created a new project and updated latest WebUI and tried to run but still there is error. But if we take Essential and Geometry from Nuget and convert with the code you pointed out, WebUI is working properly.

Thanks!
