### ISSUE TITLE
Size of wexbim file

### ISSUE THREAD

**Issue by DrorSegev** [xBimTeam/XbimWebUI#133]
Hi.
I'm using a standard in-session IFC export from revit.
My IFC File size in about 30M.
The output wexbim file size is 160M
This is wired cause in most cases wexbim size is about 10% of IFC.
What should I check?

Dror

**Comment by martin1cerny** [comment]
This might be a case for some models containing many swept solids with complicated curved profiles in which case it can be written on a few lines in IFC file but would generate very large number of triangles in a mesh. That is very likely for MEP models. Can you try to run simple analysis like this?

```cs
var items = model.Instances.OfType<IfcRepresentationItem>().GroupBy(i => i.GetType());
foreach(var item in items)
{
    Console.WriteLine($"Type: {item.Key.Name}, Count: {item.Count()}");
} 
```

That will show frequency of geometry representation types. You might want to play with deflection in `model.ModelFactors` **before** you create geometry context to make the triangulation more coarse. It can save some volume. Or if you can advise author of the model it might be a good idea to simplify profiles if possible. They are often a lot more detailed than necessary.

Martin

**Comment by martin1cerny** [comment]
Also this is not an issue to be asked in XbimWebUI. It should be asked in XbimGeometry.

**Comment by DrorSegev** [comment]
You are right. 
I'm going to supply answers three. Can you please help me?


Dror
