### ISSUE TITLE
Does xBIM support Reinforcement (rebar) display in WebUI

### ISSUE THREAD

**Issue by ravigarg1** [xBimTeam/XbimWebUI#134]
Hello Martin,

Need a bit of your help. I have an ifc file which is having Concrete + Reinforcement or Rebar elements in the model.

When we check the file in Tekla Bimsight it shows all the elements like below -
![image](https://cloud.githubusercontent.com/assets/10277898/24740586/858632e0-1abf-11e7-8abd-d78b4a2e4266.png)

But when i check in xBIM Viewer it shows only concrete item and not Rebar items -
Normal mode of xBIM
![image](https://cloud.githubusercontent.com/assets/10277898/24740842/c43ffe20-1ac0-11e7-8410-b4dde61ebfbc.png)

X-Ray mode of xBIM
![image](https://cloud.githubusercontent.com/assets/10277898/24740853/d425a1e6-1ac0-11e7-861b-4deb8127a5c1.png)

I checked that Tekla shows these Reinforcing bar elements when transparency level is changed like xBIM X-ray mode.

Below is the sample file attached.
[Sample IFC Model for xBIM.zip](https://github.com/xBimTeam/XbimWebUI/files/901683/Sample.IFC.Model.for.xBIM.zip)

Is there any option or mode in xBIM 3D viewer to show Reinforcing bars from IFC model

**Comment by martin1cerny** [comment]
It is there. It is just X-Ray mode which is perfect to put **selected** or **highlighted** objects in context but doesn't sort out transparency ordering. So your reinforcement bars are still hidden. If you try to hide the concrete item

```cs
viewer.setState(Xbim.Viewer.State.HIDDEN, [55])
```

you will see it

![image](https://cloud.githubusercontent.com/assets/773078/24742038/b26d0d90-1aa8-11e7-85d6-d22cb2b61521.png)

**Comment by ravigarg1** [comment]
Thanks. It took us some time to figure out where to use that code to give it as a functionality.

Is it possible that we can view both - concrete and rebar in one view?

**Comment by martin1cerny** [comment]
Sure, set the style of the concrete to be semitransparent.
