### ISSUE TITLE
deactivate entity

### ISSUE THREAD

**Issue by theextremeandy** [xBimTeam/XbimWebUI#135]
I work on activateEntity function and I need to deactivate current selection without using the resetStates () command.

Can you please help me?

**Comment by martin1cerny** [comment]
The best way is to keep track of your selected entity and call `setState(State.UNDEFINED, [entityId])` on the previous selection.

**Comment by theextremeandy** [comment]
Martin
you are right!
tanks

ps.
I used a variable objSelectedId to set previous selection
                        if (objSelectedId != 0)
                        {
                            viewer.setState(State.UNDEFINED, [objSelectedId]);
                        }
                        objSelectedId = id;
                        viewer.setState(xState.HIGHLIGHTED, [id]);
                        browser.activateEntity(args.id);
                        keepTarget = true;
