### ISSUE TITLE
Nuget package update

### ISSUE THREAD

**Issue by andyward** [xBimTeam/XbimWebUI#136]
Do we have plan/timescale for a nuget/myget release of the latest 0.3.x code in develop? There's been a fair few fixes since the last release in December that would be useful to get out...

e.g. I've a few wexbim files that won't load on 0.1.41 ('Invalid typed array length' in xTriangulatedShape.parse) but do open in the latest when built locally on the latest develop code

Incidentally, I wasn't able to build a nuget package locally. Not sure if that's my environment (VS 2017) or an issue with the new WebPack 2 work. Main error seems to be:

`Build:Module '../../Build/xbim-viewer' was resolved to '[path]/XbimWebUI/Xbim.WeXplorer/Build/xbim-viewer.js', but '--allowJs' is not set.	Xbim.WeXplorer	[path]\XbimWebUI\Xbim.WeXplorer\Examples\TsSingleModule\index.ts`

**Comment by andyward** [comment]
Update: I've fixed build issue. The above TS example was Importing from the Build folder not the Viewer folder. Will push up later

**Comment by martin1cerny** [comment]
Great @andyward. I noticed there was a build issue but the changes in API are code breaking so I didn't hurry to fix it. You will have realized already that thanks to @GeorgDangl it is all upgraded to use TypeScript and WebPack which produces UMD packages now.

**Comment by andyward** [comment]
Hi @martin1cerny . Yes I noticed. Good job  - it's a lot more maintainable now. Appreciate it's still work in progress. 

One other tip for others building on VS2017 - make sure you install the latest VS15.2 updates or the lib.webworker.d.ts typings may be out of date.

Sounds like we should get a package to Myget develop anyway?

**Comment by martin1cerny** [comment]
Yes, you are right. We should fix it to produce a valid NuGet package. 

Regarding the original issue: If I understand your fix it had probably broken the example. It **should** reference the file in `Build` folder. Compiler should have picked the `xbim-viewer.d.ts` file existing alongside the `xbiim-viewer.js` and compile without problems. That is the case in my development environment at least.

**Comment by andyward** [comment]
I'm a little confused then 😄 

I don't have any .d.ts typings in the Build folder. I'm guessing the TypingsBundler is supposed to create these (but I don't claim to understand what it's doing). This is my Build folder after building
![image](https://cloud.githubusercontent.com/assets/923699/25958118/c0a54afa-3667-11e7-9afc-ca5337ee557f.png)

Prior to my change, TsSingleModule and TsModulesExample each imported Viewer from different folders  - TsSingleModule referenced /Build while TsModulesExample references /Viewer (where there is a viewer.d.ts)

Have you tried cleaning out your Build folder with the latest code?

**Comment by martin1cerny** [comment]
You are right, TypingsBundler utility should do that. As I said I didn't regard the current state as being ready for publishing yet so I didn't check that.

**Comment by martin1cerny** [comment]
However, after-build batch file contains line which should do it.

**Comment by martin1cerny** [comment]
I can see the problem now. It is in a after-build event but that doesn't get called because it fails to compile the typescript. It is cyclic and impossible now. If you run the utility on its own now it should generate the file and allow further compilation and work.
