### ISSUE TITLE
Performance Issue: To display a  viewer diagram in Browser.

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#14]
Hi,

As you suggest ,a  Graphics card is required  in Issues #7 .
We are tested application on M/c which have a graphics card.
The overall funcionality is working fine .But When the diagram is loaded on browser ,browser is still Hanged for a min. I am sending you a screenshot regarding a browser .

1) Chrome
![chrome](https://cloud.githubusercontent.com/assets/10378872/7835403/5269b79c-0496-11e5-8ff2-c683583983aa.png)
2) FireFox 
![Uploading firefox.png…]()

**Comment by martin1cerny** [comment]
Hi Amol,

Graphic card is necessary but integrated GPU should be all right for many
models and that is present in almost all modern devices.

The problem you are facing is related to very big JSON file containing
semantic structure and data about the building. I've been looking at this
for a while and there are several strategies you might want to deploy. The
easiest is to strip the overall amount of data. It is the case most of the
time that your user is not interested in all data in the model. I'd
recommend to delete CreatedBy, CreatedOn, ExternalSystem and Categories in
all objects for start. These are important but not for a visualization.
This would strip your model down to 40% of the original size. You should do
this on server as a part of the JSON file creation.

Another way is to implement your own tree view (which would be very easy
using some existing plugins to any popular javascript ui framework) and
fetch only data you need. Actual I implementation is very simplistic and it
creates view model of the whole structure and tree view might get very big
even if you only see the top level.

Martin
Dne 27. 5. 2015 14:06 napsal uživatel "Amol D" <notifications@github.com>:

**Comment by dhundaleamol** [comment]
Hi Martin ,

I think , Its takes a time to read a binary data in Xbim.binary.reader.js  instead of reading a Json file.
When .wexbim model is loaded ,browser will hang for a some minute(ajax loader icon is also stop) for a big size of ifc file. 
This is my issue Martin.

And I am using 4GB and 2GB graphics card  on two machines respectively. Still Browser will be hanged ,when wexbim model is loaded. But , the overall smoothness is working fine due to graphics card .

Please suggest any clue to avoid this .

**Comment by dhundaleamol** [comment]
![issues](https://cloud.githubusercontent.com/assets/10378872/8103753/9a098e5c-1048-11e5-8726-6a7cbb491666.png)

Refer this screenshot . Beowser is hanging when parsing is processing . Hanging time is depend on parsing time.

**Comment by martin1cerny** [comment]
Try to get the latest code please. I have speeded up this particular function 3 times about 2 weeks ago. It takes time to parse the compressed binary data. You can use timeout function inside the parsing loop to keep the loader running but that will only make loading a lot longer.

Martin

**Comment by LloydPickering** [comment]
Martin,

Another thing you could do (when you get time, and if not already done) is to pass the parsing off the a Web Worker. This will keep the browser responsive while it's chugging away on the binary. The important thing is if you are going to use web workers, to also support the transferable objects so it passes the buffers to the web workers by ref instead of a copy.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers
https://developer.mozilla.org/en-US/docs/Web/API/Transferable

Lloyd

**Comment by martin1cerny** [comment]
Thanks Lloyd,

I'll have a look on this. I don't do this so far but you are right it is a
way to go.

Martin


2015-06-15 11:24 GMT+02:00 Lloyd Pickering <notifications@github.com>:

**Comment by martin1cerny** [comment]
To  @LloydPickering: The major problem I found is that IE11 doesn't support transferable objects as [you know](https://connect.microsoft.com/IE/feedback/details/793722/ie11-feature-request-support-for-shared-workers-and-transferable-objects). Current implementation works fine even for IE11. Using anything else to pass data from web worked would increase RAM usage significantly. I'll keep looking and thinking about this.

**Comment by LloydPickering** [comment]
Martin,

Yep, but what you can do is test for the presence of transferable and degrade gracefully to not using the standard web workers in browsers which don't support them. It's not ideal, but when IE does support them, no code changes are necessary for it to take advantage of the situation.

Lloyd

**Comment by martin1cerny** [comment]
Thanks Lloyd, I have in plan to do it that way in the close future.

**Comment by dhundaleamol** [comment]
Thanx Martin.

**Comment by BIMDevelopement** [comment]
Hi @LloydPickering ,@Martin

I am trying to implement a web worker for parsing function of xbim-model-geometry.debug.js. But I am unable to implement that concept here.

xModelGeometry.prototype.load = function (source) {
    //binary reading
    var br = new xBinaryReader();
    var self = this;
    br.onloaded = function () {
        self.parse(br);
        

        if (self.onloaded) {
            self.onloaded();
        }
    };

    br.onerror = function (msg) {
        if (self.onerror) self.onerror(msg);
    };
    $('#blocker').show();
    br.load(source);
};


Here , I want to Put this line in web worker    self.parse(br);

Can you suggest me , How do it ?

**Comment by martin1cerny** [comment]
I'm sorry but you will have to provide us with more detail. Parse function is implemented in the same file. It is called from `self` local variable only to put it into the right scope when the callback is called from another object.

**Comment by BIMDevelopement** [comment]
Yes , I knew it . For a big file , My browser will hang for moment while parsing is done. SO that , I am trying to implement worker concept on that parse function. But I am fail to implement that .

**Comment by martin1cerny** [comment]
I did understand this part. I also thought about implementing this but my development priorities are located in a different part of xBIM now. But if you need any help or assistance you will have to provide more detail about what you do and what you've tried.

**Comment by BIMDevelopement** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10378872/12255603/84bb83e4-b91b-11e5-9483-12af71d6b2b8.png)

**Comment by martin1cerny** [comment]
You need either to copy all the code you need into your parseworker.js (including implementation of readInt32()) or you will have to [include other scripts](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Importing_scripts_and_libraries) which means you will only create proxy worker, include all scripts needed and than use them. 

But this all has a little to do with WebUI so I'd recommend you to study [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) and structure of WebUI project yourself.
