### ISSUE TITLE
Opening elements not shown in WexBim

### ISSUE THREAD

**Issue by Holgenberg** [xBimTeam/XbimWebUI#140]
Hi, 

In xBim Explorer, Opening Elements seem to show. However, when a WexBim file is created, the elements seem to disappear in the SimpleViewer.html. Any Idea why this is?

Attached is the IFC file.
[Lucion.zip](https://github.com/xBimTeam/XbimWebUI/files/1122024/Lucion.zip)

**Comment by martin1cerny** [comment]
Openings are excluded from wexBIM file by default. If you want you can have a look in the code in `IfcStore` and enhance it.

**Comment by Holgenberg** [comment]
Thanks, I fixed it by using an extrusion for the wall instead of a Faceted Brep

**Comment by Holgenberg** [comment]
Sorry to bother again,

I looked further into the issue. It seems that when openings are created in relation to Brep wall, the extrusion creates an element out of the same material as the wall rather than a void. Repeating this with an extruded wall yielded a void. I am trying to create a void in the Brep wall, where [I am](url
[LucionExtrudeAndBrep.zip](https://github.com/xBimTeam/XbimWebUI/files/1156386/LucionExtrudeAndBrep.zip)

) going wrong?

**Comment by martin1cerny** [comment]
Not sure if this is the reason but your file with BRep geometry is not a valid IFC as it breaks the rule [WR24](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcrepresentationresource/lexical/ifcshaperepresentationtypes.htm) of `IfcShapeRepresentation`. You state that the shape representation is `Brep` but than it references `IfcExtrudedAreaSolid`.

**Comment by martin1cerny** [comment]
Also, this issue doesn't have anything to do with the XbimWebUI project. It should be asked in [XbimGeometry](https://github.com/xBimTeam/XbimGeometry) where the data is processed and converted into triangulated representation for visualization.
