### ISSUE TITLE
Help: How To move the model 

### ISSUE THREAD

**Issue by XbimUser** [xBimTeam/XbimWebUI#141]
Hi I'm using xbimWebUI to browse the IFC model, and I need to transform the specified shape now. How can I do that? Thank you for your guidance

**Comment by martin1cerny** [comment]
This isn't supported. WexBIM file is designed for a static content. If you need to change it you will need to change the original definition in IFC and recreate the wexBIM file.

**Comment by XbimUser** [comment]
Thank you for your prompt reply, I just checked in, and commented "foreach (var kv in lookup.Where (v = v.Value = = 1))" in Xbim3DModelContext.cs, and change" if (repetition > 1) "to "if (repetition > 0)" in xbim-model-geometry.js,    this._model.matrices  seems to be able to do some work,   but cannot move the specified shape, Is this method correct? What is your suggestion?

**Comment by martin1cerny** [comment]
What kind of transformation do you want to do? Is it simple translation? Or do you also want to scale? Rotate? Change the shape completely? You can put in some additional transformations in the area you highlighted but you would have to do it both for single instances and for mapped instances in the same way. Commenting this section will only lead to data loss.

**Comment by XbimUser** [comment]
I just need to translate and rotate ,thanks

**Comment by martin1cerny** [comment]
Than, you are looking at right places.

**Comment by XbimUser** [comment]
Thank you so much!

**Comment by XbimUser** [comment]
My test code is as follows:
```
********  Xbim3DModelContext.cs*************************************************
          //write out the multiple  instances and single instances 
    foreach (var kv in lookup){
        .......}
 *********************** xbim-model-geometry.js  ************************************************************      
  
  if (repetition > 0) {//repetition > 1
                transformation = version === 1 ? br.readFloat32(16) : br.readFloat64(16);
                this.matrices.set(transformation, iMatrix);
                var m = {
                    pLabel: prodLabel,
                    iLabel: instanceLabel,
                    startIndex: iMatrix,
                    matrix: transformation
                };
                this.matrixMap[prodLabel] = m;
                iMatrix += 16;
            }

**********************  xbim-model-handle.js       *****

 for (var i = 0 ;i <  100 ;i+=16) {
          this._model.matrices[i+12]+=1000;
     };
   this.matrixTextureSize = this._bufferTexture(this.matrixTexture, this._model.matrices, 4);
```

The above code works to achieve the desired results, but the following code is confusing results, Can you give me some more directions? Thanks!

  ```
for (var l = 0; l < args.length; l++) {
        var id = args[l];
        var map = this.getProducMatrixtMap(id);
        if (map != null) maps.push(map);
    }
    for (var k = 0 ; k < maps.length ; k++) {
        var map = maps[k];
        var ntransform = mat4.multiply(mat4.create(), map.matrix, transform);
   
            this._model.matrices.set ( ntransform,map.startIndex);
            map.matrix  = ntransform;
   
    } ;
    this.matrixTextureSize = this._bufferTexture(this.matrixTexture, this._model.matrices, 4);
```
