### ISSUE TITLE
3DModel is not getting rendered though wexbim is created.

### ISSUE THREAD

**Issue by pagumakwana** [xBimTeam/XbimWebUI#142]
IFC is getting converted to wexbim. I get to see the 3D Model only once out of 10 times. I tried on another system as well. Please let me know the solution. It display unresponsive script on browser i.e too long time time but doesn't render 3D Model. Please find the attached file.
![script_load_issue](https://user-images.githubusercontent.com/14257643/28109200-d7554b5e-670b-11e7-8033-c9461c11573c.png)
[Recovery_IFC_R1.zip](https://github.com/xBimTeam/XbimWebUI/files/1141373/Recovery_IFC_R1.zip)

**Comment by GeorgDangl** [comment]
As far as I understand it, this is caused when the imported geometry is very large. The model geometry is read and rendered in a synchronous process, and if this takes too long (for big models), browsers may display the warning that you've shown.

I think this can be solved by splitting the parsing process up, e.g. dividing large models in chunks and load them one-by-one with a `setTimeout` call to yield in between chunks.
I've thought about looking into that myself, but haven't come around to do it yet.

**Comment by pagumakwana** [comment]
Thanks. Let me know if you come up with any other solution.

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It has `viewer.loadAsync()' function which offloads part of processing to a web worker. Also, new TS compiler seems to produce more efficient code in general.
