### ISSUE TITLE
Properties available for selection id in simpleviewer.html

### ISSUE THREAD

**Issue by Holgenberg** [xBimTeam/XbimWebUI#144]
Hi, I am just wondering how to make the properties of building elements viewable on a viewer similar to the simpleviewer.html? I am not looking for anything too complex.

**Comment by martin1cerny** [comment]
You can use our convertor in [xBIM Exchange](https://github.com/xBimTeam/XbimExchange) to extract JSON data from IFC model and than tie it together with 3D view. Or you can use [xBIM Essentials](https://github.com/xBimTeam/XbimEssentials) to access raw IFC data and serve it any way you want.
