### ISSUE TITLE
Issue when resizing

### ISSUE THREAD

**Issue by chadbimuser** [xBimTeam/XbimWebUI#147]
Hi,
I am building an MVC application to load ifc models on the web page, using XbimWebUI library (I got it through Nuget)
The models are being loaded on scene with no issue, however, when resizing the window, the model disappears from the scene and doesn't appear again until I hover over it with the mouse.
Is there any way to keep it on scene?
Thanks

**Comment by GeorgDangl** [comment]
Hey Chad,

without looking at the code, could you subscribe to the browser windows `resize` event and call the `draw()` method on the viewer after every window resize? Could be working, but I could also be totally on the wrong path=)
