### ISSUE TITLE
Screenshot/snapshot from canvas

### ISSUE THREAD

**Issue by palktonderAtpowelno** [xBimTeam/XbimWebUI#148]
Hi, I'm trying to get a screenshot/snapshot of the xViewer canvas to use in BCF.

I tried to use the following code:

    const width = 400;
    const height = 400;
    const backCanvas = document.createElement('canvas');
    backCanvas.width = width;
    backCanvas.height = height;
    // save main canvas contents
    const backCtx = backCanvas.getContext('2d');
    backCtx.drawImage(this.viewerCanvas, 10, 10, width, height);
    this.savedData.src = backCanvas.toDataURL('image/png');

but the created image is just transparent. Is there a way to do this?

**Comment by martin1cerny** [comment]
The viewer doesn't preserve the drawing buffer at the moment so the image data in not available.

**Comment by palktonderAtpowelno** [comment]
So there is no way to tap into the painting process to draw to an image rather than the canvas?

**Comment by Girjesh25** [comment]
Is there any way to save the image from canvas dynamically for further processing.
or to copy canvas current view as Image to other canvas control.

**Comment by dzakmic** [comment]
> Resolved by setting preserveDrawingBuffer = trure

Can you provide some explanation or help how to implement this?

**Comment by Girjesh25** [comment]
> > Resolved by setting preserveDrawingBuffer = trure
> 
> Can you provide some explanation or help how to implement this?

You may search for **preserveDrawingBuffer = false** in all files and replace it with  preserveDrawingBuffer = trure

**Comment by dzakmic** [comment]
The following line `const backCtx = backCanvas.getContext('2d');` will return null because xBim is using WebGL and therefore you can get only 'webgl' context.
One of the easiest workarounds I found out is setting preserveDrawingBuffer as true just before loading your page.
There you can add simple javascript:

`HTMLCanvasElement.prototype.getContext = function (origFn) {
            return function (type, attributes) {
                if (type === 'webgl') {
                    attributes = Object.assign({}, attributes, {
                        preserveDrawingBuffer: true,
                    });
                }
                return origFn.call(this, type, attributes);
            };
        }(HTMLCanvasElement.prototype.getContext);`

**Comment by heltonmatiazi** [comment]
Dzakmic implementation solves this issue.
After preserving the buffer you can add something like this and attach it to a button that generates the snapshot:

canvas = document.querySelector("#viewer-canvas");
			gl = canvas.getContext("webgl");
			canvas.toBlob((blob) => {
				saveBlob(blob, `screencapture-${canvas.width}x${canvas.height}.png`);
			});

and in the save function:

let saveBlob = function (blob, fileName) {
let url = window.URL.createObjectURL(blob);
		let a = document.createElement("a");
		document.body.appendChild(a);
		a.style.display = "none";
		a.href = url;
		a.download = fileName;
		a.click();
}

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). Taking screenshots is a supported feature now.
