### ISSUE TITLE
entity with different color

### ISSUE THREAD

**Issue by theextremeandy** [xBimTeam/XbimWebUI#151]
I need to color some entities differently
something like:

                 var color = [255, 255, 255, 255]; // white
                 viewer.defineStyle (10, color);
                 viewer.setStyle (10, [id]);

but my code does not work
Can you please help me?

**Comment by theextremeandy** [comment]
I found that you can set the style after setting the status
this work!
```
var color = [255, 255, 255, 255]; // white
viewer.defineStyle (10, color);
viewer.setState(states.UNDEFINED, [id]);
viewer.setStyle (10, [id]);
```

**Comment by martin1cerny** [comment]
Shall I close the issue than?

**Comment by theextremeandy** [comment]
Yes Martin please!
