### ISSUE TITLE
Wrong representation of a geometry

### ISSUE THREAD

**Issue by annpag** [xBimTeam/XbimWebUI#152]
Hi, i use Xbim libraries to extract geometry information of a ifc file but i have a wrong representation of some objects. I installed Xbim.Geometry 4.0.11 and Xbim.Essentials 4.0.27 from Nuget. To create a smaller problem, i've extracted an object from the file and i've used some different software to visualize the result.
The result with Solibri (and also with Tekla BIMsight) is this: 
![image](https://user-images.githubusercontent.com/33696293/32882750-a740fc66-cab5-11e7-9d26-1755f8346f87.png)

The visualization with Xbim.WindowsUI (and with our software) is this:
![image](https://user-images.githubusercontent.com/33696293/32883011-6860de5c-cab6-11e7-9a2f-8fff7e246c17.png)

The ifc file is that:
[Progetto5.zip](https://github.com/xBimTeam/XbimWebUI/files/1477936/Progetto5.zip)

Thanks

**Comment by martin1cerny** [comment]
Can you try to use our develop NuGet feed (https://www.myget.org/F/xbim-develop/api/v3/index.json) please? There has been some development in this area since the last NuGet was published.

**Comment by annpag** [comment]
I tried to uninstall both libraries and use versions  from your develop NuGet, but visualization has not changed. Do you have any idea what the problem might be?

**Comment by martin1cerny** [comment]
Yes, this is often cause by poor quality geometry using faceted breps with Boolean operations. Will try to point my college to the case.

**Comment by CBenghi** [comment]
Hello @annpag,
this is very odd. The problems appear to be dependent on the radius of the circles drilled in the slabs.
I'll keep investigating.
Claudio

**Comment by martin1cerny** [comment]
That actually makes sense @CBenghi. The problem is caused by holes which are only partially overlapping the shape. When you change the diameter they are either outside or inside. But in particular configuration they will invert the volume so holes are solids and solids are holes which is what we see.

**Comment by CBenghi** [comment]
@martin1cerny, the tricky part is that by changing a digit in the 0.0000001 position of the radius the problem comes and goes... that's very odd.
I've tried to look at ways to identify the problem to rectify, but couldn't find one yet.

**Comment by martin1cerny** [comment]
Than it is likely to be a problem with precision and how geometry engine evaluates Boolean operation like this.

**Comment by CBenghi** [comment]
still minor changes in the radius (set manually) make or break the geometry. I've tested it.

**Comment by martin1cerny** [comment]
I remember Steve usually solved problems like these by setting better value of precision in OCC.

**Comment by CBenghi** [comment]
@martin1cerny, you are right, but I've tried that alley with no luck.
This actually seems to me like an occ bug, I'm trying to produce a test case to send them.

**Comment by annpag** [comment]
Thank you for your replies and interest!
If the problem is related to occ library, i'll wait for your news..

**Comment by CBenghi** [comment]
![image](https://user-images.githubusercontent.com/5476273/33221010-877b5576-d144-11e7-9e16-bf478da802b3.png)

I've got it!

Wow, this was difficult.
:)

I'll be pushing an update to geometry soon; mind you it's going to be in the develop branch for a while.
Claudio

**Comment by CBenghi** [comment]
The file now loads correctly in the latest xbimxplorer.
If you don't have it already download from http://docs.xbim.net/downloads/xbimxplorer.html
Otherwise it will update automatically at some point in the future...

**Comment by annpag** [comment]
Great!It's ok, thank you so much!!!!!! :)
