### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by XbimUser** [xBimTeam/XbimWebUI#153]
Hi, Under Android:
 [http://xbimteam.github.io/XbimWebUI/1_Hello_building.live.html](url)
does not load any content. 
Error: WebGL warning: Exceeded 2 live WebGL contexts for this principal, losing the least recently used one.
xbim-viewer.debug.bundle.js:2844:196
Error: WebGL warning: texImage2D: Unexpected error during upload: 0x0502
xbim-viewer.debug.bundle.js:753:9  
it's:    **_gl.texImage2D(gl.TEXTURE_2D, 0, type, size, size, 0, type, gl.FLOAT, image)_**

```
`xModelHandle.prototype._bufferTexture = function (pointer, data, arity) {
    var gl = this._gl;
    if (data.length == 0) return 0;

    //detect floating point texture support and data type
    var fp = this._fpt && data instanceof Float32Array;

    //compute size of the image (length should be correct already)
    var size = 0;
    var maxSize = gl.getParameter(gl.MAX_TEXTURE_SIZE);
    if (fp) {
        //recompute to smaller size, but make it +1 to make sure it is all right
        size = Math.ceil(Math.sqrt(Math.ceil(data.length / arity))) + 1;
    }
    else {
        var dim = Math.sqrt(data.byteLength / 4);
        size = Math.ceil(dim);
    }

    if (size == 0) return 0;
    if (size > maxSize) throw 'Too much data! It cannot fit into the texture.';

    gl.bindTexture(gl.TEXTURE_2D, pointer);
    gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, false); //this is our convention
    gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, false);  //this should preserve values of alpha
    gl.pixelStorei(gl.UNPACK_COLORSPACE_CONVERSION_WEBGL, gl.NONE);  //this should preserve values of colours

    if (fp) {
        //create new data buffer and fill it in with data
        var image = null;
        if (size * size * arity != data.length) {
            image = new Float32Array(size * size * arity);
            image.set(data);
        }
        else {
            image = data;
        }
        var type = null;
        switch (arity) {
            case 1: type = gl.ALPHA; break;
            case 3: type = gl.RGB; break;
            case 4: type = gl.RGBA; break;
        }
        **gl.texImage2D(gl.TEXTURE_2D, 0, type, size, size, 0, type, gl.FLOAT, image);**
    }
    else {
        gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, size, size, 0, gl.RGBA, gl.UNSIGNED_BYTE, new Uint8Array(data.buffer));
    }
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE); //Prevents s-coordinate wrapping (repeating).
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE); //Prevents t-coordinate wrapping (repeating).

    return size;
};`
```
Thanks

**Comment by martin1cerny** [comment]
Hi @XbimUser , from the log I can see two things:
1) It is [WebGL context error](https://www.google.cz/search?ei=sLEOWtOeBsey0gWL5Zf4CQ&q=Exceeded+live+WebGL+contexts+for+this+principal%2C+losing+the+least+recently+used+one&oq=Exceeded+live+WebGL+contexts+for+this+principal%2C+losing+the+least+recently+used+one&gs_l=psy-ab.3..0i30k1.2399.3346.0.3670.2.2.0.0.0.0.144.266.0j2.2.0....0...1.1.64.psy-ab..0.2.264....0.UYvmKpip-Lg) which we can do very little about. It might be caused by too many open tabs with WebGL or browser bug or having too many WebGL contexts on your page. Our viewer only uses one. 
2) Saying so, it doesn't handle loss of the context, hence the second error where upload of the texture failed after the context is lost. Feel free to contribute with PR to handle lost context gracefully.

**Comment by XbimUser** [comment]
Hi , @martin1cerny ,Thanks for your reply, but I can not access your link ( WebGL context error),So how to   modify  [ http://xbimteam.github.io/XbimWebUI/1_Hello_building.live.html](url)  so that it can access through Android?
thanks.

**Comment by martin1cerny** [comment]
The link points to Google search results. You can try to search for more about the webgl error. We have people using the viewer on Android devices so it is very hard to guess what is specific about your device or web browser. WebGL uses hardware acceleration and therefore has different behavior based on hw platform and browser implementation. It is virtually impossible to test all combinations.

**Comment by XbimUser** [comment]
Hi , @martin1cerny ,
Thanks for your reply,I have not found a solution, but I found that  Threejs and other 3D libraries can be viewed on my device, I will continue to look for solutions, if you have any new progress, please let me know, thank you！

**Comment by XbimUser** [comment]
Hi , @martin1cerny ,
I found that my device does not support "OES_texture_float", When i use the develop version of xbim-shaders.js, google debugging without any error reporting, using Firefox, suggesting that the error is Error: WebGL warning: Exceeded 2 live WebGL contexts for this principal, losing the least recently used one. and
 WebGL warning: texImage2D: Unexpected error during upload: 0x0502

I should do anything to solve this problem?
thanks.

**Comment by martin1cerny** [comment]
The only thing you can do is to test capabilities of the browser and show a message that the viewer can't run there. We took an approach to load all data in GPU memory to speed things up. But current WebGL version can only use floating point textures to load our data in one go. And it is available on absolute majority of devices. We made a decision based on [these stats](https://webglstats.com/webgl/extension/OES_texture_float). Saying so, I see for the first time that general support has dropped in June this year.  That is kind of unexpected. We might change how this works in the future but there is no plan to do this now.
