### ISSUE TITLE
Solution on Develop-branch broken

### ISSUE THREAD

**Issue by stonecompass** [xBimTeam/XbimWebUI#154]
Hi there! I wanted to use the mobile touch navigation functionality implemented on the develop-branch, but the solution seems to miss a lot of files, since any page I open gives me a ton of missing file errors.
Any way to fix this?

**Comment by martin1cerny** [comment]
Not sure what you mean. Can you share more information please?

**Comment by stonecompass** [comment]
Sorry for the vague desription.
I cloned the develop-branch and opened the solution in Visual Studio 2017.
When running the xbim.WeXplorer project the browser console gives me errors about some missing js-files, and I'm not sure if I just need to install some additional tools.

The errors are the following:

![screenshot_1](https://user-images.githubusercontent.com/6901364/33472450-9ef8325e-d672-11e7-95c0-ebf3a7127e41.png)

**Comment by martin1cerny** [comment]
I see. Yes, you will need to install Task Runner Explorer. That will watch the files based on webpack config. The build process is currently slightly broken in `development` branch. If you use Task Runner to build the project it should create all files you need.
