### ISSUE TITLE
ids in SampleHouse.json does not correspond with ids in SampleHouse.wexbim

### ISSUE THREAD

**Issue by pabloDon** [xBimTeam/XbimWebUI#155]
Hi!

I'm testing XbimWebUI with SampleHouse sample, but ids in wexbim file doesn't match with properties in JSON file, so I can't link elements and properties.

Maybe am I wrong? Please some light in this issue :smile: Thanks!

**Comment by martin1cerny** [comment]
You most probably use wexBIM file and JSON file which were not generated from the same IFC file so they are not synced.

**Comment by pabloDon** [comment]
I'm using resources from here: https://github.com/xBimTeam/XbimWebUI/tree/master/Xbim.WeXplorer/Resources/doctemplate/static/data

**Comment by pabloDon** [comment]
Ooops!! My fault! I've understood that resources are part of "facility" property. Sorry!

**Comment by CBenghi** [comment]
@martin1cerny,
what is the API to create the json file from xbim?
Is it in essentials or exchange?

**Comment by martin1cerny** [comment]
It is COBieLiteUK project in Xbim.Exchange.
