### ISSUE TITLE
To get geometry and json data of a particular object in a wexbim 

### ISSUE THREAD

**Issue by Anu004** [xBimTeam/XbimWebUI#159]
Hi,

I refered XbimWebUI-master and created an application  which opens and renders wexbim files. Now, I have to read a particular object(using entity label) from a wexbim file and need to display only that object. Is it possible? 

I have read the geometry data from ifc file and displayed that single object. But it takes much time since i'm calling CreateContext() of Xbim3DModelContext() to get the geometry.

**Comment by Anu004** [comment]
Seems like my question is not clear to you. Is it?

**Comment by martin1cerny** [comment]
You can either copy just a single object from original IFC into new IFC model and create a wexBIM file containing just a single object or you can hide all objects by type in WebUI and reset the one to `state.UNDEFINED`.
