### ISSUE TITLE
Problem trying to run XbimGeometryEngine

### ISSUE THREAD

**Issue by IFChaos** [xBimTeam/XbimWebUI#16]
Hello, i'm new in Xbim, i need to load the geometry of an IFC file, but i obtain this error.

"Could not load file or assembly 'Xbim.Geometry.Engine32.dll' or one of its dependencies. The specified module could not be found."

The same problem emerges when i try to open a IFC file using XbimXplorer

Any ideas on what i'm doing wrong?

**Comment by LloydPickering** [comment]
The Xbim Geometry Nuget package includes 2 unmanaged C++ dlls for geometry generation (Engine 32 and Engine 64). These are loaded when creating an Xbim file from an IFC file, and need to be in a subdirectory in your Working Dir/Bin folder.

Restoring the package should ultimately run the following Powershell Script to insert the files into your Solution and copy them on build, but if it does not you need to do this manually:
https://github.com/xBimTeam/XbimGeometry/blob/master/install.ps1

**Comment by IFChaos** [comment]
I copied Xbim.Geometry.Engine32 and Xbim.Geometry.Engine64 files in the BIN directory, but it still fails, i copied it in "Bin/Debug" also but still fails. I tried the same when running XbimXplorer, but anyway it fails. I tried it using folders X86 and X64 but it fails again.

I'm using a windows 7 x64 and Visual studio 2012. Maybe it's a problem of my computer.

I also tried to add both Dlls to the references, but anyway in XbimWindowsUI-master/XbimXplorer it is already present in references and it fails with the same error.

I'm lost at this point because i need to obtain the point coordinates and the triangles of columns, walls, etc.

**Comment by martin1cerny** [comment]
This whole issue thread should really be moved/asked in XbimGeometry repository as it is not related to XbimWebUI. Try to use NuGet distribution please. It should sort out all dependencies including geometry engine DLLs being placed to the right directory for you.

**Comment by IFChaos** [comment]
I'm sorry, i posted it in the wrong place, Is there a method to move it to XbimGeometry or i have to close it and open a new one?

**Comment by martin1cerny** [comment]
I'll try to move it there.

**Comment by martin1cerny** [comment]
This issue was moved to xBimTeam/XbimGeometry#2
