### ISSUE TITLE
Cannot change visibility of some objects

### ISSUE THREAD

**Issue by Anu004** [xBimTeam/XbimWebUI#160]
Hi,

In my wexbim viewer, in the tree view, I have added check-boxes for each item to turn them on or off.  And while trying to turn off all the objects, some remains there. I think there is a mismatch between their id in the json file and in the wexbim file. I have generated these files using 'ifcToCoBieLiteUkExchanger.Convert(), WriteJSON' and 'SaveAsWexBim'. Please check the attached screen shots. I'm attaching the ifc file also.
![ss2](https://user-images.githubusercontent.com/8133894/35209444-057afc08-ff74-11e7-84b3-899c1c9001f2.png)
![ss1](https://user-images.githubusercontent.com/8133894/35209445-05b6a60e-ff74-11e7-88b7-2a615e5a16be.png)
[Duplex_A_20110907.zip](https://github.com/xBimTeam/XbimWebUI/files/1651064/Duplex_A_20110907.zip)

**Comment by Anu004** [comment]
Do we have any other way to identify each objects in order to turn on and off all the objects ?

**Comment by martin1cerny** [comment]
You can use [types of objects](http://docs.xbim.net/XbimWebUI/global.html#xProductType) to do that.
