### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by adamblok** [xBimTeam/XbimWebUI#161]
In the `handleMouseScroll` function we look at the `event.deltaX` value which is horizontal scroll amount. Is this something we really need to? If a mouse's wheel scrolling is using for zooming out and in, then I think we shoud take care only of `event.deltaY`, but no `event.deltaX`.

The reason why I'm writing issue is that many mouses have actually three buttons in a wheel. These two extra buttons are used for horizontal scrolling. The problem in the XbimWebUI is when we try to move a model by clicking the middle button of a mouse. If we do that, then it's quite common to miss-click on an one of these two extra buttons for horizontal scrolling. The effects is that instead of just move a model, we also zoom it in or out. We could prevent this kind of situations by stop using `event.deltaX` in the `handleMouseScroll` function.

Anyway maybe there is some reason that we actually use `event.deltaX` in this function, but it seems to me that we could just stop using it. What do you think?

**Comment by martin1cerny** [comment]
This behavior is intentional but I agree it is not necessary. Feel free to make a PR.

**Comment by adamblok** [comment]
Ok, I'll do that soon.

**Comment by martin1cerny** [comment]
Fixed in PR.
