### ISSUE TITLE
very large fileload the file on the webis slow

### ISSUE THREAD

**Issue by jiisn** [xBimTeam/XbimWebUI#162]
if  my ifc file change to  webim file then get a very large file, when i##   load the file on the webis slow,and 
i use mouse to transform the model it become more slowly ,user can't  accept that,
so i want to ask if i want to change the situation,can you give me some suggest or direction.
thanks!

**Comment by martin1cerny** [comment]
The only thing I can suggest is to split the data. Web browser is a constrained sandboxed environment.
