### ISSUE TITLE
Adding an extra elements to a model

### ISSUE THREAD

**Issue by adamblok** [xBimTeam/XbimWebUI#164]
After a model is loaded, I need to add some extra 2D elements (like a sign) to it. These kind of elements should stick to a provided position, move and rotate with everything else. So it's something else than the navigation cube or the navigation home plugins, because these have fixed positions.

Could anyone show me a way I should follow to do that? Should I do that using the XbimWebUI's plugin interface or rather should I edit the source code of this library?

I'll be grateful for any help :).

**Comment by martin1cerny** [comment]
Plug-in is the best way to go. Have a look at how navigation cube is implemented. It renders in 3D world of the model. As you just said: It is just fixed position. So, render your signs where ever you want them to be. Consider contributing to the project if you feel it is a generally useful feature. Pull requests to `development` branch are welcome and appreciated.
