### ISSUE TITLE
3D model is not getting rendered

### ISSUE THREAD

**Issue by Dhruti03** [xBimTeam/XbimWebUI#165]
Hello,
I am facing an issue in rendering 3D model. IFC is getting converted to wexbim but am unable to view 3D model. Kindly let me know what is the problem and why model is not getting rendered. I am sharing IFC file of which model is not rendered.

[Test Model.zip](https://github.com/xBimTeam/XbimWebUI/files/1718465/Test.Model.zip)

Thanks.

**Comment by adamblok** [comment]
Could you attach also the wexbim file? I could try to open it in my environment

**Comment by GeorgDangl** [comment]
I can convert the IFC file to wexbim and also successfully load it in the viewer:

![download 1](https://user-images.githubusercontent.com/10274404/36152533-acbfb05e-10cb-11e8-8e80-2585f3f4df25.png)

I've used [this example project](https://github.com/GeorgDangl/xbim-meets-angular), however, I noticed that the generated wexbim file is almost 34MB, which is putting a bit of stress on the browser. It's working fine in Chrome for me, but is hardly usable in Opera, although it still renders in both browsers.

Does your browser console log any errors when you attempt to load the wexbim model?

**Comment by martin1cerny** [comment]
This is a Tekla model which typically contains large number of complex extruded profiles. I like this kind of geometry representation and it makes Tekla models very concise. But it has to be triangulated for rendering and this triangulated representation of curved sweeps is usually very large. Good news is that you can control how fine the triangulation is with **deflection angle and tolerance**. You can try some combinations if it makes difference. If the model contains many circular and curved profiles the difference might be significant. It will make no difference if profiles are straight line polygons.

```
using (var model = IfcStore.Open(fileName))
{
    var context = new Xbim3DModelContext(model);
    context.CreateContext();

    model.ModelFactors.DeflectionAngle = 1.0;
    model.ModelFactors.DeflectionTolerance = 0.1;

    var wexBimFilename = Path.ChangeExtension(fileName, "wexbim");
    using (var wexBimFile = File.Create(wexBimFilename))
    {
        using (var wexBimBinaryWriter = new BinaryWriter(wexBimFile))
        {
            model.SaveAsWexBim(wexBimBinaryWriter);
            wexBimBinaryWriter.Close();
        }
        wexBimFile.Close();
    }
}
```
