### ISSUE TITLE
Highlighted items being hidden in x-ray mode

### ISSUE THREAD

**Issue by shaneconaty** [xBimTeam/XbimWebUI#167]
Hello,
When I highlight an object and change to x-ray mode, it disappears. When I switch back to normal mode the item is still highlighted.
Has anyone seen anything like this before?
Highlighted Normal View
![image](https://user-images.githubusercontent.com/30483101/36202889-78572e16-117d-11e8-905b-56b55c4469cd.png)
Highlighted X-Ray View
![image](https://user-images.githubusercontent.com/30483101/36202911-89d351f6-117d-11e8-94c1-03efaaebbce1.png)
Not Highlighted X-Ray View
![image](https://user-images.githubusercontent.com/30483101/36202966-bda8d578-117d-11e8-8a1e-f2c8bd61da51.png)

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It keeps highlighted elements visible in x-ray mode. Also, there is new state `XRAY-VISIBLE` which makes products appear in x-ray mode with their normal colours.
