### ISSUE TITLE
Customize highlighted functionality color for XbimWebUI

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#17]
Hello, please could you advise on how can we customize the highlighted item color( by setting the style id for highlight)? 
I would like to give user the ability to set the color for highlighted items. 
thanks

**Comment by andyward** [comment]
Take a look at http://xbimteam.github.io/XbimWebUI/tutorial-5_Colourful_building.html which shows how to give different items their own style, and handle picking.

If you really want to change the default highlight colour you're probably going to have to change the shader code at: https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/vertex_shader.c#L167

**Comment by johnBim** [comment]
Hello,
thank you again for your help, I will check that.

regards

**Comment by martin1cerny** [comment]
You can also find it in the [latest version](http://xbimteam.github.io/XbimWebUI/xViewer.html#highlightingColour) now.

**Comment by johnBim** [comment]
Hello,
great!! thank you a lot :-)

**Comment by johnBim** [comment]
Hello Martin,
the highlighting doesn't work anymore even using the default or new set RGBA. the issue appears also in the demo of the documentation.
http://xbimteam.github.io/XbimWebUI/5_Colourful_building.live.html

Could you please help with this?

thanks again

**Comment by martin1cerny** [comment]
I'm sorry for that. This is an unrelated error introduced during the refactoring of the code. Just published the new version with the fix. Thanks for spotting this out.

**Comment by johnBim** [comment]
Hello Martin,
thanks i will check that
