### ISSUE TITLE
Transforming an object

### ISSUE THREAD

**Issue by adamblok** [xBimTeam/XbimWebUI#172]
Hi,

Is it possible to transform an object that is already loaded using 4x4 matrixes? I've tried to prepare a new method that push some transform matrix to the _transformationBuffer_ of the model, but the effect is that the model just disappears:

```javascript
xViewer.prototype.setModelPosition = function (modelId, params) {
    let handle = this._handles.filter(function (h) { return h._model.id === modelId }).pop();
    if (typeof (handle) === "undefined") throw "Model with id: " + modelId + " doesn't exist.";

    const model = handle._model;

    const transform = [
      1, 0, 0, 0,
      0, 1, 0, 0,
      0, 0, 1, 0,
      0, 0, 0, 1,
    ];

    model.transformations = [];
    model.transformations.push(transform);

    handle._bufferData(handle.transformationBuffer, model.transformations);
};
```

Am I doing something wrong? Is it even possible to do that in this way?

Thanks for every help and suggestion!

**Comment by martin1cerny** [comment]
Well, not really. Only some objects use transformation matrices. Those having a single instance are rendered without transformation so pushing transform in the buffer will not have any affect for them. You would have to change several other buffers which bind together specific instance and its transformation matrix index. Also, to save memory current implementation loads all transformations in the GPU and forgets it. You would need to keep it in memory to be able to alternate it.
