### ISSUE TITLE
Not able to get a screenshot of the model using "toDataURL()" 

### ISSUE THREAD

**Issue by adamblok** [xBimTeam/XbimWebUI#173]
I've recently noticed that it's not possible to get a screenshot of the loaded model using the "toDataURL()" method. Manually it works fine, when we use mouse's right button and select "Save image as" option.

To reproduce this simply go to http://docs.xbim.net/XbimWebUI/ and type in the browser's console:

```javascript
document.getElementsByTagName('canvas')[0].toDataURL();
```

It returns empty PNG image encoded by base64.

Did you guys know this issue and do you have any idea how to fix this?

**Comment by martin1cerny** [comment]
Yes, it has been asked before: #148
