### ISSUE TITLE
Getting a center point the camera is looking at

### ISSUE THREAD

**Issue by adamblok** [xBimTeam/XbimWebUI#178]
We've got the `getCameraPosition()` method, but is it possibile to also get a center point the camera is looking at? Do you think is it possible to retrieve this position from view and projection matrix?

I'll be grateful for any help! Thanks.

**Comment by martin1cerny** [comment]
This is possible but not straightforward. It is not possible to get this information from the view and projection matrix. You would need to project a ray to the centre of the screen and than use other techniques to get the Z coordinate from a depth buffer. See the question #77.

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It has functions to get 3D point of user interaction. You can use these to get a 3D point of the middle of the screen as well.
