### ISSUE TITLE
Wexbim test subjects doesnt work in Unity

### ISSUE THREAD

**Issue by luoyuke** [xBimTeam/XbimWebUI#179]
Hi everyone,
First I want to thank @liszto and @Vizzr for answering my question about Xbim.Geometry at Issue [https://github.com/xBimTeam/XbimGeometry/issues/94](url)  Now I'm jumping on the Wexbim boat and it has been working well this week!

What I have been doing so far: 
1. build an exe standalone(in my case a Revit Plugin) to save IFCdata as .Wexbim.
2. (Unity)Read Wexbim Stream and save Geometry information into mesh.
3. (Unity)Generate Mesh with corresponding style/Mat/Shaders and properties.

It works perfectly so far as long as I convert IFC to Wexbim in step one. But when I try to let unity to read the wexbim files from this repo ie. LakesideRestaurant.wexbim, Unity will throw :

**binaryreader ArgumentOutOfRangeException: Non-negative number required. Parameter name:
capacity**

Which bothers me because I can open both(the wexbim provided and the one I generated) using the viewer3D/Simpleviewer. Both must be valid, then what gives?

the error comes from line   **var triangulation = br.ReadShapeTriangulation();**

public class LoadAssetXbim : MonoBehaviour
{
    bool swch = false;
    // Use this for initialization
    public float Flo_convert(double input)
    {
        float result = (float)input;
        if (float.IsPositiveInfinity(result))
        {
            result = float.MaxValue;
        }
        else if (float.IsNegativeInfinity(result))
        {
            result = float.MinValue;
        }
        return result;
    }

    void Start()
    {
        Material true_mat = new Material(Shader.Find("Standard"));

        GameObject parent = new GameObject("WexbimModel");
        GameObject go;
        Mesh mesh;

        var editor = new XbimEditorCredentials
        {
            ApplicationDevelopersName = "yuke",
            ApplicationFullName = "ifc_to_unity",
            ApplicationIdentifier = "Your app ID",
            ApplicationVersion = "4.0",
            //your user
            EditorsFamilyName = "Luo",
            EditorsGivenName = "Yuke",
            EditorsOrganisationName = "Educational study"
        };

        const string fileName = "IFCBuilding";

        using (var fs = new FileStream(fileName+".wexBIM", FileMode.Open, FileAccess.Read))
        {
            using (var br = new BinaryReader(fs))
            {
                var magicNumber = br.ReadInt32();
                if (magicNumber != 94132117) throw new ArgumentException( "Magic number mismatch.");
                //   Assert.IsTrue(magicNumber == IfcStore.WexBimId);
                var version = br.ReadByte();
                var shapeCount = br.ReadInt32();
                var vertexCount = br.ReadInt32();
                var triangleCount = br.ReadInt32();
                var matrixCount = br.ReadInt32();
                var productCount = br.ReadInt32();
                var styleCount = br.ReadInt32();
                var meter = br.ReadSingle();
                //    Assert.IsTrue(meter > 0);
                var regionCount = br.ReadInt16();
                

                for (int i = 0; i < regionCount; i++)
                {
                    var population = br.ReadInt32();
                    var centreX = br.ReadSingle();
                    var centreY = br.ReadSingle();
                    var centreZ = br.ReadSingle();
                    var boundsBytes = br.ReadBytes(6 * sizeof(float));
                    var modelBounds = XbimRect3D.FromArray(boundsBytes);
                }

                
                for (int i = 0; i < styleCount; i++)
                {
                    var styleId = br.ReadInt32();
                    var red = br.ReadSingle();
                    var green = br.ReadSingle();
                    var blue = br.ReadSingle();
                    var alpha = br.ReadSingle();
                 
                    true_mat.SetColor(styleId, new Color(red, green, blue, alpha));
                }

                for (int i = 0; i < productCount; i++)
                {
                    var productLabel = br.ReadInt32();
                    var productType = br.ReadInt16();
                    var boxBytes = br.ReadBytes(6 * sizeof(float));
                    XbimRect3D bb = XbimRect3D.FromArray(boxBytes);
                }
                for (int i = 0; i < shapeCount; i++)
                {
                    var shapeRepetition = br.ReadInt32();
                    //   Assert.IsTrue(shapeRepetition > 0);
                    Debug.Log(" repes: " + shapeRepetition);
                    if (shapeRepetition > 1)
                    {
                        GameObject[] repes = new GameObject[shapeRepetition];
                        int[] ColorStyleId = new int[shapeRepetition];
                        for (int j = 0; j < shapeRepetition; j++)
                        {
                            var ifcProductLabel = br.ReadInt32();
                            var instanceTypeId = br.ReadInt16();
                            var instanceLabel = br.ReadInt32();
                            var styleId = br.ReadInt32();
                            var transform = XbimMatrix3D.FromArray(br.ReadBytes(sizeof(double) * 16));

                            
                            go = new GameObject(ifcProductLabel.ToString());
                            go.transform.parent = parent.transform;
                            repes[j] = go;
                            
                            //order of ro/po makes no diference
                            go.transform.rotation = new Quaternion(Flo_convert(transform.GetRotationQuaternion().X), Flo_convert(transform.GetRotationQuaternion().Y), Flo_convert(transform.GetRotationQuaternion().Z), Flo_convert(transform.GetRotationQuaternion().W));
                            go.transform.position = new Vector3(Flo_convert(transform.Translation.X / meter), Flo_convert(transform.Translation.Y / meter), Flo_convert(transform.Translation.Z / meter));

                            Debug.Log("-------Next Reps--------");
                            ColorStyleId[j] = styleId;
                           
                        }
                        var triangulation = br.ReadShapeTriangulation();
       
                        int TriangleIndexCount = 0;
                        

                        foreach (var face in triangulation.Faces)
                        {
                            foreach (var triIndex in face.Indices)
                            {
                                ++TriangleIndexCount;
                            }
                        }
                        
                        int VerticesCount = triangulation.Vertices.Count;
                        int FaceCount = triangulation.Faces.Count;
                        
                       Vector3[] vertices = new Vector3[VerticesCount]; //these eventully write into unity gameobject
                        int[] triangleIndices = new int[TriangleIndexCount];

                        //Debug.Log("styleId:" + styleId + ", ifcProductLabel: " + ifcProductLabel + ", faceCount: " + FaceCount + ", TriangleIndexCount: " + TriangleIndexCount);
                        int TriangleIndex;
                        foreach (var repete in repes)
                        {
                            int id = 0;
   
                            TriangleIndex = 0;
                            
                            for (int j = 0; j < VerticesCount; j++)
                            {
                                var vert = new Vector3(Flo_convert(triangulation.Vertices[j].X), Flo_convert(triangulation.Vertices[j].Y), Flo_convert(triangulation.Vertices[j].Z));
                                vertices[j] = vert / meter;
                            }
                            
                            for (int j = 0; j < FaceCount; j++)
                            {
                                for (int k = 0; k < triangulation.Faces[j].Indices.Count; k++)
                                {
                                    triangleIndices[TriangleIndex++] = triangulation.Faces[j].Indices[k];
                                }
                            }

                            repete.AddComponent<MeshFilter>();
                            repete.AddComponent<MeshRenderer>();
                            mesh = new Mesh() ;
                            repete.GetComponent<MeshFilter>().mesh = mesh;
                            
                            MeshRenderer meshRenderer = repete.GetComponent<MeshRenderer>();
                            meshRenderer.material.color = true_mat.GetColor(ColorStyleId[id++]);

                            mesh.vertices = vertices;// in unity vertices must defined before triangles
                            mesh.triangles = triangleIndices;

                            mesh.RecalculateNormals();
                            repete.AddComponent<MeshCollider>();
                        }
                        
                        //    Assert.IsTrue(triangulation.Vertices.Count > 0, "Number of vertices should be greater than zero");

                    }
                    else if (shapeRepetition == 1)
                    {
                        var ifcProductLabel = br.ReadInt32();
                        var instanceTypeId = br.ReadInt16();
                        var instanceLabel = br.ReadInt32();
                        var styleId = br.ReadInt32();
                        XbimShapeTriangulation triangulation = br.ReadShapeTriangulation();
                        //     Assert.IsTrue(triangulation.Vertices.Count > 0, "Number of vertices should be greater than zero");

                        go = new GameObject(ifcProductLabel.ToString());
                        go.transform.parent = parent.transform;
                        mesh = new Mesh();

                        go.AddComponent<MeshFilter>();
                        go.AddComponent<MeshRenderer>();
                        go.GetComponent<MeshFilter>().mesh = mesh;
                        MeshRenderer meshRenderer = go.GetComponent<MeshRenderer>();
                        meshRenderer.material.color = true_mat.GetColor(styleId);

                        int TriangleIndexCount = 0;
                        int TriangleIndex = 0;

                        foreach (var face in triangulation.Faces)
                        {
                            foreach (var triIndex in face.Indices)
                            {
                                ++TriangleIndexCount;
                            }
                        }

                        int VerticesCount = triangulation.Vertices.Count;
                        int FaceCount = triangulation.Faces.Count;

                        Vector3[] vertices = new Vector3[VerticesCount]; //these eventully write into unity gameobject
                        Vector3[] Norm = new Vector3[VerticesCount];//just make it all isometrical, wexbim has some absurd amount of normals in one face sometime.
                        Vector2[] UV = new Vector2[VerticesCount];
                        int[] triangleIndices = new int[TriangleIndexCount];
                        //Debug.Log("styleId:" + styleId + ", ifcProductLabel: " + ifcProductLabel + ", faceCount: " + FaceCount + ", TriangleIndexCount: " + TriangleIndexCount);

                        for (int j = 0; j < VerticesCount; j++)
                        {
                            vertices[j] = new Vector3(Flo_convert(triangulation.Vertices[j].X), Flo_convert(triangulation.Vertices[j].Y), Flo_convert(triangulation.Vertices[j].Z));
                            vertices[j] /= meter;
                        }
                        mesh.vertices = vertices;

                        for (int j = 0; j < FaceCount; j++)
                        {
                            
                            for (int k = 0; k < triangulation.Faces[j].Indices.Count; k++)
                            {
                                triangleIndices[TriangleIndex++] = triangulation.Faces[j].Indices[k];
                            }
                        }
                        mesh.triangles = triangleIndices;
                        mesh.RecalculateNormals();
                        go.AddComponent<MeshCollider>();

                    }
                    
                }

        
            }
        }
        Debug.Log("finish start");
    }
    private void Update()
    {

        if (!swch)
        {
            GameObject go = GameObject.Find("WexbimModel");
            go.transform.Rotate(-90f,0,0); //first generate Wexbim XYZ then rotate the parent to XZY
            
            foreach (var child in go.GetComponentsInChildren<Transform>())
            {
                if (child.gameObject.name == "WexbimModel")
                    continue;
                var goo = child.gameObject;                 //shader will always be stadart instance in start(), update it here to make it right
                MeshRenderer meshRenderer = goo.GetComponent<MeshRenderer>();
              
                meshRenderer.material.shader = Shader.Find("CullOffStandard"); //custome shader to render both sides of the face 
                
                if (meshRenderer.material.color.a <.95f)    //only rewrite the shader when alpha make a difference
                    meshRenderer.material.shader = Shader.Find("Transparent/VertexLit");
                 
            }
            swch = true;
        }
    }

here are some snips with my wexbim
[https://imgur.com/iGEYdt0](url)
[https://imgur.com/rB1dB6M](url)
[https://imgur.com/bSlY2Bm](url)
[https://imgur.com/4hwofrp](url)

Importing IFC into Unity is like walking in the minefield. xD Ask me anything regarding unity, and bare with the rough code for I am not in computer science major.

**Comment by martin1cerny** [comment]
Please, note that XbimWebUI is a clear javascript/typescript project so it is **unrelated to your issue**.

**Comment by luoyuke** [comment]
please move this thread to the right place. I dont know where to ask, thought it is related to wexbim. meanwhile i wll try to run this in command console to see if it's unity's Problem. If the binaryreader randomly picks up negative values from the Triangulation meathod, the reliability of the app i'm building will be put in jeopardy.

**Comment by liszto** [comment]
I'm not sure they can move it between project. 
Why not close this one and recreate it at the right place.

I think the best place would be xBimEssentials and not xBimGeometry

**Comment by luoyuke** [comment]
I'll post it in xBimEssentials instead then.
