### ISSUE TITLE
The function ZoomTo probable issue in XbimWebUI

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#18]
Hello
The function ZoomTo  in yhe xviewer sometime zooms too much, mostly in the case of a wall. for example. users have to zoom out a bit in order to see the element fully.
Is a way to fix that?

thank you

**Comment by andyward** [comment]
Try increasing the 'distance' factor used at https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L993

I found distance * 1.5 works better.

**Comment by johnBim** [comment]
Hello,
thank you for your help.
have a nice one

**Comment by johnBim** [comment]
Hello,
trying the distance*1.5 doesn't help indeed and strangely in my case distance/7 is better but I still  have a question:
is there a way to position the camera front of an element after zooming to... so we can just see that element ?
e.g
the current camera is showing the front door of the house, and somewhere in my elements list, clicking on the element of the back door of the house, the camera will be in front of that one and show it.

is it possible?

**Comment by andyward** [comment]
Hmm. Are you sure you're refreshing the browser? A better fix would have been to update this

`viewer._distance = size / Math.tan(viewer.perspectiveCamera.fov * Math.PI / 360.0) * ratio * 1.2`

to have a ratio of > 1.2 . Basically you're using the size of the object and being some multiple of that away.

In terms of viewing the element 'face on' that's possible but probably going to take some matrix magic to work out what is the 'front' and set the camera appropriately.. Take a look at viewer.show and viewer.setCameraTarget

**Comment by johnBim** [comment]
Hello Andy,
thanks I will try that one.

regards
