### ISSUE TITLE
Hide all entities of a Domain

### ISSUE THREAD

**Issue by MarcoGiorgi** [xBimTeam/XbimWebUI#183]
Is there a way to hide an entire "Domain"?
I'd like to show the complete model, with "Electrical Domain", "HVAC Domain", etc...
Once loaded, I'd like to hide/show all the entities of a particular domain.

I've found example and documentation about _viewer.setState(state, type)_ but nothing about a way to hide a whole set of entities of a particular domain.

**Comment by martin1cerny** [comment]
Types are not grouped into domains in WebUI project. They are actually not grouped in original EXPRESS definitions either. It is only a way to organize the documentation and to maintain the project. You can use xBIM Essentials and reflection to extract this kind of information.

**Comment by MarcoGiorgi** [comment]
Thanks Martin,

So I could retrieve the Types, server side, with the following code, i.e. for **electrical domain**:
`var types = typeof(IfcProduct).Assembly.GetTypes().Where(t => t.Namespace == "Xbim.Ifc4.ElectricalDomain");`
and then pass the "_typeID_" array of types to hide.

My problem is that I'm not able to understand which is the property to read server side to get the ID needed by the _viewer.setState()_ method, any suggestion?

**Comment by MarcoGiorgi** [comment]
@martin1cerny 
Hi Martin, could you please give me a quick direction on how to relate Type object retrieved server-side with xBIM Essentials using 
`var types = typeof(IfcProduct).Assembly.GetTypes().Where(t => t.Namespace == "Xbim.Ifc4.ElectricalDomain");` 

and the TypeID to pass to the js client function **viewer.setState(...)** ?
Thanks!

**Comment by martin1cerny** [comment]
Every IFC type has a custom attribute [ExpressTypeAttribute](https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc4/ProductExtension/IfcBuildingElement.cs#L34) which defined the [ExpressTypeId](https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Common/Attributes.cs#L15). That is the ID you need.

**Comment by MarcoGiorgi** [comment]
@martin1cerny Many thanks!

Here is the code to get it (it could be useful for someone else):

```
var types = typeof(IfcProduct).Assembly.GetTypes().Where(t => t.Namespace == "Xbim.Ifc4.ElectricalDomain");

                
foreach(var t in types)
 {
                    //{[Xbim.Common.ExpressTypeAttribute("IfcAudioVisualAppliance", (Int32)1099)]}
                    string name = t.Name;
                    Xbim.Common.ExpressTypeAttribute expressType = (Xbim.Common.ExpressTypeAttribute)t.GetCustomAttributes(typeof(Xbim.Common.ExpressTypeAttribute), false).First();
                    int typeId = expressType.EntityTypeId;
}
```

In this way I can extract from the IFC model all the Types, Name and ID, that belongs to the known Domains that we can find in the IFC model (http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/chapter-7.htm)

The IDs can then reused in the client viewer to show or hide a whole Domain, i.e. hide the HVAC system, or make the architecture and structure semi-transparent and highlight the Electrical system.

Sorry Martin if my questions are very basic but I'm trying to understand how the xBim library works, as I really want to push for it on my projects, and contribute in any form (code development, bug fixes, documentation, consultancy request...), to this project.

Thanks!
