### ISSUE TITLE
Change the scale of the wexbim model geometry

### ISSUE THREAD

**Issue by Edvanio** [xBimTeam/XbimWebUI#185]
I am generating the wexbim files from the IFC model, and since the models are different from software (Revit-m, ARCHICAD-mm and Eberick-cm), I have scale problems when merging the wexbim files in the web viewer.
Does anyone know how to generate wexbim on a default drive or scale the file's geometry?

For the federation of files in XbimWindowsUI, have the fix. However, I could not generate the wexbim file.

In XbimWindowsUI ok:

```cs
XbimVector3D modelTranslation = new XbimVector3D(X, Y, Z);
double oneMeter = model.ModelFactors.OneMetre/100;
XbimMatrix3D translation = XbimMatrix3D.CreateTranslation(modelTranslation * oneMeter);
XbimMatrix3D scaling = XbimMatrix3D.CreateScale(1 / oneMeter);
XbimMatrix3D transform = translation * scaling;
WpfMaterial mat = new WpfMaterial();
Color SelectionColor = Colors.Blue;
mat.CreateMaterial(new XbimColour("Selection", 
    SelectionColor.ScR, SelectionColor.ScG, SelectionColor.ScB, SelectionColor.ScA));
Console.WriteLine("model.Instances amount: " + model.Instances.Count);
bool runOnce = false;
string nameOfType;

foreach (IPersistEntity entityThe in model.Instances)
{
    WpfMeshGeometry3D m = WpfMeshGeometry3D.GetGeometry(entityThe, transform, mat);
```

**Comment by martin1cerny** [comment]
This kind of scaling can be done in `IfcStore.SaveAsWexBIM()` when the wexBIM file is generated in very similar way. Or, it can be applied dynamically in the viewer. Feel free to contribute with pull request containing this change as an optional behaviour.

**Comment by adam9000** [comment]
Hi @martin1cerny 

My problem is the same as Edvanio's mentions in this post:
https://github.com/xBimTeam/XbimWebUI/issues/185

In fact, we are co-workers... :)

I made some progress, with a custom SaveAsWexBIM, with a new parameter named "customTransformation", as follow. But, I'm not a 3D developer, so can you please validade the changes?

Thank you so much in advance!

        static private void SaveAsWexBim(IfcStore model, BinaryWriter binaryStream, XbimMatrix3D customTransformation, IEnumerable<IIfcProduct> products = null)
        {
            products = products ?? model.Instances.OfType<IIfcProduct>();
            // ReSharper disable RedundantCast
            var GeometryStore = model.GeometryStore;
            // ReSharper disable once CollectionNeverUpdated.Local

            var colourMap = new XbimColourMap();
            using (var geomRead = GeometryStore.BeginRead())
            {

                var lookup = geomRead.ShapeGeometries;
                var styles = geomRead.StyleIds;
                var regions = geomRead.ContextRegions.SelectMany(r => r).ToList();
                //we need to get all the default styles for various products
                var defaultStyles = geomRead.ShapeInstances.Select(i => -(int)i.IfcTypeId).Distinct();
                var allStyles = defaultStyles.Concat(styles).ToList();
                int numberOfGeometries = 0;
                int numberOfVertices = 0;
                int numberOfTriangles = 0;
                int numberOfMatrices = 0;
                int numberOfProducts = 0;
                int numberOfStyles = allStyles.Count;
                //start writing out

                binaryStream.Write((Int32)IfcStore.WexBimId); //magic number

                binaryStream.Write((byte)2); //version of stream, arrays now packed as doubles
                var start = (int)binaryStream.Seek(0, SeekOrigin.Current);
                binaryStream.Write((Int32)0); //number of shapes
                binaryStream.Write((Int32)0); //number of vertices
                binaryStream.Write((Int32)0); //number of triangles
                binaryStream.Write((Int32)0); //number of matrices
                binaryStream.Write((Int32)0); //number of products
                binaryStream.Write((Int32)numberOfStyles); //number of styles
                binaryStream.Write(Convert.ToSingle(model.ModelFactors.OneMetre));
                //write out conversion to meter factor

                binaryStream.Write(Convert.ToInt16(regions.Count)); //write out the population data
                foreach (var r in regions)
                {
                    binaryStream.Write((Int32)(r.Population));
                    var bounds = r.ToXbimRect3D();
                    var centre = r.Centre;
                    //write out the centre of the region
                    binaryStream.Write((Single)centre.X);
                    binaryStream.Write((Single)centre.Y);
                    binaryStream.Write((Single)centre.Z);
                    //bounding box of largest region
                    binaryStream.Write(bounds.ToFloatArray());
                }
                //textures

                foreach (var styleId in allStyles)
                {
                    XbimColour colour;
                    if (styleId > 0)
                    {
                        var ss = (IIfcSurfaceStyle)model.Instances[styleId];
                        var texture = XbimTexture.Create(ss);
                        colour = texture.ColourMap.FirstOrDefault();
                    }
                    else //use the default in the colour map for the enetity type
                    {
                        var theType = model.Metadata.GetType((short)Math.Abs(styleId));
                        colour = colourMap[theType.Name];
                    }
                    if (colour == null) colour = XbimColour.DefaultColour;
                    binaryStream.Write((Int32)styleId); //style ID                       
                    binaryStream.Write((Single)colour.Red);
                    binaryStream.Write((Single)colour.Green);
                    binaryStream.Write((Single)colour.Blue);
                    binaryStream.Write((Single)colour.Alpha);

                }

                //write out all the product bounding boxes
                var prodIds = new HashSet<int>();
                foreach (var product in products)
                {
                    if (product is IIfcFeatureElement) continue;
                    prodIds.Add(product.EntityLabel);

                    var bb = XbimRect3D.Empty;
                    foreach (var si in geomRead.ShapeInstancesOfEntity(product))
                    {
                        //original code
                        //var bbPart = XbimRect3D.TransformBy(si.BoundingBox, si.Transformation);
                        var bbPart = XbimRect3D.TransformBy(si.BoundingBox, si.Transformation * customTransformation);
                        //make sure we put the box in the right place and then convert to axis aligned
                        if (bb.IsEmpty) bb = bbPart;
                        else
                            bb.Union(bbPart);
                    }
                    //do not write out anything with no geometry
                    if (bb.IsEmpty) continue;

                    binaryStream.Write((Int32)product.EntityLabel);
                    binaryStream.Write((UInt16)model.Metadata.ExpressTypeId(product));
                    binaryStream.Write(bb.ToFloatArray());
                    numberOfProducts++;
                }

                //projections and openings have already been applied, 

                var toIgnore = new short[4];
                toIgnore[0] = model.Metadata.ExpressTypeId("IFCOPENINGELEMENT");
                toIgnore[1] = model.Metadata.ExpressTypeId("IFCPROJECTIONELEMENT");
                if (model.IfcSchemaVersion == IfcSchemaVersion.Ifc4)
                {
                    toIgnore[2] = model.Metadata.ExpressTypeId("IFCVOIDINGFEATURE");
                    toIgnore[3] = model.Metadata.ExpressTypeId("IFCSURFACEFEATURE");
                }

                foreach (var geometry in lookup)
                {
                    if (geometry.ShapeData.Length <= 0) //no geometry to display so don't write out any products for it
                        continue;
                    var instances = geomRead.ShapeInstancesOfGeometry(geometry.ShapeLabel);



                    var xbimShapeInstances = instances.Where(si => !toIgnore.Contains(si.IfcTypeId) &&
                                                                 si.RepresentationType ==
                                                                 XbimGeometryRepresentationType
                                                                     .OpeningsAndAdditionsIncluded && prodIds.Contains(si.IfcProductLabel)).ToList();
                    if (!xbimShapeInstances.Any()) continue;
                    numberOfGeometries++;
                    binaryStream.Write(xbimShapeInstances.Count); //the number of repetitions of the geometry
                    if (xbimShapeInstances.Count > 1)
                    {
                        foreach (IXbimShapeInstanceData xbimShapeInstance in xbimShapeInstances)
                        //write out each of the ids style and transforms
                        {
                            binaryStream.Write(xbimShapeInstance.IfcProductLabel);
                            binaryStream.Write((UInt16)xbimShapeInstance.IfcTypeId);
                            binaryStream.Write((UInt32)xbimShapeInstance.InstanceLabel);
                            binaryStream.Write((Int32)xbimShapeInstance.StyleLabel > 0
                                ? xbimShapeInstance.StyleLabel
                                : xbimShapeInstance.IfcTypeId * -1);

                            //original code
                            //binaryStream.Write(xbimShapeInstance.Transformation);

                            var ms2 = new MemoryStream(((IXbimShapeGeometryData)geometry).ShapeData);
                            var br2 = new BinaryReader(ms2);
                            var tr2 = br2.ReadShapeTriangulation();
                            var trTransformed = tr2.Transform(((XbimShapeInstance)xbimShapeInstance).Transformation * customTransformation);
                            trTransformed.Write(binaryStream);

                            numberOfTriangles +=
                                XbimShapeTriangulation.TriangleCount(((IXbimShapeGeometryData)geometry).ShapeData);
                            numberOfMatrices++;
                        }
                        numberOfVertices +=
                            XbimShapeTriangulation.VerticesCount(((IXbimShapeGeometryData)geometry).ShapeData);

                        var ms = new MemoryStream(((IXbimShapeGeometryData)geometry).ShapeData);
                        var br = new BinaryReader(ms);
                        var tr = br.ReadShapeTriangulation();

                        tr.Write(binaryStream);
                    }
                    else //now do the single instances
                    {
                        var xbimShapeInstance = xbimShapeInstances[0];

                        // IXbimShapeGeometryData geometry = ShapeGeometry(kv.Key);
                        binaryStream.Write((Int32)xbimShapeInstance.IfcProductLabel);
                        binaryStream.Write((UInt16)xbimShapeInstance.IfcTypeId);
                        binaryStream.Write((Int32)xbimShapeInstance.InstanceLabel);
                        binaryStream.Write((Int32)xbimShapeInstance.StyleLabel > 0
                            ? xbimShapeInstance.StyleLabel
                            : xbimShapeInstance.IfcTypeId * -1);

                        //Read all vertices and normals in the geometry stream and transform

                        var ms = new MemoryStream(((IXbimShapeGeometryData)geometry).ShapeData);
                        var br = new BinaryReader(ms);
                        var tr = br.ReadShapeTriangulation();
                        //original code
                        //var trTransformed = tr.Transform(((XbimShapeInstance)xbimShapeInstance).Transformation);
                        var trTransformed = tr.Transform(((XbimShapeInstance)xbimShapeInstance).Transformation * customTransformation);
                        trTransformed.Write(binaryStream);
                        numberOfTriangles += XbimShapeTriangulation.TriangleCount(((IXbimShapeGeometryData)geometry).ShapeData);
                        numberOfVertices += XbimShapeTriangulation.VerticesCount(((IXbimShapeGeometryData)geometry).ShapeData);
                    }
                }


                binaryStream.Seek(start, SeekOrigin.Begin);
                binaryStream.Write((Int32)numberOfGeometries);
                binaryStream.Write((Int32)numberOfVertices);
                binaryStream.Write((Int32)numberOfTriangles);
                binaryStream.Write((Int32)numberOfMatrices);
                binaryStream.Write((Int32)numberOfProducts);
                binaryStream.Seek(0, SeekOrigin.End); //go back to end
                // ReSharper restore RedundantCast
            }
        }

**Comment by adam9000** [comment]
...and, in order to produce the customTransformation value:

                XbimModelPositioningCollection ModelPositions = new XbimModelPositioningCollection();
                ModelPositions.AddModel(model);
                XbimRect3D ModelBounds = ModelPositions.GetEnvelopeInMeters();
                var p = ModelBounds.Centroid();
                XbimVector3D modelTranslation = new XbimVector3D(-p.X, -p.Y, -p.Z);

                double oneMeter = model.ModelFactors.OneMetre / 1000;
                XbimMatrix3D translation = XbimMatrix3D.CreateTranslation(modelTranslation * oneMeter);
                XbimMatrix3D scaling = XbimMatrix3D.CreateScale(1 / oneMeter);
                XbimMatrix3D transform = translation * scaling;

**Comment by martin1cerny** [comment]
Hi @Edvanio , I'm sorry but I'm not going to validate 200+ lines of code. Feel free to submit commented Pull Request where I can clearly see the diff.

**Comment by Edvanio** [comment]
I made some adjustments and the exportation for wexbim worked correctly.



        private void SaveWexBIM_Click(string Caminho_Ifc01)
        {
            var model = IfcStore.Open(Caminho_Ifc01);
                if (model.GeometryStore.IsEmpty)
                {
                    Console.WriteLine("model.GeometryStore.IsEmpty");
                    var context = new Xbim3DModelContext(model);
                    context.CreateContext();
                }
            XbimModelPositioningCollection modelPositions = new XbimModelPositioningCollection();
            short userDefinedId = 0;
            model.UserDefinedId = userDefinedId;
            modelPositions.AddModel(model.ReferencingModel);
            //Permite aplicar um deslocamento no modelo IFC simplificado
            double X = 0;
            double Y = 0;
            double Z = 0;
            XbimVector3D modelTranslation = new XbimVector3D(0, 0, 0);
            double OneMeter = model.ModelFactors.OneMeter;
            XbimMatrix3D scaling = XbimMatrix3D.CreateScale(1 / OneMeter);
            XbimMatrix3D transform = scaling;
            var wexBimFilename = Path.ChangeExtension(@"C:\Users\Edvanio\Desktop\webEscalado.wexbim", "wexBIM");
            var wexBiMfile = File.Create(wexBimFilename);
            var wexBimBinaryWriter = new BinaryWriter(wexBiMfile);
            SaveAsWexBim(transform, model, wexBimBinaryWriter);
        }
        static byte[] GetBytesAlt(double[] values)
        {
            /*var result = new byte[values.Length * sizeof(double)];
            Buffer.BlockCopy(values, 0, result, 0, result.Length); 
            return result;*/
            return values.SelectMany(value => BitConverter.GetBytes(value)).ToArray();
            //return values.SelectMany(value => BitConverter.GetBytes(value)).ToArray(); 
        }
        static double[] GetDoublesAlt(byte[] bytes)
        {
            /* var result = new double[bytes.Length / sizeof(double)];
             Buffer.BlockCopy(bytes, 0, result, 0, bytes.Length);
             return result;*/
            return Enumerable.Range(0, bytes.Length / sizeof(double)).Select(offset => BitConverter.ToDouble(bytes, offset * sizeof(double))).ToArray();
        }
        public void SaveAsWexBim(XbimMatrix3D customTransformation, IfcStore model, BinaryWriter binaryStream, IEnumerable<IIfcProduct> products = null)
        {
            products = products ?? model.Instances.OfType<IIfcProduct>();
            // ReSharper disable RedundantCast
            // if (GeometryStore == null) throw new XbimException("Geometry store has not been initialised");
            // ReSharper disable once CollectionNeverUpdated.Local
            var ForMeter = 1 / model.ModelFactors.OneMeter;
            var colourMap = new XbimColourMap();
            using (var geomRead = model.GeometryStore.BeginRead())
            {
                var lookup = geomRead.ShapeGeometries;
                var styles = geomRead.StyleIds;
                var regions = geomRead.ContextRegions.SelectMany(r => r).ToList();
                //we need to get all the default styles for various products
                var defaultStyles = geomRead.ShapeInstances.Select(i => -(int)i.IfcTypeId).Distinct();
                var allStyles = defaultStyles.Concat(styles).ToList();
                int numberOfGeometries = 0;
                int numberOfVertices = 0;
                int numberOfTriangles = 0;
                int numberOfMatrices = 0;
                int numberOfProducts = 0;
                int numberOfStyles = allStyles.Count;
                //start writing out
                binaryStream.Write((Int32)IfcStore.WexBimId); //magic number
                binaryStream.Write((byte)2); //version of stream, arrays now packed as doubles
                var start = (int)binaryStream.Seek(0, SeekOrigin.Current);
                binaryStream.Write((Int32)0); //number of shapes
                binaryStream.Write((Int32)0); //number of vertices
                binaryStream.Write((Int32)0); //number of triangles
                binaryStream.Write((Int32)0); //number of matrices
                binaryStream.Write((Int32)0); //number of products
                binaryStream.Write((Int32)numberOfStyles); //number of styles
                binaryStream.Write(Convert.ToSingle(1));
                //binaryStream.Write(Convert.ToSingle(model.ModelFactors.OneMilliMeter));
                //write out conversion to meter factor
                binaryStream.Write(Convert.ToInt16(regions.Count)); //write out the population data
                foreach (var r in regions)
                {
                    binaryStream.Write((Int32)(r.Population));
                    var bounds = (r.ToXbimRect3D()).Transform(customTransformation);
                    var centre = r.Centre* customTransformation;
                    //write out the centre of the region
                    binaryStream.Write((Single)centre.X);
                    binaryStream.Write((Single)centre.Y);
                    binaryStream.Write((Single)centre.Z);
                    //bounding box of largest region
                    binaryStream.Write(bounds.ToFloatArray());
                }
                //textures
                foreach (var styleId in allStyles)
                {
                    XbimColour colour;
                    if (styleId > 0)
                    {
                        var ss = (IIfcSurfaceStyle)model.Instances[styleId];
                        var texture = XbimTexture.Create(ss);
                        colour = texture.ColourMap.FirstOrDefault();
                        string a = "";
                    }
                    else //use the default in the colour map for the enetity type
                    {
                        var theType = model.Metadata.GetType((short)Math.Abs(styleId));
                        //colour = colourMap[theType.Name];
                            colour = colourMap[theType.Name];
                    }
                    if (colour == null) colour = XbimColour.DefaultColour;
                    binaryStream.Write((Int32)styleId); //style ID                       
                    binaryStream.Write((Single)colour.Red);
                    binaryStream.Write((Single)colour.Green);
                    binaryStream.Write((Single)colour.Blue);
                    binaryStream.Write((Single)colour.Alpha);
                }
                //write out all the product bounding boxes
                var prodIds = new HashSet<int>();
                foreach (var product in products)
                {
                    if (product is IIfcFeatureElement) continue;
                    prodIds.Add(product.EntityLabel);
                    var bb = XbimRect3D.Empty;
                    foreach (var si in geomRead.ShapeInstancesOfEntity(product))
                    {
                        var bbPart = XbimRect3D.TransformBy(si.BoundingBox, si.Transformation).Transform(customTransformation);
                        //make sure we put the box in the right place and then convert to axis aligned
                        if (bb.IsEmpty) bb = bbPart;
                        else
                            bb.Union(bbPart);
                    }
                    //do not write out anything with no geometry
                    if (bb.IsEmpty) continue;
                    binaryStream.Write((Int32)product.EntityLabel);
                    binaryStream.Write((UInt16)model.Metadata.ExpressTypeId(product));
                    binaryStream.Write(bb.ToFloatArray());
                    numberOfProducts++;
                }
                //projections and openings have already been applied, 
                var toIgnore = new short[4];
                toIgnore[0] = model.Metadata.ExpressTypeId("IFCOPENINGELEMENT");
                toIgnore[1] = model.Metadata.ExpressTypeId("IFCPROJECTIONELEMENT");
                if (model.IfcSchemaVersion == IfcSchemaVersion.Ifc4)
                {
                    toIgnore[2] = model.Metadata.ExpressTypeId("IFCVOIDINGFEATURE");
                    toIgnore[3] = model.Metadata.ExpressTypeId("IFCSURFACEFEATURE");
                }
                foreach (var geometry in lookup)
                {
                    if (geometry.ShapeData.Length <= 0) //no geometry to display so don't write out any products for it
                        continue;
                    var instances = geomRead.ShapeInstancesOfGeometry(geometry.ShapeLabel);
                    var xbimShapeInstances = instances.Where(si => !toIgnore.Contains(si.IfcTypeId) &&
                                                                 si.RepresentationType ==
                                                                 XbimGeometryRepresentationType
                                                                     .OpeningsAndAdditionsIncluded && prodIds.Contains(si.IfcProductLabel)).ToList();
                    if (!xbimShapeInstances.Any()) continue;
                    numberOfGeometries++;
                    binaryStream.Write(xbimShapeInstances.Count); //the number of repetitions of the geometry
                    if (xbimShapeInstances.Count > 1)
                    {
                        foreach (IXbimShapeInstanceData xbimShapeInstance in xbimShapeInstances)
                        //write out each of the ids style and transforms
                        {
                            binaryStream.Write(xbimShapeInstance.IfcProductLabel);
                            binaryStream.Write((UInt16)xbimShapeInstance.IfcTypeId);
                            binaryStream.Write((UInt32)xbimShapeInstance.InstanceLabel);
                            binaryStream.Write((Int32)xbimShapeInstance.StyleLabel > 0
                                ? xbimShapeInstance.StyleLabel
                                : xbimShapeInstance.IfcTypeId * -1);
                            //Possível REGIÂO COM ERRO
                            //binaryStream.Write(xbimShapeInstance.Transformation);
                            var xb = GetDoublesAlt(xbimShapeInstance.Transformation);
                            xb[12] = xb[12] * ForMeter;
                            xb[13] = xb[13] * ForMeter;
                            xb[14] = xb[14] * ForMeter;
                            var vb2 = GetBytesAlt(xb);
                            binaryStream.Write(vb2);
                            numberOfTriangles +=
                                XbimShapeTriangulation.TriangleCount(((IXbimShapeGeometryData)geometry).ShapeData);
                            numberOfMatrices++;
                        }
                        numberOfVertices +=
                            XbimShapeTriangulation.VerticesCount(((IXbimShapeGeometryData)geometry).ShapeData);
                        // binaryStream.Write(geometry.ShapeData);
                        var ms = new MemoryStream(((IXbimShapeGeometryData)geometry).ShapeData);
                        var br = new BinaryReader(ms);
                        var tr = br.ReadShapeTriangulation().Transform(customTransformation);
                        tr.Write(binaryStream);
                    }
                    else //now do the single instances
                    {
                        var xbimShapeInstance = xbimShapeInstances[0];
                        // IXbimShapeGeometryData geometry = ShapeGeometry(kv.Key);
                        binaryStream.Write((Int32)xbimShapeInstance.IfcProductLabel);
                        binaryStream.Write((UInt16)xbimShapeInstance.IfcTypeId);
                        binaryStream.Write((Int32)xbimShapeInstance.InstanceLabel);
                        binaryStream.Write((Int32)xbimShapeInstance.StyleLabel > 0
                            ? xbimShapeInstance.StyleLabel
                            : xbimShapeInstance.IfcTypeId * -1);
                        //Read all vertices and normals in the geometry stream and transform
                        var ms = new MemoryStream(((IXbimShapeGeometryData)geometry).ShapeData);
                        var br = new BinaryReader(ms);
                        var tr = br.ReadShapeTriangulation();
                        var trTransformed = tr.Transform(((XbimShapeInstance)xbimShapeInstance).Transformation*customTransformation);
                        trTransformed.Write(binaryStream);
                        numberOfTriangles += XbimShapeTriangulation.TriangleCount(((IXbimShapeGeometryData)geometry).ShapeData);
                        numberOfVertices += XbimShapeTriangulation.VerticesCount(((IXbimShapeGeometryData)geometry).ShapeData);
                    }
                }
                binaryStream.Seek(start, SeekOrigin.Begin);
                binaryStream.Write((Int32)numberOfGeometries);
                binaryStream.Write((Int32)numberOfVertices);
                binaryStream.Write((Int32)numberOfTriangles);
                binaryStream.Write((Int32)numberOfMatrices);
                binaryStream.Write((Int32)numberOfProducts);
                binaryStream.Seek(0, SeekOrigin.End); //go back to end
                // ReSharper restore RedundantCast
            }
        }`

**Comment by martin1cerny** [comment]
Hi @Edvanio. As I said above: I'm sorry but I'm not going to investigate 200+ lines of the code. Feel free to submit a commented Pull Request where I can clearly see the diff and we can have a conversation about the changes you made.

**Comment by qc529491527** [comment]
Hi, friend.
I wonder how to generate the .wexbim file from .ifc file?
I am stuck here..
Hope your reply. ^_^

**Comment by martin1cerny** [comment]
@qc529491527: This is duplicate to #190.
