### ISSUE TITLE
Create Viewer from RVT project that contains rvt link files

### ISSUE THREAD

**Issue by bracha-ziv** [xBimTeam/XbimWebUI#187]
#### Expected behavior:
The expected behavior is opening the viewer and display all the links within the project/file.

#### Actual behavior or exception details:
Now ,the viewer represents only the main file without displaying its link files

#### My expected Steps:
For example:
The Project contains two links, means 3 RVT files-> 3 IFC files -> 3 wexBIM files
I have two suggestions:
1. Converting the 3 IFC files to one wexBIM file (favorite).
2. Opening the 3 wexBim files in the viewer  at once.

How can i do one of those steps?

**Comment by martin1cerny** [comment]
Just load 3 wexBIM files at once.

**Comment by ChagiLevi** [comment]
thanks,
how can i do that?
It is possible Converting the 3 IFC files to one wexBIM file?How?

**Comment by martin1cerny** [comment]
You can convert 3 IFC files into 3 wexBIM files and load them one by one. You should have noticed that linked project file is just Revit concept which doesn't translate to IFC data schema. But you can treat these 3 files as a coordinated set of models.

**Comment by ChagiLevi** [comment]
Thanks,
I loaded the 3 ifc files, one of them  is the model and the two others are links,
but when i loaded all the files, the location of the links files was not like the original source
How can i load them in the correct location?
