### ISSUE TITLE
Selecting item from XbimTreeview outside view

### ISSUE THREAD

**Issue by admicom** [xBimTeam/XbimWebUI#188]
#### Expected behavior:
We want XbimTreeview to scroll to item to make it visible.

#### Actual behavior or exception details:
XbimTreeview does not scroll to item.IsSelected = true

#### Version of the xBIM Viewer:
v4.0.11

#### Minimal code (or steps) to reproduce the issue:
            toSelect.IsSelected = true;
            SpatialControl.ScrollIntoView(toSelect);

**Comment by martin1cerny** [comment]
Please, see the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) of `ScrollIntoView()`.
