### ISSUE TITLE
How to solve "There are no shaders in source folder" ?

### ISSUE THREAD

**Issue by qc529491527** [xBimTeam/XbimWebUI#189]
#### Expected behavior:
I just downloaded XBimWebUI and import it into Visual Studio.
When i click "run" button, the message "There are no shaders in source folder" shows.
How can i solve this issue?

#### Version of the xBIM Viewer:
Newest

#### Minimal code (or steps) to reproduce the issue:
```js
var viewer = new Viewer(canvas);
(...)
```

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*

**Comment by qc529491527** [comment]
Actual behavior or exception details:

I just downloaded XBimWebUI and import it into Visual Studio.
When i click "run" button, the message "There are no shaders in source folder" shows.
How can i solve this issue?

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It is a pure TS project now, so you can use VS Code or other code editors. It uses webpack to build shaders as well as an integrated build (and watch) step.
