### ISSUE TITLE
How to generate wexbim file with all the properties from IFC File.

### ISSUE THREAD

**Issue by hashmedia1** [xBimTeam/XbimWebUI#193]
Hello

I need to generate wexbim format from IFC file and load it into XBimWebUI.. so how to do it? How to genereate JSON file with properties? Please help me.

Thanks in Advance.

**Comment by martin1cerny** [comment]
Please, read the [docs](http://docs.xbim.net/examples/creating-wexbim-file.html) and previous [questions already asked](https://github.com/xBimTeam/XbimWebUI/issues?utf8=%E2%9C%93&q=is%3Aissue+json+generate+).
