### ISSUE TITLE
Rotate and Zoom of 3D model not working on Android(Chrome)

### ISSUE THREAD

**Issue by thegam3r2045** [xBimTeam/XbimWebUI#194]
I went to your tutorial page (http://docs.xbim.net/XbimWebUI/1_Hello_building.live.html) on Android using Chrome, it loads the 3D model but it can't be rotated and zoomed like on a windows desktop system.

**Comment by martin1cerny** [comment]
The version in docs uses older version of the library with no support for touch navigation. Try the develop branch for the latest code which supports touch navigation.

**Comment by johnnyontheweb** [comment]
Actually is not working in chrome on Android, black rendering window is shown

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It uses WebGL2 if available which makes it working on Android devices.
