### ISSUE TITLE
mobile browsers and labels

### ISSUE THREAD

**Issue by stefHin** [xBimTeam/XbimWebUI#196]
hi

for a project I need a webviewer for ifc files that runs on android and IOS browsers. I found your XbimWebUI, which looks quite promising, but I'm i bit worried because the last changes on github were a while ago. Are you still working on the project? And do you have any experience running it on mobile browsers?

Furthermore we need a possibility to attach a label (with simple text) to objects in the 3d viewer (similar to this: http://opensourcebim.github.io/bimvie.ws-viewer/docs/classes/Label.html). Is it possible to do that with your viewer?

Regards,
stefan

**Comment by martin1cerny** [comment]
Please check the `develop` branch for the latest changes. That includes touch basic navigation support. We didn't test on Android or iOS explicitly but it should work as long as the device supports WebGL and floating point texture extension.

Labels are not implemented but feel free to contribute with this kind of functionality. I developed most of the code for the viewer and I use it on some of my current projects as it is now.
