### ISSUE TITLE
Conversion of large IFC models through the Esent Database not working if int is exceeded

### ISSUE THREAD

**Issue by larstoennigs** [xBimTeam/XbimWebUI#197]
#### Expected behavior:
IfcStore class open method converts ifc files larger than the ifcMaxLength threshold variable to the wexbim format by using an Esent database.  

#### Actual behavior or exception details:
Conversion fails with a value out of range exception due to the usage of integer key identifiers within the Esent database. The conversion of larger IFC files where the line numbers exceed the limits of integer is not possible. The EsentCursor class uses int instead of long variables starting in the CreateGlobalTable method and subsequently literally everwhere.

#### Version of the xBIM Viewer:
not relevant 

#### Version of xBIM.IO
4.0.0.0

#### Minimal code (or steps) to reproduce the issue:
```js
var viewer = new Viewer(canvas);
(...)
```

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*

**Comment by martin1cerny** [comment]
This is not an issue of WebUI. WebUI is pure Javascript/Typescript project which only handles web presentation of preprocessed data.
