### ISSUE TITLE
Can i use threejs with this ?

### ISSUE THREAD

**Issue by hashmedia1** [xBimTeam/XbimWebUI#198]
Hello

I want to use threejs in this. Can I use threejs in this project. Please help.

Thanks

**Comment by martin1cerny** [comment]
No, our 3D viewer is completely independent and self-contained without any dependencies. But you can observe the way we parse data produced by xBIM (our custom wexBIM file format) and you can do anything you want with the geometry.

**Comment by hashmedia1** [comment]
In description, it is written that this supports SceneJS... how to get particular geometry ? can i apply culling method supported by scenejs ?

**Comment by martin1cerny** [comment]
I see that project description is somehow misleading so I changed it. It was a generic (and slightly outdated) description we put in xBIM projects as the default.
