### ISSUE TITLE
Manipulate Geometry

### ISSUE THREAD

**Issue by hashmedia1** [xBimTeam/XbimWebUI#199]
In description, it is written that this supports SceneJS... how to get particular geometry ? can i apply culling method supported by scenejs ? Please help.

**Comment by martin1cerny** [comment]
I see. The project description was somehow misleading so I changed it. It was a generic (and slightly outdated) description we put in xBIM projects as the default. XbimWebUI is completely independent of any third party WebGL framework. We use WebGL directly.

Culling is a work to do but it doesn't fit very well in the current architecture. Feel free to contribute (to `develop` branch preferably).

**Comment by hashmedia1** [comment]
You can split model into several 'topics' when creating wexbim.. can you please explain that ? How to do that ?
