### ISSUE TITLE
Getting IDs from wexBIM file

### ISSUE THREAD

**Issue by Harara81** [xBimTeam/XbimWebUI#20]
Hi all,

I want to catch all IDs of the elements in the wexBIM file, is thee a method to achieve that?

Thanks,

Micheal

**Comment by martin1cerny** [comment]
See [this](http://xbimteam.github.io/XbimWebUI/xViewer.html#event:mouseDown) and [this](http://xbimteam.github.io/XbimWebUI/tutorial-3_Eventful_building.html) please.

**Comment by Harara81** [comment]
Thanks Martin,
these tutorials enables me to know the ID of the picked element..I need to catch all the products IDs in wexbim file without any end user interaction event.
you get me

**Comment by martin1cerny** [comment]
There is no public (documented) method to do this. However, you can access these from [product maps](https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/xbim-model-handle.debug.js#L153) in [handles](https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L198).

**Comment by Harara81** [comment]
Thanks I'll check it

**Comment by Holgenberg** [comment]
Hi, just as a follow up to this. Is it possible to retrieve all ID's of a model for a particular xProductType?
