### ISSUE TITLE
Metalic Shader

### ISSUE THREAD

**Issue by hashmedia1** [xBimTeam/XbimWebUI#206]
Hello

I want to make every component metalic. So how to do that ? e.g. Metalic effect to wall. Please help.

Thank You.

**Comment by martin1cerny** [comment]
You need to change the shader.

**Comment by hashmedia1** [comment]
Yes i know that. but how to do that ? I dont know very much about shaders. what i have to change in shader ?

**Comment by martin1cerny** [comment]
You will need to study the source of WebUI and how it uses shaders. Than you have to study how WebGL shaders work and learn the shader language syntax. Than you can make changes in the shader to enhance it as you like. This is complex are and I'm sorry but we can't provide detailed guidance on this.

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It uses new shader which may look like what you ask for. It is using phong shading now.
