### ISSUE TITLE
Mobile rendering error

### ISSUE THREAD

**Issue by jkfhto** [xBimTeam/XbimWebUI#207]
Rendering on Android phone has the following error：

LogSystemNetworkElementStorage
All
Log
Info
Warn
Error
Uncaught RangeError: Array buffer allocation failed
/XbimWebUIdevelop/docs/scripts/xbim.bundle.js:345:33 RangeError: Array buffer allocation failed
at new ArrayBuffer (<anonymous>)
at typedArrayConstructByLength (<anonymous>)
at new Float32Array (native)
at xModelGeometry.parse (http://192.168.2.100/XbimWebUIdevelop/docs/scripts/xbim.bundle.js:345:33)
at xBinaryReader.br.onloaded (http://192.168.2.100/XbimWebUIdevelop/docs/scripts/xbim.bundle.js:486:19)
at FileReader.fReader.onloadend (http://192.168.2.100/XbimWebUIdevelop/docs/scripts/xbim.bundle.js:127:39)

**Comment by martin1cerny** [comment]
This is more likely problem with the data.

**Comment by jkfhto** [comment]
Mobile model rendering does not display
![471680549594134362](https://user-images.githubusercontent.com/27767452/47599289-41382b00-d9dd-11e8-9732-e156d421edd9.jpg)

**Comment by jkfhto** [comment]
Should not support OES_texture_float extension causing rendering failure

**Comment by martin1cerny** [comment]
OES_texture_float is essential part of the implementation. It is not needed with WebGL2 where it became integral part of the standard but is necessary for WebGL1.

**Comment by jkfhto** [comment]
@martin1cerny   thanks

**Comment by johnnyontheweb** [comment]
Any news for that?
Can anyone explain if there's a workaround to make it work on Android browsers?
Thanks

**Comment by martin1cerny** [comment]
This is not a general problem for Android browsers. It more depends on the underlying hardware. We are about to publish new version with significant improvements including WebGL2 support. But due to other workload it may take a few more weeks to happen.

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer).  It uses WebGL2 which makes it working on Android devices.

**Comment by abolfazlpadash090-code** [comment]
[]()
