### ISSUE TITLE
Zoom in XZ Plane only

### ISSUE THREAD

**Issue by hashmedia1** [xBimTeam/XbimWebUI#208]
Hello

Currently Zoom is working like wherever we are looking it will zoom there only. I want to modify that functionality like that i can not change Y coordinate when we zoom the object. It must only zoom into XZ plane only. Please help.

Thank You.

**Comment by martin1cerny** [comment]
Feel free to add additional optional navigation with this functionality (though I can't see this any useful to be fair).

**Comment by hashmedia1** [comment]
I am asking  for the help... how to do that ? It will be helpful for me..

**Comment by martin1cerny** [comment]
You need to add another `case: 'zoom-fixed-y'` in the `navigate()` function [here](https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/viewer.ts#L1287) with different matrix operations.

**Comment by martin1cerny** [comment]
I'm sorry but this is a new feature request and we don't have any plan for this now. I can't afford to do this in my spare time. Let me know if you are interested in a commercial support for this request.

**Comment by hashmedia1** [comment]
@martin1cerny  Thank You for the reply... we can discuss commercial support for this request.. How much it will cost ?

**Comment by martin1cerny** [comment]
If you send me your email I'll send you a quote.

**Comment by hashmedia1** [comment]
@martin1cerny  please give me your email. and my email is harshit@hashmedia.in
