### ISSUE TITLE
Label follow camera movement

### ISSUE THREAD

**Issue by jkfhto** [xBimTeam/XbimWebUI#209]
Is there any way to make 2d annotations follow the camera?

![3p g t5 n vz l ius5zrp](https://user-images.githubusercontent.com/27767452/47949752-53890a80-df83-11e8-9b21-1e3db9939cc6.png)

**Comment by martin1cerny** [comment]
This is not implemented now. Feel free to contribute.

**Comment by jkfhto** [comment]
@martin1cerny    Try to write a label plugin, but it doesn't display properly on the page. Can you help me analyze what went wrong with the code?

// Vertex shader program
var VSHADER_SOURCE =
    'uniform mat4 matrixWorld;\n' +
    'uniform mat4 viewMatrix;\n' +
    'uniform mat4 projectionMatrix;\n' +
    'uniform float rotation;\n' +
    'uniform vec2 center;\n' +
    'uniform vec2 scale;\n' +
    'uniform vec2 uvOffset;\n' +
    'uniform vec2 uvScale;\n' +
    'varying vec2 vUV;\n' +
    'attribute vec2 position;\n' +
    'attribute vec2 uv;\n' +
    'varying vec2 v_TexCoord;\n' +
    'void main() {\n' +
    '	vUV = uvOffset + uv * uvScale;\n' +

    '	vec2 alignedPosition = ( position - center ) * scale;\n' +

    '	vec2 rotatedPosition;\n' + 
    '	rotatedPosition.x = cos( rotation ) * alignedPosition.x - sin( rotation ) * alignedPosition.y;\n' +
    '	rotatedPosition.y = sin( rotation ) * alignedPosition.x + cos( rotation ) * alignedPosition.y;\n' +

    '	vec4 mvPosition;\n' +

    '   mvPosition = viewMatrix * matrixWorld * vec4( 0.0, 0.0, 0.0, 1.0 );\n' + 
    '	mvPosition.xy += rotatedPosition;\n' +
    '   gl_Position = projectionMatrix * mvPosition;\n'+
    // '   gl_Position = vec4(position.x,position.y,0.0,1.0);\n' +
    '   v_TexCoord = uv;\n' +
    '}\n';

// Fragment shader program
var FSHADER_SOURCE =
    '#ifdef GL_ES\n' +
    'precision mediump float;\n' +
    '#endif\n' +
    'uniform sampler2D u_Sampler;\n' +
    'varying vec2 v_TexCoord;\n' +
    'void main() {\n' +
    // '	vec4 texture = texture2D( u_Sampler, v_TexCoord );\n' +
    // '	gl_FragColor = vec4( texture.xyz, texture.a * 1.0 );\n'+
    '   gl_FragColor = vec4(1.0,0.0,0.0,1.0);\n' +
    '}\n';
    
var xSprite = (function () {
    var xSpriteArr=[];
    function xSprite(image) {
        this._initialized = false;
        this.imageUrl = image || "data/sprite2.png";
        this.position = new Vector3(50550, 50, 61220);
        this.matrixWorld = glMatrix.mat4.create();
        this.viewMatrix = glMatrix.mat4.create();
        this.projectionMatrix = glMatrix.mat4.create();

        this.vertices = new Float32Array([
            -0.5, -0.5, 0, 0,
            0.5, -0.5, 1, 0,
            0.5, 0.5, 1, 1,
            -0.5, 0.5, 0, 1
        ]);

        this.faces = new Uint16Array([
            0, 1, 2,
            0, 2, 3
        ]);
    };
    xSprite.prototype.init = function (xviewer) {
        var self = this;
        this.viewer = xviewer;
        var gl = this.viewer._gl;

        //create own shader 
        this._program = null;
        this._initShader();

        //set own shader for init
        gl.useProgram(this._program);

        this.matrixWorld = glMatrix.mat4.translate(glMatrix.mat4.create(), glMatrix.mat4.create(), this.viewer._origin);

        var program = this._program;
        this.vertexBuffer = gl.createBuffer();
        this.elementBuffer = gl.createBuffer();

        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexBuffer);
        gl.bufferData(gl.ARRAY_BUFFER, this.vertices, gl.STATIC_DRAW);

        gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this.elementBuffer);
        gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, this.faces, gl.STATIC_DRAW);
        //create uniform and attribute pointers

        this.attributes = {
            position: gl.getAttribLocation(program, 'position'),
            uv: gl.getAttribLocation(program, 'uv')
        };

        this.uniforms = {
            u_Sampler: gl.getUniformLocation(program, 'u_Sampler'),
            uvOffset: gl.getUniformLocation(program, 'uvOffset'),
            uvScale: gl.getUniformLocation(program, 'uvScale'),

            rotation: gl.getUniformLocation(program, 'rotation'),
            center: gl.getUniformLocation(program, 'center'),
            scale: gl.getUniformLocation(program, 'scale'),

            color: gl.getUniformLocation(program, 'color'),
            map: gl.getUniformLocation(program, 'map'),
            opacity: gl.getUniformLocation(program, 'opacity'),

            matrixWorld: gl.getUniformLocation(program, 'matrixWorld'),
            viewMatrix: gl.getUniformLocation(program, 'viewMatrix'),
            projectionMatrix: gl.getUniformLocation(program, 'projectionMatrix'),

            // fogType: gl.getUniformLocation(program, 'fogType'),
            // fogDensity: gl.getUniformLocation(program, 'fogDensity'),
            // fogNear: gl.getUniformLocation(program, 'fogNear'),
            // fogFar: gl.getUniformLocation(program, 'fogFar'),
            // fogColor: gl.getUniformLocation(program, 'fogColor'),
            // fogDepth: gl.getUniformLocation(program, 'fogDepth'),

            // alphaTest: gl.getUniformLocation(program, 'alphaTest')
        };

        //create texture
        var self = this;
        this._texture = gl.createTexture();
        if (typeof (this._image) === "undefined") {
            //add HTML UI to viewer port
            var data = this.imageUrl;
            var image = new Image();
            self._image = image;
            image.addEventListener("load", function () {
                //load image texture into GPU
                gl.bindTexture(gl.TEXTURE_2D, self._texture);
                gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
                gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, self._image);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);

                gl.generateMipmap(gl.TEXTURE_2D);
            });
            image.src = data;
        } else {
            //load image texture into GPU
            gl.bindTexture(gl.TEXTURE_2D, self._texture);
            gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
            gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, self._image);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
            gl.generateMipmap(gl.TEXTURE_2D);
        }


        this._initialized = true;
        xSpriteArr.push(this);
    };
    xSprite.prototype._initShader = function () {
        var gl = this.viewer._gl;
        var viewer = this.viewer;
        var compile = function (shader, code) {
            gl.shaderSource(shader, code);
            gl.compileShader(shader);
            if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
                viewer._error(gl.getShaderInfoLog(shader));
                return null;
            }
        };
        //fragment shader
        var fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
        compile(fragmentShader, FSHADER_SOURCE);
        //vertex shader (the more complicated one)
        var vertexShader = gl.createShader(gl.VERTEX_SHADER);
        compile(vertexShader, VSHADER_SOURCE);
        //link program
        this._program = gl.createProgram();
        gl.attachShader(this._program, vertexShader);
        gl.attachShader(this._program, fragmentShader);
        gl.linkProgram(this._program);
        if (!gl.getProgramParameter(this._program, gl.LINK_STATUS)) {
            viewer._error('Could not initialise shaders for a navigation cube plugin');
        }
    };

    xSprite.prototype.onAfterDraw = function () {
        var gl = this.setActive();
        // //set uniform for colour coding to false
        // gl.uniform1i(this._colourCodingUniformPointer, 0);
        this.draw();
        this.setInactive();
    };
    xSprite.prototype.onBeforeDrawId = function () {};

    xSprite.prototype.onAfterDrawId = function () {
        var gl = this.setActive();
        // //set uniform for colour coding to false
        // gl.uniform1i(this._colourCodingUniformPointer, 1);
        this.draw();
        this.setInactive();
    };

    xSprite.prototype.onBeforeGetId = function (id) {};
    xSprite.prototype.setActive = function () {
        var gl = this.viewer._gl;
        //set own shader
        gl.useProgram(this._program);
        return gl;
    };

    xSprite.prototype.setInactive = function () {
        var gl = this.viewer._gl;
        //set viewer shader
        gl.useProgram(this.viewer._shaderProgram);
    };

    xSprite.prototype.draw = function () {
        if (!this._initialized)
            return;
        var gl = this.viewer._gl;
        gl.useProgram(this._program);
        this.matrixWorld = glMatrix.mat4.translate(glMatrix.mat4.create(), glMatrix.mat4.create(), this.viewer._origin);
        gl.uniformMatrix4fv(this.uniforms.matrixWorld, false, this.matrixWorld);
        gl.uniformMatrix4fv(this.uniforms.viewMatrix, false, this.viewer._mvMatrix);
        gl.uniformMatrix4fv(this.uniforms.projectionMatrix, false, this.viewer._pMatrix);
        gl.enableVertexAttribArray(this.attributes.position);
        gl.enableVertexAttribArray(this.attributes.uv);
        gl.uniform2f(this.uniforms.uvOffset,-0.5, -0.5);
        gl.uniform2f(this.uniforms.uvScale, 1, 1);
        // gl.uniform1f(this.uniforms.opacity, 1);
        // gl.uniform3f(this.uniforms.color, material.color.r, material.color.g, material.color.b);
        gl.uniform1f(this.uniforms.rotation, 0);
        gl.uniform2fv(this.uniforms.center, [0,0]);
        gl.uniform2fv(this.uniforms.scale, [100,100]);

        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexBuffer);
        gl.vertexAttribPointer(this.attributes.position, 2, gl.FLOAT, false, 2 * 8, 0);
        gl.vertexAttribPointer(this.attributes.uv, 2, gl.FLOAT, false, 2 * 8, 8);
        //bind texture
        gl.activeTexture(gl.TEXTURE1);
        gl.bindTexture(gl.TEXTURE_2D, this._texture);
        gl.uniform1i(this.uniforms.u_Sampler, 1);

        gl.drawElements(gl.TRIANGLES, 6, gl.UNSIGNED_SHORT, 0);
    }

    return xSprite;
})()

**Comment by jkfhto** [comment]
@martin1cerny   Try to write a label plugin, but it doesn't display properly on the page. Can you help me analyze what went wrong with the code? Is the related matrix calculation wrong?
`// Vertex shader program
var VSHADER_SOURCE =
    'uniform mat4 matrixWorld;\n' +
    'uniform mat4 viewMatrix;\n' +
    'uniform mat4 projectionMatrix;\n' +
    'uniform float rotation;\n' +
    'uniform vec2 center;\n' +
    'uniform vec2 scale;\n' +
    'uniform vec2 uvOffset;\n' +
    'uniform vec2 uvScale;\n' +
    'varying vec2 vUV;\n' +
    'attribute vec2 position;\n' +
    'attribute vec2 uv;\n' +
    'varying vec2 v_TexCoord;\n' +
    'void main() {\n' +
    '	vUV = uvOffset + uv * uvScale;\n' +

    '	vec2 alignedPosition = ( position - center ) * scale;\n' +

    '	vec2 rotatedPosition;\n' + 
    '	rotatedPosition.x = cos( rotation ) * alignedPosition.x - sin( rotation ) * alignedPosition.y;\n' +
    '	rotatedPosition.y = sin( rotation ) * alignedPosition.x + cos( rotation ) * alignedPosition.y;\n' +

    '	vec4 mvPosition;\n' +

    '   mvPosition = viewMatrix * matrixWorld * vec4( 0.0, 0.0, 0.0, 1.0 );\n' + 
    '	mvPosition.xy += rotatedPosition;\n' +
    '   gl_Position = projectionMatrix * mvPosition;\n'+
    // '   gl_Position = vec4(position.x,position.y,0.0,1.0);\n' +
    '   v_TexCoord = uv;\n' +
    '}\n';

// Fragment shader program
var FSHADER_SOURCE =
    '#ifdef GL_ES\n' +
    'precision mediump float;\n' +
    '#endif\n' +
    'uniform sampler2D u_Sampler;\n' +
    'varying vec2 v_TexCoord;\n' +
    'void main() {\n' +
    // '	vec4 texture = texture2D( u_Sampler, v_TexCoord );\n' +
    // '	gl_FragColor = vec4( texture.xyz, texture.a * 1.0 );\n'+
    '   gl_FragColor = vec4(1.0,0.0,0.0,1.0);\n' +
    '}\n';
    
var xSprite = (function () {
    var xSpriteArr=[];
    function xSprite(image) {
        this._initialized = false;
        this.imageUrl = image || "data/sprite2.png";
        this.position = new Vector3(50550, 50, 61220);
        this.matrixWorld = glMatrix.mat4.create();
        this.viewMatrix = glMatrix.mat4.create();
        this.projectionMatrix = glMatrix.mat4.create();

        this.vertices = new Float32Array([
            -0.5, -0.5, 0, 0,
            0.5, -0.5, 1, 0,
            0.5, 0.5, 1, 1,
            -0.5, 0.5, 0, 1
        ]);

        this.faces = new Uint16Array([
            0, 1, 2,
            0, 2, 3
        ]);
    };
    xSprite.prototype.init = function (xviewer) {
        var self = this;
        this.viewer = xviewer;
        var gl = this.viewer._gl;

        //create own shader 
        this._program = null;
        this._initShader();

        //set own shader for init
        gl.useProgram(this._program);

        this.matrixWorld = glMatrix.mat4.translate(glMatrix.mat4.create(), glMatrix.mat4.create(), this.viewer._origin);

        var program = this._program;
        this.vertexBuffer = gl.createBuffer();
        this.elementBuffer = gl.createBuffer();

        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexBuffer);
        gl.bufferData(gl.ARRAY_BUFFER, this.vertices, gl.STATIC_DRAW);

        gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this.elementBuffer);
        gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, this.faces, gl.STATIC_DRAW);
        //create uniform and attribute pointers

        this.attributes = {
            position: gl.getAttribLocation(program, 'position'),
            uv: gl.getAttribLocation(program, 'uv')
        };

        this.uniforms = {
            u_Sampler: gl.getUniformLocation(program, 'u_Sampler'),
            uvOffset: gl.getUniformLocation(program, 'uvOffset'),
            uvScale: gl.getUniformLocation(program, 'uvScale'),

            rotation: gl.getUniformLocation(program, 'rotation'),
            center: gl.getUniformLocation(program, 'center'),
            scale: gl.getUniformLocation(program, 'scale'),

            color: gl.getUniformLocation(program, 'color'),
            map: gl.getUniformLocation(program, 'map'),
            opacity: gl.getUniformLocation(program, 'opacity'),

            matrixWorld: gl.getUniformLocation(program, 'matrixWorld'),
            viewMatrix: gl.getUniformLocation(program, 'viewMatrix'),
            projectionMatrix: gl.getUniformLocation(program, 'projectionMatrix'),

            // fogType: gl.getUniformLocation(program, 'fogType'),
            // fogDensity: gl.getUniformLocation(program, 'fogDensity'),
            // fogNear: gl.getUniformLocation(program, 'fogNear'),
            // fogFar: gl.getUniformLocation(program, 'fogFar'),
            // fogColor: gl.getUniformLocation(program, 'fogColor'),
            // fogDepth: gl.getUniformLocation(program, 'fogDepth'),

            // alphaTest: gl.getUniformLocation(program, 'alphaTest')
        };

        //create texture
        var self = this;
        this._texture = gl.createTexture();
        if (typeof (this._image) === "undefined") {
            //add HTML UI to viewer port
            var data = this.imageUrl;
            var image = new Image();
            self._image = image;
            image.addEventListener("load", function () {
                //load image texture into GPU
                gl.bindTexture(gl.TEXTURE_2D, self._texture);
                gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
                gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, self._image);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);

                gl.generateMipmap(gl.TEXTURE_2D);
            });
            image.src = data;
        } else {
            //load image texture into GPU
            gl.bindTexture(gl.TEXTURE_2D, self._texture);
            gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
            gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, self._image);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
            gl.generateMipmap(gl.TEXTURE_2D);
        }


        this._initialized = true;
        xSpriteArr.push(this);
    };
    xSprite.prototype._initShader = function () {
        var gl = this.viewer._gl;
        var viewer = this.viewer;
        var compile = function (shader, code) {
            gl.shaderSource(shader, code);
            gl.compileShader(shader);
            if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
                viewer._error(gl.getShaderInfoLog(shader));
                return null;
            }
        };
        //fragment shader
        var fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
        compile(fragmentShader, FSHADER_SOURCE);
        //vertex shader (the more complicated one)
        var vertexShader = gl.createShader(gl.VERTEX_SHADER);
        compile(vertexShader, VSHADER_SOURCE);
        //link program
        this._program = gl.createProgram();
        gl.attachShader(this._program, vertexShader);
        gl.attachShader(this._program, fragmentShader);
        gl.linkProgram(this._program);
        if (!gl.getProgramParameter(this._program, gl.LINK_STATUS)) {
            viewer._error('Could not initialise shaders for a navigation cube plugin');
        }
    };

    xSprite.prototype.onAfterDraw = function () {
        var gl = this.setActive();
        // //set uniform for colour coding to false
        // gl.uniform1i(this._colourCodingUniformPointer, 0);
        this.draw();
        this.setInactive();
    };
    xSprite.prototype.onBeforeDrawId = function () {};

    xSprite.prototype.onAfterDrawId = function () {
        var gl = this.setActive();
        // //set uniform for colour coding to false
        // gl.uniform1i(this._colourCodingUniformPointer, 1);
        this.draw();
        this.setInactive();
    };

    xSprite.prototype.onBeforeGetId = function (id) {};
    xSprite.prototype.setActive = function () {
        var gl = this.viewer._gl;
        //set own shader
        gl.useProgram(this._program);
        return gl;
    };

    xSprite.prototype.setInactive = function () {
        var gl = this.viewer._gl;
        //set viewer shader
        gl.useProgram(this.viewer._shaderProgram);
    };

    xSprite.prototype.draw = function () {
        if (!this._initialized)
            return;
        var gl = this.viewer._gl;
        gl.useProgram(this._program);
        this.matrixWorld = glMatrix.mat4.translate(glMatrix.mat4.create(), glMatrix.mat4.create(), this.viewer._origin);
        gl.uniformMatrix4fv(this.uniforms.matrixWorld, false, this.matrixWorld);
        gl.uniformMatrix4fv(this.uniforms.viewMatrix, false, this.viewer._mvMatrix);
        gl.uniformMatrix4fv(this.uniforms.projectionMatrix, false, this.viewer._pMatrix);
        gl.enableVertexAttribArray(this.attributes.position);
        gl.enableVertexAttribArray(this.attributes.uv);
        gl.uniform2f(this.uniforms.uvOffset,-0.5, -0.5);
        gl.uniform2f(this.uniforms.uvScale, 1, 1);
        // gl.uniform1f(this.uniforms.opacity, 1);
        // gl.uniform3f(this.uniforms.color, material.color.r, material.color.g, material.color.b);
        gl.uniform1f(this.uniforms.rotation, 0);
        gl.uniform2fv(this.uniforms.center, [0,0]);
        gl.uniform2fv(this.uniforms.scale, [100,100]);

        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexBuffer);
        gl.vertexAttribPointer(this.attributes.position, 2, gl.FLOAT, false, 2 * 8, 0);
        gl.vertexAttribPointer(this.attributes.uv, 2, gl.FLOAT, false, 2 * 8, 8);
        //bind texture
        gl.activeTexture(gl.TEXTURE1);
        gl.bindTexture(gl.TEXTURE_2D, this._texture);
        gl.uniform1i(this.uniforms.u_Sampler, 1);

        gl.drawElements(gl.TRIANGLES, 6, gl.UNSIGNED_SHORT, 0);
    }

    return xSprite;
})()`

**Comment by jkfhto** [comment]
// Vertex shader program
var VSHADER_SOURCE =
    "uniform mat4 matrixWorld;\n" +
    "uniform mat4 viewMatrix;\n" +
    "uniform mat4 projectionMatrix;\n" +
    "uniform float rotation;\n" +
    "uniform vec2 center;\n" +
    "uniform vec2 scale;\n" +
    "uniform vec2 uvOffset;\n" +
    "uniform vec2 uvScale;\n" +
    "varying vec2 vUV;\n" +
    "attribute vec2 position;\n" +
    "attribute vec2 uv;\n" +
    "varying vec2 v_TexCoord;\n" +
    "void main() {\n" +
    "	vUV = uvOffset + uv * uvScale;\n" +

    "	vec2 alignedPosition = ( position - center ) * scale;\n" +

    "	vec2 rotatedPosition;\n" + 
    "	rotatedPosition.x = cos( rotation ) * alignedPosition.x - sin( rotation ) * alignedPosition.y;\n" +
    "	rotatedPosition.y = sin( rotation ) * alignedPosition.x + cos( rotation ) * alignedPosition.y;\n" +

    "	vec4 mvPosition;\n" +

    "   mvPosition = viewMatrix * matrixWorld * vec4( 0.0, 0.0, 0.0, 1.0 );\n" + 
    "	mvPosition.xy += rotatedPosition;\n" +
    "   gl_Position = projectionMatrix * mvPosition;\n"+
    // "   gl_Position = vec4(position.x,position.y,0.0,1.0);\n" +
    "   v_TexCoord = uv;\n" +
    "}\n";

// Fragment shader program
var FSHADER_SOURCE =
    "#ifdef GL_ES\n" +
    "precision mediump float;\n" +
    "#endif\n" +
    "uniform sampler2D u_Sampler;\n" +
    "varying vec2 v_TexCoord;\n" +
    "void main() {\n" +
    // "	vec4 texture = texture2D( u_Sampler, v_TexCoord );\n" +
    // "	gl_FragColor = vec4( texture.xyz, texture.a * 1.0 );\n"+
    "   gl_FragColor = vec4(1.0,0.0,0.0,1.0);\n" +
    "}\n";
    
var xSprite = (function () {
    var xSpriteArr=[];
    function xSprite(image) {
        this._initialized = false;
        this.imageUrl = image || "data/sprite2.png";
        this.position = new Vector3(50550, 50, 61220);
        this.matrixWorld = glMatrix.mat4.create();
        this.viewMatrix = glMatrix.mat4.create();
        this.projectionMatrix = glMatrix.mat4.create();

        this.vertices = new Float32Array([
            -0.5, -0.5, 0, 0,
            0.5, -0.5, 1, 0,
            0.5, 0.5, 1, 1,
            -0.5, 0.5, 0, 1
        ]);

        this.faces = new Uint16Array([
            0, 1, 2,
            0, 2, 3
        ]);
    };
    xSprite.prototype.init = function (xviewer) {
        var self = this;
        this.viewer = xviewer;
        var gl = this.viewer._gl;

        //create own shader 
        this._program = null;
        this._initShader();

        //set own shader for init
        gl.useProgram(this._program);

        this.matrixWorld = glMatrix.mat4.translate(glMatrix.mat4.create(), glMatrix.mat4.create(), this.viewer._origin);

        var program = this._program;
        this.vertexBuffer = gl.createBuffer();
        this.elementBuffer = gl.createBuffer();

        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexBuffer);
        gl.bufferData(gl.ARRAY_BUFFER, this.vertices, gl.STATIC_DRAW);

        gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this.elementBuffer);
        gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, this.faces, gl.STATIC_DRAW);
        //create uniform and attribute pointers

        this.attributes = {
            position: gl.getAttribLocation(program, 'position'),
            uv: gl.getAttribLocation(program, 'uv')
        };

        this.uniforms = {
            u_Sampler: gl.getUniformLocation(program, 'u_Sampler'),
            uvOffset: gl.getUniformLocation(program, 'uvOffset'),
            uvScale: gl.getUniformLocation(program, 'uvScale'),

            rotation: gl.getUniformLocation(program, 'rotation'),
            center: gl.getUniformLocation(program, 'center'),
            scale: gl.getUniformLocation(program, 'scale'),

            color: gl.getUniformLocation(program, 'color'),
            map: gl.getUniformLocation(program, 'map'),
            opacity: gl.getUniformLocation(program, 'opacity'),

            matrixWorld: gl.getUniformLocation(program, 'matrixWorld'),
            viewMatrix: gl.getUniformLocation(program, 'viewMatrix'),
            projectionMatrix: gl.getUniformLocation(program, 'projectionMatrix'),

            // fogType: gl.getUniformLocation(program, 'fogType'),
            // fogDensity: gl.getUniformLocation(program, 'fogDensity'),
            // fogNear: gl.getUniformLocation(program, 'fogNear'),
            // fogFar: gl.getUniformLocation(program, 'fogFar'),
            // fogColor: gl.getUniformLocation(program, 'fogColor'),
            // fogDepth: gl.getUniformLocation(program, 'fogDepth'),

            // alphaTest: gl.getUniformLocation(program, 'alphaTest')
        };

        //create texture
        var self = this;
        this._texture = gl.createTexture();
        if (typeof (this._image) === "undefined") {
            //add HTML UI to viewer port
            var data = this.imageUrl;
            var image = new Image();
            self._image = image;
            image.addEventListener("load", function () {
                //load image texture into GPU
                gl.bindTexture(gl.TEXTURE_2D, self._texture);
                gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
                gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, self._image);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);

                gl.generateMipmap(gl.TEXTURE_2D);
            });
            image.src = data;
        } else {
            //load image texture into GPU
            gl.bindTexture(gl.TEXTURE_2D, self._texture);
            gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
            gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, self._image);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
            gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
            gl.generateMipmap(gl.TEXTURE_2D);
        }


        this._initialized = true;
        xSpriteArr.push(this);
    };
    xSprite.prototype._initShader = function () {
        var gl = this.viewer._gl;
        var viewer = this.viewer;
        var compile = function (shader, code) {
            gl.shaderSource(shader, code);
            gl.compileShader(shader);
            if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
                viewer._error(gl.getShaderInfoLog(shader));
                return null;
            }
        };
        //fragment shader
        var fragmentShader = gl.createShader(gl.FRAGMENT_SHADER);
        compile(fragmentShader, FSHADER_SOURCE);
        //vertex shader (the more complicated one)
        var vertexShader = gl.createShader(gl.VERTEX_SHADER);
        compile(vertexShader, VSHADER_SOURCE);
        //link program
        this._program = gl.createProgram();
        gl.attachShader(this._program, vertexShader);
        gl.attachShader(this._program, fragmentShader);
        gl.linkProgram(this._program);
        if (!gl.getProgramParameter(this._program, gl.LINK_STATUS)) {
            viewer._error('Could not initialise shaders for a navigation cube plugin');
        }
    };

    xSprite.prototype.onAfterDraw = function () {
        var gl = this.setActive();
        // //set uniform for colour coding to false
        // gl.uniform1i(this._colourCodingUniformPointer, 0);
        this.draw();
        this.setInactive();
    };
    xSprite.prototype.onBeforeDrawId = function () {};

    xSprite.prototype.onAfterDrawId = function () {
        var gl = this.setActive();
        // //set uniform for colour coding to false
        // gl.uniform1i(this._colourCodingUniformPointer, 1);
        this.draw();
        this.setInactive();
    };

    xSprite.prototype.onBeforeGetId = function (id) {};
    xSprite.prototype.setActive = function () {
        var gl = this.viewer._gl;
        //set own shader
        gl.useProgram(this._program);
        return gl;
    };

    xSprite.prototype.setInactive = function () {
        var gl = this.viewer._gl;
        //set viewer shader
        gl.useProgram(this.viewer._shaderProgram);
    };

    xSprite.prototype.draw = function () {
        if (!this._initialized)
            return;
        var gl = this.viewer._gl;
        gl.useProgram(this._program);
        this.matrixWorld = glMatrix.mat4.translate(glMatrix.mat4.create(), glMatrix.mat4.create(), this.viewer._origin);
        gl.uniformMatrix4fv(this.uniforms.matrixWorld, false, this.matrixWorld);
        gl.uniformMatrix4fv(this.uniforms.viewMatrix, false, this.viewer._mvMatrix);
        gl.uniformMatrix4fv(this.uniforms.projectionMatrix, false, this.viewer._pMatrix);
        gl.enableVertexAttribArray(this.attributes.position);
        gl.enableVertexAttribArray(this.attributes.uv);
        gl.uniform2f(this.uniforms.uvOffset,-0.5, -0.5);
        gl.uniform2f(this.uniforms.uvScale, 1, 1);
        // gl.uniform1f(this.uniforms.opacity, 1);
        // gl.uniform3f(this.uniforms.color, material.color.r, material.color.g, material.color.b);
        gl.uniform1f(this.uniforms.rotation, 0);
        gl.uniform2fv(this.uniforms.center, [0,0]);
        gl.uniform2fv(this.uniforms.scale, [100,100]);

        gl.bindBuffer(gl.ARRAY_BUFFER, this.vertexBuffer);
        gl.vertexAttribPointer(this.attributes.position, 2, gl.FLOAT, false, 2 * 8, 0);
        gl.vertexAttribPointer(this.attributes.uv, 2, gl.FLOAT, false, 2 * 8, 8);
        //bind texture
        gl.activeTexture(gl.TEXTURE1);
        gl.bindTexture(gl.TEXTURE_2D, this._texture);
        gl.uniform1i(this.uniforms.u_Sampler, 1);

        gl.drawElements(gl.TRIANGLES, 6, gl.UNSIGNED_SHORT, 0);
    }

    return xSprite;
})()

**Comment by martin1cerny** [comment]
This is now supported in the latest version of the viewer.
