### ISSUE TITLE
uVertexSampler problem

### ISSUE THREAD

**Issue by jkfhto** [xBimTeam/XbimWebUI#211]
Is the vertex data stored in the texture not forced to map to the [0-1] range? As shown below

![image](https://user-images.githubusercontent.com/27767452/48937703-e9dc9a80-ef49-11e8-9c64-cef1b5fea661.png)

**Comment by martin1cerny** [comment]
Can you explain why this is a problem please? Do you experience any issues? How are these issues related to the texture?

**Comment by jkfhto** [comment]
I got it wrong.
