### ISSUE TITLE
Bounding Box Coordinates from Xviewer

### ISSUE THREAD

**Issue by satregiftc** [xBimTeam/XbimWebUI#214]
Hi ..

How to get bownding box  coordinates for the selected entity on the xViewer map displayed on the browser from viwer API. please help out

Regards
Satish

**Comment by martin1cerny** [comment]
This is not exposed through the API. Feel free to make a contribution to expose this. You can get inspired [here](https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/viewer.ts#L638).

**Comment by martin1cerny** [comment]
This can be done in the latest version of the viewer.
