### ISSUE TITLE
Why was support for noFPT seemingly dropped ?

### ISSUE THREAD

**Issue by SBRK** [xBimTeam/XbimWebUI#215]
The last commit for the noFPT shader seems to be 2 years before the last commit to the regular shader, and rendering doesn't seem to work on devices with no Floating Point Texture support, so I assume the support for these devices was dropped ? It's a shame because [with the release of the Galaxy S8, the support for this extension dropped from 95% to 79%](https://webglstats.com/webgl/extension/OES_texture_float). Basically all Samsung Galaxy Sx devices don't support it which is a big problem. 

Why was it dropped? Was it too much work to maintain both versions, or did a particular change made it impossible to make it work without FPT? What was wrong with using 3 pixels instead of one for the vertices? (appart from making the maximum triangles 3 times lower)? With my biggest models I'm still way below the limit, even with a max texture size of 4096.

**Comment by SBRK** [comment]
By the way, why using a texture for vertices instead of a vertex buffer ?

**Comment by SBRK** [comment]
After a test using buffers to pass vertices instead of textures, I see no impact on performance

**Comment by martin1cerny** [comment]
The reason is that [WebGL has a limit of 16bit index](https://stackoverflow.com/a/5018021/6345585) so almost all models would have to be split across several buffers. Instead of management of this we decided to use floating point texture to transfer all the data to GPU to simplify the process. The fallback implementer in start which uses normal texture where float is encoded as RGB components of the texture makes the performance very poor so it wasn't actively maintained. 

Saying so, the problem is actually different. New mobile devices have support for floating point texture in WebGL2 but current version of the viewer only implements version 1.

**Comment by SBRK** [comment]
I managed to fix the noFPT shader myself, and yes, it was painfully slow. 

However I did my own version with vertices in a buffer, already transformed. From what I read, the 16 bit index limit doesn't stand for `drawArrays` ? That way you can still keep the vertices in a buffer, without relying on an index buffer. Takes up more ram, but it should work even for bigger models, right ?

**Comment by martin1cerny** [comment]
Yes, that is why we use `drawArrays`. The problem is a lot more RAM as you say because you have to transform it all upfront. And I already have several models which take my GPU down completely because it is overloaded.

**Comment by SBRK** [comment]
Would making several drawArrays with the transform matrix passed as uniform be too slow ?

**Comment by martin1cerny** [comment]
I'm happy for you to try it out. This is very dependant on the model you have. Some models will only have very small number or no transforms, others might have thousands. No-transform is modelled as a -1 in the transform index and leaves out part of the processing in the shader. With your approach you would have to pass identity matrices for all objects with no transforms as well. This is always a trade-off. But as I said: I'm very happy to learn if you find a more efficient way.

**Comment by martin1cerny** [comment]
A new version of the viewer has been published with many improvements. It is available as an [npm package](https://www.npmjs.com/package/@xbim/viewer) now. It supports WebGL2 which makes it run on most current devices.
