### ISSUE TITLE
How can i show grid with xBim Web UI?

### ISSUE THREAD

**Issue by mobdev313** [xBimTeam/XbimWebUI#216]
How can I show grid with xBim Web Viewer?

**Comment by martin1cerny** [comment]
What kind of grid do you mean? `IfcGrid`, or the grid which some viewers show bellow the model?

**Comment by mobdev313** [comment]
Thanks for reply, I mean the grid which some viewers show below the model.

**Comment by martin1cerny** [comment]
This is not implemented now but is not very hard to do. It can be implemented as a plugin into the current viewer.

**Comment by mobdev313** [comment]
I am a newer in xBim. could you let me know any hint for implement it?

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It has a grid plugin implemented.
