### ISSUE TITLE
How to unload or hide a model

### ISSUE THREAD

**Issue by Harara81** [xBimTeam/XbimWebUI#22]
Hello,

I have loaded two models in the xViewer...I want hide or unload on of them when a button clicked

        viewer.load("../data/pro.wexbim");
        viewer.load("../data/SampleHouse.wexbim");
        viewer.start();

**Comment by martin1cerny** [comment]
Hi @Harara81 ,

models are kept separate inside of the viewer class so it is technically possible to switch them on/off separately. However, this functionality is not implemented now. If you want to implement it you would have to modify [this piece of code](https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L966). Every model is in one handle:
```javascript
for (var i in this._handles) {
    var handle = this._handles[i];
    handle.setActive(this._pointers);
    handle.draw();
}
```
