### ISSUE TITLE
Model highlighting problem

### ISSUE THREAD

**Issue by jkfhto** [xBimTeam/XbimWebUI#220]
Use xViewer.prototype.setState This method highlights the model, but it will be occluded by other models. Is there any solution?

**Comment by martin1cerny** [comment]
I'm sorry, but I don't understand your question.

**Comment by jkfhto** [comment]
Use Use xViewer.prototype.setState to highlight the model locally, but to change the camera's perspective, other objects will block the highlighted model. How do you keep the local model highlighted and not occluded?

**Comment by martin1cerny** [comment]
That is a good question. What do you suggest?

**Comment by martin1cerny** [comment]
A new version of the viewer has been published with many improvements. It is available as an [npm package](https://www.npmjs.com/package/@xbim/viewer) now. It has an ultra x-reay rendering mode which solves this issue.
