### ISSUE TITLE
Show Dimensions on X-Bim web viewer 

### ISSUE THREAD

**Issue by satregiftc** [xBimTeam/XbimWebUI#224]
Hi..

Can i get help to show line , dimension and annotation on web viewer

Regards
Satish

**Comment by martin1cerny** [comment]
This is relatively complex task requiring days to weeks of development. Showing the line is easy, computing distance between two points is easy but user interaction allowing to identify the end points for the measurement is uneasy.

**Comment by satregiftc** [comment]
Hi..

Thank you for your support. We are using QTIP for showing details in Pop-up.

It will be a big help if you can make provision programatically in XBIMWEBUI to 

1. Draw a Line between 2 Points identified programatically without user interaction

2. Compute Distance between 2 Points and display distance as a bubble at center of the line

![distance_line](https://user-images.githubusercontent.com/33161851/51298515-d716ab80-1a4a-11e9-900f-c2f1a648a230.png)


Regerds
Satish

**Comment by satregiftc** [comment]
Hi..
it would be helpful if you can you send me pointers where to look in to source code as we have gone thru most of your code. Thank you 

Reagrds
Satish

**Comment by martin1cerny** [comment]
Have a look at the navigation cube plugin. You should be able to implement what you need using the same extension points.

**Comment by OmarKhairyHosny** [comment]
> Hi..
> 
> Thank you for your support. We are using QTIP for showing details in Pop-up.
> 
> It will be a big help if you can make provision programatically in XBIMWEBUI to
> 
> 1. Draw a Line between 2 Points identified programatically without user interaction
> 2. Compute Distance between 2 Points and display distance as a bubble at center of the line
> 
> ![distance_line](https://user-images.githubusercontent.com/33161851/51298515-d716ab80-1a4a-11e9-900f-c2f1a648a230.png)
> 
> Regerds
> Satish

Hi,
Can you show how do you implement this Pop-up ?

Regards,
Omar

**Comment by HristijanJohn** [comment]
Hello, 
Any news on this topic? Can we get any help, even on commercial basis, because we really need this plugin for our project. Thanks.

**Comment by martin1cerny** [comment]
The latest version has support for 3D measurements built in. All interaction events contain [x,y,z] coordinates. We haven't published the source yet, but the NPM package is available: https://www.npmjs.com/package/@xbim/viewer
From two clicks you can obviously compute the distance. You just need to draw an overlay with this information and line. You can do this using canvas or SVG and format the overlay any way you want to fit into your application.

**Comment by HristijanJohn** [comment]
Thanks a lot. Are you planning to publish the source code soon? Because we have a lot of changes inside js files at our side.

**Comment by martin1cerny** [comment]
A new version of the viewer has been published with many improvements. It is available as an [npm package](https://www.npmjs.com/package/@xbim/viewer) now. It has the functionality described earlier where you can get a 3D point from any user interaction.
