### ISSUE TITLE
Rotate 3D model

### ISSUE THREAD

**Issue by MarcoGiorgi** [xBimTeam/XbimWebUI#226]
I'm experiencing some issue in the automatic rotation of the model.
I've copied the code found here http://docs.xbim.net/ to rotate the model every 20ms

Randomly doesn't work on my site, let's say 80% of times.

this is the error I get:
```
gl-matrix.min.js:63 Uncaught TypeError: Cannot read property '0' of null
    at Object.mat4.translate (gl-matrix.min.js:63)
    at rotate (DashboardView:1428)
```

the line that raise the exception is:
`transform = mat4.translate(mat4.create(), transform, translation);`

here is the full code:
`

            viewer.on('loaded', function () {
                var shouldRotate = true;
                function rotate() {
                    if (!shouldRotate) {
                        return;
                    }

                    var origin = viewer._origin;
                    var camera = viewer.getCameraPosition();

                    //get origin coordinates in view space
                    var mvOrigin = vec3.transformMat4(vec3.create(), origin, viewer._mvMatrix)

                    //movement factor needs to be dependant on the distance but one meter is a minimum so that movement wouldn't stop when camera is in 0 distance from navigation origin
                    var distanceVec = vec3.subtract(vec3.create(), origin, camera);
                    var distance = Math.max(vec3.length(distanceVec), viewer._handles[0]._model.meter);

                    //move to the navigation origin in view space
                    var transform = mat4.translate(mat4.create(), mat4.create(), mvOrigin)

                    //z rotation around model z axis
                    var mvZ = vec3.transformMat3(vec3.create(), [0, 0, 1], mat3.fromMat4(mat3.create(), viewer._mvMatrix));
                    mvZ = vec3.normalize(vec3.create(), mvZ);
                    transform = mat4.rotate(mat4.create(), transform, Math.PI / 700.0, mvZ);

                    //reverse the translation in view space and leave only navigation changes
                    var translation = vec3.negate(vec3.create(), mvOrigin);
                    transform = mat4.translate(mat4.create(), transform, translation);

                    //apply transformation in right order
                    viewer._mvMatrix = mat4.multiply(mat4.create(), transform, viewer._mvMatrix);

                }
                $("#ifcViewer").mousedown(function () { shouldRotate = false; });

                setTimeout(function () { setInterval(rotate, 30); }, 1500);
            });
            viewer.background = [220, 220, 220];
            viewer.load('/x2.wexbim');
                viewer.start();
            var cube = new xNavigationCube();
            cube.passiveAlpha = 0.5;
            cube.ratio = 0.05;
            cube.activeAlpha = 0.8;
            viewer.addPlugin(cube);
`
I've noticed that the more I **reduce** the size of the viewer more exception I get (under 450-500px in width, it always raise the exception).

**Comment by MarcoGiorgi** [comment]
You're right Martin, finally I've debug it and it's all a timing issue.
I've noticed that during the viewer.start() the UI become unresponsive for a time that depends by the complexity of the model.

Is there a way/workaround to keep the UI responsive while the viewer initialize and draw the model?

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). That has `viewer.loadAsync()` function which uses web worker to fetch and parse the data. While it will still take time to pass data to GPU, general responsiveness should be much better. Also, using new TS compiler seems to produce more efficient code in general.
