### ISSUE TITLE
Custom development?

### ISSUE THREAD

**Issue by krosoftware** [xBimTeam/XbimWebUI#227]
Hello,
we need some additional features ti viewer - are you guys available for custom development?
My email is DELETEkro.softwareDELETE@gmail.com (please remove words DELETE from email).
Thank you.

**Comment by andyward** [comment]
Picked up by email.

More generally, yes, we're available to do custom work particularly if well aligned with the goals of the XBIM project. Just drop @martin1cerny @andyward  or @SteveLockley a note
