### ISSUE TITLE
Window and door normals seem wrong

### ISSUE THREAD

**Issue by SBRK** [xBimTeam/XbimWebUI#228]
I entirely rewrote lighing in my version of the viewer, and noticed something odd. 
The lighting of the windows and doors seems wrong. On some sides of the building I'm rendering, the window and doors would be black when the rest of the facade is all white. 

It does not appear to be just inverted, since depending on the side and the position of my light, they would sometime match the lighting of the wall and sometimes not. I suspect they have the same bogus  normal

**Comment by martin1cerny** [comment]
If these are OK with the default shader than I don't think this is the case because it would be visible there too. Windows and doors are usually mapped geometries so make sure you transform the normals as well as geometries.

**Comment by SBRK** [comment]
I changed the code to apply transforms to the vertices directly, but didn't think about transforming the normals as well. That's probably the issue. Thanks !

**Comment by martin1cerny** [comment]
We published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). This applies transformations to normals of mapped items correctly.
