### ISSUE TITLE
xViewer.getStyle(id) doesn't return result

### ISSUE THREAD

**Issue by psurpl** [xBimTeam/XbimWebUI#229]
#### Expected behavior:
xViewer.getStyle(id) should return value.

#### Actual behavior or exception details:
xViewer.getStyle(id) doesn't return value at all. If you assign result of it to some variable you will always get undefined.

I think getStyle is missing return before second line (should be _return this.forHandleOrAll..._):

```
    public getStyle(id: number, modelId?: number) {
        this.forHandleOrAll((handle: ModelHandle) => {
            return handle.getStyle(id);
        }, modelId);
    }
```

Here is code to reproduce:

```
            this.xviewer.on('pick', (args: IxViewerPickEventArg) => {
                let colorIndex: number = 5;
                let labels: number[] = [];
                labels.push(args.id);
                this.xviewer.setStyle(colorIndex, labels);
                let style = this.xviewer.getStyle(args.id); //here we always get undefined
                console.log(style);
            });
```

**Comment by Kiiiwiii** [comment]
The same as getState
```
xViewer.prototype.getState = function (id) {
    this._handles.forEach(function (handle) {
        var state = handle.getState(id);
        if (state !== null) {
            return state;
        }
    }, this);
    return null;
};
```

**Comment by martin1cerny** [comment]
A new version of the viewer has been published with many improvements. It is available as an [npm package](https://www.npmjs.com/package/@xbim/viewer) now. This issue has been fixed in there.
