### ISSUE TITLE
.Wexbim Viewer Diagram is not displayed on IE11...

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#23]
Hi,
I have problem to display a .wexbim diagram on IE11 . I got an error as follows
.ie WEBGL11041: INVALID_VALUE: enableVertexAttribArray: Parameter outside of bounds
       File: xbim-viewer.debug.js, Line: 619, Column: 5

I have also check with latest XbimWebUI resource on IE11 browser. That Source is also not displaying a .wexbim diagram on IE and getting a same error.

**Comment by dhundaleamol** [comment]
Hi Martin,

Can you please give me any suggestion to resolve this issue.
I got an error on this line 
result = new ctor(this._buffer.slice(offset, offset + length));
in Xbim.binary.reader.js

**Comment by martin1cerny** [comment]
Hi Amol,

you will have to provide me with wider context so that I can make any suggestions. Also, please make sure to get the latest code both for generation of the wexBIM file and for visualization.

**Comment by BIMDevelopement** [comment]
Hi Martin,

I already check a leatest source of XBIMWEBUI  from Github. It is also not displaying a viewer diagram on IE11

**Comment by BIMDevelopement** [comment]
Hi Martin, 

Thanx I got a solution .
