### ISSUE TITLE
setCameraPosition() called immediately after getCameraPosition() changes camera position

### ISSUE THREAD

**Issue by psurpl** [xBimTeam/XbimWebUI#230]
The assumption is that you can get camera position by calling getCameraPosition() and then restore the same position using setCameraPosition(). Hence calling setCameraPosition() just after getCameraPosition() (obviously passing to set... data returned by get...) should not change camera position - you should see the same view.

But this not always happens. For example when you rotate building to be upside down then after calling getCameraPosition() -> setCameraPosition() it is rotated so that it is not upside down anymore. Something similar usually happens when building is seen from the bottom. More ordinary camera positions works correctly.

Calling setCameraTarget() doesn't change anything.

Here is TypeScript code to illustrate (loop is because setCameraPosition() expects different type than getCameraPosition() returns):
```
            let cameraPositionTyped = this.xviewer.getCameraPosition();

            let cameraPosition: number[] = [];
            for (let i = 0; i < cameraPositionTyped.length; i++)
                cameraPosition.push(cameraPositionTyped[i]);

            // tried with each of this and without it - all combinations:
            // this.xviewer.setCameraTarget(undefined, modelId);
            // this.xviewer.setCameraTarget();

            this.xviewer.setCameraPosition(cameraPosition);
```

Maybe it is somehow related with hardcoding last argument ("up") of lookAt function.
```
	    xViewer.prototype.setCameraPosition = function (coordinates) {
	        if (typeof (coordinates) == 'undefined')
	            throw 'Parameter coordinates must be defined';
	        glMatrix.mat4.lookAt(this._mvMatrix, coordinates, this._origin, [0, 0, 1]);
	    };
```

**Comment by laarmen** [comment]
I have a fix for that, I should post it Monday.

**Comment by martin1cerny** [comment]
If you want to recreate exactly same view it is better to get/set the `_mvMatrix` directly.

**Comment by psurpl** [comment]
Thank you very much Martin, it is indeed what I needed.
