### ISSUE TITLE
is there any xBrowser usage example?

### ISSUE THREAD

**Issue by Getequ** [xBimTeam/XbimWebUI#232]
Hi guys, is there any xBrowser usage example? I found examples of xViewer and how to convert IFC to weXbim. But how to use xBrowser with xViewer?

**Comment by andyward** [comment]
Not a lot but there's the BrowserExample in the develop branch: https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Examples/BrowserExample/browser.js

And there's some JSDocs at http://docs.xbim.net/XbimWebUI/xBrowser.html

**Comment by Getequ** [comment]
@andyward Thank you for first link! 
Can you also give me a guide for how i can get json-file for browser from ifc-model?

**Comment by andyward** [comment]
Take a look at https://github.com/xBimTeam/XbimExchange/blob/master/CreateCobiePas1192/Program.cs

**Comment by Getequ** [comment]
Thanks again!

I noticed that in browser.js used old class names - Browser instead of xBrowser, 4ex, and this project are lacked xbim-viewer/xbim-browser files. And `<remove fileExtension=".json"/>` node in web.config is causing 404 for json-files

**Comment by Getequ** [comment]
@andyward thank you very much for quick and useful answers! All works great (in common). This issue can be closed.

The only issue i met is that .json generation failed on some models
