### ISSUE TITLE
Fullscreen Clipping

### ISSUE THREAD

**Issue by patrickluethi** [xBimTeam/XbimWebUI#238]
Hi, 

Clipping works fine and does exactly what it needs to. But if I try to do it in fullscreen I am not able to see the red clip line. As soon as i exit the fullscreen and click into the canvas the red clip line is shown. Any idea how to fix that?

Thanks

**Comment by martin1cerny** [comment]
The viewer is using an interactive SVG overlay to show the red line. So, presumably the placement of the SVG layer is wrong when in full-screen mode. You can try to debug your HTML when interactive clipping is on to see what is happening. You should see SVG as a rectangle aligned with the viewer canvas.

**Comment by patrickluethi** [comment]
That's it! Thanks!
