### ISSUE TITLE
Select only one specific IFC Class

### ISSUE THREAD

**Issue by patrickluethi** [xBimTeam/XbimWebUI#239]
When I try to select a space in the 3D Viewer, I always select a wall or what ever is 'behind' the space. Is it possible to determine which IFC Classes I only want to be able to select?

**Comment by martin1cerny** [comment]
No, this is not possible. Selection respects visibility of the objects. If you hide the wall in front of the space you can select the space. It is no spacial compared to any other object. When you see a chair behind the window, you need to hide the window to be able to select the chair.

**Comment by patrickluethi** [comment]
How can i hide all elements of an IFC Class in the Viewer?

**Comment by martin1cerny** [comment]
See the [docs and examples](http://docs.xbim.net/XbimWebUI/tutorial-5_Colourful_building.html) please.

**Comment by patrickluethi** [comment]
@martin1cerny I cant seem to find a solution in the docs. Is it possible that this is not implemented?

**Comment by martin1cerny** [comment]
No, that is not possible.

```js
viewer.setState(xState.HIDDEN, xProductType.IFCSPACE);
```

This will hide all spaces. This functionality has been supported from the very first version.

**Comment by patrickluethi** [comment]
Thank You! Solved my problem.
