### ISSUE TITLE
 BIM ID changing with minor modifications in original file

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#24]
The Bim ID for all objetcs are changing ,everytime any object is deleted or added to the original file. What i want to achieve is, if i make minor modifications to a file such as adding a chair or removing a table, the other objects which have not been changed at all, the BIM id should not change. Is there any other ID's that i can extract from .Xbim file that are unique to every object, so the id's of all objects dont change after some minor modifications have been made in the file..?

**Comment by LloydPickering** [comment]
The EntityLabel refers the the ID in the IFC File. I think that's what you mean by BIM ID. There is also the IFC GUID of the objects which in theory should be stable (in practice it depends on the design tool).

**Comment by dhundaleamol** [comment]
Thanx LloydPickering .

I was aware about EntityLabel .but I didnot about GUID.I will check it..
