### ISSUE TITLE
About collision detection

### ISSUE THREAD

**Issue by xujunpro2** [xBimTeam/XbimWebUI#242]
You have done a great job and I want to know if there is a development plan for collision detection.

**Comment by martin1cerny** [comment]
Thanks. Collision detection will certainly not be a feature of the viewer as it would be very CPU intensive task for the browser. But you can implement this server-side and than present the results in the viewer.

**Comment by xujunpro2** [comment]
Thanks for your reply, based on the api you provided, I implemented the first perspective of roaming. The current requirement is that if you are bumping a model part while roaming, I need to avoid it. I guess this function should be implemented on the client side. I would like to ask if you have any ideas. Thank you again for your great work！

**Comment by martin1cerny** [comment]
This is typically a feature of gaming engines. While geometry in games is always optimised to be as lightweight as possible, BIM geometry represents an engineering model and is typically very detailed and complex. Therefore it would be quite computing intensive to perform computations in real time as the user navigates through the model. 

We don't intend to implement this in the viewer. But is you implement this and contribute to the project as an optional feature, the contribution would certainly be most welcome.
