### ISSUE TITLE
Multiple semantic JSON in the same browser

### ISSUE THREAD

**Issue by mmmggg** [xBimTeam/XbimWebUI#243]
Is it possible to load multiple semantic JSON in the same browser?
For me, it seems that only the last loaded file is being kept.

Is there an optimal approach for archiving this: multiple wexBIM in the viewer  with all the corresponding semantic JSONs in the browser.

Thank you!

**Comment by mmmggg** [comment]
Can anyone help me with this?

**Comment by martin1cerny** [comment]
Current semantic viewer can only handle single model.

**Comment by martin1cerny** [comment]
A new version of the viewer has been published with many improvements. It is available as an [npm package](https://www.npmjs.com/package/@xbim/viewer) now. Recommended way to present semantic data is to implement your own server side code which can serve data from multiple federated models. We also work on a commercial cloud service which can be used for this purpose. [Get in touch](mailto:info@xbim.net) if interested.
