### ISSUE TITLE
how to download the xbim.geometry.Engine64.dll

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#244]

**Comment by andyward** [comment]
You don't need to download it. It's included in the [XBIM.Geometry Nuget package](https://www.nuget.org/packages/Xbim.Geometry/)

It should be automatically copied to the build bin folder when you include the Nuget package. However web projects are a bit different - so you may need to copy it manually (or with something like a Post-build step)

**Comment by castronelson** [comment]
Hi,

 

We have upgraded the xbim.geometry packages. 

 

Now we have received the different error like below:

 

 

Server Error in '/practicexbimnew' Application.

  _____  

Method 'get_Logger' in type 'Xbim.Geometry.XbimGeometryCreator' from assembly 'Xbim.Geometry.Engine64, Version=0.0.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9' does not have an implementation. 

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.TypeLoadException: Method 'get_Logger' in type 'Xbim.Geometry.XbimGeometryCreator' from assembly 'Xbim.Geometry.Engine64, Version=0.0.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9' does not have an implementation.

Source Error: 


 

Line 237:            {

Line 238:                var context = new Xbim3DModelContext(model);

Line 239:                context.CreateContext();

Line 240:

Line 241:                var wexBimFilename = Path.ChangeExtension(IfcTestFile, "wexbim");


Source File: D:\Castro\Practice1\XbimWebUI-master\Xbim.WeXplorer\ConversionfromIFC.aspx.cs    Line: 239 

Stack Trace: 


 

[TypeLoadException: Method 'get_Logger' in type 'Xbim.Geometry.XbimGeometryCreator' from assembly 'Xbim.Geometry.Engine64, Version=0.0.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9' does not have an implementation.]

   Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor() +191

   Xbim.ModelGeometry.Scene.Xbim3DModelContext.get_Engine() +44

   Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs) +78

   Xbim.WeXplorer.ConversionfromIFC.ConvertIFCtoWEXBIM(String filePath) in D:\Castro\Practice1\XbimWebUI-master\Xbim.WeXplorer\ConversionfromIFC.aspx.cs:239

   Xbim.WeXplorer.ConversionfromIFC.btnConversionfromIFC_Click(Object sender, EventArgs e) in D:\Castro\Practice1\XbimWebUI-master\Xbim.WeXplorer\ConversionfromIFC.aspx.cs:75

   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +11764877

   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +150

   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1665

 

 


Best Regards,

Castro Nelson D

Software Engineer

Email:  <mailto:castro.nelson@sierratec.com> castro.nelson@sierratec.com | Voice: +91-422-711 5566, +91 93632-20483 | Ext. 508


 <http://www.greenestbuilding.com/> 

WORLD'S SECOND HIGHEST RANKING GREEN BUILDING

rated by GBCI under LEED NC v2009

                                <https://www.greenestbuilding.com/efacility-building-walkthrough-worlds-second-greenest-building/>

**Comment by andyward** [comment]
You must have mis-matched set of assemblies somehow. Hard to sort this for you without seeing your project/package files but:

1. Clear your bin folders out
2. Make sure you're on the latest nuget packages for XBIM
3. Make sure you're project file is referencing those latest versions (and not some assembly reference
4. Rebuild everything
5. Check the versions of everything XBIM.*dll in the bin folder (notably the File Version)

I'm assuming here that it's failing on a dev machine not a server...

**Comment by castronelson** [comment]
Hi ,

 

Now we are facing this issue


Server Error in '/practicexbim' Application.



  _____  



Parser Error 


Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Could not load type 'Xbim.WeXplorer.Global'.

Source Error: 


 
Line 1:  <%@ Application Codebehind="Global.asax.cs" Inherits="Xbim.WeXplorer.Global" Language="C#" %>


Source File: /practicexbim/global.asax    Line: 1 

  _____  

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2558.0

 

Please let me know any solution ,

Thanks in advance


Best Regards,

Castro Nelson D

Software Engineer

Email:  <mailto:castro.nelson@sierratec.com> castro.nelson@sierratec.com | Voice: +91-422-711 5566, +91 93632-20483 | Ext. 508


 <http://www.greenestbuilding.com/> 

WORLD'S SECOND HIGHEST RANKING GREEN BUILDING

rated by GBCI under LEED NC v2009

                                <https://www.greenestbuilding.com/efacility-building-walkthrough-worlds-second-greenest-building/>
