### ISSUE TITLE
Walk XBIM Camera Modus

### ISSUE THREAD

**Issue by patrickluethi** [xBimTeam/XbimWebUI#246]
Is it possible to change the function of the camera. I want the camera not to move around an object while drag mouse. I want it to move around the angle. More specific the position and camera stays over an object and just the angle changes on mouse drag.

**Comment by tthmartin** [comment]
Hi! DrawingControl.Viewport has a lot of functions, IsPanEnabled= false will make the camera not to move around the object. IsRotationEnabled = true will make it move around the angle. I hope I could help you

**Comment by martin1cerny** [comment]
Current release has several new navigation modes including look-around mode.
