### ISSUE TITLE
Add a custom object into 3D model

### ISSUE THREAD

**Issue by hakimuddinhh** [xBimTeam/XbimWebUI#247]
Does a developer has the ability to add a custom object into 3D model by either using native WebGL (like NavigationCube plugin) or any other libraries like threejs.

Thanks.

**Comment by martin1cerny** [comment]
You can create your own plugin using WebGL.

**Comment by hakimuddinhh** [comment]
I dont know much about WebGL(only worked in threejs framework) and I think many users don't know much about it and As there would be requirements at many scenarios to add custom objects to the model. It would be great this feature (custom object) or plugin would be added.

**Comment by martin1cerny** [comment]
This is not a planned feature.

**Comment by hakimuddinhh** [comment]
Maybe there is some way to load the model into threejs?

**Comment by martin1cerny** [comment]
Maybe there is. It is a bunch of triangles with colours in the end. So, feel free to take the wexBIM file and push the data into any visualisation engine you like.

**Comment by andyward** [comment]
I guess it depends on what you mean by "custom object". If you wanted to place a simple pre-defined piece of geometry in the scene (e.g. an annotation marker) you could use an approach like the Navigation Cube plugin uses. 

But if you wanted to a user to have full design of the item (e.g. putting in a new building element or furniture item), it's a different level of complexity and beyond what we could support here. Three JS might provide some options -  maybe see https://github.com/xBimTeam/XbimWebUI/issues/205
