### ISSUE TITLE
Xbim Reber selection

### ISSUE THREAD

**Issue by divyanatsteel** [xBimTeam/XbimWebUI#248]
Hi  martin1cerny ,
How to select the  single rebar from reinforcement and how to extract the properties of rebar?
 can I customize the properties of the rebar?
in Xbim webui using xviewer
![reinforcement](https://user-images.githubusercontent.com/55271797/64843614-247a0580-d638-11e9-8a41-1c7b42feeca5.PNG)
thanks

**Comment by martin1cerny** [comment]
This depends on how it is modelled. Are individual rebars modelled as independent `IfcReinforcingBar`?

**Comment by divyanatsteel** [comment]
yes independent ifcreinforcingbars..

**Comment by martin1cerny** [comment]
Viewer is just a 3D viewer. To catch the `EntityLabel` of the click, see the [viewer documentation](http://docs.xbim.net/XbimWebUI/). To access any semantic data you need, see general [xBIM documentation and examples](http://docs.xbim.net/examples/basic-model-operations.html).

**Comment by divyanatsteel** [comment]
var highlightreinforcement = function () {
                viewer.setState(states.HIGHLIGHTED, types.IFCREINFORCINGBAR);
this code highlighted all reinorcingbar's I want to highlight only onclick() of single  bar's is it possible?

**Comment by martin1cerny** [comment]
Try [pick](http://docs.xbim.net/XbimWebUI/tutorial-3_Eventful_building.html) event.

**Comment by divyanatsteel** [comment]
Thank you 
  viewer.on("pick", function (args) {
                        var id = args.id;
                        viewer.setState(states.HIGHLIGHTED, [id]);
                   });

**Comment by divyanatsteel** [comment]
under pick how extract information of rebar properties like lenght,weght,name,id ,shape etc.,

**Comment by martin1cerny** [comment]
You will need to use xBIM Essentials to access the data from the model. Check our [examples](http://docs.xbim.net/examples/basic-model-operations.html) to see how to do so. The ID you get from the `pick` event is `IPersistEntity.EntityLabel` in xBIM Essentials.

```cs
var entity = model.Instances[entityLabel];
```

**Comment by divyanatsteel** [comment]
0x800a1391 - JavaScript runtime error: 'IPersistEntity' is undefined
getting this error  currently I am using xbimwebui /viewer3dhtml page under pick we want to highlight picked rebar  and properties of rebar

**Comment by divyanatsteel** [comment]
how to use xbim essentials into the xbim webui/viewer3d.html 
can u please explain thanks

**Comment by divyanatsteel** [comment]
this is from autodesk like this I want to 
![autodesk](https://user-images.githubusercontent.com/55271797/65105218-d3d32580-da06-11e9-8355-56a79a7f6680.PNG)
implement using xbim[(url)

**Comment by martin1cerny** [comment]
xBIM Essentials is a .NET server side library you had to use to get wexBIM. You will need to implement a server-side .NET code to access semantic data from the model and expose it to your application depending on frameworks/technologies you use.

http://docs.xbim.net/examples/basic-model-operations.html

**Comment by divyanatsteel** [comment]
Hello martin ,
let me how to get the all the REINFORCING bars details thought the Column selection currently iam using this code:     var ifc= model.Instances.FirstOrDefault<IIfcProduct>(d => d.EntityLabel == identity);//returns ifcloumn
after that iam trying to collect the inside the reinforcement :var rebar = ifc.ContainedInStructure.SelectMany(rel=>rel.RelatedElements).OfType<IIfcReinforcingBar>();  its retuns all the bars of model .but i want only inside column rebars..
thanks
