### ISSUE TITLE
Problem occur in Deployment on another PC 

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#25]
Hi ,

I am trying to deploy my application on another PC where visual studio 2013 is not installed .I have installed 4.5.1 & 4.5.2 both framework. But still conversion of ifc to wexbim is not done .

**Comment by martin1cerny** [comment]
Hi Amol,

this description is not sufficient. You will need to provide us with more detail. If you don't mind I'll move this issue to the XbimExchange project because it is unrelated to anything in XbimWebUI project. 

Martin

**Comment by martin1cerny** [comment]
This issue was moved to xBimTeam/XbimExchange#2

**Comment by BIMDevelopement** [comment]
Hi Martin ,
No problem.
