### ISSUE TITLE
How to avoid duplicate IDs？

### ISSUE THREAD

**Issue by xujunpro2** [xBimTeam/XbimWebUI#250]
I found in the xNavigationCube:“this.TOP = 1600000;”. Then you use it in “xShaders.cube_vshader” to calculate the color. This way you can get the ID of the entity in “xViewer.prototype._getID”. How do you ensure that the value of 160000 is not occupied by the BIM productID?

**Comment by martin1cerny** [comment]
The latest version in `develop` branch is using internal mapping for product ids to avoid problems with GPU precision for ID retrieval. Because of that, it would only clash if there were more than 1600000 products in the model. I've never seen a model containing that number of products. 

Saying so, I work on a version which uses additional level of isolation between rendered objects which avoids this potential clash completely. This will be published at some point but it is not scheduled yet.

**Comment by xujunpro2** [comment]
thank you for your reply. In fact, I use it to run more than 3,000,000 products now. It works great! Also, I checked the spatial structure file generated by xbim, and more than 3,000,000 products did not contain the ID you defined in the NavigationCube. Is this a coincidence?：）

**Comment by martin1cerny** [comment]
It might be a coincidence. Are you sure you have over 3 millions of products in the model? Or is the highest entity label bigger than 3,000,000? That is quite possible.

**Comment by xujunpro2** [comment]
To be precise, it should be the number of entityLabel(productLabel) generated in the wexbim file exported by xbim. Because the number of entityLabel is not continuous, the actual number of all products must be less than 3,000,000. There are probably more than 200 original ifc files.So, I am curious, how do you avoid the range of 1600000 to 1600025 in the xNavigationCube?

**Comment by martin1cerny** [comment]
The viewer is using 0-based sequential ids for all products and keeps a map between these and entity labels. So, unless there are more than 1600000 products, which is extremely unlikely, there is not a clash.

**Comment by xujunpro2** [comment]
Because the product id does not grow continuously, if the bim model is larger, it is quite possible that the product id exceeds 1.600000 (not the number of products exceeds 1.600000). I have now added a method to record the maximum product id of the model while traversing the product object. In this way, the plugin can continue to grow on a maximum basis, thereby avoiding conflicts between the 3D object id and the product id in the plugin.

**Comment by martin1cerny** [comment]
See my reply above. The viewer is handling this. It is not a problem unless the **number** of products exceeds 1600000. Entity labels are not used internally.
