### ISSUE TITLE
Entity label

### ISSUE THREAD

**Issue by divyanatsteel** [xBimTeam/XbimWebUI#253]
hi,
Generaly we get the id from "pick event "but know I want all the ids in model and status is highlighted  ids I want.
thanks

**Comment by xujunpro2** [comment]
xModelGeometry.productMap contains about all entities

**Comment by everystone** [comment]
So there is no way of extracting a list of entity ids from the wexbim model using javascript?

**Comment by xujunpro2** [comment]
ProductMap has all the information you need! Look at the source code!

**Comment by martin1cerny** [comment]
You can also use [getModelState](https://docs.xbim.net/XbimWebUI/classes/_viewer_.viewer.html#getmodelstate) to get all product ids and related states and styles.
