### ISSUE TITLE
Any Solution to View Cobie file in Xbim Viewer?

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#256]
I want to make xbim viewer to display the Cobie file, so what procedures have to take?

Could you please suggest some solution.

thanks in advance.:)

**Comment by martin1cerny** [comment]
You have to implement COBie viewer. xBIM viewer is designed for IFC, not for COBie.

**Comment by castronelson** [comment]
okay thanks.
May i know what are the procedures have to  do for Cobie viewer

**Comment by castronelson** [comment]
How to View the Cobie file as same like 3D Viewer of IFc file? Any link for reference.

**Comment by castronelson** [comment]
I have developed the IFC file Viewer by using json and wexbim from Ifc file  for displaying image.

At the same How to View Cobie file?
