### ISSUE TITLE
Clip model at different points and plans

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#258]
I can clip at a certain point and plan
Is it possible to clip at more point and plan ? so the model will be clipped at different points

Thanks

**Comment by andyward** [comment]
Currently there are 2 clipping planes available in the viewer. `clippingPlaneA` & `clippingPlaneB`

Typically you can use these to clip top and bottom to section a building, (but you don't have to orient them this way.). There's a vector you use to determine the direction of the clip.

So you can do something like:

``` typescript

const top = 100;
const bottom = 0;

// first 3 params are x,y,z vector defining a plane  The last is the distance from that plane
viewer.setClippingPlaneA([0,0,1, top);  // up
viewer.setClippingPlaneB([0,0,-1, -bottom); // down
```
... and you'll clip between 100 and 0 units.

I guess it would be nice to have more planes (or at least 6), so we could do a clip box.

**Comment by OmarKhairyHosny** [comment]
Hi Andy,

"I guess it would be nice to have more planes (or at least 6), so we could do a clip box."

Yes it would be nice to have a section box

Sorry.... but I haven't found  "clippingPlaneA & clippingPlaneB" 
Can you help me in this ?

Thanks

**Comment by andyward** [comment]
Make sure you're using the _develop_ branch

https://github.com/xBimTeam/XbimWebUI/blob/3997572703400ab2ae9a123702c7d8e557f066f9/Xbim.WeXplorer/Viewer/viewer.ts#L2254
