### ISSUE TITLE
How will create Cobielite json file from cobie file

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#259]
Hai,
I have referenced the Xbim.CobieLite project from Xbim.Exchange
below i mention the codeit was not working
`using (var model = new XbimModel())
            {
                model.CreateFrom(filename, null, null, true);
                var cobieFileName = "semantics.json";
                using (var cobieFile = new FileStream(cobieFileName, FileMode.Create))
                {
                    var helper = new CoBieLiteHelper(model, "UniClass");
                    var facility = helper.GetFacilities().FirstOrDefault();
                    if (facility != null)
                    {
                        using (var writer = new StreamWriter(cobieFile))
                        {
                            CoBieLiteHelper.WriteJson(writer, facility);
                            writer.Close();
                        }
                    }
                }

                model.Close();
            }`

**Comment by andyward** [comment]
Please don't duplicate questions in different repos. It just creates more work and confusion.

Duplicates https://github.com/xBimTeam/XbimCobieExpress/issues/11
Duplicates https://github.com/xBimTeam/XbimExchange/issues/48 <= Will answer here
