### ISSUE TITLE
Unexpected Products in latest myget Geometry causing crashes

### ISSUE THREAD

**Issue by andyward** [xBimTeam/XbimWebUI#26]
@martin1cerny , just a heads up, this may be one for you or it may be one for @CBenghi 

It looks like there's been a change in how we're handling openings in the Geometry Engine (possibly this change: xBimTeam/XbimGeometry@e63ad958e9edfa158834fe50775c7b8bd2bacf64) - which is causing the xbim-viewer[...].js to throw an exception during parsing of the wexbim file.

**Repro**

Using Xbim.Geometry 3.1.3 from Myget/develop, and the latest XbimWebUI (pre-release from myget)

Take any Model with an opening(e.g. OneWallTwoWindows.ifc) and you'll get error on the console at this line:

https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-model-geometry.debug.js#L175

If you use a wexbim generated from the latest **Nuget** Xbim.Geometry it's fine.

I'll see if I can track it back to a particular change but it may be a few days before I can look at it. I put a spot fix in to skip the problem items and you see something like this:

![image](https://cloud.githubusercontent.com/assets/923699/8971341/5c06b2fe-3647-11e5-9210-82d8c5fd9ac8.png)

Left is latest Geometry (Myget 3.1.3). Right is the old Geometry (Nuget 3.0.21). Both are the same source model file and XbimWebUI code. The only difference is the version of Xbim.Geometry used to generate the webxbim. Might be worth speaking to Claudio to see what the intention is with the above change. The newer wexbim is larger so I'm assuming it contains extra records (intentionally, or unintentionally).

Loading the new (and old) xbim files into XbimXplorer renders OK

Sounds like either:

1. WebUI needs to handle the new entries
or
2. The Xbim3DModelContext Serialiser needs to strip them out during wexbim serialisation

**Comment by CBenghi** [comment]
Hi,
I'll look into it this afternoon.
Thanks for the heads up.
Quite strange the file is larger... I've only changed the value of an enum
in xbim to handle voids differently.
Claudio



On 29 Jul 2015, at 23:24, Andy Ward <notifications@github.com> wrote:

@martin1cerny <https://github.com/martin1cerny> , just a heads up, this may
be one for you or it may be one for @CBenghi <https://github.com/CBenghi>

It looks like there's been a change in how we're handling openings in the
Geometry Engine (possibly this change:
e63ad958e9edfa158834fe50775c7b8bd2bacf64) - which is causing the
xbim-viewer[...].js to throw an exception during parsing of the wexbim file.

*Repro*

Using Xbim.Geometry 3.1.3 from Myget/develop, and the latest XbimWebUI
(pre-release from myget)

Take any Model with an opening(e.g. OneWallTwoWindows.ifc) and you'll get
error on the console at this line:

https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-model-geometry.debug.js#L175

If you use a wexbim generated from the latest *Nuget* Xbim.Geometry it's
fine.

I'll see if I can track it back to a particular change but it may be a few
days before I can look at it. I put a spot fix in to skip the problem items
and you see something like this:

[image: image]
<https://cloud.githubusercontent.com/assets/923699/8971341/5c06b2fe-3647-11e5-9210-82d8c5fd9ac8.png>

Left is latest Geometry (Myget 3.1.3). Right is the old Geometry (Nuget
3.0.21). Both are the same source model file and XbimWebUI code. The only
difference is the version of Xbim.Geometry used to generate the webxbim.
Might be worth speaking to Claudio to see what the intention is with the
above change. The newer wexbim is larger so I'm assuming it contains extra
records (intentionally, or unintentionally).

Loading the new (and old) xbim files into XbimXplorer renders OK

Sounds like either:

   1. WebUI needs to handle the new entries or
   2. The Xbim3DModelContext Serialiser needs to strip them out during
   wexbim serialisation

—
Reply to this email directly or view it on GitHub
<https://github.com/xBimTeam/XbimWebUI/issues/26>.

**Comment by andyward** [comment]
@CBenghi Did you get any further with this? Still seeing the issue with latest develop code.

**Comment by martin1cerny** [comment]
@andyward I'm sorry I didn't catch on this before. Thanks for the heads up. But it seems it is a bug in XbimGeometry or XbimIO rather than in WeXplorer. It just indicates that the wexbim file is wrong which is apparently true. I also wonder if @CBenghi got any further.

P.S.: It is interesting that most issues raised on GitHub in XbimWebUI project are related to different parts of xBIM :-)

**Comment by andyward** [comment]
I did a bit a investigation into this. There are actually two issues.

1. The WexBIM contains shape definitions that reference products not listed in the products list. Notably IfcOpeningElement geometry is coming though, but the elements are not.
2. The WexBIM file contains duplicate geometry where there has been cutting. E.g. A wall will have geometry for before and after any opening. 

So after resolving the first issue you get:
![image](https://cloud.githubusercontent.com/assets/923699/9544017/48e439c2-4d75-11e5-8009-bf238c321d1d.png)
not
![image](https://cloud.githubusercontent.com/assets/923699/9544032/5af9e936-4d75-11e5-9c73-3515a5a7963c.png)

Using OneWallTwoWindows.ifc as a test case I added some diagnostics using Geometry 3.0.23 and the latest Develop.

Geometry 3.023:
![image](https://cloud.githubusercontent.com/assets/923699/9544171/56300d4e-4d76-11e5-9cf5-10f74facd276.png)

Latest Geometry (develop)
![image](https://cloud.githubusercontent.com/assets/923699/9544240/caefd86c-4d76-11e5-84b4-db324768f0da.png)

We have the same 3 products (1 Wall and 2 Windows), but three extra shapes (# 5-7). Shape 6 is the uncut wall, while 5&7 are the openings with no product reference.

Hope that helps you @CBenghi 

Andy

**Comment by CBenghi** [comment]
Hi Andy,
I think I have a solution to post, but I'm currently travelling overseas,
I'll post it as soon as I get a sound connection for you to test.
I'm not really strong on the web viewer, to be sure it's all right.
Also I think the wexbim format should be enriched. At the moment it cannot
differentiate between model shape types.
Claudio



On 28 Aug 2015, at 13:26, Andy Ward <notifications@github.com> wrote:

I did a bit a investigation into this. There are actually two issues.

   1. The WexBIM contains shape definitions that reference products not
   listed in the products list. Notably IfcOpeningElement geometry is coming
   though, but the elements are not.
   2. The WexBIM file contains duplicate geometry where there has been
   cutting. E.g. A wall will have geometry for before and after any opening.

So after resolving the first issue you get:
[image: image]
<https://cloud.githubusercontent.com/assets/923699/9544017/48e439c2-4d75-11e5-8009-bf238c321d1d.png>
not
[image: image]
<https://cloud.githubusercontent.com/assets/923699/9544032/5af9e936-4d75-11e5-9c73-3515a5a7963c.png>

Using OneWallTwoWindows.ifc as a test case I added some diagnostics using
Geometry 3.0.23 and the latest Develop.

Geometry 3.023:
[image: image]
<https://cloud.githubusercontent.com/assets/923699/9544171/56300d4e-4d76-11e5-9cf5-10f74facd276.png>

Latest Geometry (develop)
[image: image]
<https://cloud.githubusercontent.com/assets/923699/9544240/caefd86c-4d76-11e5-84b4-db324768f0da.png>

We have the same 3 products (1 Wall and 2 Windows), but three extra shapes
(# 5-7). Shape 6 is the uncut wall, while 5&7 are the openings with no
product reference.

Hope that helps you @CBenghi <https://github.com/CBenghi>

Andy

—
Reply to this email directly or view it on GitHub
<https://github.com/xBimTeam/XbimWebUI/issues/26#issuecomment-135728974>.

**Comment by CBenghi** [comment]
Hi Andy,
I've posted a couple of changes to Geometry that should fix this problem, but I don't know enough of the webviewer to understand how it ever worked before them...
Can you please double check?
Thanks,
Claudio

**Comment by dazmahal** [comment]
Hi Claudio
Has the Geometry fix been published to Nuget / MyGet
If so I can test this fix

Thanks
Darren

**Comment by CBenghi** [comment]
Hi Darren,
yes it's been uploaded under the develop branch.
You will find the nuget package in the myget develop repo.
https://www.myget.org/F/xbim-develop/api/v2
Best,
Claudio

**Comment by andyward** [comment]
@CBenghi Nice work! Looks to have fixed the issue :+1: 
![image](https://cloud.githubusercontent.com/assets/923699/9563577/ddc90788-4e7f-11e5-8dc0-b05996a4c9aa.png)

Note for anyone else - I used 3.1.10-V00006

I guess we need to discuss if we ever want these geometries in a wexbim at some point. My gut feel is to wait until we find a need since we want to keep the wexbim payload a light as possible.

**Comment by andyward** [comment]
Closing
