### ISSUE TITLE
Chrome warning about non-passive eventlisteners

### ISSUE THREAD

**Issue by Truning** [xBimTeam/XbimWebUI#260]
When using the xbim-viewer in a chrome browser I get the following warnings:
![image](https://user-images.githubusercontent.com/42533827/68116988-76cef880-fefc-11e9-853e-2ca191e36f43.png)

Here the link that the warnings refer to:
https://www.chromestatus.com/feature/5745543795965952

Is this a known problem? I have not found any other issue refering to this.
Or does the viewer **require** these eventlisteners to be non-passive?
Maybe I misunderstand something, but I am guessing that setting them to passive could increase the performance.

**Comment by martin1cerny** [comment]
Very interesting and new to me. But we use it in scenarios where we do consistently cancel wheel and touch events because they are captured by the canvas to drive 3D interaction. So, after reading that link I have to say that what we do is correct and doesn't need to be changed.

**Comment by Truning** [comment]
Alright! Thank you for clarifying!
