### ISSUE TITLE
Is there any way to do multi selection ? 

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#262]
Is it possible to select multi objects by click on canvas and drag ?

**Comment by andyward** [comment]
Did you sort this? The answer is yes, because selection is just a _state_ of an element. You'd need to handle this on the pick event

**Comment by OmarKhairyHosny** [comment]
No I didn't, I was trying to select multi elements by selection box as below image:
![2020-02-19_14-13-52](https://user-images.githubusercontent.com/41702983/74833462-2dc37880-5322-11ea-9915-0c7c4906d2b0.png)

Is it possible ?
