### ISSUE TITLE
How to Select object in XBimViewer

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#263]
Hai,
I want to pass the object ID as a parameter to the viewer page using QueryString. 
Now the object should  be selected and zoomed in the viewer. 
Currently this happens only when I double click the object in the left tree menu. The same I want to perform using QueryString value.
Can anyone help me with this?
Thanks in advance!.

**Comment by martin1cerny** [comment]
You need to use javascript.

**Comment by castronelson** [comment]
yes.
Please help me if there is any delegate to perform this function

**Comment by martin1cerny** [comment]
Read the [documentation](http://docs.xbim.net/XbimWebUI/) please.

**Comment by castronelson** [comment]
Thank you. I got it

**Comment by martin1cerny** [comment]
Yes it is. The `id` you get from all interaction events is `EntityLabel` in xBIM model. So, you need to access IFC model on the server, find the entity, send any data you need and present it to your user.

```cs
var entity = model.Instances[id];
```

**Comment by krosoftware** [comment]
Hello
I try to find (in the documentation) how to select specific object(s) but can not find nothing.
For example, if I know IFC GUID, how to select it in the viewer?
Thank you.
