### ISSUE TITLE
How to Zoom objects exactly?

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#265]
Hi,
I have some issues related to zooming objects for some Assets like door closer.

When loading some door closer it zooming backside of the door not exactly the object.I have tried 
setCameraPosition() with coordinate its not works.
Any solution ?
thank you.

**Comment by martin1cerny** [comment]
If the closer is not an independent product but geometrical part of the door it can't be distinguished.

**Comment by castronelson** [comment]
thank you.

**Comment by castronelson** [comment]
Hi,
Sorry, I am rephrasing my question.

In the tree view if I click on the object then it is zoomed in the 3D diagram. Similarly can I zoom any object by sending parameters? is there any such method?
Please help.

With Regards,
Castro Nelson

**Comment by andyward** [comment]
You can zoom by the entityId/label using `zoomTo()`: https://github.com/xBimTeam/XbimWebUI/blob/3997572703400ab2ae9a123702c7d8e557f066f9/Xbim.WeXplorer/Viewer/viewer.ts#L1640
