### ISSUE TITLE
How to resolve 'WebGL support is unsufficient' error

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimWebUI#267]
Hi,
We have integrated BIM Viewer in our web application. 
When we open the BIM Viewer from ASPX page (Button click) - The BIM Viewer has opened without any issues in chrome browser.
But if we open the same BIM Viewer in Internet Explorer - we will receive the **WebGL support is unsufficient** error.

Could you help us how to resolve this issue.
Thank you in advance.

**Comment by martin1cerny** [comment]
If the web browser in question doesn't have sufficient support for technologies we are using than there is very little we can do for you.
