### ISSUE TITLE
is it possible to scale selected element in the viewer ? 

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#269]
Hi,
I want in the "pick" event to scale the selected object, is it possible?

Thanks,

**Comment by martin1cerny** [comment]
Yes it is, use the `zoomTo()` function.

**Comment by OmarKhairyHosny** [comment]
@martin1cerny Hi martin,

Thanks for your reply

sorry.. but I mean to scale the element itself with scaling factor not to zoom camera to it
is it possible ?

**Comment by martin1cerny** [comment]
OK, that is not possible.

**Comment by OmarKhairyHosny** [comment]
Thanks :(
