### ISSUE TITLE
How to run XbimExchanger common line to covert IFC to wexbim.

### ISSUE THREAD

**Issue by zhengcongyin** [xBimTeam/XbimWebUI#27]
Hi,
I just encountered the problem that I have no idea how to run XbimExchanger common line to covert IFC to wexbim by downloaded code. Does anyone explain the process to me? Thanks in advanced.

Best,

**Comment by andyward** [comment]
There's a console app in Xbim Exchange but I don't think it's deployed in the Nuget package. You can see what it does to generate the xbim and wexbim files at 

https://github.com/xBimTeam/XbimExchange/blob/master/Xbim.Exchange/Program.cs

You may not need to do all the processing for DPoW or XLSx formats, so could stop at line 49. If you want to see a simpler implementation look at 

In terms of the process it's essentially doing 3 things

1. Create/Parse the model using `XbimModel.CreateFrom(ifcFile)` to create an .xbim file
2. Generate the Geometry for a chosen type using `Xbim3DModelContext.CreateContext( XbimGeometryType.PolyhedronBinary)` - which supplements the .xbim file with geometry
3. Export the geometry to a .wexbim file with `Xbim3DModelContext.Write(stream)`

The wexbim file is essentially a web optimised version of the geometry, while the xbim file contains all the data from the IFC optimised for querying and data processing.

I've got a little demo of this and the WebUI in action at https://github.com/andyward/XbimWebDemo

**Comment by dhm** [comment]
Andy,
I added the extra NuGet source for the solution but when I try to build it fails to find version 3.0.24 of Xbim.Geometry. Can you please advise?

**Comment by andyward** [comment]
You probably need to configure the xbim MyGet feeds in your Nuget sources. E.g.

![image](https://cloud.githubusercontent.com/assets/923699/9729991/750f8bb6-560b-11e5-9024-a8537d411bcf.png)

Also make sure you've got the latest source as I can't see anywhere in XbimExchange referencing that version of Geometry.

One final suggestion if you're struggling - there's another repo with a cut down Converter for IFC-xBim you could use: https://github.com/xBimTeam/XbimUtilities See the XbimConvert project

**Comment by dhm** [comment]
thanks Andy - I used the XbimUtilities to create wexbim files from my original ifcs and now have a viewer working to visualise those files.
