### ISSUE TITLE
I need to add more lights to the viewer or make it more brightness, any help?

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#270]
#### Minimal code (or steps) to reproduce the issue:
```js
var viewer = new Viewer(canvas);
(...)
```

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*

**Comment by thyss2** [comment]
https://github.com/xBimTeam/XbimWebUI/blob/3c69be256b094a7b53779132cd4d32702980990e/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L97-L106

Changing the last value of those variables will adjust the brightness of those lights. The higher the value the brighter they will be.

**Comment by martin1cerny** [comment]
If you want to add more lights, you will then need to make changes in the shader as well.

**Comment by OmarKhairyHosny** [comment]
> https://github.com/xBimTeam/XbimWebUI/blob/3c69be256b094a7b53779132cd4d32702980990e/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L97-L106
> 
> Changing the last value of those variables will adjust the brightness of those lights. The higher the value the brighter they will be.

Hi @thyss2 

Thanks for your reply

this doesn't work for me
