### ISSUE TITLE
can we change the color of spaces in xbim viewer

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#271]
Hi,
I want to set colors in xbim viewer for space types when clicking from tree.
Now the actual source is describe to use xstate Enumeration to highlight area.But I am expecting different colors to spaces
And For Asset , asset types its working fine using setStyle property.
Could you understand?
Please help me asap

**Comment by martin1cerny** [comment]
http://docs.xbim.net/XbimWebUI/tutorial-5_Colourful_building.html

**Comment by JosefUIBK** [comment]
Is there an answer. Having the same problem.

Thx

**Comment by martin1cerny** [comment]
Updated the link to the current location.
https://docs.xbim.net/examples/colourful-building.html
