### ISSUE TITLE
How to know which model the selected element belongs to?

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#273]
if I load more than model, the selected or picked element id can be exist in another model
so when I highlight the selected element another element also highlight 

is there any way to know which model I have selected ? 

Another issue: pan and zoom speed is too high is there any way to slow them or make that more smoothly ?

**Comment by andyward** [comment]
Like this: 

https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Examples/TsModulesExample/index.ts#L59

On the callback args, `id` is the element label. `model` is the ordinal of the model

(Make sure you're using the latest develop code)

**Comment by andyward** [comment]
In terms of sensitivity, the code you need is all in https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/viewer.ts

**Comment by OmarKhairyHosny** [comment]
@andyward Thanks for your response. are all in develop branch ?

**Comment by pml1711** [comment]
Hi there, I cant access these links anymore. Are they published somewhere else?
Thanks.

https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/viewer.ts
https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Examples/TsModulesExample/index.ts#L59

**Comment by martin1cerny** [comment]
Yes, we use another documentation generator, so the structure is different now:
https://docs.xbim.net/XbimWebUI/classes/_viewer_.viewer.html
https://docs.xbim.net/examples/hello-building.html (and other WebUI examples from the main menu)
