### ISSUE TITLE
Can't convert to wexBIM

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#274]
I am trying to do wexbim example "https://docs.xbim.net/examples/creating-wexbim-file.html"
by creating console app and install the latest version of libraries from nuget 

after running show the error below 

![Capture](https://user-images.githubusercontent.com/41702983/73344081-61166880-428a-11ea-83a1-973024ab4822.PNG)

**Comment by martin1cerny** [comment]
Can you share the file?

**Comment by OmarKhairyHosny** [comment]
Hi Martin,
Thanks for your response.

kindly find the link below:
https://we.tl/t-mImDDeChqV

![Capture2](https://user-images.githubusercontent.com/41702983/73345817-6aed9b00-428d-11ea-9d27-57fee722de96.PNG)

**Comment by OmarKhairyHosny** [comment]
Any Help with this one, this problem has happen when I am trying to generate wexbim file with version 5 and work fine with 4

**Comment by andyward** [comment]
Screenshots in this kind of case aren't that useful. That's basically the Xbim Hello World - it's not a code issue - it'll be environmental of something with your project / dependencies.

Here's basically the same code in a repo I created: https://github.com/andyward/WebUI-274

Try pulling it, and run it it. If it works it's a problem in your project. Likely candidates:

1. Project references / nuget versions. What nuget versions of XBIM are you using?
1. 32/64 bit issues. Are you running a 32 bit or 64 bit process?
1. Target framework issues. What version of net framework are you targeting? Are you using netcore?

If my repo **doesn't** work, you've an environmental issue on your PC. In which case:

* Check what version of Visual Studio you've got. Make sure it's updated
* Check what Windows SDKs are installed
* Check the versions of .net framework
* Share your version # of Windows
* Head over to https://www.google.com/search?q=managed+debugging+assistant+%27fatalexecutionengineerror%27+site:stackoverflow.com

**Comment by OmarKhairyHosny** [comment]
@andyward Thanks for your Reply 

I will give it a shot and back to you again, Thanks.

**Comment by OmarKhairyHosny** [comment]
@andyward 
the code in the repo work fine but it creates an empty wexbim file as "context.CreateContext()" is called 
after calling this function the same error appears
Kindly find the following:
 

- I have update visual studio (my version is 2017)

- Windows SDKs (7,8,8.1,10)

- I am using 4.7.2 for .net framework

- Windows 7 ultimate service pack 1 x64, windows 10 ultimate x64

**Comment by martin1cerny** [comment]
When you say *empty wexbim file*, do you mean it has 0 bytes?

**Comment by OmarKhairyHosny** [comment]
Hi martin,
@martin1cerny it is 1 KB
![2020-02-06_14-12-24](https://user-images.githubusercontent.com/41702983/73936134-d1586600-48ea-11ea-948b-ad762b8ee81c.png)

**Comment by martin1cerny** [comment]
So, why do you think it is empty?

**Comment by martin1cerny** [comment]
I just tried and the result for me has 1.4kB and looks like this in our viewer:
![image](https://user-images.githubusercontent.com/773078/73939943-ca315800-48ea-11ea-88eb-de7f94488a71.png)
[4walls1floorSite_wexbim.zip](https://github.com/xBimTeam/XbimWebUI/files/4165235/4walls1floorSite_wexbim.zip)

**Comment by OmarKhairyHosny** [comment]
@martin1cerny I am using the code that @andyward shared it with me to create wexbim file and this code generate an empty wexbim because of it is missing "context.CreateContext()" that is what I think.

So, I don't actually know what is the problem this error still appears when using nuget version 5.1.288

![73344081-61166880-428a-11ea-83a1-973024ab4822](https://user-images.githubusercontent.com/41702983/73941235-8bed6600-48f5-11ea-985c-d24fc73af252.png)

**Comment by OmarKhairyHosny** [comment]
@martin1cerny  @andyward 
any help with this issue #273 also ? 
I appreciate your time.

**Comment by andyward** [comment]
Apologies I missed the important line to Create context as you spotted. Can you try my code again now and report back?

**Comment by OmarKhairyHosny** [comment]
@andyward the same error 
![2020-02-06_16-27-56](https://user-images.githubusercontent.com/41702983/73945888-b17e6d80-48fd-11ea-8a6d-baab5f1786dd.png)

**Comment by andyward** [comment]
So it's definitely something up with your machine. All I can really suggest is to see what they're saying on Stackoverflow https://www.google.com/search?q=managed+debugging+assistant+%27fatalexecutionengineerror%27+site:stackoverflow.com

Also I'd recommend:

1. Go back and test the basics. Can you debug **any** .net apps on this machine (I've never seen this .net error before but it looks like catastrophic failure in the .net CLR.)
1. Does the code work on another machine you have access to?
1. Can you identity the point in the application that triggers this failure.

**Comment by OmarKhairyHosny** [comment]
@andyward 

- Yes all apps work fine 

- I have tried on other machines all give the same error

- It fails at "context.CreateContext()"

**Comment by andyward** [comment]
Are they all Windows 7 machines? if so, I'd be suspecting you're missing the expected Windows 10 runtime.

Have you tried any of the recommendations from SO?

Have you got a stack trace? Anything in the event log?

**Comment by OmarKhairyHosny** [comment]
@andyward  I didn't found any solution for this so, I will back to the older version 4.011 it work fine with me. Anyway
Thanks for time and effort

**Comment by OmarKhairyHosny** [comment]
@andyward If you have a time can you have a look to this issue also #273 ? Thank you.

**Comment by andyward** [comment]
I think you're hitting this issue. https://github.com/xBimTeam/XbimGeometry/issues/154

The latest Geometry v5+ engine doesn't support Win7
