### ISSUE TITLE
file size and performance

### ISSUE THREAD

**Issue by goalbased** [xBimTeam/XbimWebUI#278]
I follow the [demo](http://docs.xbim.net/XbimWebUI/) and download the [bundle](http://docs.xbim.net/XbimWebUI/scripts/xbim-viewer.debug.bundle.js) here  (because I can't find where to download it), my original ifc file is about to 51 MB and after convert it(by .NET sample) to .wexbim format is about to 6 MB, and the demo one is 300KB. Every function is work smoothly on demo file but very slowly on my file, it's take 1.5 seconds to complete Turn Left function. 

Just want to know anything wrong in my testing or is because my file is too big?
My ifc file is from [here](http://openifcmodel.cs.auckland.ac.nz/Model/Details/335)

**Comment by martin1cerny** [comment]
A new version of the viewer has been published with many improvements. It is available as an [npm package](https://www.npmjs.com/package/@xbim/viewer) now. Can you try it? It has many improvements, but is still hardware dependent as any other WebGL component.
