### ISSUE TITLE
Rendering issue when moving the model far from the origin

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#279]
I have transferred the model from (0,0) to (350000, 3000000) according to the actual location of certain building and the geometry got messed up as the photos show. I don't know what is wrong and I have done many trials with the model and the problem gets repeated when the model is in a very far location from the origin.

Model at origin : 
![2](https://user-images.githubusercontent.com/41702983/74606587-696c0180-50da-11ea-84cd-94a48cb4efee.png)

Model at the far location:
![1](https://user-images.githubusercontent.com/41702983/74606603-7b4da480-50da-11ea-94d2-787b4ede8eec.png)

**Comment by CBenghi** [comment]
This is a common issue due to math rounding errors of applying transform matrices on single precision numbers. It is advised that you avoid doing this.

If you are doing this to federate models have a look at what we do in xplorer, there's a class to center the first model on the center of coordinates of the viewer and then adapt the others accordingly, without moving much away from 0,0,0.

I hope this helps.

**Comment by OmarKhairyHosny** [comment]
@CBenghi Thanks so much for your reply 
To be more clear, I have a model in "Revit" and I am trying to translate the model of building to actual coordinates in real world, when the model at origin and exported IFC file then converted to wexbim and view this file all work fine but after translation model got messed up.

I am really appreciate you help. Thanks.

**Comment by OmarKhairyHosny** [comment]
Any Help with this issue?

**Comment by CBenghi** [comment]
Hello,
I'm not sure I understand your question.
Have you tried changing the adjustwcs option in the createContext function?

**Comment by OmarKhairyHosny** [comment]
Hi @CBenghi,
I mean if the model is located at origin or any point near from it and then exported to IFC format and view this file everything work fine but if I locate the model at  (350000, 3000000) and do the same step model is messed in viewer as shown below:

Model at origin ( the desired view for model);
![2](https://user-images.githubusercontent.com/41702983/74720408-6c800280-523e-11ea-87f7-16c26ae290d9.png)

Model at (350000, 3000000) (it is messed):
![1](https://user-images.githubusercontent.com/41702983/74720413-6ee25c80-523e-11ea-90b5-37bb2fa2af87.png)

I have read #240 and https://github.com/xBimTeam/XbimGeometry/issues/213 which are related issues but they try solving the problem by translate the model.

**Comment by CBenghi** [comment]
Have you tried changing the adjustwcs option in the createContext function?

**Comment by OmarKhairyHosny** [comment]
@CBenghi  I appreciate your response.

Yes I have tried to do that but not working for me.

**Comment by martin1cerny** [comment]
When you say you have moved the model. Have you physically moved it to remote place in the authoring SW, or did you set the local WCS origin to large coordinates? In other words: Does your IFC file contain large coordinates, or is there large displacement stored on the level of IfcBuilding or IfcSite in the placement hierarchy? Is your model using placement hierarchy at all?

**Comment by OmarKhairyHosny** [comment]
I have physically moved it to remote place and my IFC file contains large coordinates

**Comment by martin1cerny** [comment]
That is generally not the best practise. If your SW allows to define real world coordinates for the project origin it is best to do it that way. It is usually than exported to IFC this way and allows for easier handling of large coordinates.

**Comment by OmarKhairyHosny** [comment]
What do you mean with "SW"? Is there any way to solve this?

**Comment by martin1cerny** [comment]
Sure, there is always a way. By SW I mean Revit, Bentley, ArchiCAD, Tekla, DDS-CAD and other SW for model authoring. What did you use to move the model?

**Comment by OmarKhairyHosny** [comment]
I hope so, I use Revit

**Comment by OmarKhairyHosny** [comment]
Any help with this issue ?

**Comment by martin1cerny** [comment]
You can use [Project Base Point](https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/Revit-Model/files/GUID-68611F67-ED48-4659-9C3B-59C5024CE5F2-htm.html) in Revit to set it's real position and orientation. This will be reflected in the exported IFC file.
