### ISSUE TITLE
Can't generate wexBIM file with latest version of xbim

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#280]
I am trying to generate wexbim file from IFC file but the error below is shown
![Capture](https://user-images.githubusercontent.com/41702983/74825393-84c15180-5312-11ea-9278-02aea7f717a1.JPG)

this is the IFC file
[Demo.zip](https://github.com/xBimTeam/XbimWebUI/files/4224447/Demo.zip)

**Comment by martin1cerny** [comment]
I have just checked and while it fails with older versions of xBIM, the latest development version can process it OK.
![image](https://user-images.githubusercontent.com/773078/74916326-f1495880-53c5-11ea-9df9-77c7f0809b7a.png)

**Comment by OmarKhairyHosny** [comment]
I have installed latest version on nuget. What should I try? can you share your code?

**Comment by OmarKhairyHosny** [comment]
@martin1cerny Hi Martin, Can you share the wexBIM file ? Thanks.

**Comment by OmarKhairyHosny** [comment]
@martin1cerny any help with this :) ?

**Comment by martin1cerny** [comment]
If you add `nuget.config` file like [this](https://github.com/xBimTeam/XbimGeometry/blob/master/nuget.config) to your solution you will see our latest builds from both `master` and `develop` branch.

**Comment by OmarKhairyHosny** [comment]
Okay I will try, can you share the wexbim file?

**Comment by martin1cerny** [comment]
[Demo.zip](https://github.com/xBimTeam/XbimWebUI/files/4248966/Demo.zip)

**Comment by save2004** [comment]
I have the same problem:
- if I run my project (ASP.NET MVC) in in visual studio in localhost, I can generate .xBIM file and then .wexBim without problems;
- but when this process takes place on the corporate server where the project resides, the .wexBIM file is no longer generated and I receive a generic error 500


`private BimModel BuildModel(string modelName, bool refresh = false)
        {
            var ifcModel = Path.Combine(DataDir, modelName);

            string geometryFileName = Path.ChangeExtension(ifcModel, ".wexBIM");
            string xbimFileName = Path.ChangeExtension(ifcModel, ".xbim");

            if (refresh)
            {
                Clean(xbimFileName, geometryFileName);
            }

            var modelToOpen = Cached(xbimFileName) ? xbimFileName : ifcModel;
            //Parse IFC to xbim
            using (var model = IfcStore.Open(modelToOpen))
            {
                if (!Cached(xbimFileName))
                {
                    model.SaveAs(xbimFileName, StorageType.Xbim);
                }

                // Generate Geometry
                BuildGeometry(model, geometryFileName);
            }

            return new BimModel(modelName, Path.GetFileName(geometryFileName));
        }


private void BuildGeometry(Xbim.Common.IModel model, string geometryFileName)
        {
            if (Cached(geometryFileName))
            {
                return;
            }
            var m3DModelContext = new Xbim3DModelContext(model);
            m3DModelContext.CreateContext();

            ExportGeometryData(geometryFileName, model);
        }

        private static void ExportGeometryData(string geometryFileName, Xbim.Common.IModel model)
        {
            try
            {
                using (var wexBimFileStream = new FileStream(geometryFileName, FileMode.Create, FileAccess.Write))
                {
                    using (var writer = new BinaryWriter(wexBimFileStream))
                    {
                        model.SaveAsWexBim(writer);

                        writer.Close();                        
                    }
                    wexBimFileStream.Close();
                }
            }
            catch (Exception ex)
            {
                string messaggio = ex.Message.ToString();

            }
        }



`

**Comment by andyward** [comment]
This is a common problem almost always caused by one of the following:

1. Missing _Xbim.Geometry.EngineXX.dll_ native binaries (where XX is one of 86 or 64 depending on 32/64 bit process)
2. Deploying both 32 but and 64 bit under IIS (but I would expect it to crash at app start with a BadImageFormatException)
3. Not having the VC runtime deployed

You'll likely be seeing a 500 error as you have no catch block around  BuildGeometry and Issues 1 & 3 above will cause `m3DModelContext.CreateContext()` to fail.

See these issues for background: 
https://github.com/xBimTeam/XbimGeometry/search?q=IIS&type=Issues
