### ISSUE TITLE
Coordinate System/IFC4

### ISSUE THREAD

**Issue by WENTBY** [xBimTeam/XbimWebUI#282]
Hi
Is there any example about defining coordinates system like WGS_1984 through XBim?

**Comment by martin1cerny** [comment]
No, there is no such an example. You should study IFC schema for this. As a hint: there are several ways to do this depending on your needs and depending on the SW you target for exchange. [IfcSite](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcsite.htm) has reference latitude and longitude in WGS84. But IFC4 has whole new data infrastructure supporting geographical reference systems through [IfcMapConversion](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcmapconversion.htm). Are you targeting any specific SW for data exchange?

**Comment by WENTBY** [comment]
Yes, I am doing an experiment for data exchange with the SW ArcGIS.Thank you very much for your reply, I think I have solved this problem after studying IFC schema, and thanks again for XBim team。
