### ISSUE TITLE
Passing wexbim file data from c# to javascript

### ISSUE THREAD

**Issue by TasigurIshtar** [xBimTeam/XbimWebUI#283]
Hello XBIM,
Firstly, I am using MVC with your xbimwebui 0.1.41 via nuget.
Then I tried your simple example from here http://docs.xbim.net/XbimWebUI/ 
That was ok.
When I looked more closely, it shows the method viewer.load('data/SampleHouse.wexbim'); accepts also BLOB, File or bytearray.

The goal is to load wexbim file inside of controller and then pass it into view (= into viewer.load method).

Unfortunately, I was not successful at this point.

I know this might be beginner question but still.  May I ask you for some simple code example how to achieve this kind of behavior? 

Thanks for your time.

**Comment by martin1cerny** [comment]
I'm sorry, but this is very specific to your application. You can pass is through your application stack as any other binary resource.

**Comment by GeorgDangl** [comment]
Here’s an example doing just that in Angular: https://github.com/GeorgDangl/xbim-meets-angular/blob/master/src/xBimMeetsAngular/ClientApp/app/components/custom-file/custom-file.component.ts
