### ISSUE TITLE
How to load CobieLite json in XBrowser

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimWebUI#284]
Hi,
How to generate the CobieLite json from IFC file?

How to load the CobieLite json in the XBrowser?

Kindly provide the working samples (web application samples) for the above requirrments.

Thank you in advance.

**Comment by andyward** [comment]
Take a look at **Xbim.Exchanger** at https://github.com/xBimTeam/XbimExchange

In particular, you can use https://github.com/xBimTeam/XbimExchange/blob/master/Xbim.Exchanger/IfcToCOBieLiteUK/IfcToCOBieLiteUkExchanger.cs

Loading json into the browser is just a matter of something like:

```javascript

var browser = new xBrowser();
browser.load('https://somehost/path-to-your.json');
```

See a fuller example at https://github.com/xBimTeam/XbimWebUI/blob/3997572703400ab2ae9a123702c7d8e557f066f9/Xbim.WeXplorer/Examples/BrowserExample/browser.js#L135

**Comment by martin1cerny** [comment]
New version of the viewer has been published which is available as a [npm package](https://www.npmjs.com/package/@xbim/viewer). For the reasons described [here](https://github.com/xBimTeam/XbimWebUI/issues/288#issuecomment-645410195) it no longer contains xBrowser.
