### ISSUE TITLE
IFC Conversion file loading issue

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimWebUI#285]
Hi,
We have converted the IFC file to JSON  and WEXBIM. The IFC file size is 500 MB.
It will take more than 5 minutes to convert from IFC file to JSON and WEXBIM. But the conversion was successful.

**But in XBIM Viewer, the file is not getting loaded. Please help to resolve this issue.**

Note: If we convert the 100 MB file to WEXBIM and JSON, it will be displayed properly in XBIM Viewer.

Thank you in advance.

**Comment by martin1cerny** [comment]
Using one big JSON file exported from IFC is not a scalable solution. JSON is an expanded text with high level of redundancy of tokens and it is not suited for this purpose. You should build a web service to serve semantic data from IFC model. You can use xBIM to do that.

**Comment by Nandhakumar2187** [comment]
But we have seen in browser.js file, the 3D diagram will be displayed using JSON and WEXBIM files. 
So these two are the supported files.
Am i right?

**Comment by martin1cerny** [comment]
While we continue to develop wexBIM viewer for 3D presentation on web, we will drop support for JSON viewer of semantic data once we publish next version. You can use our 3D  viewer to present 3D and use xBIM to read IFC file and serve any data you like from it through web service of your design and choice.

**Comment by Nandhakumar2187** [comment]
Thank you Martin.
Do we have sample source code on this?
Or it will be covered in XbimWebUI?

**Comment by martin1cerny** [comment]
No, we currently don't have such a sample code but we have hundreds of users doing this. Just think of IFC as an object database and xBIM as a database reader. In the simplest setup: Create a web service, open the database, read data you want, transform it into serializable form and send it to your web application.

**Comment by Nandhakumar2187** [comment]
ok. As you suggested we can use 3D Viewer to display the 3D image.
Is it possible to zoom the selected asset in 3D Viewer?

**Comment by martin1cerny** [comment]
Yes it is.

**Comment by Nandhakumar2187** [comment]
Ok. We checked the Viewer3D.html file to load the large size files. But in web application it will take long time to load.

**Comment by andyward** [comment]
A 500MB model is pretty **big**. If you take a naive approach to this it won't perform well:

* the user will have to download 100s MB of wexbim & JSON data. That could take minutes depending on bandwidth
* the xBrowser component will need to handle 100's of MB of JSON in memory. Browser's JavaScript engines are quick, but still limited by the fundamentals of algorithms and Big O etc
* the GPU will need to handle some very large scenes. Depending on hardware and what else is running, and you may exhaust the GPU RAM.

This would be the case regardless of BIM toolkit I'd suggest.

If you're regularly dealing with models this size over the web you will need to be smart in how you architect the application for your use case. Do you need to load all the data and all the geometry into the browser? As an analogy, Google Maps would never work if it had to load the maps and GIS data for the entire globe would it? Have you tried loading a 500MB word document into Office 365 (hint: it won't be pretty!)

The server-side infrastructure required for this kind of system is not something we're looking to address with this toolkit. We have some commercial technology that addresses this problem space.

**Comment by Nandhakumar2187** [comment]
Hi Andyward,
Thank you for your information.
Kindly let us know the commercial versions of xBIM Viewer in order to solve this problem.

Thank you in advance.

**Comment by andyward** [comment]
You can drop me an email, or follow up on some of the details at https://docs.xbim.net/cloud.html
