### ISSUE TITLE
3Dviewer not displaying the image to large IFC file

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#286]
Hi 
I have Converted IFC file (size 512mb) to Json and Wexbim.
It takes very more to display in 3DViewer Page, while other files are displaying well
how to resolve this.

Note: files are converted successfully from IFC to Json and WEXBIM,

**Comment by martin1cerny** [comment]
You will need to be a lot more specific about your issue.

**Comment by castronelson** [comment]
yes,
Large Wexbim file is not loaded in Xbim Viewer
But Small size file will be loaded correctly in xbim viewer

**Comment by martin1cerny** [comment]
What does your browser say? Is there any error log in console? Does it crash the browser completely? Does it crash GPU completely? Does it crash your computer completely? Are you loading just wexBIM file? Or are you also loading some other data in the context? Did you try CPU, GPU and RAM profiling? How big is the wexBIM file? What have you tried to solve the problem?

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It has `loadAsync()` function which offloads part of the model loading and parsing to a web worker. Also, new TS compiler seems to produce more efficient code.
