### ISSUE TITLE
Failed to fetch binary data from server. Server code: 0, CORS policy issue

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimWebUI#287]
#### Expected behavior:
no errors in web page

#### Actual behavior or exception details:
errors, see below

#### Version of the xBIM Viewer:
up to date with master in this repo

#### Minimal code (or steps) to reproduce the issue:
I simply openened viewer3d in a browser

Hello all,
I cannot find a solution to this, I have this error (not 404 !):
Failed to fetch binary data from server. Server code: 0. This might be due to CORS policy of your browser if you run this as a local file.

This happens also with both Edge, Firefox and Chrome browsers for the file "viewer3D.html" in the repository.
Can you help on this? This error is new to me, it never happened before today.

![errorXbimWebUI](https://user-images.githubusercontent.com/10365055/79890821-550cf380-8400-11ea-910c-8320dcaa43b1.PNG)

**Comment by GeorgDangl** [comment]
This is very likely not an issue with xBim but with how browsers behave when accessing resources. You're opening a local file, which then tries to retrieve the geometry, but this gets blocked.

You could try to run a simple, local webserver to simulate a proper website, e.g. with something like this: https://www.npmjs.com/package/http-server

**Comment by johnnyontheweb** [comment]
Thanks, from a web server it works. 
Since this issue is a noverlty in windows, can you suggest how to change such blocking settings? I have no idea where to look, since it's common on all browsers.

**Comment by martin1cerny** [comment]
Imagine you open an HTML page locally and it will serve well known files from your PC to anywhere on the internet. That is most possibly not what you want. You should keep browser settings as they are and use a web server for development.
