### ISSUE TITLE
Can I get IFC properties from wexbim files?

### ISSUE THREAD

**Issue by goswinr** [xBimTeam/XbimWebUI#289]
Can I get properties like in this screenshot from wexbim files using XbimWebUI ? 
Would [this](http://docs.xbim.net/XbimWebUI/tutorial-6_Building_described.html) be the example ?
I would be greatful for a small snippet.
![image](https://user-images.githubusercontent.com/884885/85130871-00d29400-b236-11ea-987f-2343f1b55f69.png)

**Comment by martin1cerny** [comment]
WexBIM file only contains geometry and element IDs. To show any properties, you need to serve them from the server and get them by element ID (`EntityLabel` in xbim).
