### ISSUE TITLE
Can we zoom the floor type in xbim viewer solution?

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#290]
In the solution given by our blog, the Asset and spaces are zooming perfect.when floor type entity clicking that is not zooming.
I have tried for zooming the floors in browser.js file but its not works
How to zoom for floor types
any resolving ideas please let me know
thanks in advance

**Comment by andyward** [comment]
I think I answered this over at https://github.com/xBimTeam/XbimGeometry/issues/264
