### ISSUE TITLE
How to load properties tab from viewer loaded function?

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#291]
Hi 
In solution if we clicks entity from spatial/assettypes tabs the properties tab will shows the asset zooming and exact details corresponding to selected item.

In my case,
I will zoom asset when loading page, using external id in "viewer.on("loaded", function (args)" the function.
I will hide left side tabls (spatial/assettypes tabs).by default i will zoom specific asset/space.Now this time i want load properties tab corresponding to which item was loaded/zoom.

So how to handle this/ how to load properties tab based on external ID?

**Comment by martin1cerny** [comment]
What do you mean by *external ID*? The `loaded` event will give you the ID of the model you just loaded so that you can use it for the further interaction in case you have loaded multiple wexBIM files.

**Comment by castronelson** [comment]
yeah. 
I will highlight the asset by passing externalID in "viewer.on("loaded", function (args)" this function.
now this time i want to view the properties and attributes tab. Is it possible?

**Comment by martin1cerny** [comment]
Yes, it is.

**Comment by castronelson** [comment]
could you please help. how to load the details in properties and attributes tab corresponding to highlighted asset
in viewer-loaded method (in browser page viewer-loaded method entity  is not available )

**Comment by martin1cerny** [comment]
All interaction events (like `pick` etc.) will give you ID of the product. This is what you will get as `EntityLabel` in xbim. So, when you have the model open, you can simply get the product like `var product = model.Instances[id] as IfcProduct`. You can then get any data you want, serialize it and send it to the browser and present it any way you like.

**Comment by castronelson** [comment]
Thank you so much.
