### ISSUE TITLE
Large IFC files (500 MB files) not loaded in Internet Explorer

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimWebUI#293]
Hi,

Hope you are doing good.

In Web application - We are trying to convert 500 MB IFC file to JSON & Wexbim.

The files are converted but the BIM model is not displayed in xBIM Viewer if we are using in Internet Explorer.

We have tried other browsers like Chrome, Microsoft Edge - the BIM model has been displayed in xBIM viewer but it will take 40 seconds for loading.

Please clarify the below questions:

Please let us know if any size constraints to load the BIM model in Internet explorer.

Please let us know, how to avoid delays if we upload more than 500 MB IFC files in xBIM Viewer.

Thank you in advance.

**Comment by Nandhakumar2187** [comment]
Hi,
Kindly provide your feedback on the above.
Thank you.

**Comment by andyward** [comment]
Firstly: what version of Internet Explorer? Assuming IE 11 as anything prior won't support WebGL at all.

But even IE11 is an awful, outdated, unsupported browser that no one should be using for modern web applications. 
IE11's lack of full support for HTML5 means the 3D viewer is not well optimised in our web viewer. Secondly IE11's javascript engine is much slower than modern JS engines you'll find in Chrome, Firefox, Safari etc.  So it will really struggle with large JSON payloads.

All models are different. One 500MB model can have different performance characteristics to another 500MB model. but I commented previously on how large models won't perform well if implemented naively. This even more the case with IE 11.
https://github.com/xBimTeam/XbimWebUI/issues/285#issuecomment-612143296

Your best bet with IE with real world models is to nudge the users towards using a modern 'evergreen' browser.  If you are working with enterprises who still aren't on Windows 10 (where legacy and new Edge are deployed), you have my sympathies... but that's a vanishing pool of laggards I'd not be inclined we spend much time on. Happy to take a PR for optimisations but I don't see us 'fixing' it
