### ISSUE TITLE
Possibility to load the 2D diagrams in XBIM Viewer

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimWebUI#294]
Hi,

Hope you are doing well!!!

Kindly let know if we have any possibilities to load the 2D image like .dwg file in xBIM Viewer.

Also please let us know if we can able to extract the assets from 2D image.

Please provide your suggestions on this.

Thank you in advance.

**Comment by martin1cerny** [comment]
No, this is not a supported functionality. But the viewer is extensible, so you can intercept the rendering loop and render DWG yourself. 

Which kind of assets would you like to extract from which kind of 2D image?

**Comment by Nandhakumar2187** [comment]
That is Floor plan in DWG format AutoCAD file.

**Comment by andyward** [comment]
There are some folks working on open libraries to support Autodesk's DWG format. But it's a **massive** job to support a complex proprietary file format with a [40+ year history](https://en.wikipedia.org/wiki/.dwg#History)... If you take a look at that wiki link it has some providers of tech to open/view DWG format - but I don't think it makes sense to overload the xbim toolkit with support for other proprietary formats - and it's not something I can see us taking on. (If we support DWG, what about DGN, DXF, PDF, etc ?)

What may make sense is extending the wexbim viewer to support 2D planes to be inserted into a coordinated 3D wexbim view - but using open formats (rasterized or possibly vector). That would open a workflow where you could use some other software to convert DWG=> PNG/SVG etc, ensure it's appropriately coordinated, to see floor plans etc in a 3D model.

This should be possible with a Plugin...
