### ISSUE TITLE
How to extract data from mvMatrix to save BCF viewpoint's PerspectiveCamera/OrthogonalCamera data

### ISSUE THREAD

**Issue by adam9000** [xBimTeam/XbimWebUI#295]
Hello everyone!

I spend a lot of efford in this matter. but I stucked. My knowledge in WebGL is almost zero...I started some studies, but it's a bit hard for beginners to deal with the mat...vec3...mat4 and so on...

I got it that XML PerspectiveCamera.CameraViewpoint we can get from getCameraPosition method, but CameraDirection and UpVector I have no idea how to obtain.

I play with _pMatrix, some hidden classes (ViewerSession.Snapshot), but none do the job. 

Any help to solve this question would be veeeeeeeeery much appreciated.

I saw that we'll have full support to deal with BCF in the upcomming-heavily-waited new release.
Maybe can you gave us some glimpses from that part of the release @martin1cerny ? 
;)

Tnx in advance.

**Comment by adam9000** [comment]
I solve it. The studies pay the bills.

**Comment by CBenghi** [comment]
Hi @adam9000, 

well done! 
Can I ask you to share the solution?

Even if you have solved it by yourself. It might help others in the future.

Thanks,
Claudio

**Comment by adam9000** [comment]
Sure I will Claudio!!! 

Just give me a time to do it right with a proper Pull Request (in develop branch), to maybe account me as a another contribution.

**Comment by tg-pool** [comment]
Hi @adam9000 ,
I'm probably too stupid to find your solution. I'm stuck on exactly the same question and would be very happy about any idea to solve this.

Thanks in advance,
Till

**Comment by martin1cerny** [comment]
There is [native support](https://docs.xbim.net/XbimWebUI/classes/_bcf_viewpoint_.viewpoint.html#getviewpoint) for BCF viewpoints in the viewer.
