### ISSUE TITLE
How to load two or more cobie.json files to xBrowser

### ISSUE THREAD

**Issue by SergiMacian** [xBimTeam/XbimWebUI#296]
Hi mates,

#### Expected behavior:
I'm currently trying to load a couple of .wexBIM files with their respective cobie.json data files. 
I'm wondering if I can call browser.load(cobie.json) twice and get the information from both. 
If I can call it twice, is there any restriction? 
If I cannot, shall I merge the two cobie.json files into one? (ensuring that no ids are reapeated)

#### Actual behavior or exception details:
I call it twice (as shown below in the code), with the two different cobie.json files and I get the following output:

![multiple_xBrowser_loading](https://user-images.githubusercontent.com/45793287/92747745-cedc5400-f384-11ea-95e2-656d8de580d2.jpg)

Problems: 
- the left menu is not properly loaded
- I cannot access the information of both models (just from one of them)

#### Minimal code (or steps) to reproduce the issue:

        //TwoProxy
        viewer.load("data/TwoProxy.wexBIM");
        browser.load("data/TwoProxy_DPoW.json");

        //FourWallsDoorWindows
        viewer.load("data/FourWallsDoorWindows.wexBIM");
        browser.load("data/FourWallsDoorWindows_DPoW.json");

#### Minimal file to reproduce the issue:

The four used files (two .wexBIM and two cobie.json) are attached here: 

[xBrowser.zip](https://github.com/xBimTeam/XbimWebUI/files/5202481/xBrowser.zip)

Thank you all in advance! :)

**Comment by martin1cerny** [comment]
A new version of the viewer has been published with many improvements. It is available as an [npm package](https://www.npmjs.com/package/@xbim/viewer) now. Recommended way to present semantic data is to implement your own server side code which can serve data from multiple federated models. We also work on a commercial cloud service which can be used for this purpose. [Get in touch](mailto:info@xbim.net) if interested.
