### ISSUE TITLE
How to identify/locate the Rooms in the IFC File

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#297]
Hai sir,
In xbim viewer we can identify the floors,Assets,spaces etc..
But how to identify/locate the Rooms?
And How to get the data of Rooms from JSON file and locate the room in Xbim viewer.

we need to locate the Rooms in viewer and get data.

Please help!.
Thank you.

**Comment by andyward** [comment]
Rooms and Spaces are the same concept (in IFC) and it sounds like you've already bee able to identify spaces.

If you have the EntityLabel of the IfcSpace you can highlight the volume in the 3D view - see the tutorial: http://docs.xbim.net/XbimWebUI/tutorial-5_Colourful_building.html

Note that Spaces may not be displayed / pickable by default in the viewer.
