### ISSUE TITLE
what is the minimum and maximum value of origin in viewer.clip(origin, direction)

### ISSUE THREAD

**Issue by Joao-b4** [xBimTeam/XbimWebUI#299]
example: http://docs.xbim.net/XbimWebUI/4_Building_seen_from_everywhere.live.html
how to know the maximum value that can be passed to the origin. in the example, a text field is used, but how to do it programmatically, and get the maximum coordinates of the model

**Comment by martin1cerny** [comment]
There isn't any limit on this. But if you are asking for sensible values, then you can get these from region bounding box.

**Comment by Joao-b4** [comment]
tks for answer martin
how can I access this values from the bounding box? 
any API example?

**Comment by martin1cerny** [comment]
Which version of the viewer are you using?

**Comment by Joao-b4** [comment]
I don't know for sure, but I believe it is the most recent

**Comment by Joao-b4** [comment]
hello, any answer on how to get the values ​​from the bounding box?

**Comment by andyward** [comment]
Slightly tricky in the master branch, and I think this has been improved in develop and our latest version. But if you want to get the bounding box of the model you can get it via the private __handles_ property on the viewer.

```viewer._handles[0].region.bbox```

You can also take a look at `setCameraTarget()` which acquires the bounding box for the whole model or a specific product. https://github.com/xBimTeam/XbimWebUI/blob/3c69be256b094a7b53779132cd4d32702980990e/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L538

**Comment by Joao-b4** [comment]
thanks @andyward
