### ISSUE TITLE
Issue with converting IFC file to WEXBIM

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#30]
Hello,
I have a question regarding converting IFC file to WEXBIM on C# side, I have the attached error. Is there a limitation size for conversion? Because I tried to convert a file of size 256 MB
![ifc_to_wexbim_issue](https://cloud.githubusercontent.com/assets/12897988/9397840/fdd4d31c-47a0-11e5-877d-24936f78b75d.PNG)

Thank you for help.

Regards

**Comment by CBenghi** [comment]
Hello,
there should be no particular problems when converting models of any size.
If you can share the model (under NDA, if needed) I can have a look at any problems.
The error I read seem to be connected to possible out of memory, or some other bug, but it's difficult to say.
Are you using a late build?
Claudio

**Comment by andyward** [comment]
While unlikely, it's possible you're hitting 32bit memory limits while processing the geometry in a x86 process. Try running as a 64 bit process which will let you use more than 2GB of RAM. 

If it still fails it sounds like an edge case in the Geometry engine - make sure you've the latest version of Xbim.Geometry nuget package

**Comment by johnBim** [comment]
Hello Andy,
sorry for the delay, I will try that asap.

thx

**Comment by andyward** [comment]
Closing. Re-open if still a problem
