### ISSUE TITLE
How to get all object ids in XBIMViewer

### ISSUE THREAD

**Issue by Aokijic** [xBimTeam/XbimWebUI#300]
hi, 
i want to get the ids of all objects without using the pick event after the model is loaded
how to do that?
thanks

**Comment by andyward** [comment]
`viewer.getModelState(modelId)` should give you an array of all items and their state.

**Comment by andyward** [comment]
In the latest viewer you can use `viewer.getProductsState(modelId)`

https://docs.xbim.net/XbimWebUI/classes/_viewer_.viewer.html#getproductsstates
