### ISSUE TITLE
when Publishing the source -"Could not load file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies" 

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#301]
Hi sir,
We have created the web application with all required xbim dlls
Its working very fine when running from source.
But when publishing the source, it throws an error below
**"Could not load file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies. An attempt was made to load a program with an incorrect format".**
why it happening when publishing
Please help me to resolve the issue..

**Comment by martin1cerny** [comment]
There is a lot written about this in [XbimGeometry project](https://github.com/xBimTeam/XbimGeometry/issues?q=is%3Aissue+is%3Aclosed+Xbim.Geometry.Engine64).
