### ISSUE TITLE
How to centralize and zoom in the element that I double click ?

### ISSUE THREAD

**Issue by boosterwu** [xBimTeam/XbimWebUI#31]
How to centralize the element when I double click ?
and how to make the zoom in size small than default setting it it too large in my use case?

**Comment by andyward** [comment]
Take a look at Issue #18 - I think that is a similar question

**Comment by boosterwu** [comment]
great! I solved my problem. I try to modify xbim-viewer.debug.js and and some code to change the _distinct value as below:

var setDistance = function (bBox) {
        var size = Math.max(bBox[3], bBox[4], bBox[5]);
        var ratio = Math.max(viewer._width, viewer._height) / Math.min(viewer._width, viewer._height);
        var resize = 1.0;
        if (typeof (prodId) != 'undefined' && prodId != null) {
            resize = 5.0;
        }
        viewer._distance = size / Math.tan(viewer.perspectiveCamera.fov * Math.PI / 360.0) * ratio * resize;        
    }
