### ISSUE TITLE
npm install @xbim/viewer does not work

### ISSUE THREAD

**Issue by JosefUIBK** [xBimTeam/XbimWebUI#311]
Hey,

i get this error messege using the npm command:

> npm : npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\c846
> 1275\Documents\PhD\RevitDALEC_NewUI\vec-modul-revit\ResultViewer\package.json'
> In Zeile:1 Zeichen:1
> + npm install @xbim/viewer
> + ~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (npm WARN saveEr...r\package.json' 
>    :String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> npm
>  WARN enoent ENOENT: no such file or directory, open 'C:\Users\c8461275\Documen
> ts\PhD\RevitDALEC_NewUI\vec-modul-revit\ResultViewer\package.json'
> 
> npm
>  WARN ResultViewer No description
> npm WARN
>  ResultViewer No repository field.
> 
> npm
>  WARN ResultViewer No README data
> npm WARN ResultViewer No license field.

node-modules folder is generated, but folder ../js/xbim-viewer.js is missing. Any Idea

**Comment by martin1cerny** [comment]
I just tried in a vanilla project and everything worked fine. I can't see any `@xbim/viewer` specific error in there. It seems like you didn't initialize your NPM project first.

```
PS C:\Users\Martin\Source\Delete> npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (delete) Test
Sorry, name can no longer contain capital letters.
package name: (delete) test
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to C:\Users\Martin\Source\Delete\package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) yes
PS C:\Users\Martin\Source\Delete> npm install @xbim/viewer
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ @xbim/viewer@1.0.3-pre202010081449
added 4 packages from 9 contributors and audited 4 packages in 6.479s
found 0 vulnerabilities
```

**Comment by JosefUIBK** [comment]
Okay, now this works fine for me too. But in the Hello "Building Example" there is a source

`<script src="../js/xbim-viewer.js"></script>`

But i have no such source. There is no xbim-viwer.js in any of the folders.

**Comment by martin1cerny** [comment]
This is a simplistic example. The JS file is in `node_modules/@xbim/viewer/index.js` If you are going to use NPM, just import/require the module `@xbim/viewer`. If you use Typescript, you also get all the type safety and code hints.

**Comment by JosefUIBK** [comment]
Okay,

it's running. It seems you are expecting only professionals working with it. A better desciption with explaining how to start a server in localhost and so on would be helpfull :)

**Comment by martin1cerny** [comment]
You are welcome to contribute to the tutorial.
