### ISSUE TITLE
After load heavy file viewer has smoothness issue

### ISSUE THREAD

**Issue by dammyBisht** [xBimTeam/XbimWebUI#312]
#### I'm facing a problem to use a heavy Wexbim file. if I'm using a heavy file then the viewer has a smoothness issue, can you please tell me why it's happening, is the issue in my file, or anything I missed? I've attached wexbim file which is I'm using.

[wexbim.zip](https://github.com/xBimTeam/XbimWebUI/files/5840513/P-061.Merck.Unit.20.zip)

**Comment by martin1cerny** [comment]
I just tried on my machine and while it is not perfect, I get something around 20fps, which is workable. But this depends on the specific client and its GPU capabilities as WebGL is using HW acceleration.
![image](https://user-images.githubusercontent.com/773078/105144984-576ebc00-5afe-11eb-82cb-275ea308dba6.png)

**Comment by dammyBisht** [comment]
Thanks you @martin1cerny for your quick response. I'll check it on another system.

**Comment by andyward** [comment]
It may be something a bit strange with this model as a 16MB file should not be a major performance issue. If it were 10x that I could understand.

I had a brief look and it does have a lot of rebar and similar complex meshes in there - and there's more elements than it may appear. 

If you do find outliers on different machines, you can use https://webglreport.com/ to report on their support for WebGL1/2
