### ISSUE TITLE
Add hotspot inside the viewer

### ISSUE THREAD

**Issue by dammyBisht** [xBimTeam/XbimWebUI#313]
#### I need your help to add hotspot insied the viewer.

![image](https://user-images.githubusercontent.com/54030353/105338841-00520f80-5c02-11eb-8821-2c3752e775af.png)

**Comment by martin1cerny** [comment]
What do you mean by 'hotspot'? The rotation origin?

**Comment by dammyBisht** [comment]
@martin1cerny I want to add the yellow hotspot which is marked by red circle.

![image](https://user-images.githubusercontent.com/54030353/105344063-78233880-5c08-11eb-9ea3-f2e2008ae07a.png)

After loading the wexbim file, a yellow hotspot should be added wherever I click.

**Comment by martin1cerny** [comment]
I did get that. The question is what it should represent. There is a mechanism of plugins in the viewer. You can develop webgl plugin which will render any kind of circle wherever you want. There isn't such a plugin right now. We will develop it in at some point but it is not a priority right now. Any contributions are most welcome.
