### ISSUE TITLE
Wrong import in viewer.d.ts causes error on unix systems

### ISSUE THREAD

**Issue by jenswoelkerling** [xBimTeam/XbimWebUI#316]
Seems that the version using  npm i @xbim/viewer: 

still contains the 

ERROR in node_modules/@xbim/viewer/src/viewer.d.ts:8:29 - error TS2307: Cannot find module './common/checkResult' or its corresponding type declarations.

8 import { CheckResult } from './common/checkResult';

#### possible solution:
I think this is already solved in the code. 
Can you please build a new npm package?

**Comment by GeorgDangl** [comment]
I'm hitting the same issue, on CI builds running on Linux where the file system is case sensitive. I'm just fixing this in my build script like this:

```csharp
if (Environment.OSVersion.Platform == PlatformID.Unix)
{
    // Case sensitive systems, need to fix this issue here: https://github.com/xBimTeam/XbimWebUI/issues/316
    CopyFile(RootDirectory / "ui" / "my-app" / "node_modules" / "@xbim" / "viewer" / "src" / "common" / "checkresult.d.ts",
        RootDirectory / "ui" / "my-app" / "node_modules" / "@xbim" / "viewer" / "src" / "common" / "checkResult.d.ts",
        FileExistsPolicy.Overwrite);
}
```

**Comment by martin1cerny** [comment]
New `npm` package is available now.
