### ISSUE TITLE
How to load heavy file in the part. 

### ISSUE THREAD

**Issue by dammyBisht** [xBimTeam/XbimWebUI#318]
#### For eg.: If we load the file then the file will visible with column only, and wall or other elements will load one by one later.

How I can achieve it?

**Comment by martin1cerny** [comment]
To do this, you can split the original data into as many partial wexBIM files as you want and you can load them incrementally.

**Comment by dammyBisht** [comment]
Thank you @martin1cerny, got your point. but can you guide me on how to create multiple wexbim files from single IFC file based on element types? For eg.: Wall, Bim, Window, etc.

**Comment by martin1cerny** [comment]
Use the optional `products` parameter of the [SaveAsWexbim() function](https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc/Extensions/IfcStoreGeometryExtensions.cs#L25).

**Comment by dammyBisht** [comment]
@martin1cerny thank you mate. 👍
