### ISSUE TITLE
how can I add the hint or pop windows when click the element ?

### ISSUE THREAD

**Issue by boosterwu** [xBimTeam/XbimWebUI#32]
I would like to add some labels and hints on the 3D web page when use click the specific element?
is it possible to do it?

**Comment by andyward** [comment]
If you mean you want to show data relating to an element when the user selects it, I think one way would be to use the [xBrowser.js](http://xbimteam.github.io/XbimWebUI/xBrowser.html) library.

**Comment by boosterwu** [comment]
I just review the xBrowser.js but still not found how to do?
I am trying to add pop windows like
![image](https://cloud.githubusercontent.com/assets/829351/9461533/f068784c-4b41-11e5-9d13-b6ce72119d7c.png)

When I selection the green element, it should show the relation information at pop window.

**Comment by andyward** [comment]
xBrowser gives you something like this (from the XbimAzure project):

![image](https://cloud.githubusercontent.com/assets/923699/9462433/acc7dc06-4b0d-11e5-991a-59a18102cc1d.png)

You could probably use the same approach (using xVisualModel COBieLite data) to display selected values in a tooltip, but you'd have to wire it up yourself.

**Comment by martin1cerny** [comment]
Hi @boosterwu I'd recommend to have a look at [this tutorial](http://xbimteam.github.io/XbimWebUI/tutorial-3_Eventful_building.html) and [this documentation entry](http://xbimteam.github.io/XbimWebUI/xBrowser.html#event:entityDblclick). It shows you how to listen to events you need to do any user interaction like pop up windows. As @andyward said already you will have to write this wiring yourself. [xBrowser class](http://xbimteam.github.io/XbimWebUI/xBrowser.html) provides an access to semantic COBie data extracted from the model. That includes spatial hierarchy containment, system relations, most of properties and other information. If you need full access to BIM model you should have a look at this issue #28 where it is discussed.

**Comment by boosterwu** [comment]
hi @martin1cerny , thank you for your reply. I will refer your suggestions and feed to you my solution later.

**Comment by boosterwu** [comment]
hi @andyward and @martin1cerny , I still working on this feature, so far I can draw a quadrangle like pop window on 3D graph using WebGL directly, but I have no idea to draw the same into the xBim Web UI , could you please give me some hints that I can draw something with xBim API ?

Thanks.
James

**Comment by LloydPickering** [comment]
Do you have to do it in WebGL? You are in a browser which already has a HTML rendering engine in it, and WebGL is ultimately just a HTML element (canvas). Why not just use a standard html popup using javascript and save yourself the headache of rendering in WebGL?

**Comment by martin1cerny** [comment]
Hi @boosterwu, I agree 100% with @LloydPickering. It will be much easier to do in HTML. WeXplorer API doesn't support any kind of custom WebGL rendering. You can certainly branch and hack it but you'll be on your own in that case.

**Comment by boosterwu** [comment]
thank you @LloydPickering and @martin1cerny , I totally agree what your suggestion . I'll try to use HTML element to show pop windows directly.

**Comment by boosterwu** [comment]
Sorry for my late reply. 
I already add the tooltip inside the xBimWebUi using the [qtip2]("http://qtip2.com") jquery plugin.
I add some javascript code in **entityActive** event of **browser.js** as below.
```
    $("#viewer-canvas").qtip({
    show: {
        event:'click'
    },
    hide: {
        event: 'false' 
    },
    content: {        
        text: function (event, api) {
            $.ajax({
                url: 'http://qtip2.com/demos/data/owl' // Use href attribute as URL
            })
            .then(function (content) {                
               api.set('content.text', content);
            }, function (xhr, status, error) {
                // Upon failure... set the tooltip content to error
                api.set('content.text', status + ': ' + error);
            });
            return 'Loading...'; // Set some initial text
        }
    },
    position: {
        target: 'mouse', // Use the mouse position as the position origin       
        adjust: {
            // Don't adjust continuously the mouse, just use initial position
            mouse: false
        }
    }});
```
when you click any entity will show the tooltips windows on the XBim.
![image](https://cloud.githubusercontent.com/assets/829351/9976560/644987c4-5f1a-11e5-8258-099e2e8679dc.png)

**Comment by martin1cerny** [comment]
Thanks for the suggestion @boosterwu . It might be useful function so I'll add it once I get to do something with xBrowser. You might also like to use built-in functions like [renderAttributes()](http://xbimteam.github.io/XbimWebUI/xBrowser.html#renderAttributes) to render into HTML straight away. It might boost your development. 

I suppose your issue is solved now. Can I close this issue?

**Comment by boosterwu** [comment]
@martin1cerny ,sure please close this issue. 
thank you.
