### ISSUE TITLE
Color change on converting

### ISSUE THREAD

**Issue by dammyBisht** [xBimTeam/XbimWebUI#321]
#### So can you tell me, how we can use same alpha from IFC.

![image](https://user-images.githubusercontent.com/54030353/107517151-5e578e80-6bd3-11eb-85d5-d06c2646fe47.png)

**Comment by martin1cerny** [comment]
You can play around with gamma, brightness and contrast.

**Comment by andyward** [comment]
See also #367 which may impact this.
