### ISSUE TITLE
Orbit reset Origin not working

### ISSUE THREAD

**Issue by bcanteneurEiffage** [xBimTeam/XbimWebUI#326]
#### Expected behavior:
In your example here : https://docs.xbim.net/examples/4_Building_seen_from_everywhere.live.html you say that everytime an object is picked the origin for the Orbit center is reset to that object.
I cannot find how you do it, I do not see any function setting the origin of orbiting.

#### Actual behavior or exception details:
The orbit center is not changing when clicking an object in the viewer

#### Version of the xBIM Viewer:
I am using the NuGet package https://www.nuget.org/packages/XbimWebUI/0.1.41 in an ASP.NET Framework solution.
I am not sure that the verison used in the example is the same as the constructor for the Viewer is new Viewer wherease in the NuGet package it is new xViewer.

#### Minimal code (or steps) to reproduce the issue:
    var viewer = new xViewer('viewer');
    var selectedIds = [];
    viewer.on('loaded',
        () => {
            viewer.start();
        });

    viewer.on('pick', function (args) {
        if (args == null || args.id == null) {
            return;
        }

        var id = args.id;

        //If the id was previously clicked then remove it from the list and remove the highlight
        if (selectedIds.includes(id)) {
            viewer.setState(xState.UNDEFINED, [id]);
            var index = selectedIds.indexOf(id);
            selectedIds.splice(index, 1);
         } else {
            viewer.setState(xState.HIGHLIGHTED, [id]);
            //Add element to selected list
            selectedIds.push(id);
        }
    });

    viewer.load('../Content/3d/Maintenance.wexbim');

#### Minimal file to reproduce the issue:
I use the SampleHouse.wexbim file for now

**Comment by martin1cerny** [comment]
We recently published a new version of the `Viewer` and it is now available as an [npm package](https://www.npmjs.com/package/@xbim/viewer). The documentation is for this new version. I'd encourage you to upgrade it. If you get in touch at info@xbim.net, we can put you on the mailing list for our occasional newsletter so you don't miss information like this.

**Comment by bcanteneurEiffage** [comment]
Ok thanks for the information. Sadly it seems that npm packages are not really easy to use in a framework project and so I am kind of stuck in manually including the ts files in my solution in the Script folder

Thanks for the newsletter, I will write to it in order to have this kind of info

**Comment by bcanteneurEiffage** [comment]
Hi @martin1cerny . Sorry to bother you but I cannot find any way to install the new version with npm package in an ASP.NET MVC solution in Visual Studio.
Have you ever done this and if so could you explain how to do it?
Thanks a lot!

**Comment by martin1cerny** [comment]
You would [install and use it as any other npm package](https://stackoverflow.com/questions/37805599/using-npm-with-an-mvc-project). I didn't try this lately but there isn't anything special about our npm package.
