### ISSUE TITLE
Recreate camera view using 3 vectors

### ISSUE THREAD

**Issue by HristijanJohn** [xBimTeam/XbimWebUI#329]
Hello,
Is there any way to recreate 3D view, if I have stored camera position direction and heading. I am using the code below but I am not getting accurate view (it's very close to the original, but not the same). Am I missing something before calling viewTo function?

var mv = mat4.lookAt(mat4.create(), cameraposition, cameradirection, cameraheading);
viewer.animations.viewTo({ mv: matrixView, height: height }, 0);

Thanks,
Hristijan

**Comment by andyward** [comment]
Hi Hristijan

I think the 4th parameter of `lookAt()` should be the 'up' vector. That might be the issue.

But actually, the latest viewer has this all built in. In fact it can create and restore a BCF-API compatible viewpoint out the box:

You can see this in action in the 'featured viewer' example: https://github.com/xBimTeam/XbimWebUI/blob/master/examples/featured-viewer/index.ts#L202

```typescript

/*** Create a BCF viewpoint */
createViewpoint() : Viewpoint {

  // Creates a BCF Viewpoint (including camera, projection, clip-planes,  500px snapshot etc)
  const width = 500;
  return Viewpoint.GetViewpoint(this.viewer, null, width) ;
  // Then serialize the bcf json somewhere
}

/*** Restore viewpoint from BCF-API */
restoreViewpoint(bcf: Viewpoint) {

  // reinstates the camera, projection, clip-planes and any selected items (subject to mapping)
  const animationMs=1000;
  Viewpoint.SetViewpoint(this.viewer, bcf, null, animationMs);
}


```
**Note** on the mapping of Ids, used for selection, coloring etc... Internally the viewer uses a composite key consisting of the EntityLabel/Id and the internal *model* number to track things like selection. Wexbim (and hence the viewer) doesn't have access to the UniqueIdentifier or have access to a stable key for the model in a federation). Instead you can provide a function to manage this mapping at runtime. i.e.
`GetViewpoint` and `SetViewpoint` each take a mapping function that enables you to map the internal ids used for selected elements to some stable key. (e.g. you could map to the UUID).

**Comment by HristijanJohn** [comment]
It works fine, thanks. You have option for saving only selected elements and I've added some more code for saving colorings and hidden elements as well.
