### ISSUE TITLE
Create WexBIM with version >= 3

### ISSUE THREAD

**Issue by klamarth** [xBimTeam/XbimWebUI#331]
Reading the most recent model-geometry.ts I can see that it is prepared to load a WebBIM with version >= 3 (better rendering I suppose)

I could not find how to generate files with this version. 

The ***Xbim.Ifc.IfcStoreGeometryExtensions*** is prepared to save it as version 2

```binaryStream.Write((byte)2); //version of stream, arrays now packed as doubles```

Can you, please, tell me how to do it?

Thanks in advance

**Comment by martin1cerny** [comment]
Version 3 is something we implemented in our commercial cloud service so far. It has the same rendering quality but deals better with federated models.

**Comment by klamarth** [comment]
Ok cool. Thanks.
