### ISSUE TITLE
Using code in web server

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimWebUI#332]
Recently I asked about Electron-app packaging (#328) and I wish to thank you for all the support. One of my major concerns about the change to JS was that about usability. 
For example, how to publish it in a web server... Is there any tutorial or guide to do so? I'm not a js dev, any hint would be much appreciated.

thanks in advance

**Comment by martin1cerny** [comment]
I'm sorry, but your question is not specific to this project. You will find better advice on Stackoverflow and in Electron documentation.

**Comment by johnnyontheweb** [comment]
@andyward asked me to open a thread.
@martin1cerny I understand, but IMHO some hints should be given. This is not related to Electron.

**Comment by martin1cerny** [comment]
It all depends on your development environment, your web server and your hosting. This is all under your control and is specific to your project. Any Javascript is just a static file. So, you should search for the documentation which describes how to develop a web application in your development environment for your web server and how to deploy it to your hosting provider. Our WebUI is just one of the resources you will be using in your project.

**Comment by johnnyontheweb** [comment]
If I want to test the repo directly, it seems that npm uses a dist virtual folder, I'll look under the repo to find out where it is set.

**Comment by johnnyontheweb** [comment]
Well, not straighforward at all... When using webpack.prod.js, I get the error `Cannot GET /dist/basic-viewer/index.html`, because virtual `dist` folder is not set...
IMHO it would be easier to understand for all if webpack uses:
```
...
publicPath: "/dist/",
...
```
for all configurations.

**Comment by martin1cerny** [comment]
`basic-viewer/index.html` is only meant for development where `dist` is only virtual as anything can dynamically change. `webpack.prod.js` is used to build the release. It doesn't define **any** webserver settings and doesn't even have HTML loader. Use  `webpack.dev.js` for development and `webpack.prod.js` to build the release.
