### ISSUE TITLE
iOs Mobile render error

### ISSUE THREAD

**Issue by bcanteneurEiffage** [xBimTeam/XbimWebUI#334]
#### Actual behavior or exception details:
When rendered on a mobile (iOs) web browser the model displays a lot darker than in computer web browsers.
![image0](https://user-images.githubusercontent.com/68943107/113139992-198dc280-9228-11eb-843b-5c918a633789.png)

Here is the same page but on computer :
![image](https://user-images.githubusercontent.com/68943107/113140179-58237d00-9228-11eb-8ad6-1892f22084b6.png)

#### Version of the xBIM Viewer:
"@xbim/viewer": "2.0.1-pre202103091921"

#### Minimal file to reproduce the issue:
Bug is not dependent of a wexbim model but happens everytime

**Comment by andyward** [comment]
Weird because it has been tested on IoS Safari and Chrome

It would be useful to get the stats on the level of Webgl support for the two different browsers. You can use the tool a https://webglreport.com/?v=2 to get the data

**Comment by bcanteneurEiffage** [comment]
Mobile browser :
![image](https://user-images.githubusercontent.com/68943107/113152736-b48d9900-9236-11eb-9c12-9906c5cc2a0c.png)
![image](https://user-images.githubusercontent.com/68943107/113152773-bfe0c480-9236-11eb-8cbe-f157ce83dbfe.png)

**Comment by bcanteneurEiffage** [comment]
Computer :
![image](https://user-images.githubusercontent.com/68943107/113152919-e272dd80-9236-11eb-8df4-2656cdfab7e4.png)
![image](https://user-images.githubusercontent.com/68943107/113152952-ebfc4580-9236-11eb-8b0d-b50b9a76f185.png)

**Comment by martin1cerny** [comment]
The viewer prefers WebGL2, so your mobile iOS is using different shaders than your computer. There might be some discrepancy between our shaders implementations. Will look at it in the next few days.

**Comment by bcanteneurEiffage** [comment]
Ok I enabled WebGL2 and it looks better but still different from computer 
![image](https://user-images.githubusercontent.com/68943107/113154518-5e215a00-9238-11eb-9060-a58bb40c388e.png)

**Comment by andyward** [comment]
This should have been fixed with #367

Was down to a precision issue affecting mobile viewer engines
