### ISSUE TITLE
Difference between Nuget and Myget packages

### ISSUE THREAD

**Issue by klamarth** [xBimTeam/XbimWebUI#335]
Hi, I noticed that the latest Nuget is different from latest MyGet for some packages.

Any special reason for that?

![image](https://user-images.githubusercontent.com/80955361/113716520-ce4f4480-973e-11eb-8044-944604547b9c.png)

**Comment by martin1cerny** [comment]
We use MyGet for development and only publish to NuGet manually from MyGet irregularly.

**Comment by andyward** [comment]
And I don't think we publish WebUI to Nuget or Myget any more. `npm` is the more natural choice.
