### ISSUE TITLE
AddModelReference to add ifc reference file

### ISSUE THREAD

**Issue by Anu004** [xBimTeam/XbimWebUI#336]
Hi,

I want to show the mechanical and architectural models together in the XbimWeb viewer. For that I added the architectural model as a reference using the following code

 m_Model.AddModelReference(FilePath, "RefModel", "Architecture");

Then I saved and converted this ifc file to wexbim file. Is this enough to show the referenced wexbim file in the viewer? Or should i open both these files manually after checking if there is a reference file?

**Comment by martin1cerny** [comment]
You need to process both models separately to create their wexbim representation. You can then load both in the viewer.

**Comment by Anu004** [comment]
How can I find if there is a referenced model in the opened ifc file? Even if I added the Architecture file as model reference (as I told above), its not showing as a referenced model while trying to get the data.

![ref](https://user-images.githubusercontent.com/8133894/114401318-6c6c6000-9bc0-11eb-9c21-f71c75da1cf0.PNG)
