### ISSUE TITLE
Large WeXBim File (250MB) Load Time

### ISSUE THREAD

**Issue by gstevenson12** [xBimTeam/XbimWebUI#339]
Hi there,

There have been several issues opened on this topic, but I haven't seen a concise answer on this, at least not in several years. We have a relatively large .wexbim file (250MB) that we are hoping to have load from the server quickly. We are exploring splitting up the large model into many smaller models, and opening several models in the same viewer. Does that help performance at all in terms of loading time? Is there a good way to "select" a specific model that will be viewed at a given time? 

Really appreciate the help in advance!

**Comment by martin1cerny** [comment]
- You can split the file info several smaller files, but if the bottleneck is a network then you still need to pass 250MB through the network and multiple parallel downloads will just be smaller. Every model you load is kept separate so you can control which partial models are running and which are stopped. 

- You can implement server-side gzip compression, which will speed the download at least a bit.

- You can (and should) use `loadAsync()` method which uses web worker to fetch and parse the file. But it then still has to pass the data to the main thread (even though we use transferable arrays to optimise the memory usage) and has to pass the data to GPU.

- Our web UI is using WebGL with hardware acceleration like all other 3D viewers. Hardware acceleration means that performance is device specific based on GPU speed and memory. But from my experience, 250MB will be too much for most devices. 

- You should check why your model is so large. In most cases you will find that most of the geometry data is in objects which either don't have any real value (like a beautiful, highly detailed 3D car in the garage), or are modelled with unnecessary detail (like a model of the door with all nuts, bolts and springs). We recently saw a file where 200MB was just in a single door. You should do some basic QA of the model to find out why it is so large.

- Other option is that your model contains loads of curved extruded profiles (loads of wires, tubes, pipes, reinforcing bars etc.). In that case, you could try to adjust deflection angle of geometry processing. That will create coarser geometry with less triangles. Depending on your model, this might have a significant impact on the final number of triangles.

**Comment by gstevenson12** [comment]
Thank you, Martin, for your detailed and quick response. For what its worth, this file is a full rebar model for a structure that is a dozen stories tall. I will look into adjusting deflection angle of geometry processing and get back to you--thank you for the suggestion! 

We are exploring the option of having a 'main' model that controls the other sub-models. Perhaps with some sort of box elements bounding the area of the sub-models that can be picked that prompt opening that specific sub-model. Have you seen anything like that done (anyone else out there seen that)? If so, any suggestions on that?

**Comment by martin1cerny** [comment]
It is effectively the same as if you had a set of coordinated models, say one model per floor. That sounds sensible and you can do this with xbim quite easily. I haven't seen it, but that doesn't mean it is not a good idea. 

We will soon send around a next issue of our newsletter where I'm going to share some benchmarks related to deflection angle impact on the rendering quality and size of the resulting triangulated geometry. If you don't receive our newsletter yet, you can [sign up here](https://share.hsforms.com/1IQizWxh-SGCOQ0CQnikEJw3myli).
