### ISSUE TITLE
Drawing lines inside viewer

### ISSUE THREAD

**Issue by HristijanJohn** [xBimTeam/XbimWebUI#343]
Hello,
Is it possible to draw lines inside web viewer canvas if I have 3D start and end coordinates. I am using SVG overlay now, but I want to know if there is any possible way to draw them inside the viewer canvas.  As I can see in the viewpoint.ts class there is array for adding lines, but there isn't any code for implementing drawing of the lines. Any help would be appreciated. 
Thanks
![image](https://user-images.githubusercontent.com/15907845/117953028-09343180-b316-11eb-86a3-62102e269f0c.png)

**Comment by martin1cerny** [comment]
Yes, this is definitely possible. You would need to implement your own `IPlugin` which can be added as `viewer.addPlugin()`. IPlugin is invoked in the rendering pipeline to it can render any 3D objects as part of the view. You can have a look at our `Grid` plugin which is similar as it renders 3D lines as part of the 3D view.
