### ISSUE TITLE
XbimWebUI with React

### ISSUE THREAD

**Issue by fabriziopaolopetrelli** [xBimTeam/XbimWebUI#345]
Hi everyone, 

I want to use this toolkit with **ReactJS**, has someone tried? 
Any advice on how to achieve it?

Thanks.

**Comment by martin1cerny** [comment]
This component is a pure JS (authored in TS) and doesn't have any code specific to ReactJS, Angular or Vue.js. You can use it in the same way as you would use any other JS component.
