### ISSUE TITLE
Possible to split/mark an element into several small ones?

### ISSUE THREAD

**Issue by pml1711** [xBimTeam/XbimWebUI#352]
Hi there, my issue is more like a question that I hope you can help me.
What I would like to do is to be able to segment an entire element into different pieces. For example, I have a large slab that I need to program its production, so what I would like to do is to segment it into three pieces. When I write segment I do not really mean split, but more like mark it and apply a different shade/color for each "piece".
Is that possible to do that? Can you enlighten me?

**Comment by martin1cerny** [comment]
To do this properly, you would actually need to manipulate the geometry of the slab. So, you may use WebUI as an interactive environment to identify cutting lines or profiles. All user interactions will give you 3D point (with limited precision, so you may need to apply some snapping algorithm for points exactly on the surface/corners). Then you would need to go back to IFC or to lower levels of [Xbim Geometry Engine](https://github.com/xBimTeam/XbimGeometry/) to apply the cutting and different styling. You would then reload this into the viewer. 

Or, depending on the desired result, you may implement a plugin which would allow you to simply draw on top of the slab and export it in another format you may want to use for your other tooling.
