### ISSUE TITLE
runtime

### ISSUE THREAD

**Issue by AdnanAhdali** [xBimTeam/XbimWebUI#353]
I would like to ask 2 questions hopefully you will have the time and answer.
  
What algorithms does the software use?
  
How does runtime change with building size / resolution?

**Comment by martin1cerny** [comment]
Hi @AdnanAhdali , I'm not quite sure which algorithms you mean. Feel free to investigate the code to find out anything you want.

Runtime doesn't change the building size or resolution. Resolution is driven by the resolution of the browser.
