### ISSUE TITLE
how to decompose the model by product?

### ISSUE THREAD

**Issue by 376084782** [xBimTeam/XbimWebUI#356]
we have a demand to decompose the model by product
i saw there was some ways to move the model,
but how can i move the product?
please help

**Comment by martin1cerny** [comment]
Can you try to be more specific in what you are trying to achieve? I'm not quite sure how model decomposition by product is related to changed product placement.

**Comment by 376084782** [comment]
Simply,we want to move the target by prodid

**Comment by martin1cerny** [comment]
Do you want to move the camera, or do you want to move it temporarily to highlight it in the view, or do you want to actually change its position in the model?

**Comment by martin1cerny** [comment]
Closing for a lack of feedback. Reopen if needed.
