### ISSUE TITLE
Is there a possibility to set a specific Wall, Door etc to highlighted without a trigger?

### ISSUE THREAD

**Issue by htl-struckll** [xBimTeam/XbimWebUI#357]
My goal is to call a Website from an External program. The Website calls a Webserver to load a wexbim file. That file then is send back and shown on the Website. On the Website a specific Wall, Door, etc should be highlighted. That specific Wall, which should be highlighted, is selected in the external program.

Everything is set up and working (except the highlighting of a specific Model). I can also send the GlobalID or other data via the URL to the Webserver and then to the Website.
I found a lot of examples to highlight Models with onclick triggers or to highlight all IfcWalls but I haven´t found a function or a possibility to Highlight a specific Model without a trigger.

**Comment by martin1cerny** [comment]
Of course, we do this often, for example when analytical results are to be presented to the user. The ID of the entity in webim file is what you can see as `IPersistEntity.EntityLabel` in xbim. And what you can see at the beginning of the line in IFC file:

```
  #36495= IFCDOOR('3j6EBIBH10GfYqbRitzyYR',#47,'Door02',$,'DoorType02',#250324,#36489,'400368',2030.,830.);
     ^
     |
entity label

```
