### ISSUE TITLE
Add typescript to existing javascript project

### ISSUE THREAD

**Issue by jo5zek** [xBimTeam/XbimWebUI#358]
Hello everybody!
i'am a young building engineer and i'am trying to implement XbimWebUI packet ( https://github.com/xBimTeam/XbimWebUI.git ) to my existing ajax project (in microsoft visual studio), but my ajax project doesn't read the typescript. Can someone give me any tips, how can i solve this issue?
Thank you!
jo5zek

**Comment by martin1cerny** [comment]
I'm sorry, but we won't be able to help you with the tooling. In general, you need to set up your development environment for JS/TS/Node development.
