### ISSUE TITLE
Rendering issue (scene flickering when rotate/zoom)

### ISSUE THREAD

**Issue by simiii** [xBimTeam/XbimWebUI#362]
#### Expected behavior:

The model should not flicker when converting to wexbim and show in the WebUI-Viewer

#### Actual behavior or exception details:

The scene is flickering when rotating / zooming. A similar problem was described here #113. The problem resolution described in #113 by disabling the chrome webgl does not help. Also the coordinates in the model seem to be fine and not too big.

Screenshot of the problem:
![Problem-Flickering](https://user-images.githubusercontent.com/5853121/129021681-3e319ccb-e12c-425e-9e48-75952fe2f3bd.gif)

#### Version of the xBIM Viewer:

Backend-Packages used to create the wexbim file (and other stuff):
```
  <package id="Xbim.Common" version="5.1.329" targetFramework="net472" />
  <package id="Xbim.DPoW" version="5.1.179" targetFramework="net472" />
  <package id="Xbim.Essentials" version="5.1.329" targetFramework="net472" />
  <package id="Xbim.Exchange" version="5.1.179" targetFramework="net472" />
  <package id="Xbim.Exchanger" version="5.1.179" targetFramework="net472" />
  <package id="Xbim.Geometry" version="5.1.430" targetFramework="net472" />
  <package id="Xbim.Geometry.Engine.Interop" version="5.1.430" targetFramework="net472" />
  <package id="Xbim.Ifc" version="5.1.329" targetFramework="net472" />
  <package id="Xbim.Ifc2x3" version="5.1.329" targetFramework="net472" />
  <package id="Xbim.Ifc4" version="5.1.329" targetFramework="net472" />
  <package id="Xbim.IO.CobieExpress" version="5.1.146" targetFramework="net472" />
  <package id="Xbim.IO.Esent" version="5.1.329" targetFramework="net472" />
  <package id="Xbim.IO.MemoryModel" version="5.1.329" targetFramework="net472" />
  <package id="Xbim.IO.Table" version="5.1.146" targetFramework="net472" />
  <package id="Xbim.ModelGeometry.Scene" version="5.1.430" targetFramework="net472" />
  <package id="Xbim.PropertySets" version="4.0.1" targetFramework="net472" />
  <package id="Xbim.Tessellator" version="5.1.329" targetFramework="net472" />
```

Frontend NPM Package used:
`"@xbim/viewer": "^2.0.1-pre202103091921",`

#### Minimal code (or steps) to reproduce the issue:
We create the wexbim with the following snippet:
```
var context = new Xbim3DModelContext(ifcStore);
context.CreateContext();
var memStream = new MemoryStream();
using (var wexBimBinaryWriter = new BinaryWriter(memStream, Encoding.Default, true))
 {
 ifcStore.SaveAsWexBim(wexBimBinaryWriter);
 }
 // ... store file 
```

#### Minimal file to reproduce the issue:
[Model.zip](https://github.com/xBimTeam/XbimWebUI/files/6967932/5.00.-.Modell.reduziert.Test.zip)

**Comment by martin1cerny** [comment]
There seems to be something in the model which makes the overall model placement very remote. Also, there seem to be a modelling issue where walls have a 0 thickness layer on top, which is causing additional visual clash:
![image](https://user-images.githubusercontent.com/773078/130424628-c9fbb2a2-6d19-4761-befc-7fa4406ddb0a.png)

**Comment by andyward** [comment]
The v3+ of the wexbim format handles this displacement much better. I think that's because Regions better handle placement around a local WCS root. xbim Flex generates this wexbim output, but I guess there's work to do in `SaveAsWexBim` to handle the same logic.

![image](https://user-images.githubusercontent.com/923699/131818539-48714b3a-794b-4b38-8e37-5f4a35de02be.png)

**Comment by simiii** [comment]
If I become a flex customer - can I use the API to create a wexbim file v3 ?

**Comment by martin1cerny** [comment]
Yes, we use slightly enhanced model processing in Flex platform. It is all based on the Toolkit fundamentals, but slightly reorganised in higher levels.

**Comment by andyward** [comment]
Yes, feel free to drop me a note. You can also try out a few models of your own at https://flexdemo.xbim-dev.net/ and see the v3 wexbim outputs.

**Comment by simiii** [comment]
@andyward @martin1cerny  thanks for the feedback. I am back from holiday and will try out the flexdemo. During the holiday we talked to our customer providing the model and we could resolve the issue. Maybe this will help other users from xbim toolkit to resolve similar issues.

The geographic coordinates are extremely high, as the customer pulled the data with the geographic zero point from the database of the Bavaria Atlas or something similar. This automatically gives you a realistic model of the terrain. However, the zero point is somewhere 500km away. (As with latitude and longitude, there is probably a defined zero point. As a result, the zero point of the project is 500km away, but the only display of the model is the building. I think that agrees with the analysis here.
