### ISSUE TITLE
Implement XbimWebUI into Microsoft Visual Studio 2017

### ISSUE THREAD

**Issue by jo5zek** [xBimTeam/XbimWebUI#363]
Hello everyone!
Can someone explain to me, how can i implement XbimWebUI- project into my existing project in microsoft visual studio 2017? 

i tried to do this instructrion, but this is not working.... :
"Getting Started
To install the viewer into your project as an npm package, just run

npm install @xbim/viewer
If you want to contribute or just play with the code, get the code and run

npm run start
Please note: all the samples in this solution are examples of how to use the Xbim library, and not intended to be used in a production environment without further development."

Best reegards
Jo5zek

**Comment by martin1cerny** [comment]
You can use it in exactly the same way as any NPM package. Please note, that `WebUI` project is only the visualization component. If you want to access and process IFC models, you need to use other xbim Toolkit projects, which are distributed as [NuGet packages](https://www.nuget.org/packages?q=xbim).
