### ISSUE TITLE
getStyle Returns void

### ISSUE THREAD

**Issue by zangyy** [xBimTeam/XbimWebUI#364]

**Comment by zangyy** [comment]
> if **viewer.getStyle()** Returns void
> How do you get it style Index of the defined custom color

**Comment by martin1cerny** [comment]
If you check [the documentation](https://docs.xbim.net/XbimWebUI/classes/_viewer_.viewer.html#getstyle), you will find that this function is used to get current style of a specific product. If you maintain a colour pallet, you need to maintain this in your code.

**Comment by zangyy** [comment]
**viewer.getStyle()**  can I get the current style
because of mine **viewer.getStyle()**  Returned is undefined  How do I get the current style
`console.log(this.viewer.getState(arg.id,arg.model))`  According to documentation , but what I got was undefined

**Comment by martin1cerny** [comment]
You are right, there was a bug. I just pushed a fix.
