### ISSUE TITLE
Viewer.resetState() - old api docs, missing hideSpaces parameter.

### ISSUE THREAD

**Issue by kolmar1991** [xBimTeam/XbimWebUI#365]
Hi,
In the xViewer implementation there was a method resetStates(). It was perfect to go back to the initial state of the model. There is a method resetState in Viewer now. If I invoke this method without parameters it seems to work like old resetStates but with hideSpaces parameter set true. Is it possible to reset a view without showing spaces? The only solution I can find know to go back to the initial state is:
1. Save ids and run resetState for each one.
2. Initialise viewer again.
Both sounds like additional work comparing to old version. Could you please advise?

Best regards,
Marcin

**Comment by martin1cerny** [comment]
It should be enough to make these two calls which is reasonably efficient:

```ts
viewer.resetState();
viewer.setState(State.HIDDEN, ProductType.IFCSPACE);
```

**Comment by kolmar1991** [comment]
Thanks you! It works.
