### ISSUE TITLE
KML/ONJ/GLT

### ISSUE THREAD

**Issue by jo5zek** [xBimTeam/XbimWebUI#371]
Hello again!
I'am very glad to use Xbim as .ifc Viewer, but i miss something here.
Does Xbim read KML/OBJ/GLT data? Or will he read these data in the future? 

If no, than i have question for @martin1cerny - it is possible to "open" the source,so that we can develop the other extension opportunity?

Best regards 
jo5zek

**Comment by martin1cerny** [comment]
Hi @jo5zek , we don't plan to support KML or OBJ files. On the GLTF side we plan to support export from xbim to GLTF, but don't plan to support it in our viewer. Bare in mind, that these formats don't have any semantics, so they don't tend to be very useful in BIM applications. [The source code is completely open already](https://github.com/xBimTeam/XbimWebUI).
