### ISSUE TITLE
Add a fake element to the model 

### ISSUE THREAD

**Issue by klamarth** [xBimTeam/XbimWebUI#372]
Hi,

I would like to add an extra element to the wexbim output file for all models that translate.

For example, I am creating the wexbim for an apartment building and I want to add an object (random shape) below the model, so it will be rendered on the viewer but it is not a real element on the IFC model. The idea in here is to add a building cadastral lot below it. I know this is strange but for testing/research purpose I would like to know the best approach to try this.

About the object to add, it is something similar to this, and I have the geometry for it:
![image](https://user-images.githubusercontent.com/80955361/135369678-83def4a8-5bc1-48b8-b713-98c3b06f7053.png)

Some ideas:
* On the wexbim creation: Seems to be the easiest option for me. But I am not sure on how to add my geometry.
* On the viewer: I believe this is the most difficult as I would need to fake a modelgeometry with the same configuration of a real model
* On the IFC: Add my element to a temp IFC and use this temp IFC to generate the wexbim. This could be good, but I don't know how to create an IfcBuildingProxyElement with my geometry (I have vertices only).

Any idea on the best approach? Any code example on how to create the BuildingProxyElement with my shape?

Cheers,
Klamarth

**Comment by klamarth** [comment]
Sometimes the best way to find a solution is to ask a question in a forum :) then your brain finally find a way to make it work.

I found the solution already, using the wall creation example.

I simple created an IfcGeographicElement and added all X and Z from the cadastral lot multipolygon into an IfcPolyline and it worked like magic. 

```
var polyline = model.Instances.New<IfcPolyline>();

foreach (var pt1 in allPts)
{
    polyline.Points.Add(pt1);
}
```

![image](https://user-images.githubusercontent.com/80955361/135398741-3342d021-e50b-4a30-b2e8-f4350d10d17a.png)

Thanks

**Comment by wong-kene** [comment]
hi @klamarth 

thanks for this thread. i have a requirement almost same with you. but for warehouse not for aprtment. the detail is
- I have an IFC file for warehouse room
- I load it on xbim
- I want to add object (like rack, box and etc) inside room with particular point (koordinate)

Is it posible use your technique?



Thanks in advance
