### ISSUE TITLE
Center camera view

### ISSUE THREAD

**Issue by simiii** [xBimTeam/XbimWebUI#374]
I want to set the camera to center the selected element. The gif of the expected behavior is from the xbim meets angular project from georg dangl. Any best practices how I can achieve this with the current xbim/viewer version in angular?

#### Expected behavior:
The target of the camera can be set with a method in former viewer versions (setCameraTarget), where the camera circles around a selected product.

![Home-Page-xBim-Meets-Angular-Google-Chrome-2021-10-13-15-18-45](https://user-images.githubusercontent.com/5853121/137140930-8fed91de-1f35-4b47-be11-2e75cf4ef31c.gif)

#### Actual behavior or exception details:
The target of the camera cannot be set

#### Version of the xBIM Viewer:
Current master branch

#### Current implementation:

```
    private init() {
        if (!this.viewer) {
            this.viewer = new Viewer('viewer');
            this.viewer.background = [0, 0, 0, 0];
            this.viewer.highlightingColour = [255, 180, 25, 255];
            this.viewer.hoverPickColour = [90, 11, 14, 255];
            this.viewer.adaptivePerformanceOn = false;

            this.viewer.canvas.addEventListener('contextmenu', event => this.onContextMenu(event));
            this.viewer.on('pick', event => this.onPick(event));
            this.viewer.on('loaded', event => this.onLoaded(event));
        }

    // .....

    onPick(event: ViewerInteractionEvent) {
        if (this.disableControl) {
            return;
        }

        if (this.idByRightClick) {
            this.viewer.setState(State.UNDEFINED, [this.idByRightClick]);
            this.idByRightClick = null;
        }

        if (event && event.id) {
            this.viewer.clearHighlighting();
            this.viewer.resetState(this.hiddenElements);
            this.viewer.setState(State.HIDDEN, this.hiddenElements);
            this.viewer.setState(State.HIGHLIGHTED, [event.id]);
            this.idByLeftClick = event.id;

           // .... 
        }
    }
```

**Comment by martin1cerny** [comment]
Available since [this NMP package version](https://www.npmjs.com/package/@xbim/viewer/v/2.0.1-pre202110140921).
