### ISSUE TITLE
transparency 100 percent

### ISSUE THREAD

**Issue by jo5zek** [xBimTeam/XbimWebUI#375]
Hello everyone!
Is it posible to set transparency of 100 %(to make the elements complete invisible), when i select other elements?
Thanks!

![transparency](https://user-images.githubusercontent.com/54819370/145561990-d71d6857-cc8c-4349-b159-20fa1eb52513.png)

**Comment by jomijomi** [comment]
Well, you can perhaps HIDE the element instead? 
```
viewer.setState(State.HIDDEN, [args.id]);
```
Check this example for more information:
https://docs.xbim.net/examples/colourful-building.html

/Mikael

**Comment by martin1cerny** [comment]
Yes, you can either just set the styling to one with 100% transparency, or make it hidden which it would be more efficient and clean.
