### ISSUE TITLE
TS2322: Type 'vec3' is not assignable to type 'Float32Array'.

### ISSUE THREAD

**Issue by dumitrugrl** [xBimTeam/XbimWebUI#377]
I am getting this error when trying to build:

```
ERROR in XbimWebUI\src\model-handle.ts
./src/model-handle.ts 99:8-21
[tsl] ERROR in XbimWebUI\src\model-handle.ts(99,9)
      TS2322: Type 'vec3' is not assignable to type 'Float32Array'.
  Type '[number, number, number]' is not assignable to type 'Float32Array'.
 @ ./src/viewer.ts 6:21-46
 @ ./index.ts 25:13-36
```

Is it a problem with my local packages?

**Comment by martin1cerny** [comment]
I definitely builds on my machine and on the CI build agent. Are you building the latest `master` branch?

**Comment by dumitrugrl** [comment]
Thank you for your fast reply.

Initially I've cloned the master branch using open in Visual Studio. Also, the path I was using had characters like [ - and spaces.

For my second attempt, I downloaded the zip into a shorter path and after the `npn install`,  the `npm run build` completed with no errors.

I appologize for wasting your time.

**Comment by martin1cerny** [comment]
That's fine. We used to use VS for the development of this component but it is a pure JS/TS project now. So, you only need NPM to build and run.
