### ISSUE TITLE
How to retrieve a model's origin base coordinate?

### ISSUE THREAD

**Issue by pml1711** [xBimTeam/XbimWebUI#379]
Hi there, this is more like a "how to" question. 
Is there a way to retrieve each model's origin base coordinate? To make myself clear, when you export an IFC from Revit, for example, you can choose the Project Base Point as Coordinate Base. So, How do I retrieve this coordinate from each model loaded?

**Comment by martin1cerny** [comment]
Revit translates this to `IfcSite` coordinate.
