### ISSUE TITLE
Cancel clipping after enabled it (red line visible)

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#38]
Hello,
I would like to know which method could be used to cancel the clipping action when we have the red line shown up (before cutting the model), so that the red line disappeared. I tried the unclip() but it could not do the trick.
thanks

**Comment by johnBim** [comment]
Hello,
Please could someone help with this? I am a bit blocked in my schedule.

Thank you in advance.

**Comment by martin1cerny** [comment]
unclip() only does what it says. It cancels the clip, not the selection operation. There is not a function to do this. Also it seems like a rather strange scenario to me. But if you do want to do this you can remove the overlaying SVG canvas which actually contains the red line and handles the click action.If you remove it before user clicks it won't essentially do anything to the model. It should be the last child of document.

**Comment by johnBim** [comment]
Hello Martin,
Thank you, I will try that.

regards

**Comment by johnBim** [comment]
Hello Martin,
yeah basically the removal only of the red line (svg canvas) don't do the whole trick since the events are still bound to the DOM. 
So if the red line is removed from DOM and I click just after that the model, the clipping is still fired up and cut the model.
any help on how I can also unbind the specific events from outside?

thanks in advance

**Comment by martin1cerny** [comment]
I've just added a function 
```js
viewer.stopClipping()
```
which you can use to stop interactive clipping before it's finished.

**Comment by johnBim** [comment]
Hello Martin,
Thank you I will get your last commit.

thank again
