### ISSUE TITLE
Possible setting zooming/clipping action sensitivities 

### ISSUE THREAD

**Issue by jean-fr** [xBimTeam/XbimWebUI#39]
Hello,
I would like to know if there is a possibility there to set the sensitivity of the zooming on dragging/clipping functionalities. I mean precision on moving action.

Thank you

**Comment by johnBim** [comment]
Hello,
Please could someone help with this? I am a bit blocked in my schedule.

Thank you in advance.

**Comment by martin1cerny** [comment]
No, sensitivity is fixed now. You would have to change [this](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L811) function. There is already an attempt to be sensitive based on distance but it is not the best.

**Comment by johnBim** [comment]
Well I see, I will check that.

regards

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It has much better user navigation based on the actual 3D point of interaction.
