### ISSUE TITLE
Select the surface of the product on the viewer, not the entire product

### ISSUE THREAD

**Issue by AlienwareBoy** [xBimTeam/XbimWebUI#390]
Hello, I met a scene where I need to associate the surface of the product with the data. When I click the page, I can only select a product. I don't know how to call the API to get the surface of the product

**Comment by AlienwareBoy** [comment]
I want to get the geometric information of the surface of the product clicked by the mouse (point, line, etc.)

**Comment by martin1cerny** [comment]
You do get 3D coordinates from all user interactions. This is an example of what you get from `viewer.on('pick', args => console.log(args))`

![image](https://user-images.githubusercontent.com/773078/170454638-468ecb77-51c3-4c9f-b8a4-5248c5b59f27.png)

**Comment by klamarth** [comment]
This will return the point only (X,Y,Z) but I believe he needs a triangle to get its normal and discover the surface, right?

**Comment by martin1cerny** [comment]
The issue is that triangles and sub-surfaces don't have any identity. So, even if you get it, there isn't any identifier to keep the association. You would have to go back to IFC file and change fundamental structure so make part of the surface an independent product representation.

**Comment by andyward** [comment]
Close until we get a better use case for this
