### ISSUE TITLE
Generate Json from xBIM

### ISSUE THREAD

**Issue by krosoftware** [xBimTeam/XbimWebUI#393]
Hello
I have JSON file generated from IFC file, but there is no all attributes inside. 
For example, missing are some Allplan Element ID properties.
If it is not possible to store all properties to XML, Is there any way to get all properties for clicked IFC object (without storing IFC to XML)?
Thank you.

**Comment by martin1cerny** [comment]
Your best option is to develop an API where you will retrieve the data in the shape you like. You might also be aware that we have developed a commercial platform on top of the Toolkit, which makes it a lot easier to develop web applications with BIM functionality. We already have a feature rich REST API for serving data as well as scalable geometry processing in the cloud.

**Comment by krosoftware** [comment]
OK thanks, already solved with mr. @SteveLockley
