### ISSUE TITLE
Display specific floor

### ISSUE THREAD

**Issue by krosoftware** [xBimTeam/XbimWebUI#396]
Hello
is there some example of how to get all floors and display (for example) second floor only?
Thank you.

**Comment by martin1cerny** [comment]
You need to go to the IFC model, get the floor and get it's top and bottom height. Then you can use two clipping planes in the viewer to show just that floor. Note you will need to apply some offsets to both top and bottom to make it look OK.

**Comment by krosoftware** [comment]
Great idea, as usual.
If you find this useful for other people, maybe you can make some quick example for xBim doc's? 😉

**Comment by martin1cerny** [comment]
You are most welcome to contribute with the sample code.
