### ISSUE TITLE
Is it possible to change a color of wall (or any object of wexbim image) in X-ray Mode?

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#40]
I want to change color of wexbim images in X-ray mode.Is it possible

**Comment by boosterwu** [comment]
yes,it's posible to change that. you can just modify the xbim-viewer.debug.js and find "this.highlightingColour = [255, 173, 33, 255]" , this will effect not only in x-ray mode but also in double clicked event and the other global highlighting color.

**Comment by martin1cerny** [comment]
Exactly, you can do so with [this](http://xbimteam.github.io/XbimWebUI/xViewer.html#highlightingColour). The overall colour of x-ray mode is hardwired into vertex shader but it might be made configurable if necessary. It is normalized colour (0.0, 0.0, 0.3, 0.5) now.

**Comment by BIMDevelopement** [comment]
Sorry , But I was not able to change color. I need to change HIGHLIGHTED property color. I was referred latest file of vertex_shader.c also . In that file , 
	//get base color or set highlighted colour
		vec4 baseColor = state == 253 ? uHighlightColour : getColor();

This line may be used for Highlighted a color object .
Can you please give me some more details about this ,How I can change the color of HIGLIGHTED ?

**Comment by martin1cerny** [comment]
If you only want to change highlighted property you just [set it in the viewer](http://xbimteam.github.io/XbimWebUI/xViewer.html#highlightingColour):
```js
viewer.highlightingColour = [255, 173, 33, 255];
```
It will take direct effect as any time. You don't need to mess around with shader. That was just as a note for the case you wanted to change overall x-ray colour.

**Comment by BIMDevelopement** [comment]
Okay Martin.
Thanks .
I will try it.
