### ISSUE TITLE
How To Highlight the different portions of wexbim files [Floors,Walls,etc]

### ISSUE THREAD

**Issue by umarone** [xBimTeam/XbimWebUI#405]
Hi Sir,
          I want to highlight the different portion of wexbim file.  suppose when I select walls from ifc structure  then the walls of wexbim file should be highlighted, when I select floors from ifc structure then the floors should be highlighted. 

Example image is attached from Open Ifc Viewer.

![HelpForHighlighting](https://user-images.githubusercontent.com/100139624/204242552-12e3e174-07d7-4188-bb71-50745077673d.png)

**Comment by andyward** [comment]
A couple of different ways:
```
// Highlight all walls in the current highlight
viewer.setState(State.HIGHLIGHTED, ProductType.IFCWALL,1);

// Set Floor slabs to style 0
viewer.setStyle(0, ProductType.IFCSLAB,1);

```

For more examples see this demo: https://docs.xbim.net/examples/colourful-building.html


In the above example it looks like most objects in the mode are 'BuildingElementProxys' - where each item is given a Type. So in this case you'll need to identify the elements belonging to a type (e.g. DiningTable type), and then select the instances. e.g.

`viewer.setState(State.HIGHLIGHTED, [instanceIds],1);`

**Comment by umarone** [comment]
viewer.setState(State.HIGHLIGHTED, [instanceIds],1);

what is instanceIds means here

**Comment by umarone** [comment]
> A couple of different ways:
> 
> ```
> // Highlight all walls in the current highlight
> viewer.setState(State.HIGHLIGHTED, ProductType.IFCWALL,1);
> 
> // Set Floor slabs to style 0
> viewer.setStyle(0, ProductType.IFCSLAB,1);
> ```
> 
> For more examples see this demo: https://docs.xbim.net/examples/colourful-building.html
> 
> In the above example it looks like most objects in the mode are 'BuildingElementProxys' - where each item is given a Type. So in this case you'll need to identify the elements belonging to a type (e.g. DiningTable type), and then select the instances. e.g.
> 
> `viewer.setState(State.HIGHLIGHTED, [instanceIds],1);`

Sir where is mean by InstanceIds Here

**Comment by umarone** [comment]
> 

In my case entitylabel is 358095 for eachline but GlobalId is available instead which is unique for everyline.
moreover if you can paste some code, I will be thankful to you.

**Comment by martin1cerny** [comment]
Server side:

```cs
[HttpGet]
[Route("/dining-tables")]
public IActionResult GetDiningTables()
{
    var instanceIds = model.Instances
        .Where<IIfcBuildingElementProxy>(p => p.IsTypedBy.Any(r => r.RelatingType.Name == "DiningTable"))
        .Select(p => p.EntityLabel);
  return JsonResult(instanceIds);
}
```

Client side:
```js
viewer.setState(State.HIGHLIGHTED, [instanceIds],1);
```
