### ISSUE TITLE
Reading Proper Spatial Structure of Ifc File

### ISSUE THREAD

**Issue by umarone** [xBimTeam/XbimWebUI#407]
Hi Sir,
          Can anyone share the proper code for reading structure of large ifc files for every Ifc file....

Moreover i want to ask is OpenIFcViewer is open source ?

**Comment by umarone** [comment]
Please sir @martin1cerny can give proper code for reading spatial structure of ifc file according to tree structure

**Comment by andyward** [comment]
Have you seen: https://docs.xbim.net/examples/spatial-hierarchy.html ?

**Comment by umarone** [comment]
> Have you seen: https://docs.xbim.net/examples/spatial-hierarchy.html ?

Sir I have seen this but consider the following line 
var project = model.Instances.FirstOrDefault<IIfcProject>();
This line is given for 1 record only in file but i have to read all the file data. if you can provide me your source code or sample.ifc file if you have please.

**Comment by umarone** [comment]
> Have you seen: https://docs.xbim.net/examples/spatial-hierarchy.html ?

sir if you can see my another issue #406 please

**Comment by andyward** [comment]
Answered on #406 where I provided link to the code example on XbimSamples repo
