### ISSUE TITLE
Spatial Structure just reads The Three(3) Lines Then breaks.

### ISSUE THREAD

**Issue by umarone** [xBimTeam/XbimWebUI#408]
Hi Everyone,
                        I am following the code example for reading the spatial structure of IFC file but code reads only three lines then exist from recursive function. Built in 'SampleHouse.ifc' file is ok but other files are not completely read.

I am trying following link please..

https://docs.xbim.net/examples/spatial-hierarchy.html

please if someone can help, please do so..

@martin1cerny  and @andyward  please help

**Comment by umarone** [comment]
Sir I have debug the code There is no exception thrown. It simply quits the block and function . I am attaching the file you please see it. sir please u try this file with print heirarchy function then u will see it is reading only three records

[ModernDiningRoom.zip](https://github.com/xBimTeam/XbimWebUI/files/10173051/ModernDiningRoom.zip)

**Comment by andyward** [comment]
I definitely advise debugging this yourself. There's nothing especially clever going on in that code - it just traverses some relationships (in this case the `IfcRelContainedInSpatialElement` relationships from the IfcProject down, and lists the entities that Decompose the spatial element.  That's just one way of going down the tree. There are others..

In this case you have a unusual model without any Levels or Spaces, and instead have a single IfcElementAssembly, which itself can be decomposed. You just need to decompose the entities themselves.

Take a look at the model in xbimXplorer to better understand the relationships

![image](https://user-images.githubusercontent.com/923699/206188590-51f4b577-c2f0-42c4-b3ea-d037f4947d5f.png)

**Comment by umarone** [comment]
Sir I have debugg the code myself but as i told you that spatial heirarchy code just shows 3 records like

ifcproject -> IfcBuilding -> IfcModerningDinningRoom

after that it quits the traverses operation and spatial structure is not read properly..

what is your advice now.

**Comment by andyward** [comment]
You need something like:
```csharp
        private static void PrintElementHierarchy(IIfcProduct element, int level )
        {
            // Print the product
            Console.WriteLine(string.Format("{0}   -> {1} [{2}] #{3}", GetIndent(level), element.Name, element.GetType().Name, element.EntityLabel));
            // using IfcRelAggregates to get sub-elements in a product
            foreach (var subItem in element.IsDecomposedBy.SelectMany(d => d.RelatedObjects).OfType<IIfcProduct>())
            {
                // Print any child products
                PrintElementHierarchy(subItem, level + 1);
            }
        }
```
which you call from the main `PrintHierarchy()` loop when you have products

See https://dotnetfiddle.net/nx5uyp (note dotnetFiddle doesn't seem to have enough RAM to load your model, but you can see the same element breakdown on `Curtain Wall:Curtain_Wall-Exterior_Glazing:285582 [IfcCurtainWall] #2375`) in the SampleModel.

`PrintElementHierarchy()` is the new bit you were missing. 

Ultimately you need to understand/explore the IFC schema to build a hierarchy that makes sense to you usecase. There's no single right way. Hence why most apps let users choose the grouping structure.

**Comment by umarone** [comment]
Thankx Sir,
                     Today morning I have solved the problem successfully... 

Thankx too much for supporting me on each step..
