### ISSUE TITLE
Can anyone give me code for structure reading

### ISSUE THREAD

**Issue by umarone** [xBimTeam/XbimWebUI#409]
Hi all,
             can anyone give me his / her code for reading spatial structure of IFC file

Regards

**Comment by jomijomi** [comment]
If you mean reading the spatial structure of an IFC-file using xBIM (Essential + Geometry), you can look at the example/tutorial at:
[https://docs.xbim.net/examples/spatial-hierarchy.html](url)

/Mikael

**Comment by andyward** [comment]
Duplicates #408
