### ISSUE TITLE
3d model issue in Chrome and FF

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#41]
Hello,
On one of our computers with Windows 10, the latest versions of FF and Chrome we have these issues:
1- Chrome, the model doesn't display and in the console we have a list of errors as seen in the attachment: 

2- FF, no model is shown and no errors in console of the browser

Please could someone advise on these situations, what could be the issues there?

thanks in advance.
chrome issue
![chrome_bim_issue](https://cloud.githubusercontent.com/assets/12897988/10219946/8dd047e0-6843-11e5-81f9-216a7f712dbd.jpg)

FF issue
![ff_bim_issue](https://cloud.githubusercontent.com/assets/12897988/10219947/8dd460c8-6843-11e5-833b-e3d2a9317e5b.jpg)

**Comment by martin1cerny** [comment]
Could go to (this)[http://alteredqualia.com/tmp/webgl-maxparams-test/] website and post here results from that computer? I realized there is a change I've made recently which requires one more vertex texture unit and it might be a problem on some GPU low spec devices. I'll switch it back tomorrow.

**Comment by johnBim** [comment]
Hello Martin,
here we go.

For chrome:

WebGL MAX parameters support

                     Max Vertex Attributes: 16
                       Max Varying Vectors: 9

                Max Vertex Uniform Vectors: 254
              Max Fragment Uniform Vectors: 221

          Max Fragment Texture Image Units: 16
            Max Vertex Texture Image Units: 4
          Max Combined Texture Image Units: 20

                       Max 2D Texture Size: 8192
                     Max Cube Texture Size: 8192

                    Max Texture Anisotropy: 16

                          Point Size Range: 1 - 256
                          Line Width Range: 1 - 1

                   Max Viewport Dimensions: 8192 - 8192
                     Max Renderbuffer Size: 8192

                      Framebuffer Red Bits: 8
                    Framebuffer Green Bits: 8
                     Framebuffer Blue Bits: 8
                    Framebuffer Alpha Bits: 8

                    Framebuffer Depth Bits: 24
                  Framebuffer Stencil Bits: 8
                 Framebuffer Subpixel Bits: 4

                              MSAA Samples: 1
                       MSAA Sample Buffers: 1

Supported Formats for UByte Render Targets     : RGBA RGB   
Supported Formats for Half Float Render Targets: RGBA RGB   
Supported Formats for Full Float Render Targets: RGBA RGB   

       Max Multiple Render Targets Buffers: 0

     High Float Precision in Vertex Shader: 23 (-2127 - 2127)
   Medium Float Precision in Vertex Shader: 23 (-2127 - 2127)
      Low Float Precision in Vertex Shader: 23 (-2127 - 2127)

   High Float Precision in Fragment Shader: 23 (-2127 - 2127)
 Medium Float Precision in Fragment Shader: 23 (-2127 - 2127)
    Low Float Precision in Fragment Shader: 23 (-2127 - 2127)

       High Int Precision in Vertex Shader: 0 (-224 - 224)
     Medium Int Precision in Vertex Shader: 0 (-224 - 224)
        Low Int Precision in Vertex Shader: 0 (-224 - 224)

     High Int Precision in Fragment Shader: 0 (-224 - 224)
   Medium Int Precision in Fragment Shader: 0 (-224 - 224)
      Low Int Precision in Fragment Shader: 0 (-224 - 224)

                      Supported Extensions: ANGLE_instanced_arrays
					    EXT_blend_minmax
					    EXT_frag_depth
					    EXT_shader_texture_lod
					    EXT_texture_filter_anisotropic
					    WEBKIT_EXT_texture_filter_anisotropic
					    OES_element_index_uint
					    OES_standard_derivatives
					    OES_texture_float
					    OES_texture_float_linear
					    OES_texture_half_float
					    OES_texture_half_float_linear
					    OES_vertex_array_object
					    WEBGL_compressed_texture_s3tc
					    WEBKIT_WEBGL_compressed_texture_s3tc
					    WEBGL_debug_renderer_info
					    WEBGL_debug_shaders
					    WEBGL_depth_texture
					    WEBKIT_WEBGL_depth_texture
					    WEBGL_lose_context
					    WEBKIT_WEBGL_lose_context

                            WebGL Renderer: WebKit WebGL
                              WebGL Vendor: WebKit
                             WebGL Version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
                  Shading Language Version: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)

                         Unmasked Renderer: ANGLE (Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0)
                           Unmasked Vendor: Google Inc.

**Comment by johnBim** [comment]
For FF:


WebGL MAX parameters support

                     Max Vertex Attributes: 16
                       Max Varying Vectors: 9

                Max Vertex Uniform Vectors: 254
              Max Fragment Uniform Vectors: 221

          Max Fragment Texture Image Units: 16
            Max Vertex Texture Image Units: 4
          Max Combined Texture Image Units: 20

                       Max 2D Texture Size: 8192
                     Max Cube Texture Size: 8192

                    Max Texture Anisotropy: 16

                          Point Size Range: 1 - 256
                          Line Width Range: 1 - 1

                   Max Viewport Dimensions: 8192 - 8192
                     Max Renderbuffer Size: 8192

                      Framebuffer Red Bits: 8
                    Framebuffer Green Bits: 8
                     Framebuffer Blue Bits: 8
                    Framebuffer Alpha Bits: 8

                    Framebuffer Depth Bits: 24
                  Framebuffer Stencil Bits: 8
                 Framebuffer Subpixel Bits: 4

                              MSAA Samples: 0
                       MSAA Sample Buffers: 0

Supported Formats for UByte Render Targets     : RGBA RGB   
Supported Formats for Half Float Render Targets: RGBA RGB   
Supported Formats for Full Float Render Targets: RGBA RGB   

       Max Multiple Render Targets Buffers: 0

     High Float Precision in Vertex Shader: 23 (-2127 - 2127)
   Medium Float Precision in Vertex Shader: 23 (-2127 - 2127)
      Low Float Precision in Vertex Shader: 23 (-2127 - 2127)

   High Float Precision in Fragment Shader: 23 (-2127 - 2127)
 Medium Float Precision in Fragment Shader: 23 (-2127 - 2127)
    Low Float Precision in Fragment Shader: 23 (-2127 - 2127)

       High Int Precision in Vertex Shader: 0 (-224 - 224)
     Medium Int Precision in Vertex Shader: 0 (-224 - 224)
        Low Int Precision in Vertex Shader: 0 (-224 - 224)

     High Int Precision in Fragment Shader: 0 (-224 - 224)
   Medium Int Precision in Fragment Shader: 0 (-224 - 224)
      Low Int Precision in Fragment Shader: 0 (-224 - 224)

                      Supported Extensions: ANGLE_instanced_arrays
					    EXT_blend_minmax
					    EXT_color_buffer_half_float
					    EXT_frag_depth
					    EXT_shader_texture_lod
					    EXT_texture_filter_anisotropic
					    OES_element_index_uint
					    OES_standard_derivatives
					    OES_texture_float
					    OES_texture_float_linear
					    OES_texture_half_float
					    OES_texture_half_float_linear
					    OES_vertex_array_object
					    WEBGL_color_buffer_float
					    WEBGL_compressed_texture_s3tc
					    WEBGL_depth_texture
					    WEBGL_lose_context
					    MOZ_WEBGL_lose_context
					    MOZ_WEBGL_compressed_texture_s3tc
					    MOZ_WEBGL_depth_texture

                            WebGL Renderer: Mozilla
                              WebGL Vendor: Mozilla
                             WebGL Version: WebGL 1.0
                  Shading Language Version: WebGL GLSL ES 1.0

                         Unmasked Renderer: null
                           Unmasked Vendor: null

**Comment by martin1cerny** [comment]
Right, this is it. I'll change it tomorrow back and it should solve your problem. Next time you might want to listen to [error](http://xbimteam.github.io/XbimWebUI/xViewer.html#event:error) event to see what is [wrong](http://xbimteam.github.io/XbimWebUI/tutorial-2_Safe_Hello_building.html).

**Comment by johnBim** [comment]
Thank you for help.
regards

**Comment by martin1cerny** [comment]
I've just switched the code back to use less textures. It didn't improve performance anyway as far as I checked. Let me know if it helps please.

**Comment by johnBim** [comment]
Hello Martin,
Thank you I will check it and let you know asap.

thank again

**Comment by johnBim** [comment]
Hello Martin,
Thanks everything works again.

regards
