### ISSUE TITLE
Convert Ifc To DWG drawing with Xbim Toolkit

### ISSUE THREAD

**Issue by umarone** [xBimTeam/XbimWebUI#415]
Hi Everyone,
                     How we can convert Ifc file into 2D DWG file.Is it possible in xbim Toolkit. if anyone can help would be highly appreciated please..

Regards

**Comment by krosoftware** [comment]
@umarone did you found a way?

**Comment by klamarth** [comment]
It's not straightforward, but you can do an edge projection of all elements on a specific storey using an orthographic view. This will create a 2D floor plan. It's not a DWG file, it doesn't contain dimensions or annotations, but it gives a general idea of the floor's layout.

Then you can overlay this representation over the model or you could save it, maybe even as a DWG but you would need to study the DWG format and implement it.

Something like this:

![image](https://user-images.githubusercontent.com/80955361/208532455-a5c28dd7-76ad-48cb-b171-7958e433d3a7.png)

**Comment by andyward** [comment]
> maybe even as a DWG but you would need to study the DWG format and implement it.

Once you've got a 2D projection you may be able to use a DWG library such as [ACadSharp](https://github.com/DomCR/ACadSharp) which should make the task a bit easier.

**Comment by krosoftware** [comment]
I see, thanks @klamarth and @andyward
