### ISSUE TITLE
Extracting Floor Plans from Ifc File

### ISSUE THREAD

**Issue by umarone** [xBimTeam/XbimWebUI#416]
Hi all,
            can we extract or make floor plans directly from Ifc file.

Regards

**Comment by andyward** [comment]
Didn't you already ask this: https://github.com/xBimTeam/XbimWebUI/issues/402

**Comment by umarone** [comment]
> Didn't you already ask this: #402

Yes sir, It was same, so sir what u suggest how we can do it, can we purchase any service please to achieve the floor plans into svg from ifc file

**Comment by martin1cerny** [comment]
Closing as duplicate of #402.
