### ISSUE TITLE
How to create XBimModel from .xBim binary file?

### ISSUE THREAD

**Issue by minhnguyenlinknode** [xBimTeam/XbimWebUI#42]
Hi,

I know how to create an instant of XBimModel from .ifc file. 
But I don't know how to create an instant of XBimModel from .xBim binary file? 

Something like this:
  var model = new Xbim.IO.XbimModel();
  model.CreateFrom(xBimFile,....);

The reason is my IFC file is very big then it takes ages to create instant of XBimModel in the first time then I don't want to parse IFC file everytime. Therefore I think I should parse the .xBim instead in the second time as it should be faster than IFC text format.

Any ideas?

**Comment by martin1cerny** [comment]
You are right, you shouldn't parse it again. XBim file is a database with an instant access. Just call

    model.Open(database)

**Comment by martin1cerny** [comment]
@minhnguyenlinknode: Can I close this issue?

**Comment by andyward** [comment]
Dupe. Also answered in xBimTeam/XbimEssentials#9
