### ISSUE TITLE
Scrolling for zoom is not working

### ISSUE THREAD

**Issue by untecnologo** [xBimTeam/XbimWebUI#435]
I get this error whenever I scroll into the canvas.

![image](https://github.com/xBimTeam/XbimWebUI/assets/37328540/89c20395-5937-406b-bf22-bae986fe36fa)

I can grab the model and move it but as soon as I scroll I get this issue.

Thank you in advance for the help.

**Comment by andyward** [comment]
Which version of the library? Can you clarify by what you're doing when scrolling? (e.g. right-click drag, scrolling the mouse wheel, left-click pan mode?)

If you click the first index.js link in the stacktrace it should take you to the line with the error, which may help

**Comment by untecnologo** [comment]
I am so sorry It was a problem with a Div it was overlapping the Canvas. Totally a bug created by me.
