### ISSUE TITLE
[Question] I need to zoom back to previous state

### ISSUE THREAD

**Issue by cuong-nguyen** [xBimTeam/XbimWebUI#454]
Hi, I am new to the library and not sure what to do. I have a model which contains building (with doors, windows,...) I want to be able to select any of them and then zoom in on them which I can achieve. But now I need to go back to previous state before zooming (on a button clicked). Can you share how would I do that?

Before zoom
<img width="331" alt="Screenshot 2024-07-22 at 17 24 54" src="https://github.com/user-attachments/assets/bfee7aa2-6892-401a-8fcb-19ecfc364536">

After zoom (click on yellow part above)
<img width="322" alt="Screenshot 2024-07-22 at 17 25 27" src="https://github.com/user-attachments/assets/c3514b1e-1ca2-41ce-b672-c7e5194ad61f">

Thanks.

**Comment by andyward** [comment]
You should check out `Viewpoint.GetViewpoint()` and `Viewpoint.SetViewpoint()` as documented [here](https://docs.xbim.net/XbimWebUI/classes/Viewpoint.html). There's a working example [here ](https://github.com/xBimTeam/XbimWebUI/blob/199def52d6235b250df5b30707c93fe163196bef/examples/basic-viewer/index.ts#L99)

Essentially this creates a BCF representation of the current state of model, which can be used to restore the viewer state later. As it's just a JSON structure you can store the viewpoint however you like before recalling it.

**Comment by cuong-nguyen** [comment]
Thank you for a quick reply.
I should have mentioned that I am still on the `xViewer` not the latest Viewer (I have to maintain the app) and Viewpoint does not exist. Is it possible to achieve same thing with xViewer?

**Comment by andyward** [comment]
You should just be able to store and recall the matrix/camera settings to achieve something similar. I think they were called _mvMatrix_ and _pMatrix_ on the `xViewer`

**Comment by cuong-nguyen** [comment]
> You should just be able to store and recall the matrix/camera settings to achieve something similar. I think they were called _mvMatrix_ and _pMatrix_ on the `xViewer`

Appreciate it. I will give it a try.
