### ISSUE TITLE
quick question about color of sharder

### ISSUE THREAD

**Issue by dozwu** [xBimTeam/XbimWebUI#46]
How to handle the colors of the objects in 3D diagram that xBIM WebUI draws.
eg. A type of wall => red , B type of wall => yellow , C type of wall => blue.

**Comment by martin1cerny** [comment]
The functionality for custom coloring of the elements is described in [this tutorial](http://xbimteam.github.io/XbimWebUI/tutorial-5_Colourful_building.html). You will additionally have to select respective walls by their types which you can easily do either from JSON semantic data or from the IFC model on your server.

**Comment by boosterwu** [comment]
got it,by the way each  color of elements in the xbim WebUI are refined on bim design time or xbim just random a color to draw the element ?

**Comment by martin1cerny** [comment]
It is defined in design time and saved in IFC. We only assign default representation style to the objects which don't have a style defined in IFC.

**Comment by boosterwu** [comment]
thank you for your quick answers.

**Comment by martin1cerny** [comment]
[Here](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.Ifc/IfcStore.cs#L958) is a lead to how we translate IFC style and how we get [default](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.Ifc/IfcStore.cs#L964) style based on the type.
