### ISSUE TITLE
How to hide whole image?

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#47]
We are using HIDDEN property to hide a particular object of wexbim image by providing an Id of that object.
So, Can you tell me ,Is any possibility to hide all image .

**Comment by martin1cerny** [comment]
I can't imagine why you would want to show an empty scene but to do it I'd just hide whole canvas element hosting the xViewer.

**Comment by adam9000** [comment]
Martin...

Hidden the whole scene (with performance) as a step to show only some elements, in a collision/detection type-situation.

It's very slow to individually hidden all of then, in other to show only elements that one need to pay attention.

**Comment by adam9000** [comment]
...unless, of course, you use the xBimWebUI only with tiny little models.

But in real world, one can have a model with 30.000 elements in a arch model, 10.000 in a plums model... 5.000 in a elech model, and so on, on a federated view...easily.

**Comment by martin1cerny** [comment]
If you only need to show a few elements, you can use `viewer.isolate()` function. Documentation [here](https://docs.xbim.net/XbimWebUI/classes/_viewer_.viewer.html#isolate). This will not just set the visibility flag, but will skip all the rest.

**Comment by adam9000** [comment]
How can I miss that?!? Sorry...

Work just fine! We do need to stop another models in cases where more than one is loaded into viewer, but that's the easy part...

Thank you @martin1cerny
