### ISSUE TITLE
Enumerating Products in Model

### ISSUE THREAD

**Issue by jtanadi** [xBimTeam/XbimWebUI#471]
Hi xBim Web UI developers! I'm writing to ask some questions about the API.

First, if I would like to get or create a list of all the product IDs in my model, what is the best way to do that? Also is it possible to get a list of all the product IDs with a certain Product Type? I was expecting some sort of `viewer.getProducts()` method, but I wasn't able to find anything like that. My ad-hoc workaround is essentially:
```javascript
const l = Object.keys(ProductType).length/2;
const productsByType = {};

viewer.resetState(ProductType.IFCSPACE);

for (let i = 0; i < l; i++) {
  let k = Object.keys(ProductType)[i + 173];
  viewer.addState(State.HIDDEN, ProductType[k]);
  productsByType[k] = viewer.getProductsWithState(State.HIDDEN);
  viewer.resetState(ProductType[k]);
}

viewer.addState(State.HIDDEN, ProductType.IFCSPACE);
```
Then I could iterate through the `productsByType` object if I need to compile every product ID in the model.

Second, I'm unclear as to where the product ID is coming from. I've been using the `SampleHouse.wexbim` file, so I haven't generated my own wexbim file from an IFC file, but my guess is that the product IDs are not related to the IFC GUIDs. Is there a way for the wexbim model to have either the GUIDs or element names that were defined in the original IFC file? Is this possible with the .NET Toolkit? I am essentially trying to see if it's possible to refer to the same elements either by ID or name across an IFC file and a wexbim file via that Web UI.

Thank you!

**Comment by martin1cerny** [comment]
Hi @jtanadi . The answer to your second question actually answers the first question. These IDs are related to the entity label in IFC file/model (i.e. `#456` ). You can access these as `entity.EntityLabel` when using `Xbim.Essentials` to open the model. From there, you can get all the products (`model.Instances.OfType<IfcProduct>()`), their type and everything else.

**Comment by jtanadi** [comment]
Thank you!
