### ISSUE TITLE
How to set style as Transparent

### ISSUE THREAD

**Issue by yangshuyi** [xBimTeam/XbimWebUI#473]
#### Expected behavior:
I am now trying to transparent other elements to highlight a specified element. Like below screenshot the highlight red ceiling element.

I try to invoke setStyle with a color array: [128, 128, 128, 64] for other element except the highlighted one.
the highlight color I set is [255, 0, 0, 255]. 
But find all elements get transparent, and the highlight red ceiling also lost its red color. 

I expect to show the whole red ceiling in view. 

![{507D9F77-959A-466E-BA8E-34B0AC3C8860}](https://github.com/user-attachments/assets/6cf8c591-5bd6-4de5-8689-fc33410e3ab5)

Can anyone help me how to implement the transparent effect.

#### Version of the xBIM Viewer:
2.1.0-pre202409212148

#### Minimal file to reproduce the issue:
The wexbim file I used is: SampleHouse.wexbim

**Comment by andyward** [comment]
Have you tried using the 'Ultra_Xray' rendering model? You can combine with with styles - essentially it ensures the highlighted elements are rendered last / top-most in z-order.  

e.g. something like

``` js
// Use Xray Ultra mode and set the default xray color
viewer.xrayColour = [128, 128, 128, 64];
viewer.renderingMode = RenderingMode.XRAY_ULTRA;

var redStyle = 10;
viewer.defineStyle(redStyle, [255, 0, 0, 255]);

// on picked...
var pickedElementIds = 1234; // Or whatever picked ID
// set Style to red
viewer.setStyle(redStyle, [pickedElementIds ]);
// set to appear topmost in xray mode
viewer.addState(State.XRAYVISIBLE, [pickedElementIds ]);
```

**Comment by yangshuyi** [comment]
> Have you tried using the 'Ultra_Xray' rendering model? You can combine with with styles - essentially it ensures the highlighted elements are rendered last / top-most in z-order.
> 
> e.g. something like
> 
> ```js
> // Use Xray Ultra mode and set the default xray color
> viewer.xrayColour = [128, 128, 128, 64];
> viewer.renderingMode = RenderingMode.XRAY_ULTRA;
> 
> var redStyle = 10;
> viewer.defineStyle(redStyle, [255, 0, 0, 255]);
> 
> // on picked...
> var pickedElementIds = 1234; // Or whatever picked ID
> // set Style to red
> viewer.setStyle(redStyle, [pickedElementIds ]);
> // set to appear topmost in xray mode
> viewer.addState(State.XRAYVISIBLE, [pickedElementIds ]);
> ```

**Comment by yangshuyi** [comment]
It works. Thanks a lot.
