### ISSUE TITLE
Content does not load on chrome / Firefox on Android

### ISSUE THREAD

**Issue by AlainBolduc** [xBimTeam/XbimWebUI#48]
Under Android 6 on a nexus 5, 

On chrome, the live demo at 
http://xbimteam.github.io/XbimWebUI/1_Hello_building.live.html does not load any content. (In the canvas).

Under Firefox, it crashes the browser.

Are mobile browsers supposed to be supported?  

Thanks

FYI, the following is a partial view of chrome://version

Google Chrome   46.0.2490.76 (Official Build) (32-bit)
Revision    56034b7e9233e7f8b0890dcd45094695a41082aa-refs/branch-heads/2490@{#528}
OS  Android 6.0.0; Nexus 5 Build/MRA58K

**Comment by martin1cerny** [comment]
Hi @AlainBolduc,

WebUI is supposed to work on mobile devices. However, we didn't test many of them and there is no touch navigation implemented in the main development branch so far. It works under Chrome on my LG Optimus L9 which is not not a high-end device at all. 

But it as it utilises HW accelerated graphics it is HW dependant. Can you try to go to [this](http://alteredqualia.com/tmp/webgl-maxparams-test/) site from your nexus 5 both using Chrome and Mozilla and send the report back here? I'll try to have a look if it breaks any minimal requirements I'm aware of.

It shouldn't crash the browser at all. That would rather mean a bug in the browser. I saw WebGL application to crash my computer completely in the early days of WebGL support but browser was to be blamed in these cases. It should well sandbox any application running inside.

**Comment by AlainBolduc** [comment]
Hi, here is the report for chrome

*WebGL MAX parameters support*

Max Vertex Attributes: *16* Max Varying Vectors: *16* Max Vertex Uniform
Vectors: *256* Max Fragment Uniform Vectors: *224* Max Fragment Texture
Image Units: *16* Max Vertex Texture Image Units: *16* Max Combined Texture
Image Units: *32* Max 2D Texture Size: *4096* Max Cube Texture Size: *4096*
Max Texture Anisotropy: *16* Point Size Range: *1 - 1023* Line Width Range: *1
- 8* Max Viewport Dimensions: *4096 - 4096* Max Renderbuffer Size: *4096*
Framebuffer Red Bits: *8* Framebuffer Green Bits: *8* Framebuffer Blue
Bits: *8* Framebuffer Alpha Bits: *8* Framebuffer Depth Bits: *24*
Framebuffer Stencil Bits: *8* Framebuffer Subpixel Bits: *4* MSAA Samples:
*4* MSAA Sample Buffers: *1* Supported Formats for UByte Render Targets : *RGBA
RGB *Supported Formats for Half Float Render Targets: *RGBA RGB *Supported
Formats for Full Float Render Targets: *RGBA *Max Multiple Render Targets
Buffers: *0* High Float Precision in Vertex Shader: *23 (-2**127** - 2**127*
*)* Medium Float Precision in Vertex Shader: *23 (-2**127** - 2**127**)*
Low Float Precision in Vertex Shader: *23 (-2**127** - 2**127**)* High
Float Precision in Fragment Shader: *23 (-2**127** - 2**127**)* Medium
Float Precision in Fragment Shader: *10 (-2**15** - 2**15**)* Low Float
Precision in Fragment Shader: *10 (-2**15** - 2**15**)* High Int Precision
in Vertex Shader: *0 (-2**31** - 2**31**)* Medium Int Precision in Vertex
Shader: *0 (-2**31** - 2**31**)* Low Int Precision in Vertex Shader: *0 (-2*
*31** - 2**31**)* High Int Precision in Fragment Shader: *0 (-2**31** - 2*
*31**)* Medium Int Precision in Fragment Shader: *0 (-2**15** - 2**15**)*
Low Int Precision in Fragment Shader: *0 (-2**15** - 2**15**)* Supported
Extensions: *ANGLE_instanced_arrays*
* EXT_blend_minmax*
* EXT_sRGB*
* EXT_texture_filter_anisotropic*
* WEBKIT_EXT_texture_filter_anisotropic*
* OES_element_index_uint*
* OES_standard_derivatives*
* OES_texture_float*
* OES_texture_half_float*
* OES_texture_half_float_linear*
* OES_vertex_array_object*
* WEBGL_compressed_texture_atc*
* WEBKIT_WEBGL_compressed_texture_atc*
* WEBGL_compressed_texture_etc1*
* WEBGL_debug_renderer_info*
* WEBGL_debug_shaders*
* WEBGL_lose_context*
* WEBKIT_WEBGL_lose_context* WebGL Renderer: *WebKit WebGL* WebGL Vendor:
*WebKit* WebGL Version: *WebGL 1.0 (OpenGL ES 2.0 Chromium)* Shading
Language Version: *WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)*
Unmasked Renderer: *Adreno (TM) 330* Unmasked Vendor: *Qualcomm*

And for Firefox

WebGL MAX parameters support

                     Max Vertex Attributes: 16
                       Max Varying Vectors: 16

                Max Vertex Uniform Vectors: 256
              Max Fragment Uniform Vectors: 224

          Max Fragment Texture Image Units: 16
            Max Vertex Texture Image Units: 16
          Max Combined Texture Image Units: 32

                       Max 2D Texture Size: 4096
                     Max Cube Texture Size: 4096

                    Max Texture Anisotropy: 16

                          Point Size Range: 1 - 1023
                          Line Width Range: 1 - 8

                   Max Viewport Dimensions: 4096 - 4096
                     Max Renderbuffer Size: 4096

                      Framebuffer Red Bits: 8
                    Framebuffer Green Bits: 8
                     Framebuffer Blue Bits: 8
                    Framebuffer Alpha Bits: 8

                    Framebuffer Depth Bits: 24
                  Framebuffer Stencil Bits: 8
                 Framebuffer Subpixel Bits: 4

                              MSAA Samples: 0
                       MSAA Sample Buffers: 0

Supported Formats for UByte Render Targets     : RGBA RGB
Supported Formats for Half Float Render Targets: RGBA RGB
Supported Formats for Full Float Render Targets:

       Max Multiple Render Targets Buffers: 0

     High Float Precision in Vertex Shader: 23 (-2127 - 2127)
   Medium Float Precision in Vertex Shader: 23 (-2127 - 2127)
      Low Float Precision in Vertex Shader: 23 (-2127 - 2127)

   High Float Precision in Fragment Shader: 23 (-2127 - 2127)
Medium Float Precision in Fragment Shader: 10 (-215 - 215)
    Low Float Precision in Fragment Shader: 10 (-215 - 215)

       High Int Precision in Vertex Shader: 0 (-231 - 231)
     Medium Int Precision in Vertex Shader: 0 (-231 - 231)
        Low Int Precision in Vertex Shader: 0 (-231 - 231)

     High Int Precision in Fragment Shader: 0 (-231 - 231)
   Medium Int Precision in Fragment Shader: 0 (-215 - 215)
      Low Int Precision in Fragment Shader: 0 (-215 - 215)

                      Supported Extensions: ANGLE_instanced_arrays
    EXT_blend_minmax
    EXT_color_buffer_half_float
    EXT_frag_depth
    EXT_sRGB
    EXT_texture_filter_anisotropic
    OES_element_index_uint
    OES_standard_derivatives
    OES_texture_float
    OES_texture_float_linear
    OES_texture_half_float
    OES_texture_half_float_linear
    OES_vertex_array_object
    WEBGL_color_buffer_float
    WEBGL_compressed_texture_atc
    WEBGL_compressed_texture_etc1
    WEBGL_depth_texture
    WEBGL_lose_context
    MOZ_WEBGL_lose_context
    MOZ_WEBGL_compressed_texture_atc
    MOZ_WEBGL_depth_texture

                            WebGL Renderer: Mozilla
                              WebGL Vendor: Mozilla
                             WebGL Version: WebGL 1.0
                  Shading Language Version: WebGL GLSL ES 1.0

                         Unmasked Renderer: null
                           Unmasked Vendor: null

**Comment by martin1cerny** [comment]
Right, this doesn't break any limits so it must be something else. Can you try to have a look in console if there are any JS errors? It should also be possible to [debug JS from Android on your desktop](https://developer.chrome.com/devtools/docs/remote-debugging) which will be far more convenient. [Here] (http://stackoverflow.com/questions/2314886/how-can-i-debug-javascript-on-android) is also discussion about how to debug JS on Android. I'd recommend to follow [this tutorial] (http://xbimteam.github.io/XbimWebUI/tutorial-2_Safe_Hello_building.html) to check for a minimal requirements to make sure everything is all right. But it should be from what I saw in the report. Also try to listen to [error](http://xbimteam.github.io/XbimWebUI/xViewer.html#event:error) event in case something goes wrong. Let me know if you find what is causing the failure please. I'll fix it ASAP after that.

**Comment by AlainBolduc** [comment]
Hi Martin,

After digging around, I found that I get some warnings that says :

xbim-viewer.debug.js:654 WebGL: INVALID_OPERATION: useProgram: program not valid
2xbim-viewer.debug.js:654 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
xbim-model-handle.debug.js:224 Uncaught Too much data! It cannot fit into the texture.xModelHandle._bufferTexture @ xbim-model-handle.debug.js:224xModelHandle.feedGPU @ xbim-model-handle.debug.js:174geometry.onloaded @ xbim-viewer.debug.js:574br.onloaded @ xbim-model-geometry.debug.js:224fReader.onloadend @ xbim-binary-reader.debug.js:28

I have set a breakpoint where this error is thrown (line 675), and it happens that  
gl.getParameter(gl.MAX_TEXTURE_SIZE); returns null. 

Let me know if you want me to do more testing for you. We are looking into integrating the web viewer in a new product, and we would really make it work with your components.

Alain

**Comment by martin1cerny** [comment]
We use textures to pass in all the geometry data at once and we only render them after that. It makes it capable of handling large model with high level of detail with good responsiveness. 

From your log it seems like texture is too big but `gl.getParameter(gl.MAX_TEXTURE_SIZE);` should never return null. It might return 0 which would mean it doesn't support textures at all. But that is clearly not the case looking at the stats you had sent before. It should return 4096 as in the stat. 

The sample model from [tutorial](http://xbimteam.github.io/XbimWebUI/1_Hello_building.live.html) is reasonably small so it shouldn't be a problem unless you have other application running on GPU using almost all its memory. GPU is a shared resource and once it gets overloaded by many applications OS might decide to cut all applications off (hence CONTEXT_LOST_WEBGL). Do you run other apps at the same time?

When you have a breakpoint  on line 675 could you try in console what this call returns: `gl.isContextLost()`? I wonder if context gets lost before or after that. Furthermore could you confirm the NuGet version of WebUI you use and which files you reference please?

Thanks 

Martin

**Comment by AlainBolduc** [comment]
I am using your very own example located at:

http://xbimteam.github.io/XbimWebUI/1_Hello_building.live.html

No other application is running on the device. 

gl.isContextLost() returns true when getting at line 675.

I remote debugged step by step , and context gets lost inside InitShaders, when doing this:

    if (!gl.getProgramParameter(this._shaderProgram, gl.LINK_STATUS)) {
        this._error('Could not initialise shaders ');
    }
GetProgramParameter returns false, then webGL loses context. 

I tried commenting everything in initShaders() and at the end I saw a grey rectangle, and a javascript error, saying that (obviously) "No shaders are available", but Context was never lost.

I also tried to use only one of the 2 shaders, but it did not work (I have absolutely zero knowledge with gl / shaders stuff, so I was kind of shooting in the dark!)

Let me know if I can do anything else to help you debugging this issue!

**Comment by martin1cerny** [comment]
You do need to have both shaders to create complete rendering pipeline as there is no default shader in WebGL. 

This is very interesting issue and I'd really like to solve it. It means that the context loss is caused by our code but I've never seen this before even that our WebUI attracted some attention and there are people out there using it. Not sure how many use it on desktop and how many use it on mobile devices. 

I'm sorry for a stupid question but did you check if the context is lost before and after this operation? If this is true, could you try to comment out just this one check? Also can you confirm that both shaders get compiled without an error [here](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Build/xbim-viewer.debug.bundle.js#L1587)? 

I've also updated a tutorial to use the latest develop version of the viewer as we made some changes recently. But that wasn't fixing any bug but dropping some changes which caused some low-end devices to stop rendering the scene because they were not able to handle enough textures. But that is definitely not your case as your device can handle up to 16 textures where we only used 5 (it is 4 now). So check it again please in case the latest code just works.

**Comment by AlainBolduc** [comment]
Hi Martin,

Yes I have tried to call IsContextLost before / after this function. It is really this function that makes the context go away.

I subscrbed to the error event as you suggested, like this:
`viewer.on("error", function(args){console.error(args)})`
at the beginning of initShaders. 

A few answers to your questions:

- The shaders compiled correctly. No errors reported.
- GetProgramParameter makes the context go away, but does not throw an error. 
The only error I get is "Could not initialise shaders", which is thrown when checking the return value of GetProgramParameter...

- As I told you before, I am not using my own web page to display a viewer. I am using your demo, located at xbimteam.github.io/XbimWebUI/1_Hello_building.live.html . I tried it again this morning and it is still not working.

Thank you very much for your time, we really want to make it work to use your component in our product.

**Comment by martin1cerny** [comment]
Hi Alain,

Thanks for all the answers. I'd really like to help you so you could use our viewer for your product. Could you try to call `gl.getError()` before and after the context is lost? I wonder if there is some error before which would cause lost context. It should return numbers representing this enum:
```c
const GLenum NO_ERROR                       = 0;
const GLenum INVALID_ENUM                   = 0x0500;
const GLenum INVALID_VALUE                  = 0x0501;
const GLenum INVALID_OPERATION              = 0x0502;
const GLenum OUT_OF_MEMORY                  = 0x0505;
```
Also could you try to get a local copy and comment out this check 
```js
if (!gl.getProgramParameter(this._shaderProgram, gl.LINK_STATUS)) {
    this._error('Could not initialise shaders ');
}
```
for the case it is actually causing the problem itself (even it shouldn't)?

Martin

**Comment by AlainBolduc** [comment]
Until gl.linkProgram(this._shaderProgram) is called, I can call gl.getError(), and it always returns 0.

 

Ater gl.linkProgram(..) is called, if I call gl.getError(), it still returns 0, but I get a CONTEXT_LOSt_WEBGL warning in the javascript console.

 

Then when I call gl.getError() again, I get error code 37442 (0x9242), which is indeed CONTEXT_LOST_WEBGL 

 

I already tried commenting these lines. If I do, it crashes in UseProgram

 

WebGL: INVALID_OPERATION: useProgram: program not valid

WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

 

De : Martin Černý [mailto:notifications@github.com] 
Envoyé : Wednesday, November 4, 2015 3:20 AM
À : xBimTeam/XbimWebUI <XbimWebUI@noreply.github.com>
Cc : Alain Bolduc <alain.bolduc@bimone.com>
Objet : Re: [XbimWebUI] Content does not load on chrome / Firefox on Android (#48)

 

Hi Alain,

Thanks for all the answers. I'd really like to help you so you could use our viewer for your product. Could you try to call gl.getError() before and after the context is lost? I wonder if there is some error before which would cause lost context. It should return numbers representing this enum:

const GLenum NO_ERROR                       = 0;
const GLenum INVALID_ENUM                   = 0x0500;
const GLenum INVALID_VALUE                  = 0x0501;
const GLenum INVALID_OPERATION              = 0x0502;
const GLenum OUT_OF_MEMORY                  = 0x0505;

Also could you try to get a local copy and comment out this check 

if (!gl.getProgramParameter(this._shaderProgram, gl.LINK_STATUS)) {
    this._error('Could not initialise shaders ');
}

for the case it is actually causing the problem itself (even it shouldn't)?

Martin

**Comment by martin1cerny** [comment]
Right, this is completely weird. I'll think about it if I can come with some suggestions/questions.

**Comment by martin1cerny** [comment]
Is this issue still alive @AlainBolduc ?

**Comment by AlainBolduc** [comment]
Hi @martin1cerny , I just tried using the develop branch and the problem is still there.

Thanks

**Comment by AlainBolduc** [comment]
Hi @martin1cerny , our friend @fomayette found the problem and got this fixed in pull request #104 

Thanks

**Comment by martin1cerny** [comment]
Thanks a lot. I'll merge it into the main code soon. This kind of contribution to xBIM is highly appreciated of course. 

Martin

**Comment by gijskoning** [comment]
When will touch be implemented?

**Comment by martin1cerny** [comment]
We don't do too much of active development on WebUI unless it is a part of some project. If you have a look to the source code implementation of touch navigation is not very complicated. Feel free to contribute.

**Comment by martin1cerny** [comment]
Touch navigation is now implemented in `develop` branch thanks to great contribution of @GeorgDangl.

**Comment by MarcoGiorgi** [comment]
I'd like to know if the examples that can be found on the xBIM pages have been updated to the latest version because from my Samsung Galaxy S7 in Chrome, I can't see the demo at http://xbimteam.github.io/XbimWebUI/1_Hello_building.live.html

Should I have to download and use the develop branch to give mobile support, or the master has been updated?

Thanks and congratulation for the excellent work!

**Comment by martin1cerny** [comment]
Our implementation requires floating point texture support. While it used to be available on 95% of devices in past, the support dropped rapidly last year when many Android devices stopped to support this extension in WebGL1 in favour of native support in WebGL2. That is most likely the problem.

**Comment by MarcoGiorgi** [comment]
Pretty sad. It was a really nice and impressive feature to see 3D rendering on tablets.
Do you plan to work on it? Is it something feasible or it needs a complete refactoring? (I could also try to get some sponsor to implement it)

**Comment by martin1cerny** [comment]
It is not general for all tablets. You can see [these stats](https://webglstats.com/webgl/extension/OES_texture_float) to get a picture of the coverage. It doesn't require complete refactoring but we don't have dedicated resources for this task at the moment.

**Comment by SBRK** [comment]
I ran in the same problem on GS8 and GS7. A solution would be packing float textures into byte textures.
