### ISSUE TITLE
Is it possible to show 2D schema?

### ISSUE THREAD

**Issue by boosterwu** [xBimTeam/XbimWebUI#49]
I would like to show 2D by floors, is there any way to show them using xbim toolkits?

**Comment by martin1cerny** [comment]
No, there is no such a functionality at the moment. It is more complex than you might think. What you can do as a simplification is to set a specific view ([top, left, ...](http://xbimteam.github.io/XbimWebUI/xViewer.html#show)) and use [programmatic clipping plane](http://xbimteam.github.io/XbimWebUI/tutorial-4_Building_seen_from_everywhere.html) to reveal what you want to show. You can [switch](http://xbimteam.github.io/XbimWebUI/xViewer.html#camera) to use [orthogonal camera](http://xbimteam.github.io/XbimWebUI/xViewer.html#orthogonalCamera) (default is perspective).

If you wanted to create proper 2D drawings you would have to use specific symbols for different features. You would also have to take into account many conditions and priorities in visualization where features overlap in the view. You would also have to create hatchings for some of the areas and you would have to consider generalization of some parts. It is all doable but not in our current scope. If you wanted to implement it we would be more than happy to take it on board.

Martin
