### ISSUE TITLE
How to convert a .json file to .wexbim or .ifc file to .wexbim ?

### ISSUE THREAD

**Issue by dhundaleamol** [xBimTeam/XbimWebUI#5]
I am using a XbimWebUI source .But i have problem in Conversion of .json file to .wexbim file in this source.
I have uploaded a .ifc file in my project and I want to convert this file into .wexbim file.Can you please tell me , how to be done this conversion either .ifc to .wexbim or .json to .wexbim? .

**Comment by martin1cerny** [comment]
You need to convert IFC to wexbim and JSON. If you get the latest code of XbimExchange project it contains Xbim.Exchanger command line application which does all the conversions in one go.

**Comment by dhundaleamol** [comment]
Thank you Martin .I found a conversion of ifc to.wexbim.

I am trying to merge a conversion code into my project (ie Program.cs of
XbimExchange project)

But now I get this error as follows:
*Method 'get_GeometryManager' in type 'Xbim.IO.XbimModel' from assembly
'Xbim.IO, Version=2.4.1.28, Culture=neutral, PublicKeyToken=null' does not
have an implementation.*

Can you please guide me to process further.

Thanks & Regards,

Amol Dhundale

On Mon, Mar 9, 2015 at 7:35 PM, Martin Černý <notifications@github.com>
wrote:

> You need to convert IFC to wexbim and JSON. If you get the latest code of
> XbimExchange project it contains Xbim.Exchanger command line application
> which does all the conversions in one go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/5#issuecomment-77858818>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
I'm sorry Amol but I haven't seen this kind of error before. Please, make sure you are using the *same versions of DLLs* as we use in XbimExchange project (these should also be the latest ones).

**Comment by dhundaleamol** [comment]
Hey Martin ,

I have resolved that error but now I occur a exception
(ieSystem.IO.FileLoadException': {"Could not load file or assembly
'Xbim.Geometry.Engine' or one of its dependencies. The parameter is
incorrect. (Exception from HRESULT: 0x80070057
(E_INVALIDARG))":"Xbim.Geometry.Engine"})

I have tried a lot but I am not able to resolve it. Can you suggest me any
solution .

On Tue, Mar 10, 2015 at 4:22 PM, Martin Černý <notifications@github.com>
wrote:

> I'm sorry Amol but I haven't seen this kind of error before. Please, make
> sure you are using the *same versions of DLLs* as we use in XbimExchange
> project (these should also be the latest ones).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/5#issuecomment-78031709>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
What kind of deployment do you use? Geometry engine is somehow special because it is written in C++ and it uses native C++ library on the background. For that reason it cannot be compiled for "Any CPU" which is the most sensible if you don't want to compile your application for different architectures. So it loads either x86 or x64 geometry engine in runtime based on the actual architecture. Just make sure these are present on the place where your application runs. It should be in a subdirectory "x86" and "x64". Only problem we had is that automated webdeploy for Azure webjobs doesn't copy subdirectories over so you need to copy it manually.

**Comment by dhundaleamol** [comment]
Thanx  Martin ..

Problem is solved . You can close this issue.
