### ISSUE TITLE
Error: Uncaught RangeError: byte length of Float32Array should be a multiple of 4 (xbim-binary-reader.debug.js:77)

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#51]
Hello,
In my application, I am loading a new model. Conversion to wexbim went etc... But I have an issue while loading it with the js framework (please see the attachment)
![xbim-binary-reader_debug_issue](https://cloud.githubusercontent.com/assets/12897988/11243005/bace2c8e-8e05-11e5-9c1a-17ea40892148.PNG)

If you want I can send you the  wexbim file itself so you can test it as well on your side.

Thanks in advance

**Comment by martin1cerny** [comment]
Hi John,

WexBIM file might be useful. Which version of XbimExchange do you use to generate wexBIM file? Version 3.1.12-V0010 fixed a minor but fatal bug where version of wexBIM file wasn't changed even if the content did. xViewer can handle it but it has to know it is a new version.

Martin

**Comment by johnBim** [comment]
Hello, I have updated the Xbim.Essential to 3.1.10 and it works now.
Thanks

**Comment by johnBim** [comment]
Hello Martin,
I have noticed that if I load a wexbim file that have bigger size (e.g. 6MB) the Xviewer become very slow for navigation. do you have any idea about?
Could you please provide me with your PM so i can send you the current wexbim file I have?

Thank you in advance

**Comment by martin1cerny** [comment]
Hi Jean,

this is unrelated to this GitHub issue thread. Please open another one.

I'll have a look but it shouldn't be a problem with this size of model. Make sure you don't have any heavy weighted handlers attached to the xViewer.

Martin

**Comment by johnBim** [comment]
Hello Martin,

Thank I will double check that.

 

Regards,

Jean
