### ISSUE TITLE
objects with label=0

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#52]
hello,
We realised that the label, which xviewer uses to select an object in the model, is not unique.
we have converted two projects and there are many elements with label =0. 
How the viewer deals with that?

thanks in advance

**Comment by martin1cerny** [comment]
Hi Jean,

not sure how you did the conversion but label is always unique within single project. This is a rule as the original IFC file would be invalid otherwise. Label is used internally within one IFC file to store object references.

If you want to use xViewer with multiple models at the same time it is possible to renumber the objects within these models before you create wexBIM file. That would create unique labels for all of them. But be careful while doing so as it is used in xBIM database as a key.

But it is doable. It just depends on the workflow you need to support.

Martin

**Comment by johnBim** [comment]
Hi Martin
Thank you for your response

We load the ifc metadata into our database using the method you have in  XbimXplorer

 List<IXbimViewModel> svList = new List<IXbimViewModel>();
 XbimModel model = new XbimModel();
 var success = model.CreateFrom(myModelPath, null, null, true);
 IfcProject project = model.IfcProject;
            if (project != null)
            {
                svList.Add(new XbimModelViewModel(project, null));
                foreach (var child in svList)
                {
                    LazyLoadAll(child);
                }
            }
 private static void LazyLoadAll(IXbimViewModel parent)
        {
            foreach (var child in parent.Children)
            {
                LazyLoadAll(child);
            }
        }

Now we loop through each IXbimViewModel in the svList  (recursive children) and save them into our database as flat rows.
for label we have this var label =  o.EntityLabel

The problem is that IXbimViewModel.EntityLabel is default value (zero) sometime.

Any idea?
Or what is the best way to extra the data using your framework?

Regards

**Comment by martin1cerny** [comment]
My only idea is that you don't set it in your IXbimViewModel implementation. EntityLabel is guaranteed to have a value of positive integer. In terms of data retrieval it depends on what you want to get. If you are interested just in one type of objects this is the most common code:
```c#
//concrete type
var walls = model.Instances.OfType<IfcWall>();
//using abstract supertype to get all products (walls, doors, windows, ...)
var products = model.Instances.OfType<IfcProduct>();
//using condition to get only some of the objects
var specialDoors = model.Instances.Where<IfcDoor>(d => r.Name == "Special");
```
If  you want to make sure all entity labels are non-zero values you can try this simple test:
```c#
foreach(var instance in model.Instances)
{
    if (instance.EntityLabel <= 0) throw new Exception("Something is wrong here");
}
```

**Comment by johnBim** [comment]
Thanks Martin
After further analysis, it seems objects with Label =0 are items which  are parents and do have children. example: Building=>floors => 1Floor==>doors==>door1.  Doors, floors have label =0. but door1 does have label non zero

So, it is not an issue. We can leave with that

Thanks again

**Comment by martin1cerny** [comment]
So again, doors and floors from your example are not IFC objects but your view model objects which don't have any IFC equivalent so it has nothing to do with xBIM or IFC.
