### ISSUE TITLE
Does'nt seem to detect staircases and elevation in Navigate function

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#54]
i have implemented walk functionality in xbim. but it does'nt seem to detect staircases and elevation..it just goes straight ..whearas it should walk up or down the stairs.....also the frame rates of the transitions are very low..giving a choppy walking experience 

I have used the following code for that in viewer.debug.js
 if (front) {
            navigate('zoom', topvalue, topvalue);
        }
        else if (Back) {
            navigate('zoom', -topvalue * viewer.scrollSpeed, -topvalue * viewer.panSpeed);
        }
        if (left) {
            navigate('orbit', -5 * viewer.panSpeed, 0);
            //   navigate('pan', 2 * viewer.panSpeed, 0);
        }
        else if (right) {
            navigate('orbit', 5 * viewer.panSpeed, 0);
            //  navigate('pan', -2 * viewer.panSpeed, 0);
        } else if (stable) {
            viewer.navigationMode = 'orbit';
        }

**Comment by martin1cerny** [comment]
I'm sorry @BIMDevelopement  but I don't understand what is the issue you are rising here. As long as this is your very own implementation I'm afraid I'm not able to help you. Is the transition also slow using the original built-in navigation? How do you compute heading and navigation on the stairs? How do you compute elevation of the camera?

**Comment by BIMDevelopement** [comment]
actually i want to have the walk functionality exactly as in solibri ifc model viewer.... the walk functionality i have implemented does'nt detect any elevation or slope and it just goes straight through the object (ex: stairs) ..can you please help me with the code ..so that i can have a walking feature in the bim model that is exactly like solibri

**Comment by martin1cerny** [comment]
Well, as you've just said. If you navigate forward viewer will do exactly what you ask it for. It doesn't have any notion of the objects or what they are. It is not a game engine so there is no collision detection or anything like that. 

To be able to navigate on a stairs you need to get the geometry and compute the exact trajectory on the stair plus some spatial buffer for that. This is definitely not easy to do as visualization geometry is just bunch of triangles. There is an information about the type of object so it is easy to detect you are within the bounding box of the stair. You might than try to approximate the level difference using the size of bounding box and difference between two floors (not sure how you compute the initial view elevation but you can do the same for the 2nd and other levels). But I should warn you that it might be potentially very computing intensive to search for all stairs which you might have entered in every step so you should introduce some kind of spatial indexing (like [Quadtree, Octree](https://en.wikipedia.org/wiki/Spatial_database) or other). 

In terms of overall performance you need to bear in mind that web is still very limited environment compared to full desktop application even if WebGL is HW accelerated.

**Comment by benjymous** [comment]
One cheap trick to detect the floor is to do a z render to a small temporary buffer with a camera pointing directly down, then sample pixels around your "feet" to work out where the obstacles are.

**Comment by martin1cerny** [comment]
Thanks @benjymous , that is a nice one for @BIMDevelopement .

**Comment by BIMDevelopement** [comment]
Is there any way to have game mode navigation in bim model... (AWDS for moving directions, mouse for view angle)

**Comment by martin1cerny** [comment]
Simple answer is yes, there is a way to have it. If you combine what you have now with @benjymous suggestion above you have it done.

**Comment by BIMDevelopement** [comment]
in my present walking scheme ..whenever i turn left or right , or move forward.. the frame rates drop significantly ..giving a laggy walk experience
this issue does'nt occur at all when i pan or rotate the bim model...then it is perfectly smooth..it only creeps in when i get into walk mode

**Comment by BIMDevelopement** [comment]
I got @benjymous  concept , but i have doubt in how can camera detect floor ,stair etc ..and how i can render z camera position .
xViewer.prototype.setCameraTarget = function (prodId) {
    var viewer = this;
    var setDistance = function (bBox) {
        if (vfalg == 1) {
            var size = Math.max(bBox[3], bBox[4], bBox[5]) - 0.8;
        } else {
            var size = Math.max(bBox[3], bBox[4], bBox[5]);
        }
        var ratio = Math.max(viewer._width, viewer._height) / Math.min(viewer._width, viewer._height);
        viewer._distance = size / Math.tan(viewer.perspectiveCamera.fov * Math.PI / 360.0) * ratio * 1.2;
    }


    //set navigation origin and default distance to the product BBox
    if (typeof (prodId) != 'undefined' && prodId != null) {
        //get product BBox and set it's center as a navigation origin
        var bbox = null;
        for (var i in this._handles) {
            var map = this._handles[i].getProductMap(prodId);
            if (map) {
                bbox = map.bBox;
                break;
            }
        }
        if (bbox) {
            this._origin = [bbox[0] + bbox[3] / 2.0, bbox[1] + bbox[4] / 2.0, bbox[2] + bbox[5] / 2.0];
            // this._origin = [bbox[0] + bbox[3] / 8.0, bbox[1] + bbox[4] / 8.0, bbox[2] + bbox[5] / 2.0];
            setDistance(bbox);
            return true;
        }
        else
            return false;
    }
        //set navigation origin and default distance to the most populated region from the first model
    else {
        //get region extent and set it's center as a navigation origin
        var handle = this._handles[0];
        if (handle) {
            var region = handle.region
            if (region) {
                this._origin = [region.centre[0], region.centre[1], region.centre[2]]
                setDistance(region.bbox);

            }
        }
        return true;
    }
};...where do i need to make modifications ..pls suggest

**Comment by LloydPickering** [comment]
@benjymous suggestion will require you to mess around with WebGL. You won't be able to use the Viewer's camera, you will need to setup another one of your own.

Rendering to a buffer can be found at http://learningwebgl.com/blog/?p=1786

I warn you that WebGL (and 3D Graphics programming in general) isn't simple.

In terms of performance, depending on how the camera is setup, certain transformations will require more processing than others. You can help by rate-limiting how often those events are firing so it doesn't get firehosed with complex math.

**Comment by BIMDevelopement** [comment]
can you please review my code in the previous comment and suggest me places of improvement ..as i am not an expert in 3d graphics programming

**Comment by martin1cerny** [comment]
As @LloydPickering has said already. This is not about improving your current code. You will need to develop new WebGL functionality.

**Comment by BIMDevelopement** [comment]
Okay @martin1cerny  . Thanx all. I will try to fix it.
