### ISSUE TITLE
How can I get the EntityLabel in the XbimWebUI just as is done in XbimWindowsUI?

### ISSUE THREAD

**Issue by soniagagliardi** [xBimTeam/XbimWebUI#55]
I'm new in Xbim, and I have to get the EntityLabel of each selected element in the  XbimWebUI project because I need to obtain the geometry and coordinates.
I have seen that in XbimWindowsUI project the EntityLabel is showed in the tab Object.

Is it possible to retrieve  that also  in the web project ?

**Comment by martin1cerny** [comment]
Hi @soniagagliardi ,

yes it is possible. Please, check the [documentation](http://xbimteam.github.io/XbimWebUI/). What you need is to listen to various [events](http://xbimteam.github.io/XbimWebUI/tutorial-3_Eventful_building.html) raised by the viewer.

**Comment by soniagagliardi** [comment]
Hi @martin1cerny , thank you for your reply. I already understand how work  the viewer but i have to  retrieve a data of object selected in the viewer .ie properties and attributes (EntityLabel) in the  code behind c#. 
I use page aspx and not html page.

**Comment by martin1cerny** [comment]
Than you should raise an issue in [XbimEssentials](https://github.com/xBimTeam/XbimEssentials) @soniagagliardi , not here. Your original question was about EntityLabel and coordinates. Now you talk about retrieving properties in C# (web technology used for this is irrelevant). Simple first lines would be like this:
```c#
var product  = model.Instances[entityLabel] as IfcProduct;
var propertyRelations = product.IsDefinedBy.OfType<IfcRelDefinesByProperties>();
var propertySets = propertyRelations.Select(pr => pr.RelatingPropertyDefinition);
var properties = propertySets.SelectMany(ps => ps.HasProperties);
```
But as I've said already. This is not a topic for XbimWebUI project.

**Comment by soniagagliardi** [comment]
My problem it's own retrieve entityLabel when click on element in viewer, then use it in the code

var product  = model.Instances[entityLabel] as IfcProduct;


I hope it was more understandable.

**Comment by martin1cerny** [comment]
I'm sorry but I can't see any complication here. You get the EntityLabel on your page and than send it to your server, retrieve any information you need about the product and send it back to client to present it to your user in some nice way. For smaller project you can also use built in functionality you can see when you get the source code of XbimWebUI and run it in VisualStudio. That uses JSON COBie data extracted from IFC file to present properties and spatial hierarchy.

**Comment by soniagagliardi** [comment]
I can get all the properties and attributes (external Id, name, type) except EntityLabel.
This code in my page aspx  that runs when I pick on the viewer:

                    var properties;
		    var attributes;

		    browser.on("entityActive", function (args) {		                    
		       properties = args.entity.properties;
		       attributes = args.entity.attributes;               
		    });

		    xBrowser.prototype.activateEntity = function (id) {
		        alert("activateEntity");
		        if (!this._model) return;          
		        var entity = this._model.getEntity(id);                
		        if (!entity) return;		      
		        this._fire('entityActive', { entity: entity });		        
		    };

		    xBrowser.prototype._fire = function (eventName, args) {
		        var handlers = this._events[eventName];
		        if (!handlers) {
		            return;
		        }
		        //call the callbacks
		        for (var i in handlers) {
		            handlers[i](args);
		        }
		    };

		    viewer.on("pick", function (arg) {		        
		        var span = document.getElementById("labelcoords");
		        var labelX = document.getElementById("labelX");
		        var hidden = document.getElementById("HiddenFieldID");
		        if (span) {           		            
		            span.textContent = arg.id;
		            hidden.value = arg.id;		            
		        }		       
		        browser.activateEntity(arg.id);
		    });

Where I'm wrong?

**Comment by martin1cerny** [comment]
Right, I see. So this is not a C# code behind. But client-side Javascript. Guess what [xVisualEntity.id](http://xbimteam.github.io/XbimWebUI/xVisualEntity.html#id) is? Yes, that is EntityLabel. That is why `browser.activateEntity(arg.id);` is being called with this `id`.

**Comment by soniagagliardi** [comment]
arg.id (External Id) and EntityLabel  have two different values.

If I use arg.id in the 

var product  = model.Instances[entityLabel] as IfcProduct;

product  will be null.

Example:

Name: Sea-Level1:Sea-Level:662315
External Entity: IfcBuildingElementProxy
External Id: 	805415
Entity Label:  #626685

**Comment by martin1cerny** [comment]
I'm sorry but this is not possible. It is granted that `id` you capture from xViewer is entity label of the product from IFC file. It is how the wexBIM file is being created. The same applies to JSON COBie data.

**Comment by soniagagliardi** [comment]
I will send screenshots of both projects , which displays two different entitylabel

![xbimviewer](https://cloud.githubusercontent.com/assets/16120780/11567444/5d0c5114-99e7-11e5-840d-6c3e85b42769.png)

![xbimwebviewer](https://cloud.githubusercontent.com/assets/16120780/11567530/ac287ec6-99e7-11e5-9d04-0cb0e3dc10fe.png)

The code

**Comment by martin1cerny** [comment]
Yes, there are two different labels because these are two different models of the same building. You can see there are trees, furniture, railings and other things missing in the desktop version which are present in the web version. If you used the same IFC file to produce these two pictures the label would be the same. EntityLabel is granted to be unique within one file but is not granted to be the same and/or unique between two versions of the model.

**Comment by soniagagliardi** [comment]
The error is exactly this. Opening two  models equals the EntityLabels are the same.
Thank you so mutch.

**Comment by martin1cerny** [comment]
If you need an identifier which is consistent across multiple versions of the same file have a look at GUID [IfcRoot.GlobalId](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifckernel/lexical/ifcroot.htm).

**Comment by soniagagliardi** [comment]
Ok, thank you for your suggestion.

Sonia
