### ISSUE TITLE
Taking a too much time to convert from ifc to wexbim 

### ISSUE THREAD

**Issue by Marks10** [xBimTeam/XbimWebUI#57]
Hi ,
 I am trying  to convert 600MB ifc file ,It is converted but it takes a near about 1 hour for that.
 Please help me to reduce time for this.

**Comment by martin1cerny** [comment]
Hi @Marks10,

you should really raise this issue in [XbimGeometryEngine](https://github.com/xBimTeam/XbimGeometry) or [XbimExchange](https://github.com/xBimTeam/XbimExchange) project as it is not related to XbimWebUI. This is only for the visualization of the data.

However, 600MB is in a category of large model but it shouldn't take that long on a reasonable HW as it is highly optimised to consume as much CPU as available in multiple threads to do the conversion as fast as possible. Can you send the details of the HW you use for the conversion? If it is for example free Azure website it only runs 1thread on 32bit processor and has very low performance.

**Comment by Marks10** [comment]
NViDIA graphics card 2gb
![configure](https://cloud.githubusercontent.com/assets/16130194/11558325/1fbf9be0-99d8-11e5-978b-affad132838d.png)

![configure](https://cloud.githubusercontent.com/assets/16130194/11558325/1fbf9be0-99d8-11e5-978b-affad132838d.png)

**Comment by Marks10** [comment]
![configure](https://cloud.githubusercontent.com/assets/16130194/11558333/2eb49aa6-99d8-11e5-8923-4f2819ea313a.png)
NViDIA graphics card 2gb

**Comment by martin1cerny** [comment]
And what do you use for a conversion? Is it XbimExchanger or your own application?

**Comment by Marks10** [comment]
Its my own application but i am using xbim.common dll and xbim.modelgemoerty scene

**Comment by martin1cerny** [comment]
Can you try to run your model through [Xbim.Exchange](https://github.com/xBimTeam/XbimExchange/tree/master/Xbim.Exchange) as a benchmark? It shouldn't take more than a few minutes (like 4 - 10) on the model of this size. It might take a long time if the original model is wrong and xBIM has to fix it (we are seeing more models like that recently). Also make sure you run it in Release mode and without debugging (Ctrl+F5). It makes a big difference.

**Comment by martin1cerny** [comment]
...also if you only want to test wexBIM file creation return from [here](https://github.com/xBimTeam/XbimExchange/blob/master/Xbim.Exchange/Program.cs#L49).
