### ISSUE TITLE
IfcTagname  for Electrical ,Plumbing ,HVAC, Lighting companonts for WeXbim file

### ISSUE THREAD

**Issue by dhundaleamol** [xBimTeam/XbimWebUI#6]
Hello ,

Can you suggest me IfcTagnames for Electrical ,Plumbing ,HVAC, Lighting companonts for WeXbim file.

for eg. IfcDistributionFlowElement ,IfcDistributionFlowElementType comes in HVAC ,

**Comment by martin1cerny** [comment]
I'm sorry but I don't know what you mean by IfcTagnames.

**Comment by dhundaleamol** [comment]
Hi Martin,

viewer.setState(states.HIDDEN, types.IFCSTRUCTURALCURVEMEMBER);

Here , you are using this "IFCSTRUCTURALCURVEMEMBER"  ifctagname ...
So ,when you are using Hide space , you used this line
-viewer.setState(states.HIDDEN, types.IFCSPACE)

Here types.IFCSPACE is generate some id .

So , Can you tell me ,how that id will come .

Thanks ,
Amol Dhundale

On Thu, Apr 2, 2015 at 7:40 PM, Martin Černý <notifications@github.com>
wrote:

> I'm sorry but I don't know what you mean by IfcTagnames.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/6#issuecomment-88919907>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
Right, I see. You have to explore IFC2x3 schema for this. Or you can use xBIM for that. Try somethig like this (just a sudo code - not tested):

    var types = typeof(IfcProduct).Assembly.GetTypes().Where(t => t.Namespace == "Xbim.Ifc2x3.HVACDomain").Select(t => t.Name.ToUpper());

Something like this should give you a list of products from HVAC domain as defined in IFC schema.

**Comment by dhundaleamol** [comment]
Thank you so much Martin.

I got a solution .You can close this issue now.

Thanks & Regards,
Amol Dhundale

On Sat, Apr 4, 2015 at 1:00 PM, Martin Černý <notifications@github.com>
wrote:

> Right, I see. You have to explore IFC2x3 schema for this. Or you can use
> xBIM for that. Try somethig like this (just a sudo code - not tested):
>
> var types = typeof(IfcProduct).Assembly.GetTypes().Where(t => t.Namespace == "Xbim.Ifc2x3.HVACDomain").Select(t => t.Name.ToUpper());
>
> Something like this should give you a list of products from HVAC domain as
> defined in IFC schema.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/6#issuecomment-89516352>.
>



-- 
Thanks & Regards,
  Amol Dhundale
