### ISSUE TITLE
how to UNDEFINED only particular IFCSPACE

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#60]
I have used following line to view an IFCSPACE .
viewer.setState(xState.UNDEFINED, xProductType.IFCSPACE);
Using this line , all Spaces in  file are visible.

But I want to view only particular ifcspace.
like as here nEntityLabbel or GUID - has  unique id .So I want to visible space only against this ID.

I have used following code for this .
viewer.setState(xState.UNDEFINED, xProductType.IFCSPACE);
                        viewer.defineStyle(6, [255, 0, 0, 220]);  //red
                        viewer.setStyle(6, [data[i].nEntityLabel]);

But Using this code , It will visible all IFCSPACEs in file/Building. My requirement is only visible IFCSPACES in only one level/floor.

Is it possible this.

**Comment by martin1cerny** [comment]
Please, see the documentation of [setState](http://xbimteam.github.io/XbimWebUI/xViewer.html#setState) and [setStyle](http://xbimteam.github.io/XbimWebUI/xViewer.html#setStyle). You can apply both just to single product.
```c#
viewer.setState(xState.UNDEFINED,  [data[i].nEntityLabel]);
viewer.defineStyle(6, [255, 0, 0, 220]); //red
viewer.setStyle(6, [data[i].nEntityLabel]);
```

**Comment by BIMDevelopement** [comment]
Thanx Martin.
