### ISSUE TITLE
xbim-viewer.debug.bundle.js runtime error: Style index not found.

### ISSUE THREAD

**Issue by mikeduberry** [xBimTeam/XbimWebUI#62]
Hi, I am new to this and have a problem with the exporter. 

WebUI throws the following exception when trying to display a converted IFC -> wexbim file ...

Unhandled exception at line 342, column 17 in http://localhost:58706/js/xbim-viewer.debug.bundle.js

0x800a139e - JavaScript runtime error: Style index not found.

when file converted IFC file size is small it works fine but if size is large then it throws this error.

I am using the latest xbim-viewer.debug.bundle.js from XbimWebUI comited on 2 Oct, Xbim.Geometry 3.1.14. The example FourWalls.ifc converts and displays OK, but the example LakesideRestaurant.ifc converts but results in the uncaught exception: Style index not found error.

My code behind is...

[Default.aspx.cs.zip](https://github.com/xBimTeam/XbimWebUI/files/68386/Default.aspx.cs.zip)

Can you guys please advise, many thanks.

NOTE: there was a similar problem with the WindowsUI, see here https://github.com/xBimTeam/XbimWindowsUI/issues/2#issuecomment-166271405

**Comment by martin1cerny** [comment]
Hi @mikeduberry , this shouldn't be a problem and it also doesn't depend on the file size. We use LakesideRestaurant for testing and it should be all right. You use the latest Xbim.Geometry but you use quite old XbimWebUI. Get the latest version please. I've just tried and it works just fine.

Also I'm sorry but our time is very constrained so we won't be able to help you based on your source code. That applies for now and also any future case.

**Comment by mikeduberry** [comment]
OK thanks, I now have it working.
