### ISSUE TITLE
who can give me a 'XbimConvert.exe',thanks!!

### ISSUE THREAD

**Issue by zhangjianbao** [xBimTeam/XbimWebUI#63]
who can give me a 'XbimConvert.exe',  thanks!!

**Comment by boosterwu** [comment]
hi @zhangjianbao , 
Here you are.
[XbimConvert.zip](XbimConvert)

**Comment by zhangjianbao** [comment]
thanks ! but i can not open XbimConvert.zip ,404 error.can you post to jianbao19842004@163.com

**Comment by boosterwu** [comment]
@zhangjianbao , I just post it to another cloud storage, please download again.
https://dl.dropboxusercontent.com/u/3846128/XbimConvert.zip

**Comment by zhangjianbao** [comment]
i have downloaded,thanks very much! when i use XbimConvert.exe,but it prompt shut down,can you give me some advice?

**Comment by boosterwu** [comment]
you have to give filepath and filename to convert your files.

**Comment by zhangjianbao** [comment]
thanks very much, in which file set filepath and filename?

**Comment by boosterwu** [comment]
XbimConvert.exe "c:\abc\def.ifc"

**Comment by zhangjianbao** [comment]
is ok!  thanks! thanks! thanks!
