### ISSUE TITLE
Xbim file  not contain Plumbing & Lighting

### ISSUE THREAD

**Issue by nikhilbabare** [xBimTeam/XbimWebUI#65]
Hi,

My problem is that when model is loading on viewer first  Plumbing & Lighting will not be display on viewer.
please give me proper solution so i have implemented on my project.

Regard's
Nikhil Babare

**Comment by martin1cerny** [comment]
Hi @nikhilbabare, 

I've seen many models containing plumbing and lighting working all right. Please make sure your IFC model contain these objects and that they have the geometry defined. 

If it is there and has a geometry but still is not presented in the viewer I can't help you unless I see the IFC file.

**Comment by nikhilbabare** [comment]
Hi ,

My IFC file contain plumbing but..When IFC file is loaded first  plumbing will not be showing on view. I am giving on check box name plumbing , click on this check then show plumbing element.
 Please give me  suitable answer.

**Comment by martin1cerny** [comment]
I'm sorry @nikhilbabare but your issue description is not detailed enough. You will need to provide us with more information so that we can help you.

**Comment by nikhilbabare** [comment]
Hi Martin,

Issue is that ..My IFC File conatin plumbing data but..i haven't showing plumbing data on view. So what i do?

**Comment by martin1cerny** [comment]
That is a question. What do you do? How do you create the wexBIM file? Which version of XbimGeometry do you use? How do you use xViewer? Do you do anything with styling and states in the model? Did you try to open wexBIM file in a vanilla viewer? Does your file contain other data you can see? What is the size of the IFC file? What is the size of wexBIM file? 

And last but not least: What have you tried to solve your problem so far?

**Comment by martin1cerny** [comment]
Closed for a lack of information about the issue.
