### ISSUE TITLE
The rendering takes too long for large 3D model

### ISSUE THREAD

**Issue by Leonsy** [xBimTeam/XbimWebUI#66]
Hi,

I am trying to use the WebUI to open a large 3d model. But the loading time is really long, and the performance of interaction with the model is also not good. Is it possible to use level-of-detail to optimize the performance, or you have any better ideas? Thank you for your time!

Regard's
Siyang

**Comment by martin1cerny** [comment]
Hi @Leonsy ,

how big is your model? Viewer doesn't have level-of-detail control. The question is: "What do you understand as a level-of-detail?" Is it coarseness of triangulation? That would mean we would have to either transfer even more data or we would have to do triangulation and GPU loading on-the-fly which would be very expensive. 

One possible solution we think about is to create multiple wexbim files for a model which would contain different parts of model. For example walls and slabs are typically big and simple so it would create kind of skeleton for the building. Spaces are even more useful for the first level of orientation. Furniture tends to be small and complicated. Plumbing tends to be large and complicated. Based on these assumptions it is possible to create separate wexbim files representing different parts of the model. xViewer is already able to load and render multiple wexbim files so it would only take a minor change to stop rendering some of the parts during navigation. Also every part would get rendered once it was available.

This is not implemented but fits well into actual implementation. Our current development effort is focused on different part of xBIM Toolkit so it won't be available in days or weeks from now unless it becomes development priority on a project we work on now. But feel free to explore [wexBIM file creation](https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L1945) and we will take your changes on board (quality code is requirement in that case of course).

**Comment by Leonsy** [comment]
Hi,

Thank you for your respond. The wexBim file I am working on is about 200MB. And the it is a model of a port, so most of the elements in the model are exposed. Because of this, even if I divide the big wexbim file into smaller chunks, I still need to load most of them when the user take a overlook of the model. But if we are able to render different parts of the model according to the distance from the camera, which means decreasing the complexity of a 3D object representation as it moves away from the viewer, the performance should be better.

**Comment by martin1cerny** [comment]
We can't decrease complexity of an object for the reason described above. We could do frustum culling but it is not there yet. 

Despite of that I can hardly imagine web application which would swallow 200MB over the network just because file loading time itself is too long for most of the applications. If WexBIM file is 200MB the original IFC had to be around 2GB (as a non-zipped STEP 21 file), right? That is a huge model even for desktop environment.
