### ISSUE TITLE
File LikesideRestaurant.ifc updated

### ISSUE THREAD

**Issue by soniagagliardi** [xBimTeam/XbimWebUI#69]
Hi,
It is available the updated version of the file IFC LakesideRestaurant.ifc?
The version with the trees.

Thank you.

**Comment by soniagagliardi** [comment]
someone could help me?

**Comment by martin1cerny** [comment]
I'm sorry but it isn't very clear what is your issue.

**Comment by soniagagliardi** [comment]
In the project  XbimWebUI i file LakesideRestaurant.wexbim e LakesideRestaurant.json are updated at 8 months ago. While the file LakesideRestaurant.ifc to a year ago.
you can have the IFC file updated?

**Comment by martin1cerny** [comment]
I'm sorry but it would be time consuming to find the version of the file used to generate these wexBIM and JSON files. I'd rather recommend you to get your own example and to create matching files yourself. XbimWebUI project doesn't contain any actual code to do anything with IFC files so all IFC files should probably be completely removed from the repository.

**Comment by soniagagliardi** [comment]
You can generate the files IFC starting from wexBIM and JSON files?
How can create the  JSON file of the IFC file?

I tried to use the code:

using (var model = new XbimModel())
{
    model.CreateFrom(fileName, null, null, true);
    var cobieFileName = "semantics.json";
    using (var cobieFile = new FileStream(cobieFileName, FileMode.Create))
    {
        var helper = new CoBieLiteHelper(model, "UniClass");
        var facility = helper.GetFacilities().FirstOrDefault();
        if (facility != null)
        {
            using (var writer = new StreamWriter(cobieFile))
            {
                CoBieLiteHelper.WriteJson(writer, facility);
                writer.Close();
            }
        }
    }
    model.Close();
}

but I do not know whether it is correct because the information are not displayed in the index.html

model.CreateFrom(fileName, null, null, true);

fileName to which file must match?

**Comment by martin1cerny** [comment]
https://github.com/xBimTeam/XbimExchange/blob/master/Xbim.Exchange/Program.cs

**Comment by soniagagliardi** [comment]
Because the code create JSON file does not work?
I also need the files updated XBIM. 
How can I generate without the updated IFC file?

**Comment by martin1cerny** [comment]
It is still not very clear what is your issue here.
