### ISSUE TITLE
Error in converting Ifc file to wexbim

### ISSUE THREAD

**Issue by dhundaleamol** [xBimTeam/XbimWebUI#7]
Can anybody please help me to resolve error which is occurred  while converting ifc file to wexbim which is working fine on my desktop but not working on some laptop's.
Error-
"Could not load file or assembly 'Xbim.Geometry.Engine' or one of its dependencies. The specified module could not be found"

**Comment by martin1cerny** [comment]
Hi dhundaleamol,
have you created an install package or anything like that? Geometry engine loads C++ DLLs in runtime and these have to be in 'x86' and 'x64' folders of your application.

Martin

**Comment by dhundaleamol** [comment]
Hi Martin,

I got the following error on this line in Xbim.Geometry.Engine .While I am
going to conversion from . ifc to .wexbim. I have refered XBIMExchange
source also.

ObjectHandle oh =
Activator.CreateInstance("Xbim.Geometry.Engine","Xbim.Geometry.XbimGeometryCreator"

On Thu, Apr 2, 2015 at 7:29 PM, Martin Černý <notifications@github.com>
wrote:

> Hi dhundaleamol,
> have you created an install package or anything like that? Geometry engine
> loads C++ DLLs in runtime and these have to be in 'x86' and 'x64' folders
> of your application.
>
> Martin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-88911707>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by dhundaleamol** [comment]
Hi Martin,

This screenshot will help you to get a problem . Please refer the
attachment.

Thanks & Regards,
Amol Dhundale

On Thu, Apr 2, 2015 at 8:11 PM, amol dhundale <dhundaleamol@gmail.com>
wrote:

> Hi Martin,
>
> I got the following error on this line in Xbim.Geometry.Engine .While I am
> going to conversion from . ifc to .wexbim. I have refered XBIMExchange
> source also.
>
> ObjectHandle oh =
> Activator.CreateInstance("Xbim.Geometry.Engine","Xbim.Geometry.XbimGeometryCreator"
>
> On Thu, Apr 2, 2015 at 7:29 PM, Martin Černý <notifications@github.com>
> wrote:
>
>> Hi dhundaleamol,
>> have you created an install package or anything like that? Geometry
>> engine loads C++ DLLs in runtime and these have to be in 'x86' and 'x64'
>> folders of your application.
>>
>> Martin
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-88911707>.
>>
>
>
>
> --
> Thanks & Regards,
>   Amol Dhundale
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
Hi Amol,

screenshot didn't make it though GitHub. Sorry. But my answer still applies:

"Have you created an install package or anything like that? **Geometry engine loads C++ DLLs in runtime and these have to be in 'x86' and 'x64' folders of your application.**"

**Comment by dhundaleamol** [comment]
Hi Martin,

No , I have'nt created an install package.
The conversion of ifc to wexbim is working fine in console application (ie.
XbimExchange)  . But Its not working in Web application for some ifc file .
Its give an above error for some .ifc files.

Thanks & Regards,
Amol Dhundale


On Sat, Apr 4, 2015 at 12:54 PM, Martin Černý <notifications@github.com>
wrote:

> Hi Amol,
>
> screenshot didn't make it though GitHub. Sorry. But my answer still
> applies:
>
> "Have you created an install package or anything like that? *Geometry
> engine loads C++ DLLs in runtime and these have to be in 'x86' and 'x64'
> folders of your application.*"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-89515484>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
This sounds strange as this kind of error should be the same for all IFC files. It seems to be related to deployment method of your web application. Geometry engine is located in a subdirectory and is not directly referenced so deployment routines might not recognize it as an indispensable dependency. Please make sure both geometry engine files are located in x32 and x64 directories of your deployed application on server.

**Comment by dhundaleamol** [comment]
Hello Martin ,

As you suggest a directory structure . I have put dll . But still it is not
working for some ifc file in web application .

I have sent you a screenshot of my directory structure . So can you check a
directory structure of my  project . Is it correct or not?.

Thanx & Regards,
Amol Dhundale

On Mon, Apr 6, 2015 at 8:55 PM, Martin Černý <notifications@github.com>
wrote:

> This sounds strange as this kind of error should be the same for all IFC
> files. It seems to be related to deployment method of your web application.
> Geometry engine is located in a subdirectory and is not directly referenced
> so deployment routines might not recognize it as an indispensable
> dependency. Please make sure both geometry engine files are located in x32
> and x64 directories of your deployed application on server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-90103863>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by dhundaleamol** [comment]
Sorry I forgot to attach an Image in previous conversion.

On Tue, Apr 7, 2015 at 11:23 AM, amol dhundale <dhundaleamol@gmail.com>
wrote:

> Hello Martin ,
>
> As you suggest a directory structure . I have put dll . But still it is
> not working for some ifc file in web application .
>
> I have sent you a screenshot of my directory structure . So can you check
> a directory structure of my  project . Is it correct or not?.
>
> Thanx & Regards,
> Amol Dhundale
>
> On Mon, Apr 6, 2015 at 8:55 PM, Martin Černý <notifications@github.com>
> wrote:
>
>> This sounds strange as this kind of error should be the same for all IFC
>> files. It seems to be related to deployment method of your web application.
>> Geometry engine is located in a subdirectory and is not directly referenced
>> so deployment routines might not recognize it as an indispensable
>> dependency. Please make sure both geometry engine files are located in x32
>> and x64 directories of your deployed application on server.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-90103863>.
>>
>
>
>
> --
> Thanks & Regards,
>   Amol Dhundale
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
Hi Amol,

screenshot didn't make it though to GitHub. I think you have to attach it on GitHub webpage. Could you try it again please?

Martin

**Comment by dhundaleamol** [comment]
Yes , Of course .
![directory](https://cloud.githubusercontent.com/assets/10378872/7061362/75abd8ba-deae-11e4-80e6-658470605e6d.png)

**Comment by dhundaleamol** [comment]
http://we.tl/Al6oxql7Fr...
this is my demo source link .You can download it and check if you can not get anything from screenshot.It include ifc file also which is not able to convert into wexbim.

**Comment by dhundaleamol** [comment]
Hey Martin, Are you check my demo source ?

Any Updates?

On Thu, Apr 9, 2015 at 10:50 AM, Martin Černý <notifications@github.com>
wrote:

> Hi Amol,
>
> screenshot didn't make it though to GitHub. I think you have to attach it
> on GitHub webpage. Could you try it again please?
>
> Martin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-91118242>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
Hi Amol,

I'm sorry but we are finishing the main project now so I didn't check your
file yet. But I've downloaded the file and will check it in the next days.

Martin
Dne 11. 4. 2015 16:14 napsal uživatel "Amol D" <notifications@github.com>:

**Comment by dhundaleamol** [comment]
Okay . But its very critical issue for my project and i didnt get any
solution yet.Please check once what was issue in that source.

Amol

On Sun, Apr 12, 2015 at 1:29 AM, Martin Černý <notifications@github.com>
wrote:

> Hi Amol,
>
> I'm sorry but we are finishing the main project now so I didn't check your
> file yet. But I've downloaded the file and will check it in the next days.
>
> Martin
> Dne 11. 4. 2015 16:14 napsal uživatel "Amol D" <notifications@github.com>:
>
> > Hey Martin, Are you check my demo source ?
> >
> > Any Updates?
> >
> > On Thu, Apr 9, 2015 at 10:50 AM, Martin Černý <notifications@github.com>
> > wrote:
> >
> > > Hi Amol,
> > >
> > > screenshot didn't make it though to GitHub. I think you have to attach
> it
> > > on GitHub webpage. Could you try it again please?
> > >
> > > Martin
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-91118242
> >.
> > >
> >
> >
> >
> > --
> > Thanks & Regards,
> > Amol Dhundale
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-91851436>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/7#issuecomment-91919947>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
Hi  Amol,

you sent me your project but as you have noted yourself it works on your machine. Your problem is not a problem of xBIM or your project but the deployment. For a reason I described above I recommend to change the Publish settings to "All items".
![snap](https://cloud.githubusercontent.com/assets/773078/7134352/6651a9f2-e29c-11e4-888b-aaa27342d46c.PNG)

**Comment by dhundaleamol** [comment]
Hi Martin,
Thanks for your reply but The source and file which I have been sent you is not working on my machine.It gives error for converting the ifc file to wexbim in below line
context.CreateContext(geomStorageType: XbimGeometryType.PolyhedronBinary); 
what would be the problem .Am I using wrong ifc file, if using how could I check it is correct file for wexbim conversion  or is there any dll issue,can you please look on it.

**Comment by martin1cerny** [comment]
Dear Amol,

current engine works absolutely fine. You are using an old and obsolete version. Please use MyGet to get the latest cutting edge version. Make sure to test your code with the latest version before you raise an issue please. Also make sure you talk about the same issue through the issue trace please.

Martin

**Comment by martin1cerny** [comment]
Yes, it throws an exception on my machine as well. But if you update the
geometry engine and all other xBIM library files it works all right.

https://www.dropbox.com/s/en24y2gusuc07gh/WebApplication3.zip?dl=0

Martin

2015-04-14 12:43 GMT+02:00 Amol D <notifications@github.com>:

**Comment by dhundaleamol** [comment]
Hi Martin,

Thanx for ur replied . 

Its working .But browser will hang on big size of ifc file(eg.90MB onwaords).Zooming and all related functionality is working very very slow.I have tested that file on latest XbimWebUI project of Github.But still getting a same issue on that project also.

Is there any more upgradation require ?

Amol

**Comment by martin1cerny** [comment]
XbimWebUI uses HW acceleration so its performance depends on your computer
really. However, we had models of this size working quite all right on
computers used for BIM authoring tools (which inherently means they have
higher spec GPU). Also make sure you do not attach any heavy handlers to a
frequently called callbacks.

Martin

2015-04-21 8:34 GMT+01:00 Amol D <notifications@github.com>:

**Comment by dhundaleamol** [comment]
Hi Martin ,

Can you please a tell me computer configuration details which is required for XbimWebUI.(Is it kind of RAM,Bit version OS?).

**Comment by martin1cerny** [comment]
Hi Amol,

There are several factors to consider. First thing is that performance is
very dependent on size of the model. Performance of GPU is more important
than RAM. CPU is under load only when parsing and loading the wexbim file.
This will be even more optimised in the next days.

xViewer id independent of 32/64 bit architecture.

As a pure web technology it should be OS independent. All web browsers
supporting WebGL should work. We tested on Firefox, Chrome, IE11. Safari
should also work. We did tests on iOS and it worked. However, navigation
needs to be different for touch devices and even for iOS as the current
navigation is most convenient with a mouse with 2 buttons and scrolling
wheel.
Dne 15. 5. 2015 13:42 "Amol D" <notifications@github.com> napsal(a):

**Comment by martin1cerny** [comment]
If you mean what I use for a development it is 8GB RAM, Windows 7 Enterprise SP1, 64bit, Intel Core i7, GPU NVIDIA Quadro K3000M. But we have tested on much lower spec devices.

**Comment by ranjitchapale** [comment]
Hi Martin,
      Is Graphics card mandatory for performance while loading file and ifc conversion?

**Comment by martin1cerny** [comment]
Graphics card is important for a responsiveness of the xViewer during the drawing loop and for a speed of loading the actual drawing data into it. It is not important for a parsing of wexbim file. IFC conversion happens on the server, not the client and no, it doesn't use the GPU.

**Comment by vomicz** [comment]
Hi, I'm experiencing the same issue with on Desktop in Win 7 with the latest version of xBIM (downloaded via NuGet on 5/26/2015 - xBIM Geometry version 3.0.21) - when I try to create an instance of Xbim3DModelContext a FileNotFoundException is thrown (Could not load file or assembly 'Xbim.Geometry.Engine' or one of its dependencies. The specified module could not be found.)

The Xbim.Geometry.Engine64.dll is in the x64 folder since it was placed there by NuGet, I have not tempered with it.

The really strange thing is that everything works ok on W8.1, but the aforementioned exception is thrown as soon as I try to run it on W7 Enterprise (both are 64-bit). The code that I'm trying to run can be viewed at the following link:
https://drive.google.com/file/d/0B8WE8PDmieCHTTBqYkozOHdqb2c/view?usp=sharing

**Comment by dhundaleamol** [comment]
Hi Vomicz, Put manually bin folder to your project .It will be working ..

**Comment by vomicz** [comment]
dhundaleamol, thanks for your comment but no, it won't work. The bin folder is created after a successful build and even if I create it manually as you suggest it makes no difference. I'm still getting the same exception.

**Comment by dhundaleamol** [comment]
Hi  vomicz,

Refer this source.
https://www.dropbox.com/s/en24y2gusuc07gh/WebApplication3.zip?dl=0

Hope so your problem will be solved.

**Comment by vomicz** [comment]
dhundaleamol, thanks again for your reply, but I'm not able to run it either.
I even replaced the dlls with their most recent versions but I'm still getting the same exception. Is there something else I should be doing?
