### ISSUE TITLE
Uncaught RangeError: Invalid typed array length

### ISSUE THREAD

**Issue by minhnguyenlinknode** [xBimTeam/XbimWebUI#70]
Hi,

I have converted my Ifc file to xbim and webxbim. Ifc file is big (200 MB).
xBim works just fine but webXBim does not work. 

In Chrome, it throws this error in javascript:  
>"Uncaught RangeError: Invalid typed array length" 

(see attached files).

[webxbimtest.zip](https://github.com/xBimTeam/XbimWebUI/files/95719/webxbimtest.zip)

![bimerror](https://cloud.githubusercontent.com/assets/9201108/12416075/2f49cb88-be97-11e5-8359-b096dc79fa3b.png)

**Comment by martin1cerny** [comment]
Which version of XbimGeometry did you use to produce the wexBIM file?

**Comment by minhnguyenlinknode** [comment]
I think it is 3.0.21. I will update to 3.1.14 to see if it is fixed or not.

**Comment by minhnguyenlinknode** [comment]
I have upgraded to use latest Nuget package and scripts then it works just fine.
Many thanks.
