### ISSUE TITLE
the use of clipping

### ISSUE THREAD

**Issue by swy0930** [xBimTeam/XbimWebUI#72]
Hi Martin,

I am confused about the function of clipping. Is it partially implemented or fully completed? I tried to click on the clip button, but nothing happened. Could you please tell me how to use clip and unclip?Thank you.

**Comment by martin1cerny** [comment]
It is fully implemented and [documented](http://xbimteam.github.io/XbimWebUI/xViewer.html#clip). Implemented UI is very simple. Just click and drug to define clipping plane (visualized as a red line). You can easily implement other ways how to define clipping plane and use [viewer.clip(point, direction)](http://xbimteam.github.io/XbimWebUI/xViewer.html#clip) to set up clipping. [Unclip](http://xbimteam.github.io/XbimWebUI/xViewer.html#unclip) will discard the clipping plane.

**Comment by swy0930** [comment]
Got it. Thank you.
