### ISSUE TITLE
Load several wexBim file

### ISSUE THREAD

**Issue by Leonsy** [xBimTeam/XbimWebUI#73]
Hi,

I know this project is able to open several wexBim file at the same time, and it works perfect at most of the time. But when the length unit for the wexBim file is different, the resulting model will be in wrong scale. Some model will be really big, and the model with the different unit will be really small. Should I make change to the xBimExchange project? Or there is some way to deal with this problem use the code in this project? Thanks!

Siyang

**Comment by martin1cerny** [comment]
It would be possible to implement on-the-fly scaling in the viewer but it would put unnecessary extra load on GPU so I wouldn't recommend that. I'd rather go for the changes in XbimExchange. I'm sure our geometry engine is able to handle this but @SteveLockley is a better person to ask about the engine.

**Comment by Leonsy** [comment]
I am trying to writing a script to pre-process the IFC file to change the unit. By the way, I found there is exception throwing when generating the json file. Am I able to get rid of this any statement? It happens when the address of an organization contains IfcTelecomAddress, but the ElectronicMailAddresses is null. Here is the screen shot.[http://imgur.com/dWqLP5T](url)

**Comment by martin1cerny** [comment]
I wouldn't recommend to change units manually in the IFC file as it is a very complex task as you may have realized already. I'd be better to scale the final geometry I think. But is is generally very bad practise to use different length units on a single project.

The null reference exception is clearly a bug. In the next release of xBIM ElectronicMailAddresses won't ever be null so this will be gone. We won't fix this here now but feel free to do it yourself for now. Or you might swap to `development` version but it is not stable yet.
