### ISSUE TITLE
Trouble with IFC with shared coordinates

### ISSUE THREAD

**Issue by AlainBolduc** [xBimTeam/XbimWebUI#74]
I have a IFC file that I made a wexbim file for. I used the following code to convert my IFC to wexbim:

```
xBimModel.CreateFrom(inputStream, XbimStorageType.IFC, tempPath, [update progress delegate], true, true);
var context = new Xbim3DModelContext(xBimModel); //upgrade to new geometry represenation, uses the default 3D model   
context.CreateContext(XbimGeometryType.PolyhedronBinary, [update progress delegate]);
context.Write(binaryWriter);

```
Using this code, the shared coordinates of the IFC file are lost. So after digging around, I found that there is a parameter, adjustWCS, that has to be set to false in CreateContext.

This kind of fixed my problem. Now 2 ifc files with objects at 0,0,0 but with a different Site Object Placement are displaying correctly instead of one over the other. (see the Position1.ifc and Position2.ifc files in the attached file.)

However, with a file (see project.ifc) which site placement is much farther, the display is not clean at all, there is some clipping all over. 

this is how it looked before , with adjustWCS = true :
[http://screencast.com/t/TfCXcQZWut]

around this point viewer.getCameraPosition() returns
[883.7939453125, 14144.12109375, 92825.8359375]

this is how it looks now, with adjustWCS = false;
[http://screencast.com/t/tDTu76mBN]

around this point, viewer.getCameraPosition() returns
[237326112, 5183997952, 91328.453125]

Do you know what is going on?

Thank you very much!

[xb.zip](https://github.com/xBimTeam/XbimWebUI/files/119905/xb.zip)

**Comment by martin1cerny** [comment]
Hi @AlainBolduc, this behaviour is intentional and correct. We have seen these files coming recently where site origin is set to something like the Land's End or similar. Result of this is that all coordinates in the model are very big numbers (mostly in millimetres). This causes problems with the precision of all transformations and also precision of GPU. Of course we use double precision floating numbers for transformations but it is not enough and we can't change GPU precision of WebGL implementations where precision vary. This is why we adjust WCS by default to avoid these problems. 

It is generally a wrong practise to create such models and it is likely that BIM authoring tools don't handle it natively in this way as well as they would run into exactly the same kind of issues. Good practise is to have site origin somewhere close to the actual model and than to georeference the WCS origin. It means your model makes a sense in terms of computer modelling and it is still possible to transform/export the coordinates in your reference system (for example if you need to set out the site).

**Comment by AlainBolduc** [comment]
Hi Martin, 

Thank you for your answer.

While I disagree on whether having a site origin is a good practice or not (we will leave this for another debate :) ), I understand the limitations and I will deal with it.

However, what I am trying to achieve here is the ability of keeping camera information at a given time and then find them back in another software. To do so, I absolutely have to know the site origin in order to perform a translation of the camera when I capture it in the viewer.

What I thought of is to keep the site origin when I perform the  conversion from ifc to wexbim and store them in my database along with the resulting wexbim file. Do you think there is an easier way of keeping site origin other than hooking in the conversion engine ( I thought of doing something [here](https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L593) since I would have access to context.PlacementTree[0], but I try to avoid modifying source code as much as I can)

Thank you very much!

Alain

**Comment by martin1cerny** [comment]
Hi @AlainBolduc,

I can see your point and it is completely valid. I think that the most sensible solution would be to have a public property in geometry engine which would return transformation matrix for the site origin so it would be very easy to transform camera (or any other) coordinates between view space and the original WCS space. This is mainly domain of @SteveLockley so I'll ask him when I talk to him.

**Comment by AlainBolduc** [comment]
Hi Martin, 

I would be interested in knowing a little more on your proposed solution.  I am on a somewhat short deadline and I may have to give it a shot myself (although I would prefer if it was made by your team,  as you are a thousand miles ahead in terms of knowledge of 3D stuff :) )

Thanks

**Comment by martin1cerny** [comment]
I don't think @SteveLockley  will be able to get into this in the next few days. Plus we work heavily on the development of the next release which will be the next generation really so it is more likely to appear there. New generation will support IFC4 in the full extent including all new geometries which are defined only in IFC4 so I hope you will appreciate it is our priority now.

The first quick shot I'd recommend is to get placement of IfcSite and call `ToMatrix3D()` on it. That might give you the transformation matrix you need I believe.

**Comment by AlainBolduc** [comment]
Hi Martin,

I think I found a way to solve my problem, but I would like your input on it (yours, or your colleague's, if the question should be asked in another project)...

I found that, when Xbim3DModelContext.CreateContext is called, it ends up calling WriteRegionsToDb, which in turns calls AddGeometry on Geometry table.

The interesting part I found is that the WCS matrix is kept when XbimRegions are created, then persisted in the database, so I thought I could give this piece of code a shot:

```
context.CreateContext(XbimGeometryType.PolyhedronBinary);
XbimGeometryData xbimGeometryData = xBimModel.GetGeometryData(XbimGeometryType.Region).FirstOrDefault();
if (xbimGeometryDatas != null)
{
     XbimMatrix3D xbimMatrix3D = XbimMatrix3D.FromArray(xbimGeometryDatas.DataArray2);
     [...]
}
```


As it turns out, the XbimMatrix3D I got by doing this seems to be exactly what I am searching for. I managed to get the transformation matrix without having to change anything in xBim source code. I would like you to tell me if it is safe enough to use the transformation matrix I found... I mean, do you see any reason not to use it?

Once I have this transformation matrix, is it just a matter of multiplying it with _mvMatrix, or you see some other caveats I should be aware of ?

Thanks!

Alain

**Comment by martin1cerny** [comment]
Hi @AlainBolduc ,

this seems to be correct. Do you work on `develop` or `master`? A lot has changed in underlying layers in `develop` recently so you are better to make sure it will still be there as you expect it. If you run in a troubles I'll try to catch prof. Steve Lockley to get it sorted. All this discussion should really be in XbimGeometry project.

Martin
