### ISSUE TITLE
Possibility to override Home icon's action on click?

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#75]
Hello Martin,
I would like to know:
- if there is the possibility to override the Home icon action when the button is clicked?
- if there is the possibility to change the Home button position as for Cube one?

Thanks

**Comment by martin1cerny** [comment]
Please, check the [documentation](http://xbimteam.github.io/XbimWebUI/xNavigationHome.html) first.

**Comment by johnBim** [comment]
Thank you!
