### ISSUE TITLE
Get the origin/direction from clip event?

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#76]
Hello Martin,
Is there a method/event to get origin and direction on clipping action?

Thanks

**Comment by martin1cerny** [comment]
It is not a public member but you can access it as `xViewer._clippingPlane` see the documentation [here](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L124).
