### ISSUE TITLE
Get mouse coordinate on mouseover 3D?

### ISSUE THREAD

**Issue by jean-fr** [xBimTeam/XbimWebUI#77]
Hello Martin,
 Is it possible that the 3D provides the mouse coordinates on mouseover? (coordinates relative to the 3D only)

Thanks

**Comment by martin1cerny** [comment]
No

**Comment by LloydPickering** [comment]
You could potentially write this yourself, but it's a fairly tricky task, so I wouldn't advise it unless you are vaguely familiar with graphics programming.

The guide at http://xeolabs.com/articles/scenejs-ray-picking-technique/ could get you started.

Ultimately, this will only be as accurate as your near and far depth planes are accurate (in covering your model space). If they are too far apart, then you will end up with a loss of precision.

**Comment by martin1cerny** [comment]
A new version of the viewer has been published with many improvements. It is available as an [npm package](https://www.npmjs.com/package/@xbim/viewer) now. It has this functionality implemented.
