### ISSUE TITLE
Get 3D product ids by product type?

### ISSUE THREAD

**Issue by jean-fr** [xBimTeam/XbimWebUI#78]
Hello Martin,
Is there the way to get the product ids by product type?
e.g. getProductIds(type)

Or simply methods like: GetAllHighlighted() , GetHidden() ?

Thanks

**Comment by martin1cerny** [comment]
There are functions like [getProductType(id)](xbimteam.github.io/XbimWebUI/xViewer.html#getProductType), [getState(id)](xbimteam.github.io/XbimWebUI/xViewer.html#getState), [getStyle(id)](xbimteam.github.io/XbimWebUI/xViewer.html#getStyle) and both [setState(state, target)](xbimteam.github.io/XbimWebUI/xViewer.html#setState) and [setStyle(state, target)](xbimteam.github.io/XbimWebUI/xViewer.html#setStyle) accept either list of product IDs or a type ID where this will set all products of that type to specific state/style. If you need to keep track of objects you have hide or changed you just need to keep track of this calls.

**Comment by johnBim** [comment]
Hi Martin,
What I am trying to say is that: e.g. if I hide element by type (a group of elements on 3D will be hidden) But if I want to get the IDs of those hidden elements (hidden by type) how is it possible since I tracked only the product type ID, how can I use this product type ID to find all hidden item IDs?

Thanks

**Comment by martin1cerny** [comment]
Such function is not implemented yet. I might do it next time I'm in the code of WebUI. For now you can hack it using [this code](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-model-handle.debug.js#L288) in model handle. xViewer has multiple model handles. Every handle has one model. Every model has one product map. Every product map has type which is a number equal to one of [product types](http://xbimteam.github.io/XbimWebUI/global.html#xProductType).

**Comment by johnBim** [comment]
Thank you, I will have a look at it

**Comment by Holgenberg** [comment]
Hi @johnBim 

I wrote some code in the xbim-viewer.debug.js which returns an array of ID's for a product type. 

`/**
 * Function returns an array of prodID's' for productType
 * @param {any} target - productType (e.g xProductType.IFCWALLSTANDARDCASE)
 */
xViewer.prototype.getProductID = function (target) {
    var productID = null;
    this._handles.forEach(function (handle) {
        productID = handle.getProductID(target);
        if (productID !== null) {
            return;
        }
    }, this);
    return productID;
}

Hope this helps!`

**Comment by 2269396307** [comment]
Hi Martin,
I'm trying to get some properties from model ,how can i do ?

Thanks

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It has functions to inspect products and their types loaded in the view. For semantic data (properties), it is better to implement a web service which will only fetch what is needed.
