### ISSUE TITLE
How to get Exact position of Object in viewer diagram

### ISSUE THREAD

**Issue by dhundaleamol** [xBimTeam/XbimWebUI#8]
Hi Martin,

I want to get a exact position of object . 
For that, I refer  xViewer.prototype.zoomTo() function , but still I did'nt get any proper position ,
And Is it possible to get a position in X,Y & Z co-ordinates  format?.

Thanks,
Amol

**Comment by martin1cerny** [comment]
Hi Amol,

zoomTo() function is not designed to zoom to a certain coordinate but to a
specified object. It computes a necessary distance and direction and zooms
to it. See the documentation please:

"Use this method to zoom to specified element. If you don't specify a
product ID it will zoom to full extent."

Martin

2015-04-09 9:13 GMT+02:00 Amol D <notifications@github.com>:

**Comment by dhundaleamol** [comment]
Okay Martin.

But My issue is, not  finding a exact position of object . I want to show a
text message on that particular object . For that ,I need a position of
object.

On Fri, Apr 10, 2015 at 4:04 PM, Martin Černý <notifications@github.com>
wrote:

> Hi Amol,
>
> zoomTo() function is not designed to zoom to a certain coordinate but to a
> specified object. It computes a necessary distance and direction and zooms
> to it. See the documentation please:
>
> "Use this method to zoom to specified element. If you don't specify a
> product ID it will zoom to full extent."
>
> Martin
>
> 2015-04-09 9:13 GMT+02:00 Amol D <notifications@github.com>:
>
> > Hi Martin,
> >
> > I want to get a exact position of object .
> > For that, I refer xViewer.prototype.zoomTo() function , but still I
> did'nt
> > get any proper position ,
> > And Is it possible to get a position in X,Y & Z co-ordinates format?.
> >
> > Thanks,
> > Amol
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/xBimTeam/XbimWebUI/issues/8>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xBimTeam/XbimWebUI/issues/8#issuecomment-91509827>.
>



-- 
Thanks & Regards,
  Amol Dhundale

**Comment by martin1cerny** [comment]
The question is what do you mean by the position of the object? Is it a centroid? Or is it minimum or maximum coordinate in one of the axes directions? Or is is somewhere on the object? On which face?

**Comment by dhundaleamol** [comment]
Thanks for your response .

Yes ,It is somewhere on the object .But , I had resolved this issue.
