### ISSUE TITLE
Ability to get the state of the model

### ISSUE THREAD

**Issue by johnBim** [xBimTeam/XbimWebUI#82]
Please could you provide the following?
Ability to get the state of the model, which can be used later to restore.  
It will be good if we can get the state of the full model as object. when user is working on model , it is very good if he can continue where it was left. This is very difficult thing to implement as some of actions are not recordable from external code. I believe that implement this in the framework is something which can be usedful and beneficial.

Thanks

**Comment by martin1cerny** [comment]
Hi @johnBim ,

it isn't very clear what do you mean as a state of the model. If it is camera settings it is accessible. If it is colouring schema different from the default one you have to do it yourself in first place so you can record it as well as any changes in state or style of any product in the model. I agree such functionality might be useful but everyone might want to store different data and different settings. It is not on our road-map to implement such functionality.

Kind regards

Martin

**Comment by martin1cerny** [comment]
New functionality is implemented to get state of the model as custom recolouring and state (highlighted, hidden,...). This is in very compact form so it is easy to serialize and store. There is also new function to restore the state from this object.
