### ISSUE TITLE
Several places in xViewer do wrong array loop in javascript

### ISSUE THREAD

**Issue by jbaan** [xBimTeam/XbimWebUI#83]
On several places in xViewer code, the looping through arrays is done via (for var i in array). This is already a warning in very basic script linting tools like jsLint. Because in this case also inherited properties like "each", "contains" will be looped through. See for detailed explanation https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in
So its better to loop via index in this case, or use the modern forEach construction. 
For example in xViewer.prototype._fire function is
for (var i in handlers)
Should be 
for (var i = 0; i < handlers.length; i++) {

Also other places like
for (var si in shapeList) {
Should be
 for (var si = 0; si < shapeList.length; si++) {
 
for (var i in this._handles) {
Should be
for (var i = 0; i < this._handles.length; i++) {

Actually this should be checked accross all xbimwebui js files. Right now I facing this issues when using webuixbim inside AngularJs application.

**Comment by martin1cerny** [comment]
Hi @jbaan ,
our development resources are focused now on IFC4 full support so I won't be able to fix this in short term. I'm aware of this flaw and I'll be happy to accept your future pull request to fix this as it should be very straightforward as you've spotted already.
Martin
