### ISSUE TITLE
Would be nice to have navigation options via API of xViewer

### ISSUE THREAD

**Issue by jbaan** [xBimTeam/XbimWebUI#84]
Like google Maps/Earth you have the navigation joystick control to move around and zoom in and zoom out buttons. Especially for tablet users this is handy. For this the inner navigation function which is called now for mouse move etc.. should be exposed to outside xViewer API.

For example for zoom in and zoom out could be an option:
xViewer.prototype.zoom = function (level) {
    navigate('zoom', level, level);
};

Whereby level = 1 will zoom in, and level -1 will zoom out.

Or maybe have a an navigation plugin for this?

![image](https://cloud.githubusercontent.com/assets/6941114/13602942/05c92816-e53a-11e5-9add-a68b363bfab7.png)

**Comment by martin1cerny** [comment]
Hi @jbaan , you are right it would be nice and I wanted to do this while ago. However, our development resources are currently located on a different part of xBIM toolkit so it won't happen soon. It is not complicated if you have a look [here](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/Viewer/xbim-viewer.debug.js#L848). You just need to make the `navigate()` function public and refactor the code around to use it. I look forward to seeing your pull request with these enhancements.

Martin

**Comment by martin1cerny** [comment]
`navigate()` function was brought to the scope of the viewer when @GeorgDangl refactored the code from javascript to typescript. The code is available in `develop` branch now.
