### ISSUE TITLE
Orthogonal position issue

### ISSUE THREAD

**Issue by jean-fr** [xBimTeam/XbimWebUI#86]
Hello,
3D model disappears when using Orthogonal in xbimviewer. Any idea why?

**Comment by martin1cerny** [comment]
Implementation of Orthogonal camera is not complete. It is not straightforward to set orthogonal camera so that it shows the same extent as the perspective one. Feel free to complete this.

**Comment by martin1cerny** [comment]
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). Orthogonal camera and navigation is properly implemented now.
