### ISSUE TITLE
View properties of clicked object

### ISSUE THREAD

**Issue by krosoftware** [xBimTeam/XbimWebUI#87]
Hello all
how to see clicked item properties? Is there some example to see (for example) Area or Volume of clicked IFCWALLSTANDARDCASE?
I downloaded XbimWebUI and when I open index.html I don't see any Spatial structure or Asset type in the left side. Is there some working example of how it works?
Thank you.

**Comment by martin1cerny** [comment]
You need to run it from a web server. Some browsers will block loading static files as CORS.

**Comment by krosoftware** [comment]
Hello
yes it works on server, using same browser.
I need to see how to enable loading of static files on my local server.
Thank you.
