### ISSUE TITLE
Convert Ifc to Wexbim - how?

### ISSUE THREAD

**Issue by krosoftware** [xBimTeam/XbimWebUI#88]
Hello all
I try to find the way to convert my Ifc file toWexbim format.
How can I do that?
Is there some program to do the conversion, please?

**Comment by martin1cerny** [comment]
Hi @krosoftware , we don't provide any compiled binaries as part of xBIM Toolkit. But converting from IFC to wexBIM only takes about 15 lines of code which you can get from [here](https://github.com/xBimTeam/XbimExchange/blob/master/Xbim.Exchange/Program.cs#L37).

It is slightly different now in `develop` but again only a few lines of code. `Develop` branch is more flexible and more performant.

**Comment by krosoftware** [comment]
Hello
I actually compiled XbimExchange and after I try to convert one of Test files (Duplex_MEP_20110907.ifc):
Xbim.Exchange.exe Duplex_MEP_20110907.ifc

here is what I see:
Unhandled Exception: System.TypeInitializationException: The type initializer for 'XbimExchanger.COBieLiteUkToIfc.CoBieLiteUkToIfcExchanger' threw an exception.
 ---> System.Exception: Error loading configuration file "COBieAttributes.config". App folder is c:\IFC\XbimExchange-master\Output\Release ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XbimExchanger.COBieLiteUkToIfc.CoBieLiteUkToIfcExchanger..cctor() in c:\IFC\XbimExchange-master\Xbim.Exchanger\COBieLiteUkToIfc\COBieLiteUkToIfcExchanger.cs:line 103
   --- End of inner exception stack trace ---
   at XbimExchanger.COBieLiteUkToIfc.CoBieLiteUkToIfcExchanger..cctor() in c:\IFC\XbimExchange-master\Xbim.Exchanger\COBieLiteUkToIfc\COBieLiteUkToIfcExchanger.cs:line 121
   --- End of inner exception stack trace ---
   at XbimExchanger.COBieLiteUkToIfc.CoBieLiteUkToIfcExchanger..ctor(Facility facility, XbimModel repository)
   at Xbim.Exchange.Program.Main(String[] args) in c:\IFC\XbimExchange-master\Xbim.Exchange\Program.cs:line 105

Thank you for any help.

**Comment by martin1cerny** [comment]
We are in the middle of translation from XbimEssentials3 to XbimEssentials4 so this is possible. Exchanger is just a development testbed. If you delete all the rest of the code and only keep wexBIM related code it will work.

**Comment by krosoftware** [comment]
OK will try it out, thank you so much.
