### ISSUE TITLE
IFC is not rendered correctly

### ISSUE THREAD

**Issue by AlainBolduc** [xBimTeam/XbimWebUI#90]
Hi,

I have a IFC file that does not render correctly. I am expecting this: 

![image](https://cloud.githubusercontent.com/assets/13261041/15017633/52537840-11e4-11e6-8184-3c567887e137.png)

but instead I get a big cube when loading in xbim web viewer : 

![image](https://cloud.githubusercontent.com/assets/13261041/15017645/6409454c-11e4-11e6-8d34-d53848812742.png)

I also see that cube when I load it in xbim windows UI : 

![image](https://cloud.githubusercontent.com/assets/13261041/15017663/7657908c-11e4-11e6-9f20-c77ae4ca4691.png)

I tried to open it using xbim windows ui in the Develop branch. It is slightly better. I can see the shape, but there is still that big cube in the windows ui. 

![image](https://cloud.githubusercontent.com/assets/13261041/15017611/37a5fd74-11e4-11e6-96af-250d717636e9.png)

This issue probably does not belong to XbimWebUI, but I am not sure if it is more related to geometry, exchange or essentials, so I will let you move this issue to the correct project...

I can open the ifc in many other IFC viewers and I do not see this problem.

I included the IFC file for your investigation.

[cube bug.zip](https://github.com/xBimTeam/XbimWebUI/files/248927/cube.bug.zip)

Thank you very much!

**Comment by AlainBolduc** [comment]
Any answer on this?

**Comment by martin1cerny** [comment]
Hi @AlainBolduc , I've just checked and it seems like a bug in our geometry engine. @SteveLockley is the best one for this so I'll try to pass this to him.

**Comment by SteveLockley** [comment]
This is technically an area in the IFC file, you may want to inform the creator. The closing point of the polyline defining the profile of the shape is duplicated
#29 = IFCPOLYLINE((#30, #31, #32, #33, #34, #35, #36, #30, #30));
nb the duplicate #30 
In the latest develop branch I have fixed xBIM so that it handles this situation, build V0071

**Comment by AlainBolduc** [comment]
Thank you everyone for your great support, as usual! :+1:
