### ISSUE TITLE
xBrowser is missing space assignments to assets

### ISSUE THREAD

**Issue by m4cx** [xBimTeam/XbimWebUI#92]
Working with the generated semantic model in Json in cooperation with the xCobieUtils-class I noticed, that the spaceassignments are missing within the xVisualEntity of an Asset instance allthough it is defined in JSON like this:

`
"AssetSpaceAssignments": {
    "SpaceAssignment": [{
        "SpaceName": "3",
	"FloorName": "Floor 1"
    }]
}
`

**Comment by martin1cerny** [comment]
Thanks for the fix. Merged in already.
