### ISSUE TITLE
expanded json and wexbim upload for browser and viewer seems inefficient

### ISSUE THREAD

**Issue by johnfoundations** [xBimTeam/XbimWebUI#94]
1) Running Solibri model optimizer on LakesideRestaurant.ifc reduces size by 22%. it appears to get rid of the duplicate Point and Orientation references in the IFC models
2) LakesideRestaurant.json is 3986 KB
3) LakesideRestaurantJson.7z is 158KB
4)LakesideRestaurant.wexbim is 3837KB
5)LakesideRestaurantWexbim.7z is 879KB

I have seen the results of an IFC dump on a Solibri optimized model, and you get much less meta data. Not easy to tell if LakesideRestaurant.json has similar optimizations. 

After doing the munload() hack to get familiar with this technology, I loaded and unloaded most of the various wexbim in the test directory. Very convenient. Compressed data should make these transitions a bit faster.

**Comment by martin1cerny** [comment]
Hi @johnfoundations , thanks for a nice use-case. JSON structure exported from xBIM is based on COBieLite project but is more rigorous and clear. However, it is not the best suit for semantic data representation of large models over the web anyway. It might be better to use xBIM to implement service to serve just pieces of data as you need it. xBIM is entirely designed as a server-side engine to do this.

We thought about using ZIP compression to speed up transmission of the data but decompression in JS didn't seem to be very good for large files. But as you've tried already there is nothing stopping you from doing so. xBIM produces all data you need and you can compress it before you serve it from your application. And WebUI can consume any Blob as an input so you can decompress your data and pass it to the viewer with no problem. And you can use any kind of compression you like.

**Comment by johnfoundations** [comment]
Hi. Interesting answer. If not this JSON, what alternative for semantic data  representation?I had something rather simple in mind. 55 storey building ... bottom section, top section, middle section.
The architecture of Xviewer and Xbrowser is really excellent. I don't know webgl, don't know IFC, but I can reverse engineer as I go along, because of the clarity of the design. I think I started looking at xViewer on Saturday.
So congratulations for some really fine work.I think I will need to import BinaryReader into constructor, but this is a tiny change.
But my real work is file system related ... so it might take a while. I threw this viewer together to present an alternative to open bim server to the guy who pays me. He needs a model browser.
I am more interested in what you might be doing regarding automated model validation and QTO.

**Comment by johnfoundations** [comment]
Hi. Are there any large wexbim and json model pairs on a repository? I don't really have time at the moment to start playing with the core utilities, and I mostly work on Linux servers.
I would like to pair Munload() with external ChunkReader(), and attachReader() method as a single update.

**Comment by martin1cerny** [comment]
No, there are no large files in our repository.

**Comment by johnfoundations** [comment]
OK. I will assume that this is also a problem for your side, and try to get some students in China to produce some samples. 
Now ... university of Nottingham, in China, wants to play with BIM. If we get some graduate students, they can only contribute back, and the motivation is that various professors, and my boss, can claim that they play with the Xbim big dogs in the UK (that is you). Let me know if you want a free visit to China to present Xbim UI. 
The agenda item would be that wexbim format for model viewing is the greatest thing since sliced bread.

**Comment by martin1cerny** [comment]
It isn't a problem for us. There are no large files in the repository because
  - it would make the repository unnecessarily large
  - it might cause an issue with legal rights regarding content of the files

However, xBIM has been going through a battlefield of various IFC files because
  - it is the engine of choice of several large enterprises so xBIM is repeatedly used on great number of IFC files of varying size and quality. If there are any issues we fix them as they come. 
  - we have extensive suit of IFC files which we use for regression and performance testing. These are just not public.

I'll think about visiting China and will let you know. It might be an interesting direction for xBIM expansion.

**Comment by johnfoundations** [comment]
China is very interesting.

**Comment by johnfoundations** [comment]
Here is a thought. University of Aukland maintains an academic sample 3d model set.  If wexbim is going to become a de-facto standard ... there should be some wexbim on this site or equivalent.

**Comment by martin1cerny** [comment]
That sounds interesting. We didn't think about wexBIM being standard for
IFC on a web but it would be nice if it become to be the one. Feel free to
get engaged with the University of Aukland to get wexBIM files along with
their IFCs.
