### ISSUE TITLE
pick event is not working?

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#95]
Hie,

**Pick event is registered in this on method successfully.**
xViewer.prototype.on = function (eventName, callback) {
    var events = this._events;
    if (!events[eventName]) {
        events[eventName] = [];
    }
    events[eventName].push(callback);
};

**but it is not working while i will click on model.** 

 viewer.on('pick', function (arg) {
           id = arg.id;
        });
****

**Comment by martin1cerny** [comment]
Hi @BIMDevelopement , we will need more detailed description to be able to investigate this. The best is a working prototype presenting the issue.

**Comment by martin1cerny** [comment]
...I've just quickly checked and the function seems to be all right. Do you load three models into a single xViewer or do you create three viewers @BIMDevelopement ? Can you post a code example?

**Comment by BIMDevelopement** [comment]
I hve noticed one thing .
If I fire pick event in handleMouseDown() method , It will work . But if i wont fire a event , then it wont work.

I think, the fire is necessary for that .Is it right ?
