### ISSUE TITLE
handlemouseDown event is called for multiple times for a single click?

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimWebUI#96]
Hi Martin,

I have uploaded 3 files .
And I am going to load a first file in browser. Then it is working fine. but
While I am going to load a **second file** in browser and going to select a model , the call goes to handlemouseDown event **twice**.

Similar to third file , ..the call goes to handlemouseDown event **three times **...

again i select a first model or any other . the call goes increment one more time ..ie Four.

All activity is done without page is refreshing.

But if I will refresh a page . it will work fine for first loaded file and above cycle is again going on..

**Comment by BIMDevelopement** [comment]
I have removed a canvas first and bind again new canvas . but still problem is getting.

**Comment by martin1cerny** [comment]
Loading multiple models is not very well tested because it wasn't in a scope of initial development. The function firing the event needs to be fixed so that it only fires only once.

**Comment by martin1cerny** [comment]
...I've just quickly checked and the function seems to be all right. Do you load three models into a single xViewer or do you create three viewers @BIMDevelopement ? Can you post a code example?

**Comment by BIMDevelopement** [comment]
Yes,it will load three models into single xViewer..

I have just passed a model to load method while i am going to select a different file. 

viewer,load(model);

**Comment by martin1cerny** [comment]
Right, this is not an example which could be used to repeated the behaviour you've described.
