### ISSUE TITLE
wexbim missing items and colors

### ISSUE THREAD

**Issue by chadbimuser** [xBimTeam/XbimWebUI#97]
Hi,
A 130 mb IFC file is converted into wexbim then rendered on the screen, but it is missing some items and colors (I compared the results against a desktop application where items are way clearer and some colorization is applied), could this be related to the file size? I used the "simpleviewer.html" page of the XbimWebUI project.
Thanks

**Comment by martin1cerny** [comment]
Did you use the latest version of geometry engine and xBIM Essentials to create the wexBIM file?

**Comment by chadbimuser** [comment]
Yes I did, still likes some walls are missing ....

**Comment by martin1cerny** [comment]
Have you used the latest  version from `master` or `develop`? I'm sorry but these are very different now so it is better to check.

**Comment by chadbimuser** [comment]
What I did is the following:
1- Downloaded XbimWebUI is from GIT using master branch
2- Got latest versions of Geometry and Essentials through Nuget in VS then added a test method (That I found in xbim.Exchanger) to the XbimWebUI project to create the wexbim out of the IFC fil
4- Ran "simpleviewer" html and uploaded the wexbim to be viewed on scene
Let me know please if this should be done differently
Thanks I appreciate your help!

**Comment by chadbimuser** [comment]
Hi Martin,
Also, please let me know which branch is recommended for development, master or develop?
Thanks

**Comment by martin1cerny** [comment]
Hi @chadbimuser , at the moment I'd recommend `develop` for a development. It is currently new generation and contains many significant changes. We still work on improvements before we promote it to `master` branch but changes shouldn't be code-braking. If you used Nuget package from https://www.nuget.org/ it is our master branch. We use MyGet for development distribution. You can get it from [here](https://www.myget.org/F/xbim-develop/api/v2).

**Comment by chadbimuser** [comment]
Thanks martin will try all that.

**Comment by chadbimuser** [comment]
![capture](https://cloud.githubusercontent.com/assets/19926550/16121700/edf4caae-33ec-11e6-8837-8c37da078c3f.PNG)
Hi Martin, when i click on the MyGet link, I get an XML document tree, it might be a problem with the URL ...

**Comment by LloydPickering** [comment]
@chadbimuser The URL is to a Nuget feed. You need to add it as a source in Visual Studio so it can see the pre-release packages.

Have a look at https://www.visualstudio.com/en-us/docs/package/get-started/nuget/consume which should give you the right hints on how to do it

**Comment by chadbimuser** [comment]
Hi LIoyd,
Thanks for the feedback, I will try this. However, is there any issue if we simply use the libraries I get through VS nuget?
Thanks

**Comment by martin1cerny** [comment]
There is no issue but current libraries distributed through NuGet.org are long behind current development. MyGet development packages are about year ahead of the NuGet.
