### ISSUE TITLE
Dragging models on scene

### ISSUE THREAD

**Issue by chadbimuser** [xBimTeam/XbimWebUI#99]
Hi,

I would like to drag the model up and down/right and left on the scene by holding the mouse right click, this is not available in the XbimWebUI in any of the viewers (I've seen this in other libraries/applications, all that can be done in the XbimWebUI is rotating the model). Not having this is problematic as it is hard sometimes to position the camera properly on the scene. Is there a method implemented somewhere in the libraries to do this? 
And what's ideally the max IFC file size to be loaded on the web as I see rendering/zooming/locating objects is too slow for large files (100 mb ...)

Thanks!

**Comment by martin1cerny** [comment]
Panning is implemented when you hold the middle button. You can also change navigation mode so that it works with left button. Other implementations are possible by yourself. 

Maximum size depends on performance of your device but more than 100MB might get slower.

**Comment by chadbimuser** [comment]
Thanks a lot Martin!
